Backup/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>This field is used to store the value of expiration date.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>It holds the License Expiration Date details.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/classes/ConflictOfInterestTrigger_AT_Test.cls
@isTest
public class ConflictOfInterestTrigger_AT_Test{
  // Mapping fields.
  public static testMethod void createConflictOfInterest(){
        Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
        Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
         Conflict_Of_Interest__c  coiRec = OrientationandTrainingUtil.createCOI(volunteerContact.Id);
        }
 
   public static testMethod void updateConflictOfInterest(){
        Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
        Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
         Conflict_Of_Interest__c  coiRec = OrientationandTrainingUtil.createCOI(volunteerContact.Id);
         coiRec.Expiration_Date__c = Date.Today().addYears(1);
         update coiRec;
        }
}