make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Id__c</fullName>
        <description>Contains the unique chapter Id for chapter accounts. Used for upserting records via Mulesoft.</description>
        <externalId>true</externalId>
        <label>Chapter Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>It will holds the account email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Resided_in_US_for_past_7_years__c</fullName>
        <description>It will capture whether the Volunteer Resided US Past 7 Years or not.</description>
        <label>Are you residing in US for past 7 years?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Region_Chapter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the contact region chapter</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Region Chapter)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DocumentController_Test.cls
@IsTest
public class DocumentController_Test {
    @IsTest
    static void testmethod1() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        //inserting account records
        Account acc = new Account();
        acc.Name = 'Make-A-Wish Alabama';
        acc.Email__c = 'test@demo.com';
        acc.Chapter_Id__c = '041501';
        insert acc;

        //inserting contact record.
        Id RecordTypeIdContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Board Member').getRecordTypeId();
        Contact con = new Contact();
        con.RecordTypeId = RecordTypeIdContact;
        con.FirstName = 'test';
        con.LastName = 'Volunteer';
        con.AccountId = acc.Id;
        con.Region_Chapter__c = acc.Id;
        insert con;

        //inserting background record.
        Background_check__c background = new Background_check__c();
        background.Volunteer__c = con.Id;
        background.Resided_in_US_for_past_7_years__c = 'yes';
        background.Order_Id__c = 'WPS-6991282';
        background.Package_Id__c = '041501';
        insert background;

        Test.startTest();
        PageReference pageRef = Page.BackgroundCheckPage;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(background.Id));
        ApexPages.StandardController stdController = new ApexPages.StandardController(background);
        DocumentController_AC controller = new DocumentController_AC(stdController);
        controller.redirect();

        controller.orderId = controller.packageId = null;
        controller.redirect();
        Test.stopTest();
    }
}