make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>It will holds the account email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <description>It will used as a hidden field to store account email to merge in the email template</description>
        <label>Hidden Account Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This Field is used as hidden field in COI Email template</description>
        <label>Hidden Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Phone__c</fullName>
        <description>It holds the value of Account Phone</description>
        <label>Hidden Account Phone</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Volunteer_Contact_Email__c</fullName>
        <description>This field is used as hidden field to store volunteer contact email in COI.</description>
        <label>Hidden Volunteer Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <description>It will be used as a hidden field to store contact&apos;s account email</description>
        <formula>Account.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hidden Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Phone__c</fullName>
        <description>It will be used as a hidden filed to store the contact&apos;s account phone</description>
        <formula>Account.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hidden Account Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Chapter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the contact region chapter</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Region Chapter)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/COI_OnBeforeInsertTriggerHelper.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 
Description : COI_OnBeforeInsertTriggerHandler is used to call the Helper class when the
              new COI record is created.
              
              Modification Log
              ------------------
              WVC-1888    Pavithra G  06/13/2018
              
*****************************************************************************************************/
public class COI_OnBeforeInsertTriggerHelper{
    /********************************************************************************************
    This method is used to create a task when the lead record is created. And share the lead
    record based on the chapter.
*********************************************************************************************/
    public static void mapAccountDetails(List<Conflict_Of_Interest__c > newCOIList,Set<Id> volContactIdSet){
        // try{
             Map<Id,Contact> conMap = new Map<Id, Contact>();
             for(Contact VoluContact : [SELECT Id,Email,AccountId,OwnerId,Region_Chapter__r.Name,Region_Chapter__r.Phone,Region_Chapter__r.Email__c,Region_Chapter__c FROM Contact WHERE Id IN : volContactIdSet]){
                conMap.put(VoluContact.Id,VoluContact);
            }
            
            for(Conflict_Of_Interest__c newCOI : newCOIList){
                if(conMap.containsKey(newCOI.Volunteer_Contact__c)){
                    newCOI.Account_Name__c = conMap.get(newCOI.Volunteer_Contact__c).Region_Chapter__r.Name;
                    newCOI.Account_Phone__c= conMap.get(newCOI.Volunteer_Contact__c).Region_Chapter__r.Phone;
                    newCOI.Hidden_Volunteer_Contact_Email__c = conMap.get(newCOI.Volunteer_Contact__c).Email;
                    newCOI.Account_Email__c = conMap.get(newCOI.Volunteer_Contact__c).Region_Chapter__r.Email__c;
                    newCOI.ownerId = conMap.get(newCOI.Volunteer_Contact__c).OwnerId;
                } 
           } 
      // }
       /* catch(Exception ex){
          for(Conflict_Of_Interest__c  currRec : newCOIList){
                ErrorMessage_AC.createdebugRec('COI_OnBeforeInsertTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'mapAccountDetails',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
           
            for(Conflict_Of_Interest__c  currRec : newCOIList){
                currRec.addError(Label.Debug_log_error_message);
            }
       }*/
    }
}