make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alert_for_Unassigned_Wishes__c</fullName>
        <description>This filed will indicate how long the wish can be unassigned</description>
        <inlineHelpText>In terms of number of days</inlineHelpText>
        <label>Alert for Unassigned Wishes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer manager</description>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rush__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to identify whether the wish is need to process quicker or not</description>
        <label>Rush</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field will be used to know the progress(Current status) of the wish</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age Expiration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign in Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss of Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Viewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refused</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wish_type__c</fullName>
        <description>It holds the details about the  type of wish</description>
        <label>Wish type</label>
        <picklist>
            <picklistValues>
                <fullName>Cruise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GKTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Diagnosis_Given_By_Referrer__c</fullName>
        <description>Used to hold the diagnosis given by referrer</description>
        <label>Diagnosis Given By Referrer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ICD_10_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold the ICD-10 code.</description>
        <label>Primary ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate the wish Child Family aware of Referral at MAWA.</description>
        <label>Is Family Aware Of Referral?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ICD_10_Code__c</fullName>
        <description>This field will hold the ICD-10 code.</description>
        <label>ICD-10 Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Please_Explain__c</fullName>
        <description>Explanation for the wish</description>
        <label>Please Explain Expedite</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Case_Trigger_Test.cls
/**
 * @author Steve Doucette, Traction on Demand 
 * @date 10/24/2019
 */
@IsTest
private class Case_Trigger_Test {

    @TestSetup
    public static void setUp() {
        trac_TriggerHandlerBase.blockTrigger = true;
        User currentUser = Utils.currentUser;
        List<Account> accounts = TestDataFactory.createAccount(1);
        Account account = accounts.get(0);
        account.Name = 'Make-A-Wish Arizona';
        account.RecordTypeId = Constant_AC.CHAPTER_RT_ID;
        account.Volunteer_Manager__c = currentUser.Id;
        account.Alert_for_Unassigned_Wishes__c = 1;
        insert accounts;

        String profileName = 'Full Access National Staff';
        String portalRole = 'Manager';
        Id userRoleId = [
                SELECT Id
                FROM UserRole
                WHERE Name = 'National Staff'
        ].Id;

        List<User> users = TestDataFactory.createUser(2);
        User nationalStaffUser1 = users.get(0);
        User nationalStaffUser2 = users.get(1);
        System.runAs(Utils.currentUser) {
            Profile profile = [
                    SELECT Id,Name
                    FROM Profile
                    WHERE Name = :profileName
                    LIMIT 1
            ];
            nationalStaffUser1.ProfileId = profile.Id;
            nationalStaffUser1.PortalRole = portalRole;
            nationalStaffUser1.UserRoleId = userRoleId;
            nationalStaffUser1.LastName = 'Doe1';
            nationalStaffUser1.Username = 'doe1@emailmawtest.com';
            nationalStaffUser1.ManagerId = Utils.currentUser.Id;

            nationalStaffUser2.ProfileId = profile.Id;
            nationalStaffUser2.PortalRole = portalRole;
            nationalStaffUser2.UserRoleId = userRoleId;
            nationalStaffUser2.LastName = 'Doe2';
            nationalStaffUser2.Username = 'doe2@emailmawtest.com';
            nationalStaffUser2.ManagerId = Utils.currentUser.Id;
            insert users;
        }

        List<ICD_Codes__c> icdCodes = TestDataFactory.createIcdCode(1);
        ICD_Codes__c icdCode = icdCodes.get(0);
        insert icdCode;

        List<Lead> leadsDataFactory = TestDataFactory.createLead(1);
        Lead lead = leadsDataFactory.get(0);
        lead.ChapterName__c = accounts[0].Id;
        lead.FirstName = 'Jack';
        lead.LastName = 'Smith';
        lead.Hidden_Chapter_Change_Confirmation__c = account.Id;
        lead.is_Family_Aware_of_Referral__c = 'Yes';
        lead.Diagnosis_Given_By_Referrer__c = 'Test Diagnosis';
        lead.PD_ICD_Code__c = icdCode.Id;
        lead.Company = 'MAW';
        insert lead;

        User volunteerUser = TestDataFactory.createVolunteerUser(1, 'Active Volunteer (Login)', 'Manager').get(0);
        volunteerUser.LastName = 'Smith0';
        System.runAs(TestDataFactory.adminUser) {
            insert volunteerUser;
        }

        List<Contact> contacts = TestDataFactory.createContact(1);
        Contact contact1 = contacts.get(0);
        contact1.FirstName = 'Test1';
        contact1.LastName = 'User2';
        contact1.AccountId = account.Id;
        contact1.ICD_10_Code__c = icdCode.Id;
        insert contacts;

        trac_TriggerHandlerBase.blockTrigger = false;
    }

    @IsTest
    static void createUpdateCase() {
        Lead lead = [
                SELECT Id
                FROM Lead
                LIMIT 1
        ];
        Contact contact = [
                SELECT Id, AccountId
                FROM Contact
                LIMIT 1
        ];
        User nationalStaffUser1 = [
                SELECT Id
                FROM User
                WHERE LastName = 'Doe1'
        ];
        User nationalStaffUser2 = [
                SELECT Id
                FROM User
                WHERE LastName = 'Doe2'
        ];

        List<Case> cases = TestDataFactory.createCase(4);
        Case wish1 = cases.get(0);
        wish1.Lead__c = lead.Id;
        wish1.RecordTypeId = Constant_AC.WISH_RT_ID;
        wish1.ChapterName__c = contact.AccountId;
        wish1.Subject = 'Wish1';
        wish1.Interview_date__c = System.today();
        wish1.Wish_Type__c = 'Hawaii';
        wish1.Start_Date__c = System.today();
        wish1.End_Date__c = System.today();
        wish1.ContactId = contact.Id;
        wish1.Rush__c = false;
        wish1.Start_Date__c = System.today();
        wish1.Budget_Submitted_Date__c = System.today();
        wish1.Budget_Approved_Date__c = System.today();
        wish1.Update_Wish_Child_Form_Info__c = true;
        wish1.Status = Constant_AC.CASE_STATUS_NEW;
        wish1.OwnerId = nationalStaffUser1.Id;

        Case wish2 = cases.get(1);
        wish2.Lead__c = lead.Id;
        wish2.RecordTypeId = Constant_AC.WISH_RT_ID;
        wish2.ChapterName__c = contact.AccountId;
        wish2.Subject = 'Wish1';
        wish2.Interview_date__c = System.today();
        wish2.Wish_Type__c = 'Hawaii';
        wish2.Start_Date__c = System.today();
        wish2.End_Date__c = System.today();
        wish2.ContactId = contact.Id;
        wish2.Rush__c = false;
        wish2.Start_Date__c = System.today();
        wish2.Budget_Submitted_Date__c = System.today();
        wish2.Budget_Approved_Date__c = System.today();
        wish2.Update_Wish_Child_Form_Info__c = true;
        wish2.Status = Constant_AC.CASE_STATUS_READY_TO_INTERVIEW;
        wish2.OwnerId = nationalStaffUser1.Id;

        Case wish3 = cases.get(2);
        wish3.Lead__c = lead.Id;
        wish3.RecordTypeId = Constant_AC.WISH_RT_ID;
        wish3.ChapterName__c = contact.AccountId;
        wish3.Subject = 'Wish1';
        wish3.Interview_date__c = System.today();
        wish3.Wish_Type__c = 'Hawaii';
        wish3.Start_Date__c = System.today();
        wish3.End_Date__c = System.today();
        wish3.ContactId = contact.Id;
        wish3.Rush__c = false;
        wish3.Start_Date__c = System.today();
        wish3.Budget_Submitted_Date__c = System.today();
        wish3.Budget_Approved_Date__c = System.today();
        wish3.Update_Wish_Child_Form_Info__c = true;
        wish3.Status = Constant_AC.CASE_STATUS_WISH_DETERMINED;
        wish3.OwnerId = nationalStaffUser1.Id;

        Case wish4 = cases.get(3);
        wish4.Lead__c = lead.Id;
        wish4.RecordTypeId = Constant_AC.DIAGNOSIS_RT_ID;
        wish4.ChapterName__c = contact.AccountId;
        wish4.Subject = 'Wish1';
        wish4.Interview_date__c = System.today();
        wish4.Wish_Type__c = 'Hawaii';
        wish4.Start_Date__c = System.today();
        wish4.End_Date__c = System.today();
        wish4.ContactId = contact.Id;
        wish4.Rush__c = false;
        wish4.Start_Date__c = System.today();
        wish4.Budget_Submitted_Date__c = System.today();
        wish4.Budget_Approved_Date__c = System.today();
        wish4.Update_Wish_Child_Form_Info__c = true;
        wish4.Status = Constant_AC.CASE_STATUS_ESCALATED;
        wish1.OwnerId = nationalStaffUser1.Id;

        Test.startTest();
        insert cases;

        wish1.Subject = 'WishUpdate';
        wish1.Comment_1__c = 'Abc';
        wish1.Appropriate_Comments__c = 'Abc';
        wish1.Please_Explain__c = 'Abc';
        wish1.Wish_Clearance_Needed__c = 'Yes';
        wish1.Status = Constant_AC.CASE_STATUS_READY_TO_INTERVIEW;
        wish1.OwnerId = nationalStaffUser2.Id;

        wish2.Subject = 'WishUpdate';
        wish2.Comment_1__c = 'Abc';
        wish2.Status = Constant_AC.CASE_STATUS_READY_TO_ASSIGN;
        wish2.Sub_Status__c = Constant_AC.CASE_SUB_STATUS_PENDING;
        wish2.OwnerId = nationalStaffUser2.Id;

        wish3.Subject = 'WishUpdate';
        wish3.Comment_1__c = 'Abc';
        wish3.Status = Constant_AC.CASE_STATUS_WISH_DETERMINED;
        wish3.OwnerId = nationalStaffUser2.Id;

        wish4.Subject = 'WishUpdate';
        wish4.Comment_1__c = 'Abc';
        wish4.Status = Constant_AC.CASE_STATUS_ESCALATED;
        wish4.OwnerId = nationalStaffUser2.Id;

        update cases;
        Test.stopTest();
    }
}