make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Awards_Recognition__c.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This describes the Chapter Name</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Awards &amp; Recognitions</relationshipLabel>
        <relationshipName>Awards_Recognitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look field used for the getting volunteer contact</description>
        <label>Volunteer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards &amp; Recognitions</relationshipLabel>
        <relationshipName>Awards_Recognitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Awards &amp; Recognition</label>
    <nameField>
        <displayFormat>AW-{0000}</displayFormat>
        <label>Awards &amp; Recognition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards &amp; Recognitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/classes/AwardsRecognitionServiceTest.cls
/**
* @description Test class for AwardsRecognitionService
* @author Michelle Cominotto, Make-A-Wish
* @createdDate 4/20/2020
*/
@isTest
private class AwardsRecognitionServiceTest {
    
    private final static Id CHAPTER_RT_ID = Constant_AC.CHAPTER_RT_ID;
    private final static Id VOLUNTEER_RT_ID = Constant_AC.VOLUNTEER_RT_ID;
    
    @testSetup
    private static void setUp() {
        trac_TriggerHandlerBase.blockTrigger = true;
        
        List<Account> accounts = TestDataFactory.createAccount(2);
        Account accountAzChapter = accounts.get(0);
        accountAzChapter.Name = 'Make-A-Wish Arizona';
        accountAzChapter.RecordTypeId = CHAPTER_RT_ID;
        Account accountFlChapter = accounts.get(1);
        accountFlChapter.Name = 'Make-A-Wish Central & Northern Florida';
        accountFlChapter.RecordTypeId = CHAPTER_RT_ID;
        insert accounts;
        
        List<Contact> contactList = TestDataFactory.createContact(1);
        Contact volunteerMarie = contactList.get(0);
        volunteerMarie.FirstName = 'Marie';
        volunteerMarie.LastName = 'Gardner';
        volunteerMarie.Email = 'marie.gardner@testmail.com';
        volunteerMarie.RecordTypeId = VOLUNTEER_RT_ID;
        volunteerMarie.AccountId = accountAzChapter.Id;
        insert contactList;
        
        List<Awards_Recognition__c> awardsList = TestDataFactory.createAwardsRecognitions(1);
        Awards_Recognition__c awardVolunteer = awardsList.get(0);
        awardVolunteer.Chapter_Name__c = accountAzChapter.Id;
        awardVolunteer.Volunteer_Contact__c = volunteerMarie.Id;
        insert awardsList;
        
        trac_TriggerHandlerBase.blockTrigger = false;
    }
    
    @isTest
    private static void validateCheckChapterRolePermission() {       
        Account floridaChapter = [
            SELECT Id, Name 
            FROM Account 
            WHERE Name = 'Make-A-Wish Central & Northern Florida'  
            LIMIT 1];		
        
        Map<Id, Awards_Recognition__c> awardRecognitionMap = new Map<Id, Awards_Recognition__c>([
            SELECT Id, Chapter_Name__c 
            FROM Awards_Recognition__c
        ]);
        List<Awards_Recognition__c> awardsListUpdated = new List<Awards_Recognition__c>();
        for(Awards_Recognition__c award : awardRecognitionMap.values()) {
            Awards_Recognition__c updatedAward = new Awards_Recognition__c(Id = award.Id);
            updatedAward.Chapter_Name__c = floridaChapter.Id;
            awardsListUpdated.add(updatedAward);
        }
        
        User azUser = [
            SELECT Id FROM User 
            WHERE IsActive = true 
            AND UserRole.Name = 'Arizona - Chapter'
            LIMIT 1];
        
        Test.startTest();
        System.runAS(azUser) {
            AwardsRecognitionService.checkChapterRolePermission(awardsListUpdated, awardRecognitionMap);
        }
        Test.stopTest();
        
        Awards_Recognition__c awardChangeCheck = [
            SELECT Id, Chapter_Name__c 
            FROM Awards_Recognition__c 
            LIMIT 1];
        System.assert(awardChangeCheck.Chapter_Name__c != floridaChapter.Id);
    }
}