make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This field holds the state name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Action_Track__c.object
<CustomObject>
    <description>It holds list of tasks for child wishes</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the Chapter Name</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Action Tracks</relationshipLabel>
        <relationshipName>Chapter_Action_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter Action Track</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Action Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/classes/WishTaskRecurrence_AC_Test.cls
/************************************************************************************
Author : Mst Solutions
Description : This class is used to increase the code coverage for WishTaskRecurrence_AC controller
*************************************************************************************/
@isTest
public class WishTaskRecurrence_AC_Test {
    
    @testSetup static void setup(){  
        Case parentCase = TestClassUtil.CreateParentCase();
        Contact wishChild = TestClassUtil.CreateWishChild();
        Account newchapterAccount = TestClassUtil.createchapterAccount();
        Chapter_Action_Track__c newAction = TestClassUtil.CreateChapterActionTrack();
        newAction.Chapter_Name__c = newchapterAccount.Id;
        insert newAction;
    }
    
    //This method is used to create recurrence task
    @isTest static void DeterminationCaseProcess() {
        Contact newContact = [SELECT Id FROM Contact];
        Case newCase = [SELECT Id FROM Case];
        
        Case newWishDeterminatonWish = TestClassUtil.DeterminationCaseProcess();
        newWishDeterminatonWish.ParentId = newCase.Id;
        newWishDeterminatonWish.ContactId = newContact.Id;
        insert newWishDeterminatonWish;
        
        Task newTask = TestClassUtil.CreateNewTask();
        newTask.WhatId = newWishDeterminatonWish.Id;
        insert newTask;
        
        Task anotherTask = TestClassUtil.CreateNewTask();
        anotherTask.WhatId = newWishDeterminatonWish.Id;
        anotherTask.Status = 'Completed';
        insert anotherTask;
        Test.setCreatedDate(anotherTask.Id, System.today()-1);
        
        Task anotherTask1 = TestClassUtil.CreateNewTask();
        anotherTask1.WhatId = newWishDeterminatonWish.Id;
        anotherTask1.Status = 'Completed';
        insert anotherTask1;
        Test.setCreatedDate(anotherTask1.Id, System.today()-1);
        
        Test.startTest();
        WishTaskRecurrence_AC c = new WishTaskRecurrence_AC();
        Database.executeBatch(c);
        Test.stopTest();
    }
}