make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will tells the final result about the background check.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved w/ Conditions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Background_Check_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to verify whether the background check is required or not</description>
        <label>Background Check Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter details and role for this chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the role name and chapters assigned for this role.</description>
        <label>Role Name</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check weather this conflict of interest is active or not.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VolunteerRoleOutofCompliance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to identify whether the volunteer has at least one volunteer role with the status of out of compliance</description>
        <label>Volunteer Role(Out of Compliance)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VolunteerRoleTrainedTpendChapReview__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to identify whether the volunteer has at least one volunteer role with the status of trained,trainning pending or chapter review</description>
        <label>Volunteer Role(Trained,Tpend,ChapReview)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Out of Compliance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the chapter named of Account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It will display the role name</description>
        <formula>Chapter_Role_Opportunity__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It indicate different status of the volunteer opportunity.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It store the chapter name.</description>
        <formula>Chapter_Role__r.Chapter_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <description>This field store the role name.</description>
        <formula>Chapter_Role__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will hold the volunteer name and define chapter and role for this volunteer.</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerRoleTriggerHandler.cls
/**************************************************************************************
Description : This class used to update volunteer opportunity status as out of compliance or 
approved based on the volunteer role status      
a. Organizational affiliation should be 'Inactive' if volunteer only has one role 
and it is in status of 'former - chapter' - 'former - volunteer' or 'Out of Compliance' 
OR if volunteer has multiple roles and they are all in status of 'former - chapter' - 'former - volunteer' - 'Not Approved' 
or 'Out of Compliance'

b. Organizational affiliation should be 'Active' if volunteer has at least one role in 'Trained'
c. Organizational affiliation should be 'Declined' if volunteer has only one role and it is 'Not Approved'
d. Organizational affiliation should be 'Prospective' if volunteer has registered/completed/cancelled orientation but not completed application
e. Organizational affiliation should be 'Pending' if volunteer has completed application but not training and/or 
other requirements (i.e. not all roles require a training so those volunteers would just need to have interview)
***************************************************************************************/
public class VolunteerRoleTriggerHandler {
    
    public static void updateVolunteerOpportunity(map<id,list<Volunteer_Roles__c>> volRoleMap){
        //list<Volunteer_Opportunity__c> updateVolOppList = new list<Volunteer_Opportunity__c>();
        Map<Id,Volunteer_Opportunity__c> updateVolOppMap = new Map<Id,Volunteer_Opportunity__c>();
        if(volRoleMap.size() > 0){
            for(Volunteer_Opportunity__c currVolOpp : [SELECT ID,Status__c,Chapter_Name__c,Chapter_Name__r.Name,Volunteer_Name__c,Role__c FROM Volunteer_Opportunity__c WHERE Volunteer_Name__c IN: volRoleMap.keySet()]){
                
                if(volRoleMap.containsKey(currVolOpp.Volunteer_Name__c) ){
                    
                    for (Volunteer_Roles__c newVolRole : volRoleMap.get(currVolOpp.Volunteer_Name__c))
                    {
                        if(currVolOpp.Chapter_Name__r.Name == newVolRole.Chapter_Name__c && currVolOpp.Role__c == newVolRole.Role_Name__c ){
                            
                            if(newVolRole.Status__c == 'Trained' && currVolOpp.Status__c == 'Out of Compliance'){
                                
                                currVolOpp.Status__c = 'Approved';
                            }
                            else if(newVolRole.Status__c == 'Out of Compliance' && currVolOpp.Status__c == 'Approved'){
                                
                                currVolOpp.Status__c = 'Out of Compliance';
                            }
                            updateVolOppMap.put(currVolOpp.id,currVolOpp);
                        }
                    }
                }
            }
        }
        if(updateVolOppMap.size() > 0){
            update updateVolOppMap.Values();
        }
    }
    // Updating Affiliation Status based on the Volunteer Role Status.
    Public static void updateVolunteerRoleStatus(map<id,list<Volunteer_Roles__c>> volunteerRoleStatusMap,String action)
    {
        
        if(action == 'Update')
        {
            Map<String,Integer> volunteerRoleCountMap = new Map<String,Integer>();
            Map<id,list<Volunteer_Roles__c>> inActiveSingleStatusMap = new Map<id,list<Volunteer_Roles__c>>();
            Map<id,list<Volunteer_Roles__c>> declinedStatusMap = new Map<id,list<Volunteer_Roles__c>>();
            Map<id,list<Volunteer_Roles__c>> inActiveMultipleStatusMap = new Map<id,list<Volunteer_Roles__c>>();
            Set<Id> trainedVRsSet = new Set<Id>();
            
            for(AggregateResult currRes : [SELECT volunteer_name__c, count(id) cnt FROM Volunteer_Roles__c 
                                           WHERE volunteer_name__c IN :volunteerRoleStatusMap.keySet() GROUP by volunteer_name__c])
            {
                volunteerRoleCountMap.put(String.valueOf(currRes.get('volunteer_name__c')),integer.valueOf(currRes.get('cnt')));
            }
            
            for(Volunteer_Roles__c currRec : [SELECT id, volunteer_name__c, Status__c FROM Volunteer_Roles__c 
                                              WHERE volunteer_name__c IN :volunteerRoleStatusMap.keySet() AND
                                              (Status__c = 'Not Approved'  OR Status__c = 'Former - Volunteer' OR Status__c = 'Out of Compliance'
                                               OR Status__c = 'Former - Chapter' OR Status__c = 'Trained') ])
            {
                if(currRec.Status__c == 'Former - Volunteer' || currRec.Status__c == 'Former - Chapter' 
                   || currRec.Status__c == 'Out of Compliance')
                {
                    if(inActiveSingleStatusMap.containsKey(currRec.Volunteer_Name__c))
                    {
                        inActiveSingleStatusMap.get(currRec.Volunteer_Name__c).add(currRec);
                    }
                    else
                    {
                        inActiveSingleStatusMap.put(currRec.Volunteer_Name__c, new list<Volunteer_Roles__c>{currRec});
                    }
                }
                
                if(currRec.Status__c == 'Former - Volunteer' || currRec.Status__c == 'Former - Chapter' 
                   || currRec.Status__c == 'Not Approved' || currRec.Status__c == 'Out of Compliance')
                {
                    if(inActiveMultipleStatusMap.containsKey(currRec.Volunteer_Name__c))
                    {
                        inActiveMultipleStatusMap.get(currRec.Volunteer_Name__c).add(currRec);
                    }
                    else
                    {
                        inActiveMultipleStatusMap.put(currRec.Volunteer_Name__c, new list<Volunteer_Roles__c>{currRec});
                    }
                }
                
                if(currRec.Status__c == 'Not Approved')
                {
                    if(declinedStatusMap.containsKey(currRec.Volunteer_Name__c))
                    {
                        declinedStatusMap.get(currRec.Volunteer_Name__c).add(currRec);
                    }
                    else
                    {
                        declinedStatusMap.put(currRec.Volunteer_Name__c, new list<Volunteer_Roles__c>{currRec});
                    }
                }
                
                if(currRec.Status__c == 'Trained')
                    trainedVRsSet.add(currRec.Volunteer_Name__c);
                
            }
            
            List<npe5__Affiliation__c> updateRecList = new List<npe5__Affiliation__c>();
            for(npe5__Affiliation__c currRec : [SELECT id, npe5__Contact__c FROM npe5__Affiliation__c  WHERE npe5__Contact__c IN :volunteerRoleStatusMap.keySet()])
            {
                npe5__Affiliation__c updateAff = new npe5__Affiliation__c();
                updateAff.id = currRec.id;
                if(volunteerRoleCountMap.get(currRec.npe5__Contact__c) == 1)
                {
                    if(inActiveSingleStatusMap.containsKey(currRec.npe5__Contact__c))
                        updateAff.npe5__Status__c = 'Inactive';
                    else if(declinedStatusMap.containsKey(currRec.npe5__Contact__c))
                        updateAff.npe5__Status__c = 'Declined';
                }
                else if(volunteerRoleCountMap.get(currRec.npe5__Contact__c) > 1)
                {
                    if(inActiveMultipleStatusMap.containsKey(currRec.npe5__Contact__c) && (inActiveMultipleStatusMap.get(currRec.npe5__Contact__c)).size() == volunteerRoleCountMap.get(currRec.npe5__Contact__c))
                        updateAff.npe5__Status__c = 'Inactive';
                }
                
                if(trainedVRsSet.contains(currRec.npe5__Contact__c))
                    updateAff.npe5__Status__c = 'Active';
                updateRecList.add(updateAff);
            }
            
            if(updateRecList.size() > 0)
                update updateRecList;
        }
        
        if(action == 'Insert')
        {
            List<npe5__Affiliation__c> updateRecList = new List<npe5__Affiliation__c>();
            for(npe5__Affiliation__c currRec : [SELECT id, npe5__Contact__c FROM npe5__Affiliation__c  
                                                WHERE npe5__Contact__c IN :volunteerRoleStatusMap.keySet() 
                                                AND npe5__Status__c != 'Active' AND npe5__Status__c != 'Pending'])
            {
                npe5__Affiliation__c updateAff = new npe5__Affiliation__c();
                updateAff.id = currRec.id;
                updateAff.npe5__Status__c = 'Prospective';
                updateRecList.add(updateAff);
            }
            
            if(updateRecList.size() > 0)
                update updateRecList;
        }
    } 
    //The purpose of this method is to get the volunteer details to update the volunteer BC & COI based on the volunteer role status   
    public static void getVolunteerBasedOnVolunteerRoleStatus(Set<Id> volunteerRoleIdsSet, Set<id> volIdsSet){
        Set<ID> trainingVolunteersIdsSet = new Set<ID>();
        Set<ID> outOfComplianceVolunteersIdsSet = new Set<ID>();
        Set<ID> coiTrainingVolunteerIdsSet = new Set<ID>();
        Set<ID> coiOutOfComplianceVolunteerIdsSet = new Set<ID>();
        Set<ID> coiVOlunteerIdsSet = new Set<ID>();
        Set<ID> volunteerIdsSet = new Set<ID>();
        system.debug('-----> inside getVolunteerBasedOnVolunteerRoleStatus');
        for(Volunteer_Roles__c currVolunteerRole :[SELECT ID,Volunteer_Name__c,Chapter_Role__r.Background_Check_Required__c,Status__c FROM Volunteer_Roles__c WHERE Chapter_Role__c != Null AND Volunteer_Name__c IN: volIdsSet ]){
            if(currVolunteerRole.Status__c == 'Trained' || currVolunteerRole.Status__c == 'Pending Training' || currVolunteerRole.Status__c == 'Chapter Review'){
                system.debug('-----> inside Training' + currVolunteerRole.Status__c + currVolunteerRole.Chapter_Role__r.Background_Check_Required__c);
                if(currVolunteerRole.Chapter_Role__r.Background_Check_Required__c == true){
                    
                    trainingVolunteersIdsSet.add(currVolunteerRole.Volunteer_Name__c);
                    coiTrainingVolunteerIdsSet.add(currVolunteerRole.Volunteer_Name__c);
                }
                else{
                    coiTrainingVolunteerIdsSet.add(currVolunteerRole.Volunteer_Name__c);
                }
                
            }
            else if(currVolunteerRole.Status__c == 'Out of Compliance'){
                if(currVolunteerRole.Chapter_Role__r.Background_Check_Required__c == true){
                    outOfComplianceVolunteersIdsSet.add(currVolunteerRole.Volunteer_Name__c);
                    coiOutOfComplianceVolunteerIdsSet.add(currVolunteerRole.Volunteer_Name__c);
                }
                else{
                    coiOutOfComplianceVolunteerIdsSet.add(currVolunteerRole.Volunteer_Name__c);
                }
                
            }
            else{
                volunteerIdsSet.add(currVolunteerRole.Volunteer_Name__c);
            }
        }
        
        if(trainingVolunteersIdsSet.size() > 0){
            updateBackGroundCheck(trainingVolunteersIdsSet, 'training');
        }
        if(coiTrainingVolunteerIdsSet.size() > 0){
            updateConflictOfInterest(coiTrainingVolunteerIdsSet, 'training');
        }
        
        if(outOfComplianceVolunteersIdsSet.size() > 0){
            updateBackGroundCheck(outOfComplianceVolunteersIdsSet, 'outOfCompliance');
        }
        
        if(coiOutOfComplianceVolunteerIdsSet.size() > 0){
            updateConflictOfInterest(coiOutOfComplianceVolunteerIdsSet, 'outOfCompliance');
        }
        if(volunteerIdsSet.size() > 0 && outOfComplianceVolunteersIdsSet.size() == 0 && trainingVolunteersIdsSet.size() == 0){
            updateBackGroundCheck(volunteerIdsSet, 'none');
        }
        
        if(volunteerIdsSet.size() > 0 && coiOutOfComplianceVolunteerIdsSet.size() == 0 && coiTrainingVolunteerIdsSet.size() == 0){
            updateConflictOfInterest(volunteerIdsSet, 'none');
        }
        
        if(outOfComplianceVolunteersIdsSet.size() > 0 && trainingVolunteersIdsSet.size() == 0){
            updateBackGroundCheck(outOfComplianceVolunteersIdsSet, '1');
        }
        if(coiOutOfComplianceVolunteerIdsSet.size() > 0 && coiTrainingVolunteerIdsSet.size() == 0){
            updateConflictOfInterest(coiOutOfComplianceVolunteerIdsSet, '1');
        }
        
        if(trainingVolunteersIdsSet.size() > 0 && outOfComplianceVolunteersIdsSet.size() == 0 ){
            updateBackGroundCheck(trainingVolunteersIdsSet, '2');
        }
        
        if(coiTrainingVolunteerIdsSet.size() > 0 && coiOutOfComplianceVolunteerIdsSet.size() == 0 ){
            updateConflictOfInterest(coiTrainingVolunteerIdsSet, '2');
        }
    }
    
    // This method is used to update the BC record based on the volunteer role status 
    public static void updateBackGroundCheck(Set<ID> volunteerIdsSet, String status){
        List<Background_check__c> updatebackgroundCheckList = new List<Background_check__c>();
        system.debug('-----> inside updateBackGroundCheck' + status);
        for(Background_check__c currBack: [SELECT ID,Current__c,Volunteer__c FROM Background_check__c WHERE Volunteer__c IN:volunteerIdsSet AND Current__c = true]){
            if(status == 'training' ){
                currBack.VolunteerRoleTrainedTpendChapReview__c = true;
                
            }
            else if(status == 'outOfCompliance' ){
                currBack.VolunteerRoleOutofCompliance__c = true;
            }
            else if(status == 'none'){
                currBack.VolunteerRoleTrainedTpendChapReview__c = false;
                currBack.VolunteerRoleOutofCompliance__c = false;
                
            }
            else if(status == '1'){
                currBack.VolunteerRoleTrainedTpendChapReview__c = false;
            }
            else if(status == '2'){
                currBack.VolunteerRoleOutofCompliance__c = false;
            }
            updatebackgroundCheckList.add(currBack);
        }
        system.debug('-----> inside updatebackgroundCheckList' + updatebackgroundCheckList);
        if(updatebackgroundCheckList.size() > 0){
            update updatebackgroundCheckList;
        }
    }
    
    // This method is used to update the BC record based on the volunteer role status  
    public static void updateConflictOfInterest(Set<ID> volunteerIdsSet, String status){
        List<Conflict_Of_Interest__c> updateConflictList = new List<Conflict_Of_Interest__c>();
        system.debug('-----> inside updateConflictOfInterest' + status);
        for(Conflict_Of_Interest__c currCOI: [SELECT ID,Current__c,Volunteer_Contact__c FROM Conflict_Of_Interest__c WHERE Volunteer_Contact__c IN:volunteerIdsSet AND Current__c = true]){
            system.debug('Inside COI Query'+ currCOI);
            if(status == 'training' ){
                currCOI.VolunteerRoleTrainedTpendChapReview__c = true;
            }
            else if(status == 'outOfCompliance' ){
                currCOI.VolunteerRoleOutofCompliance__c = true;
            }
            else if(status == 'none'){
                currCOI.VolunteerRoleTrainedTpendChapReview__c = false;
                currCOI.VolunteerRoleOutofCompliance__c = false;
            }
            else if(status == '1'){
                currCOI.VolunteerRoleTrainedTpendChapReview__c = false;
            }
            else if(status == '2'){
                currCOI.VolunteerRoleOutofCompliance__c = false;
            }
            updateConflictList.add(currCOI);
        }
        system.debug('---> updateConflictList'+ updateConflictList);
        if(updateConflictList.size() > 0){
            update updateConflictList;
        }
    }
}