make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DevStaffEmail__c</fullName>
        <description>This field will holds dev staff email</description>
        <label>Dev Staff Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Phone__c</fullName>
        <description>It will capture the emergency contact phone details</description>
        <label>Emergency Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_Wish_Form_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the wish form Id</description>
        <label>Wish Form</label>
        <referenceTo>Wish_Child_Form__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Kind_Approval_Status__c</fullName>
        <description>Picklist state status of in-kind approval</description>
        <label>Hidden In-Kind Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wish_Co_ordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to the wish coordinator(User)</description>
        <label>Wish Co-ordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This field holds the state name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Emergency_Contact_Phone__c</fullName>
        <description>It will hold the emergency contact number.</description>
        <label>Emergency Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Race_Ethnicity__c</fullName>
        <description>It will be used for statistical purpose</description>
        <label>Race/Ethnicity</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaska Native</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian/Other Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>Not Reported</fullName>
                </value>
                <value>
                    <fullName>White or Caucasian</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/Wish_Child_Form__c.object
<CustomObject>
    <description>It will hold the value of Wish Child, Wish Info and Wish Family values.</description>
    <fields>
        <fullName>Case_Team_Member1__c</fullName>
        <description>It holds the updated case team member details.</description>
        <label>Case Team Member1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Team_Member2__c</fullName>
        <description>It will hold the updated Case Team Member details.</description>
        <label>Case Team Member2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It lookup to case record</description>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wish</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipName>Wish_Child_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Emergency_First_Name__c</fullName>
        <label>Emergency First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Last_Name__c</fullName>
        <label>Emergency Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Mobilephone__c</fullName>
        <label>Emergency mobilephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Emergency_Relationship__c</fullName>
        <label>Emergency Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Other Family</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbour</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race_Ethnicity__c</fullName>
        <label>Race/Ethnicity</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaska Native</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian/Other Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>White or Caucasian</fullName>
                </value>
                <value>
                    <fullName>Middle Eastern</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>Hispanic, Latino or Spanish</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Wish Paperwork Packet</label>
    <nameField>
        <displayFormat>WC-{00}</displayFormat>
        <label>Wish Child Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Paperwork Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/AccountTrigger_Test.cls
/*****************************************************************************************************************
Author      : MST Solutions
Date        : 6/1/2016
Description : 
*******************************************************************************************************************/
@IsTest
public class AccountTrigger_Test {

	@TestSetup static void createRecords() {
		insert OrientationandTrainingUtil.createrSystemAdminUser();
	}

	static testMethod void inKindDonor() {
		User sysAdmin = [
				SELECT Id, Username, Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				LIMIT 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;

		Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
		insert volunteerContact;

		System.runAs (new User(Id = UserInfo.getUserId())) {
			User volunteerUser = OrientationandTrainingUtil.CreateActiveVolunteerUser(volunteerContact.Id);
			insert volunteerUser;
		}
		//System.RunAs(volunteerUser) {
		Id inKindDonorsAccountRTId = Constant_AC.IN_KIND_ACCOUNT_ID;
		Account inkindAccount = new Account();
		inkindAccount.Name = 'InKind Account';
		inkindAccount.RecordTypeId = inKindDonorsAccountRTId;
		inkindAccount.Chapter_Name__c = chapterAccount.Id;
		insert inkindAccount;
		inkindAccount.Wish_Co_ordinator__c = sysAdmin.Id;
		update inkindAccount;
		//}
	}

	static testmethod void inKindDonorUpdateChapterName() {
		User sysAdmin = [
				SELECT Id,userName,Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				limit 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;

		Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
		insert volunteerContact;

		System.runAs (new User(Id = UserInfo.getUserId())) {
			User volunteerUser = OrientationandTrainingUtil.CreateActiveVolunteerUser(volunteerContact.Id);
			insert volunteerUser;
		}

		Account inkindAccount = OrientationandTrainingUtil.inKindAccountWithStatus();
		inkindAccount.Chapter_Name__c = chapterAccount.Id;
		inkindAccount.In_Kind_Approval_Status__c = 'Rejected';
		insert inkindAccount;
	}

	static testmethod void inKindDonorUpdateNullChapterName() {
		User sysAdmin = [
				SELECT Id,userName,Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				limit 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;

		Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
		insert volunteerContact;

		System.runAs (new User(Id = UserInfo.getUserId())) {
			User volunteerUser = OrientationandTrainingUtil.CreateActiveVolunteerUser(volunteerContact.Id);
			insert volunteerUser;
		}

		Account inkindAccount = OrientationandTrainingUtil.inKindAccountWithSChpater(chapterAccount.id);
		//inkindAccount.Chapter_Name__c = null;
		inkindAccount.In_Kind_Approval_Status__c = 'Approved';
		insert inkindAccount;
	}

	//Account with wishCoordinator Not Null
	static testmethod void wishCoordinatorNotNull() {
		User sysAdmin = [
				SELECT Id,userName,Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				limit 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;

		Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
		insert volunteerContact;

		User volunteerUser = new User();
		System.runAs (new User(Id = UserInfo.getUserId())) {
			volunteerUser = OrientationandTrainingUtil.CreateActiveVolunteerUser(volunteerContact.Id);
			insert volunteerUser;
		}

		System.RunAs(volunteerUser) {
			Account inkindAccount = OrientationandTrainingUtil.inKindAccount();

			try {
				insert inkindAccount;
			} catch (Exception e) {
				Boolean expectedExceptionThrown = (e.getMessage().contains('There is no approver for this account.')) ? true : false;
				System.AssertEquals(expectedExceptionThrown, false);
			}

		}
	}

	//Account and wishCoordinator as null
	static testmethod void accountWishCoordinatorAsNull() {
		User sysAdmin = [
				SELECT Id,userName,Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				limit 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;
		chapterAccount.Wish_Co_ordinator__c = null;
		update chapterAccount;
		chapterAccount.Wish_Co_ordinator__c = userinfo.getUserId();
		update chapterAccount;
		chapterAccount.Wish_Co_ordinator__c = sysAdmin.id;
		update chapterAccount;

		Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
		insert volunteerContact;

		User volunteerUser = new User();
		System.runAs (new User(Id = UserInfo.getUserId())) {
			volunteerUser = OrientationandTrainingUtil.CreateActiveVolunteerUser(volunteerContact.Id);
			insert volunteerUser;
		}
		System.RunAs(volunteerUser) {
			Account inkindAccount = OrientationandTrainingUtil.inKindAccount();
			Database.SaveResult result = Database.insert(inkindAccount, false);
			// System.assertEquals('There is no approver for this account.',result.getErrors()[0].getMessage());

		}
	}

	//Account and wishCoordinator as null
	static testmethod void chapterName() {
		User sysAdmin = [
				SELECT Id,userName,Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				limit 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;

		Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
		insert volunteerContact;

		User volunteerUser = new User();
		System.runAs (new User(Id = UserInfo.getUserId())) {
			volunteerUser = OrientationandTrainingUtil.CreateActiveVolunteerUser(volunteerContact.Id);
			insert volunteerUser;
		}
		System.RunAs(volunteerUser) {
			Account inkindAccount = OrientationandTrainingUtil.inKindAccount();
			try {
				insert inkindAccount;
			} catch (Exception e) {
				// Do nothing
			}
		}
	}

	static testmethod void AddFlagonHouseHoldAccount() {
		Bypass_Triggers__c turnOnHouseHold = new Bypass_Triggers__c();
		turnOnHouseHold.setupownerId = userinfo.getUserId();
		insert turnOnHousehold;
		Account chapterAccount = OrientationandTrainingUtil.HouseHoldAccount();
		insert chapterAccount;
	}

	static testmethod void updateChapterAccountDevEmail() {
		User sysAdmin = [
				SELECT Id,userName,Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				limit 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;

		Case parentCase = OrientationandTrainingUtil.CreateParentCaseWithStatus();
		parentCase.ChapterName__c = chapterAccount.id;
		parentCase.Closed_Date__c = system.today();
		insert parentCase;

		Contact wishChildCon = OrientationandTrainingUtil.CreateWishChildCon();
		insert wishChildCon;

		Case wishGranting = OrientationandTrainingUtil.createWishGrantCase(wishChildCon.id, parentCase.id);
		insert wishGranting;

		chapterAccount.DevStaffEmail__c = 'chandru.406@gmail.com';
		update chapterAccount;
	}

	static testmethod void upadteHouseHoldAccount() {
		Id emergencyContactRecordTypeId = Constant_AC.WISH_FORM_CHILD_EMERGENCY_ID;
		Account houseHoldAccouont = OrientationandTrainingUtil.HouseHoldAccount();
		insert houseHoldAccouont;

		Case parentCase = OrientationandTrainingUtil.CreateParentCaseWithStatus();
		insert parentCase;

		Wish_Child_Form__c emergencyContact = new Wish_Child_Form__c();
		emergencyContact.Emergency_Relationship__c = 'Employee';
		emergencyContact.Emergency_First_Name__c = 'TestEmployee';
		emergencyContact.Emergency_Last_Name__c = 'TestLastEmployee';
		emergencyContact.Emergency_Mobilephone__c = '9600467559';
		emergencyContact.Race_Ethnicity__c = 'American Indian or Alaska Native';
		emergencyContact.Case_Team_Member1__c = 'Test Chandru';
		emergencyContact.Case_Team_Member2__c = 'Test Kesav';
		emergencyContact.Driver_Information__c = '{"type":"","state":"Alabama","licenseNum":"Test","expirationDate":"2019-10-02","driverName":"Father - Chandr Sek"}]';
		emergencyContact.Case__c = parentCase.id;
		emergencyContact.RecordTypeId = emergencyContactRecordTypeId;
		insert emergencyContact;
		houseHoldAccouont.Emergency_Contact_Phone__c = '9877665544';
		houseHoldAccouont.Hidden_Wish_Form_Id__c = emergencyContact.id;
		update houseHoldAccouont;
	}

	static testMethod void createInkindSysAdmin() {
		User sysAdmin = [
				SELECT Id, Username, Email
				FROM User
				WHERE Email = :'testmawa@gmail.com'
				LIMIT 1
		];
		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccountWithWishCoordinatior(sysAdmin.Id);
		insert chapterAccount;

		Id inKindDonorsAccountRTId = Constant_AC.IN_KIND_ACCOUNT_ID;
		System.runAs(sysAdmin) {
			Account inkindAccount = new Account();
			inkindAccount.Name = 'InKind Account';
			inkindAccount.RecordTypeId = inKindDonorsAccountRTId;
			inkindAccount.Chapter_Name__c = chapterAccount.Id;
			insert inkindAccount;
		}
	}
}