make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This field holds the state name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Hour_Spent_Hidden__c</fullName>
        <description>This field is used to store the value of total hour spent by the volunteer opportunity to complete this task.</description>
        <label>Total Hour Spent Hidden</label>
        <precision>13</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hour_Spent__c</fullName>
        <label>Total Hour Spent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter details and role for this chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the role name and chapters assigned for this role.</description>
        <label>Role Name</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active_Wish_Granter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Organization Affiliation=Active, Conflict of Interest=Not Expired, BGC=Not Expired, (Volunteer Role of Wish Granter=Trained or Volunteer Role of Wish Granter Mentor=Trained)</description>
        <label>Active Wish Granter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_last_engagement__c</fullName>
        <description>It capture the volunteer last engagement  date.</description>
        <label>Date Of Last Engagement</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of the chapter role.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Non-Wish &amp; Events</relationshipLabel>
        <relationshipName>Non_Wish_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will define the location of the event</description>
        <label>Chapter</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>It store the event date field</description>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>It holds the name of the Event.</description>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Hour_Spent_Hidden__c</fullName>
        <description>This field is used to store the how many hours have spent for this Non Wish &amp; Event.</description>
        <label>Total Hour Spent Hidden</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hour_Spent__c</fullName>
        <description>This field is used to store the total time spent for volunteer to complete the Non-Wish &amp; Event.</description>
        <label>Total Hour Spent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Non_Wish_Events__c.object
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is used to store the description of the chapter role. This field is used as hidden field.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Display description for each chapter role.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Time_sheet__c.object
<CustomObject>
    <description>This object is used to track the time spent by the volunteer contact to close the wish or Non Wish &amp; Event</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used to track the date value of when volunteer is entered.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is used to store the value of description entered by the volunteer.</description>
        <label>Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours_Hidden__c</fullName>
        <description>This field is used as hidden field to store the hours value.</description>
        <label>Hours Hidden</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_spent__c</fullName>
        <description>This field is used to track how many hours the volunteer have spent for the volunteer opportunity.</description>
        <inlineHelpText>Please enter two digits on decimal place.</inlineHelpText>
        <label>Hours spent</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <description>This field is used to store the volunteer opportunity records.</description>
        <label>Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Time sheet</relationshipLabel>
        <relationshipName>Time_sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time sheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the chapter named of Account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is used to store the description value entered from Add voulnteer role vf page</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>Event date indicated when the event started</description>
        <formula>Non_Wish_Event__r.Event_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>This Holds the value of event name</description>
        <formula>Non_Wish_Event__r.Event_Name__c</formula>
        <label>Non-WIsh/Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Wish_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It hold the record of each event</description>
        <label>Name</label>
        <referenceTo>Non_Wish_Events__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It will display the role name</description>
        <formula>Chapter_Role_Opportunity__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/TimesheetServiceTest.cls
/**
* @description Test class for Timesheet Service
* @author Michelle Cominotto, Make-A-Wish
* @createdDate 4/14/2020
*/
@isTest
private class TimesheetServiceTest {
    private final static Id CHAPTER_RT_ID = Constant_AC.CHAPTER_RT_ID;
    private final static Id VOLUNTEER_RT_ID = Constant_AC.VOLUNTEER_RT_ID;
    private final static String CHAPTER_ROLE_WISH_GRANTER = Constant_AC.CHAPTER_ROLE_WISH_GRANTER;
    private final static Id NON_WISH_EVENT_RT_ID = Constant_AC.NON_WISH_EVENT_RT_ID;
    
    @TestSetup
    private static void setup() {
        trac_TriggerHandlerBase.blockTrigger = true;
        
        List<Account> accounts = TestDataFactory.createAccount(1);
        Account accountAzChapter = accounts.get(0);
        accountAzChapter.Name = 'Make-A-Wish Arizona';
        accountAzChapter.RecordTypeId = CHAPTER_RT_ID;
        insert accounts;
        
        List<Contact> contactList = TestDataFactory.createContact(1);
        Contact volunteerJane = contactList.get(0);
        volunteerJane.FirstName = 'Jane';
        volunteerJane.LastName = 'Eyre';
        volunteerJane.Email = 'jane.eyre@testmail.com';
        volunteerJane.RecordTypeId = VOLUNTEER_RT_ID;
        volunteerJane.AccountId = accountAzChapter.Id;
        volunteerJane.Active_Wish_Granter__c = false;
        insert contactList;
        
        List<Case> caseList = TestDataFactory.createCase(1);
        Case wishCase = caseList.get(0);
        wishCase.Total_Hour_Spent_Hidden__c = 0.00;
        insert caseList;
        
        List<Role__c> wishRolesList = TestDataFactory.createRole(1, true);
        Role__c wishGranter = wishRolesList.get(0);
        wishGranter.Name = CHAPTER_ROLE_WISH_GRANTER;
        insert wishRolesList;
        
        List<Chapter_Role__c> chapterRoleList = TestDataFactory.createChapterRole(1);
        Chapter_Role__c chapterRoleWishGranter = chapterRoleList.get(0);
        chapterRoleWishGranter.Chapter_Name__c = accountAzChapter.Id;
        chapterRoleWishGranter.Role_Name__c = wishGranter.Id;
        insert chapterRoleList;
        
        List<Non_Wish_Events__c> nonWishEvents = TestDataFactory.createNonwishEvent(1);
        Non_Wish_Events__c nonWishEventMeetup = nonWishEvents.get(0);
        nonWishEventMeetup.Event_Name__c = 'Arizona Chapter Case Review';
        nonWishEventMeetup.Chapter__c = accountAzChapter.Id;
        nonWishEventMeetup.Event_Date__c = Date.today().addDays(-7);
        nonWishEventMeetup.Total_Hour_Spent_Hidden__c = 0.0;
        insert nonWishEvents;
        
        List<Volunteer_Opportunity__c> volOppsList = TestDataFactory.createVolunteerOpportunity(2);
        Volunteer_Opportunity__c volOpp1 = volOppsList.get(0);
        volOpp1.Volunteer_Name__c = volunteerJane.Id;
        volOpp1.Non_Wish_Event__c = nonWishEventMeetup.Id;
        volOpp1.RecordTypeId = NON_WISH_EVENT_RT_ID;
        Volunteer_Opportunity__c volOpp2 = volOppsList.get(1);
        volOpp2.Volunteer_Name__c = volunteerJane.Id;
        volOpp2.Chapter_Name__c = accountAzChapter.Id;
        volOpp2.Wish__c = wishCase.Id;
        insert volOppsList;
        
        List<Time_sheet__c> timesheetsList = TestDataFactory.createTimesheet(2);
        Time_sheet__c nonWishTimesheet = timesheetsList.get(0);
        nonWishTimesheet.Volunteer_Opportunity__c = volOpp1.Id;
        nonWishTimesheet.Date__c =  Date.today().addDays(-7);
        nonWishTimesheet.Description__c = 'Case Reviews';
        nonWishTimesheet.Hours_spent__c = 2.5;
        nonWishTimesheet.Hours_Hidden__c = 170;
        Time_sheet__c wishTimesheet = timesheetsList.get(1);
        wishTimesheet.Volunteer_Opportunity__c = volOpp2.Id;
        wishTimesheet.Date__c = Date.today().addDays(-3);
        wishTimesheet.Hours_spent__c = 1.5;
        wishTimesheet.Hours_Hidden__c = 110;
        wishTimesheet.Description__c = 'Wish Evaluation';
        insert timesheetsList;
        
        trac_TriggerHandlerBase.blockTrigger = false;
    }
    
    @isTest 
    private static void validateSplitHoursMinutes() {
        Map<Id, Time_sheet__c> timesheetMap = new Map<Id, Time_sheet__c>([
            SELECT Id, Hours_spent__c, Hours_Hidden__c
            FROM Time_sheet__c
        ]);
        for(Time_sheet__c sheet : timesheetMap.values()) {
            sheet.Hours_spent__c = 3.5;
        }
        Test.startTest();
        update timesheetMap.values();
        Test.stopTest();
        List<Time_sheet__c> timesheetsListUpdated = [
            SELECT Id, Hours_spent__c, Hours_Hidden__c 
            FROM Time_sheet__c 
            WHERE Id IN :timesheetMap.keySet()];
        system.assert(timesheetsListUpdated[0].Hours_Hidden__c == 230);
    }
    
    @isTest
    private static void validateCalculateHoursOfWish() {
        Map<Id, Time_sheet__c> caseTimesheetMap = new Map<Id, Time_sheet__c>();
        for(Time_sheet__c sheet : [
            SELECT Id, Hours_spent__c, Volunteer_Opportunity__c, Volunteer_Opportunity__r.Wish__c 
            FROM Time_sheet__c 
            WHERE Volunteer_Opportunity__r.Wish__c != null]) {
                caseTimesheetMap.put(sheet.Volunteer_Opportunity__r.Wish__c, sheet);
            }
        Test.startTest();
        TimesheetService.calculateHoursOfWish(caseTimesheetMap.values());
        Test.stopTest();
        List<Case> caseList = [
            SELECT Id, Total_Hour_Spent_Hidden__c 
            FROM Case 
            WHERE Id IN :caseTimesheetMap.keySet()];
        system.assert(caseList[0].Total_Hour_Spent_Hidden__c == caseTimesheetMap.get(caseList[0].Id).Hours_spent__c);
    }
    
    @isTest
    private static void validateCalculateHoursOfNonwish() {
        Map<Id, Time_sheet__c> nonWishTimesheetMap = new Map<Id, Time_sheet__c>();
        for(Time_sheet__c sheet : [
            SELECT Id, Hours_spent__c, Volunteer_Opportunity__c, Volunteer_Opportunity__r.Non_Wish_Event__c 
            FROM Time_sheet__c 
            WHERE Volunteer_Opportunity__r.Non_Wish_Event__c != null]) {
                nonWishTimesheetMap.put(sheet.Volunteer_Opportunity__r.Non_Wish_Event__c, sheet);
            }
        Test.startTest();
        TimesheetService.calculateHoursOfNonwish(nonWishTimesheetMap.values());
        Test.stopTest();
        List<Non_Wish_Events__c> nonWishEventsList = [
            SELECT Id, Total_Hour_Spent__c, Total_Hour_Spent_Hidden__c 
            FROM Non_Wish_Events__c 
            WHERE Id IN :nonWishTimesheetMap.keySet()];
        system.assert(nonWishEventsList[0].Total_Hour_Spent_Hidden__c == nonWishTimesheetMap.get(nonWishEventsList[0].Id).Hours_spent__c);
    }
    
    @isTest
    private static void validateFindRecentTimesheetDate() {
        Map<Id, Time_sheet__c> volunteerTimesheetMap = new Map<Id, Time_sheet__c>();
        for(Time_sheet__c sheet : [
            SELECT Id, Date__c, Volunteer_Opportunity__c, Volunteer_Opportunity__r.Volunteer_Name__c 
            FROM Time_sheet__c 
            WHERE Volunteer_Opportunity__r.Volunteer_Name__c != null]) {
                volunteerTimesheetMap.put(sheet.Volunteer_Opportunity__r.Volunteer_Name__c, sheet);
            }
        Test.startTest();
        TimesheetService.findRecentTimesheetDate(volunteerTimesheetMap.values());
        Test.stopTest();
        List<Contact> volunteerList = [
            SELECT Id, Date_of_last_engagement__c 
            FROM Contact 
            WHERE Id IN :volunteerTimesheetMap.keySet()];
        system.assert(volunteerList[0].Date_of_last_engagement__c == volunteerTimesheetMap.get(volunteerList[0].Id).Date__c);
    }
}