make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DevStaffEmail__c</fullName>
        <description>This field will holds dev staff email</description>
        <label>Dev Staff Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>It will holds the account email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Middle_Name__c</fullName>
        <description>It holds the Emergency Contact Middle Name value.</description>
        <label>Emergency Contact Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Phone__c</fullName>
        <description>It will capture the emergency contact phone details</description>
        <label>Emergency Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_Wish_Form_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the wish form Id</description>
        <label>Wish Form</label>
        <referenceTo>Wish_Child_Form__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Kind_Approval_Status__c</fullName>
        <description>Picklist state status of in-kind approval</description>
        <label>Hidden In-Kind Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_type__c</fullName>
        <description>It will capture the relationship information</description>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Step-mother</fullName>
                </value>
                <value>
                    <fullName>Step-father</fullName>
                </value>
                <value>
                    <fullName>Step-sister</fullName>
                </value>
                <value>
                    <fullName>Step-brother</fullName>
                </value>
                <value>
                    <fullName>Half-sister</fullName>
                </value>
                <value>
                    <fullName>Half-brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
                <value>
                    <fullName>Granddaughter</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wish_Co_ordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to the wish coordinator(User)</description>
        <label>Wish Co-ordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Account_OnAfterUpdateTriggerHandler.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 10/15/2016
Description : Account_OnAfterUpdateTriggerHandler is used to call the Helper class when the
              account record is get updated.

              Modification Log
              ------------------
              WVC-1884    KANAGARAJ  03/04/2018

*****************************************************************************************************/
public class Account_OnAfterUpdateTriggerHandler {
    /*This method is used to call the updateGrantingCaseDevStaffEmail and updateChapterName method when the
    account record gets updated.*/
    public static void onAfterUpdate(Map<Id,Account> newAccountMap,Map<Id,Account> oldAccountMap){

        Id chapterAccountRTId = Constant_AC.CHAPTER_RT_ID;
        Id inKindDonorsAccountRTId = Constant_AC.IN_KIND_ACCOUNT_ID;
        Id householdAccountId = Constant_AC.HOUSEHOLD_RT_ID;
        Set<String> accountIdsSet = new Set<String>();
        Set<Id> chapterIdsSet = new Set<Id>();
        Set<Id> houseHoldAccountIdsSet = new Set<Id>();
        Map<Id, Id> accWishCoorUpdateMap = new Map<Id, Id>();
        Map<Id, String> chapterEmailmap = new Map<Id, String>();
        List<Account> accountList = new List<Account>();
        List<Account> wishFormAccountList = new List<Account>();
       //This for loop is used to remove inkind account from the public group based on updated chapter name
        for(Account currentAccount : newAccountMap.values())
        {

            if(currentAccount.Wish_Co_ordinator__c != null && currentAccount.Wish_Co_ordinator__c != oldAccountMap.get(currentAccount.Id).Wish_Co_ordinator__c) {
                accWishCoorUpdateMap.put(currentAccount.Id, currentAccount.Wish_Co_ordinator__c);
            }

            if(currentAccount.RecordTypeId == inKindDonorsAccountRTId)
            {
                if(currentAccount.In_Kind_Approval_Status__c == 'Rejected' && oldAccountMap.get(currentAccount.id).In_Kind_Approval_Status__c != 'Rejected') {
                    accountIdsSet.add(currentAccount.id);
                    chapterIdsSet.add(currentAccount.Chapter_Name__c);
                    accountList.add(currentAccount);
                }
                if((currentAccount.Chapter_Name__c != oldAccountMap.get(currentAccount.id).Chapter_Name__c && currentAccount.In_Kind_Approval_Status__c != 'Rejected') ||
                   currentAccount.Chapter_Name__c == Null &&  oldAccountMap.get(currentAccount.id).Chapter_Name__c != NUll){
                       accountIdsSet.add(currentAccount.id);
                       chapterIdsSet.add(oldAccountMap.get(currentAccount.id).Chapter_Name__c);
                       accountList.add(currentAccount);
                   }
            }

            if(currentAccount.RecordTypeId == chapterAccountRTId && currentAccount.DevStaffEmail__c != Null &&
               currentAccount.DevStaffEmail__c != oldAccountMap.get(currentAccount.id).DevStaffEmail__c){
                   chapterEmailmap.put(currentAccount.id, currentAccount.DevStaffEmail__c);
               }

            if(currentAccount.RecordTypeId == householdAccountId && (currentAccount.BillingStreet != oldAccountMap.get(currentAccount.id).BillingStreet || currentAccount.BillingCity != oldAccountMap.get(currentAccount.id).BillingCity || currentAccount.BillingState != oldAccountMap.get(currentAccount.id).BillingState
                                                                      || currentAccount.BillingCountry != oldAccountMap.get(currentAccount.id).BillingCountry || currentAccount.BillingPostalCode != oldAccountMap.get(currentAccount.id).BillingPostalCode)){
                houseHoldAccountIdsSet.add(currentAccount.id);
            }

            if(currentAccount.RecordTypeId == householdAccountId && (currentAccount.Emergency_Contact_Phone__c != oldAccountMap.get(currentAccount.id).Emergency_Contact_Phone__c || currentAccount.Relationship_type__c != oldAccountMap.get(currentAccount.id).Relationship_type__c || currentAccount.Emergency_Contact_Middle_Name__c != oldAccountMap.get(currentAccount.id).Emergency_Contact_Middle_Name__c
                                                                      || currentAccount.Email__c != oldAccountMap.get(currentAccount.id).Email__c) && currentAccount.Hidden_Wish_Form_Id__c != Null){
                    wishFormAccountList.add(currentAccount);
            }
        }

        if(chapterEmailmap.size() > 0){
            Account_OnAfterUpdateTriggerHelper.updateGrantingCaseDevStaffEmail(chapterEmailmap);
        } 
        if(chapterIdsSet.size() > 0){
        Account_OnAfterUpdateTriggerHelper.updateChapterName(chapterIdsSet,accountList);
        }

        if(houseHoldAccountIdsSet.size() > 0){
            Account_OnAfterUpdateTriggerHelper.updateRelatedContactAddressWithHoushold(houseHoldAccountIdsSet);
        }
        if(wishFormAccountList.size() > 0){
        Account_OnAfterUpdateTriggerHelper.updateWishFormRecord(wishFormAccountList);
        }


    }
}