make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Region_Chapter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the contact region chapter</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Region Chapter)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This Field hold the name of the state.</description>
        <formula>&apos;Make-A-Wish &apos;+State</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ChapterChangeConfirmationPopup_AC.cls
/**
 * @description It called the when the chapter is changed in lead record.
 *
 * @author MST Solutions
 **/
global class ChapterChangeConfirmationPopup_AC {

    public ChapterChangeConfirmationPopup_AC(ApexPages.StandardController controller) {
    }

    /**
     * @description Updates Lead's ChapterName
     *
     * @param opt
     * @param leadId
     *
     * @return
     */
    @RemoteAction
    global static String updateLeadChapter(String opt, String leadId) {
        List<Id> leadIds = new List<Id>();
        leadIds.add(leadId);
        Map<Id, Lead> leadMap = new Map<Id, Lead>();
        if (opt == 'revert') {
            leadMap = LeadService.revertChapterNameChange(leadIds);
        } else {
            leadMap = LeadService.backupChapterNameChange(leadIds);
        }
        return leadMap.get(leadId).Hidden_Chapter_Change_Confirmation__c;
    }
    
    @RemoteAction
    global static void updateContactChapter(String action, String contactId) {
        Contact mpContact = [SELECT Id, Hidden_Chapter__c, Region_Chapter__c FROM Contact WHERE Id = :contactId];        
        if(action == 'revert') {
            mpContact.Region_Chapter__c = mpContact.Hidden_Chapter__c;
        } else {
            mpContact.Hidden_Chapter__c = mpContact.Region_Chapter__c;
        }
        try {
            update mpContact;
        } catch(Exception ex) {
            ErrorMessage_AC.createDebugRec('ChapterChangeConfirmationPopup_AC', String.valueOf(mpContact), String.valueOf(ex),
                                           'updateContactChapter', mpContact.Id, ex.getStackTraceString() + ' ' + ex.getMessage(), 'Error');
            mpContact.addError(Label.Debug_log_error_message);
        }
    }
    
    @RemoteAction
    global static void updateAccountChapter(String action, String accountId) {
        Account htfAccount = [SELECT Id, Hidden_Chapter__c, Chapter_Name__c FROM Account WHERE Id = :accountId];        
        if(action == 'revert') {
            htfAccount.Chapter_Name__c = htfAccount.Hidden_Chapter__c;
        } else {
            htfAccount.Hidden_Chapter__c = htfAccount.Chapter_Name__c;
        }
        try {
            update htfAccount;
        } catch(Exception ex) {
            ErrorMessage_AC.createDebugRec('ChapterChangeConfirmationPopup_AC', String.valueOf(htfAccount), String.valueOf(ex),
                                           'updateAccountChapter', htfAccount.Id, ex.getStackTraceString() + ' ' + ex.getMessage(), 'Error');
            htfAccount.addError(Label.Debug_log_error_message);
        }
    }
}