make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Action_Track__c.object
<CustomObject>
    <description>It holds list of tasks for child wishes</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <description>it holds case team role to which the task should assigned</description>
        <label>Assigned To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volunteer Manager</fullName>
                </value>
                <value>
                    <fullName>Wish Coordinator</fullName>
                </value>
                <value>
                    <fullName>Wish Granter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type_Stage__c</fullName>
        <description>It holds the wish type which it is belongs to.</description>
        <label>Case Type/Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Wish Determination</fullName>
                </value>
                <value>
                    <fullName>Wish Planning &amp; Anticipation</fullName>
                </value>
                <value>
                    <fullName>Wish Assist</fullName>
                </value>
                <value>
                    <fullName>Wish Grant</fullName>
                </value>
                <value>
                    <fullName>Wish Effect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the Chapter Name</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Action Tracks</relationshipLabel>
        <relationshipName>Chapter_Action_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>it describes the Due date for Tasks</description>
        <label>Due Date</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <description>It will display the recurring frequency value.</description>
        <label>Recurring Frequency</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It determines whether the action is recurring or not</description>
        <label>Recurring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>It holds the value for Sorting Order</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wish_type__c</fullName>
        <description>it holds the details of types of wish</description>
        <label>Wish type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Disney World</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Shopping Spree-Local</fullName>
                </value>
                <value>
                    <fullName>Travel-International</fullName>
                </value>
                <value>
                    <fullName>Cruise-Celebrity/Royal</fullName>
                </value>
                <value>
                    <fullName>Cruise-Disney</fullName>
                </value>
                <value>
                    <fullName>Cruise-Other</fullName>
                </value>
                <value>
                    <fullName>Travel-Hawai</fullName>
                </value>
                <value>
                    <fullName>Travel-Other</fullName>
                </value>
                <value>
                    <fullName>Shopping Spree-Travel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Chapter Action Track</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Action Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/classes/ChapterActionTrack_Test.cls
/************************************************************************************
Created Date :  8/8/2016
Author : Mst Solutions
Description : Unit Test for Chapter_Action_Track__c and ChapterActionTrackHandler
*************************************************************************************/
@isTest
public class ChapterActionTrack_Test {
  /*  
    //Used to create chapter and chapter action record
    @testSetup static void setup(){  
        Account newchapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
        Chapter_Action_Track__c newAction = OrientationandTrainingUtil.createChapterActionTrack();
        newAction.Chapter_Name__c = newchapterAccount.Id;
        newAction.Sort_Order__c = 1;
        insert newAction;
    }
    
    // Used to test validation if recurring frequency set to null
    @isTest static void updateChapterAction(){ 
        Chapter_Action_Track__c chapterAction =  [SELECT Id, Wish_type__c, Sort_Order__c, Recurring_Frequency__c, Recurring__c, Due_Date__c, Chapter_Name__c, Case_Type_Stage__c FROM Chapter_Action_Track__c];
        chapterAction.Sort_Order__c = 3;
        chapterAction.Recurring__c = true;
        chapterAction.Recurring_Frequency__c = null;
        chapterAction.Wish_type__c = 'Disney';
        chapterAction.Case_Type_Stage__c = 'Wish Planning & Anticipation';
        Database.saveResult result = Database.update(chapterAction,false);
        System.assertEquals('Recurring Frequency cannot be blank for Recurring Task',result.getErrors()[0].getMessage());
      
    }
    
    // Used to test validation if sort order set to null
    @isTest static void sortOrderAsNull(){ 
        Chapter_Action_Track__c chapterAction =  [SELECT Id, Wish_type__c, Sort_Order__c, Recurring_Frequency__c, Recurring__c, Due_Date__c, Chapter_Name__c, Case_Type_Stage__c FROM Chapter_Action_Track__c];
        chapterAction.Recurring__c = true;
        chapterAction.Sort_Order__c = null;
        chapterAction.Recurring_Frequency__c = 10;
        chapterAction.Wish_type__c = 'Disney';
        chapterAction.Case_Type_Stage__c = 'Wish Planning & Anticipation';
        Database.saveResult result = Database.update(chapterAction,false);
        System.assertEquals('Please Enter Sort Order',result.getErrors()[0].getMessage());
    }
    
    // Used to test validation if sort order set to zero
    @isTest static void sortOrderSizeCheck(){ 
        Chapter_Action_Track__c chapterAction =  [SELECT Id, Wish_type__c, Sort_Order__c, Recurring_Frequency__c, Recurring__c, Due_Date__c, Chapter_Name__c, Case_Type_Stage__c FROM Chapter_Action_Track__c];
        chapterAction.Recurring__c = true;
        chapterAction.Sort_Order__c = 0;
        chapterAction.Recurring_Frequency__c = 10;
        chapterAction.Wish_type__c = 'Disney';
        chapterAction.Case_Type_Stage__c = 'Wish Planning & Anticipation';
        Database.saveResult result = Database.update(chapterAction,false);
        System.assertEquals('Please Enter Sort Order greater than 0',result.getErrors()[0].getMessage());
        
    }
    
    // Used to test validation if wish stage set to null
    @isTest static void wishStageCheck(){ 
        Chapter_Action_Track__c chapterAction =  [SELECT Id, Wish_type__c, Sort_Order__c, Recurring_Frequency__c, Recurring__c, Due_Date__c, Chapter_Name__c, Case_Type_Stage__c FROM Chapter_Action_Track__c];
        chapterAction.Recurring__c = true;
        chapterAction.Sort_Order__c = 0;
        chapterAction.Recurring_Frequency__c = 10;
        chapterAction.Wish_type__c = 'Disney';
        chapterAction.Case_Type_Stage__c = null;
        Database.saveResult result = Database.update(chapterAction,false);
        System.assertEquals('Please Choose Wish Stage',result.getErrors()[0].getMessage());
    }
    
    // Used to test validation if role set to null
    @isTest static void roleNullCheck(){ 
        Chapter_Action_Track__c chapterAction =  [SELECT Id, Wish_type__c, Sort_Order__c, Recurring_Frequency__c, Recurring__c, Due_Date__c, Chapter_Name__c, Case_Type_Stage__c FROM Chapter_Action_Track__c];
        chapterAction.Recurring__c = true;
        chapterAction.Sort_Order__c = 0;
        chapterAction.Recurring_Frequency__c = 10;
        chapterAction.Wish_type__c = 'Disney';
        chapterAction.Case_Type_Stage__c = 'Wish Planning & Anticipation';
        chapterAction.Assigned_To__c=null;
        Database.saveResult result = Database.update(chapterAction,false);
        System.assertEquals('Please Choose Role',result.getErrors()[0].getMessage());
    }
    
    // Used to test duplicate record creation
    @isTest static void dupCheck(){ 
        Account chapterAccount = [SELECT Id FROM Account LIMIT 1];
        Chapter_Action_Track__c newAction = OrientationandTrainingUtil.createChapterActionTrack();
        newAction.Chapter_Name__c = chapterAccount.Id;
        newAction.Sort_Order__c = 2;
        insert newAction;
        Chapter_Action_Track__c updateSortOrder = [SELECT Id, Sort_Order__c FROM Chapter_Action_Track__c WHERE Sort_Order__c = 2 LIMIT 1];
        updateSortOrder.Sort_Order__c = 1;
        Database.SaveResult result = Database.update(updateSortOrder,false);
        System.assertEquals('Duplicate Exists',result.getErrors()[0].getMessage());
    }
    
    */
}