make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter details and role for this chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the role name and chapters assigned for this role.</description>
        <label>Role Name</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ChapterRoleService.cls
/**
 * @description Chapter Role Service, centralizes Chapter Role business rules.
 * @author Gustavo Mayer, Traction on Demand
 * @createdDate 3/19/2020
 */
public class ChapterRoleService {

	private final static String ROLE_NATIONAL_STAFF = Constant_AC.ROLE_NATIONAL_STAFF;

	/**
	 * Set Role on Chapter Role
	 * @param chapterRoles
	 */
	public static void setRole(List<Chapter_Role__c> chapterRoles) {
		Set<Id> roleIds = new Set<Id>();
		Map<Id, Role__c> roleMap = new Map<Id, Role__c>();
		for (Chapter_Role__c newChapterRole : chapterRoles) {
			if (newChapterRole.Role_Name__c != null) {
				roleIds.add(newChapterRole.Role_Name__c);
			}
		}
		if (roleIds.isEmpty()) {
		}
		for (Role__c role : [
				SELECT Id,Name
				FROM Role__c
				WHERE Id IN:roleIds
		]) {
			roleMap.put(role.Id, role);
		}
		for (Chapter_Role__c newChapterRole : chapterRoles) {
			if (roleMap.containsKey(newChapterRole.Role_Name__c)) {
				newChapterRole.Role__c = roleMap.get(newChapterRole.Role_Name__c).Name;
			}
		}
	}

	/**
	 * Build Chapter Role Record Sharing Update Map
	 * @param newChapterRoleMap
	 * @return Map of List of Roles by Chapter Name
	 */
	public static Map<String, List<Chapter_Role__c>> buildChapterRoleRecordSharingUpdateMap(
			Map<Id, Chapter_Role__c> newChapterRoleMap) {
		Map<String, List<Chapter_Role__c>> chapterRoleMap = new Map<String, List<Chapter_Role__c>>();
		for (Chapter_Role__c currRec : [
				SELECT Id, Chapter_Name__c, Chapter_Name__r.Name, OwnerId, Owner.UserRoleId,
						Owner.UserRole.Name
				FROM Chapter_Role__c
				WHERE Id IN :newChapterRoleMap.keySet()
		]) {
			if (ROLE_NATIONAL_STAFF.equals(currRec.Owner.UserRole.Name)) {
				if (chapterRoleMap.containsKey(currRec.Chapter_Name__r.Name)) {
					chapterRoleMap.get(currRec.Chapter_Name__r.Name).add(currRec);
				} else {
					chapterRoleMap.put(currRec.Chapter_Name__r.Name, new List<Chapter_Role__c>{
							currRec
					});
				}
			}
		}
		return chapterRoleMap;
	}

	/**
	 * Build Chapter Role Record Sharing Update Map
	 * @param newChapterRoleMap
	 * @param oldChapterRoleMap
	 * @return Map of List of Roles by Chapter Name
	 */
	public static Map<String, List<Chapter_Role__c>> buildChapterRoleRecordSharingUpdateMap(
			Map<Id, Chapter_Role__c> newChapterRoleMap,
			Map<Id, Chapter_Role__c> oldChapterRoleMap) {
		Map<String, List<Chapter_Role__c>> chapterRoleMap = new Map<String, List<Chapter_Role__c>>();
		for (Chapter_Role__c currRec : [
				SELECT Id, Chapter_Name__c, Chapter_Name__r.Name, OwnerId, Owner.UserRoleId,
						Owner.UserRole.Name
				FROM Chapter_Role__c
				WHERE Id IN :newChapterRoleMap.keySet()
		]) {
			if (!oldChapterRoleMap.isEmpty() && currRec.OwnerId != oldChapterRoleMap.get(currRec.Id).OwnerId) {
				if (ROLE_NATIONAL_STAFF.equals(currRec.Owner.UserRole.Name)) {
					if (chapterRoleMap.containsKey(currRec.Chapter_Name__r.Name)) {
						chapterRoleMap.get(currRec.Chapter_Name__r.Name).add(currRec);
					} else {
						chapterRoleMap.put(currRec.Chapter_Name__r.Name, new List<Chapter_Role__c>{
								currRec
						});
					}
				}
			}
		}
		return chapterRoleMap;
	}
}