make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish_Co_ordinator_Hidden_Email__c</fullName>
        <description>This filed is used to get wish co-ordinator email</description>
        <label>Wish Co-ordinator Hidden Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Wish_Co_ordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to the wish coordinator(User)</description>
        <label>Wish Co-ordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/classes/Account_OnBeforeInsertTriggerHelper.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 10/15/2016
Description : Account_OnBeforeInsertTriggerHandlerHelper is used to call the Helper class when the
              new account record is created.
              
              Modification Log
              ------------------
              WVC-1884    KANAGARAJ  03/04/2018
              
*****************************************************************************************************/
Public class Account_OnBeforeInsertTriggerHelper
{
 //Used to populate chaptername and chapter email
    public static void matchChapterForInkindAccount(Set<Id> ownerIdSet, List<Account> newInkAccountList) {
        Map<Id, Account> chapterMap = new Map<Id, Account>();
        Map<Id, Id> ownerChapterMap = new Map<Id, Id>();
        Map<String, Id> nonPortalChapterMap = new Map<String, Id>();
        Map<Id, String> ownerNoPortalMap = new Map<Id, String>();
        try{
        for(Account chapterInfo : [SELECT Id, Name, Wish_Co_ordinator__r.Email FROM Account WHERE RecordType.Name = 'Chapter' Limit 50000]) {
            chapterMap.put(chapterInfo.Id, chapterInfo);
            nonPortalChapterMap.put(chapterInfo.Name.remove('Make-A-Wish ')+' - Chapter', chapterInfo.Id);
        }
        
        for(User checkUserType : [SELECT Id, ContactId, UserRole.Name, contact.AccountId FROM User WHERE Id IN : ownerIdSet Limit 50000]) {
            if(checkUserType.ContactId != NULL) {
                //For portal user
                ownerChapterMap.put(checkUserType.Id, checkUserType.Contact.AccountId);
            } else if(checkUserType.UserRole.Name != NULL && checkUserType.UserRole.Name != 'National Staff') {
                //For non portal user
                ownerNoPortalMap.put(checkUserType.Id, checkUserType.UserRole.Name);
            }
            
        }
        
        for(Account matchChapter : newInkAccountList) {
            if(ownerChapterMap.containsKey(matchChapter.OwnerId)) {
                if(chapterMap.containsKey(ownerChapterMap.get(matchChapter.OwnerId))) {
                    matchChapter.Wish_Co_ordinator_Hidden_Email__c = chapterMap.get(ownerChapterMap.get(matchChapter.OwnerId)).Wish_Co_ordinator__r.Email;
                    matchChapter.Chapter_Name__c = chapterMap.get(ownerChapterMap.get(matchChapter.OwnerId)).Id;
                }
            } else if(ownerNoPortalMap.containsKey(matchChapter.OwnerId)) {
                if(nonPortalChapterMap.containsKey(ownerNoPortalMap.get(matchChapter.OwnerId))) {
                    matchChapter.Wish_Co_ordinator_Hidden_Email__c = chapterMap.get(nonPortalChapterMap.get(ownerNoPortalMap.get(matchChapter.OwnerId))).Wish_Co_ordinator__r.Email;
                    matchChapter.Chapter_Name__c = nonPortalChapterMap.get(ownerNoPortalMap.get(matchChapter.OwnerId));
                }
            } else if(matchChapter.Chapter_Name__c == NULL && !ownerNoPortalMap.containsKey(matchChapter.OwnerId) && !ownerChapterMap.containsKey(matchChapter.OwnerId)) {
                matchChapter.addError('Please select Chapter Name');
            }
        }
    }
    catch(Exception ex){
       for(Account currRec : newInkAccountList){
             ErrorMessage_AC.createdebugRec('Account_OnBeforeInsertTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'matchChapterForInkindAccount',currRec.Id,ex.getStackTraceString(),'Error');
            }
       for(Account currRec : newInkAccountList){
             currRec.addError(Label.Debug_log_error_message);
           }
        }
    }
}