make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This field holds the state name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field will be used to know the progress(Current status) of the wish</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age Expiration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign in Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss of Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Viewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refused</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wish_type__c</fullName>
        <description>It holds the details about the  type of wish</description>
        <label>Wish type</label>
        <picklist>
            <picklistValues>
                <fullName>Cruise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GKTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Action_Track__c.object
<CustomObject>
    <description>It holds list of tasks for child wishes</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <description>it holds case team role to which the task should assigned</description>
        <label>Assigned To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volunteer Manager</fullName>
                </value>
                <value>
                    <fullName>Wish Coordinator</fullName>
                </value>
                <value>
                    <fullName>Wish Granter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type_Stage__c</fullName>
        <description>It holds the wish type which it is belongs to.</description>
        <label>Case Type/Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Wish Determination</fullName>
                </value>
                <value>
                    <fullName>Wish Planning &amp; Anticipation</fullName>
                </value>
                <value>
                    <fullName>Wish Assist</fullName>
                </value>
                <value>
                    <fullName>Wish Grant</fullName>
                </value>
                <value>
                    <fullName>Wish Effect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the Chapter Name</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Action Tracks</relationshipLabel>
        <relationshipName>Chapter_Action_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>it describes the Due date for Tasks</description>
        <label>Due Date</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <description>It will display the recurring frequency value.</description>
        <label>Recurring Frequency</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It determines whether the action is recurring or not</description>
        <label>Recurring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>It holds the value for Sorting Order</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <description>It contains name of the task</description>
        <label>Task Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wish_type__c</fullName>
        <description>it holds the details of types of wish</description>
        <label>Wish type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Disney World</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Shopping Spree-Local</fullName>
                </value>
                <value>
                    <fullName>Travel-International</fullName>
                </value>
                <value>
                    <fullName>Cruise-Celebrity/Royal</fullName>
                </value>
                <value>
                    <fullName>Cruise-Disney</fullName>
                </value>
                <value>
                    <fullName>Cruise-Other</fullName>
                </value>
                <value>
                    <fullName>Travel-Hawai</fullName>
                </value>
                <value>
                    <fullName>Travel-Other</fullName>
                </value>
                <value>
                    <fullName>Shopping Spree-Travel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Chapter Action Track</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Action Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Number_of_wishes_active__c</fullName>
        <description>It will capture the information, number of active case related to the each contacts</description>
        <label>Number Of Active Wishes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_wishes_granted__c</fullName>
        <description>It will capture the information about, number of granted case related with each volunteer contact</description>
        <label>Number Of Wishes Granted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This Field hold the name of the state.</description>
        <formula>&apos;Make-A-Wish &apos;+State</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the chapter named of Account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/CaseTriggerHandler.cls
/*****************************************************************************************************************
Author      : MST Solutions
CreatedBy   : Kesavakumar Murugesan, Chandrasekar Nallusamy
Date        : 5/26/2016
Description :
1.'CreateActionTracks' method is used to carry CaseTeamMembers from Parent Wish to Child Wishes and Used to create
Tasks based on Chapters and Wish type from 'Chapter Action Track' custom object.
2.'CreateChildWish' method is used to create Child Wishes for Parent Wish.
3.'SubmitForApproval' method used to automatically submit Parent Wish for approval when required number of
Volunteers added to Parent Wish.
*******************************************************************************************************************/

public class CaseTriggerHandler {
    
    /* Used to create action track for different stages based on Chapter and used to pull Case team members to child wishes*/
    public static void createActionTracks(String caseType, Map<Id, Case> caseChapterIdsMap, Set<Id> parentWishIdsSet) {
        Constant_AC  constant = new Constant_Ac();    
        Id wishDeterminationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(constant.wishDeterminationRT).getRecordTypeId();
        Map<String, Case> chaptersWishMap = new Map<String, Case>();
        if(parentWishIdsSet.size()>0){
            Map<Id, List<CaseTeamMember>> parentCaseMembersMap = new Map<Id, List<CaseTeamMember>>();
            
            //Used to get case and its case team members
            for(CaseTeamMember caseTeamMem : [SELECT Id, ParentId, MemberId, TeamRoleId  FROM CaseTeamMember WHERE ParentId IN : parentWishIdsSet]) {
                if(parentCaseMembersMap.containsKey(caseTeamMem.ParentId)) {
                    parentCaseMembersMap.get(caseTeamMem.ParentId).add(caseTeamMem);
                } else {
                    parentCaseMembersMap.put(caseTeamMem.ParentId, new list<CaseTeamMember>{caseTeamMem});
                }
            }
            List<CaseTeamMember> childWishTeamMembersList = new List<CaseTeamMember>();
            Map<String, List<Case>> wishDeterminationCases = new Map<String, List<Case>>();
            
            //Used to include the parent wish case team members to child wish case team
            for(Case addTeamMember : caseChapterIdsMap.values()) {
                chaptersWishMap.put(addTeamMember.Chapter_Name__c, addTeamMember);
                if(parentCaseMembersMap.containsKey(addTeamMember.ParentId)) {
                    for(CaseTeamMember createWishTeamMember : parentCaseMembersMap.get(addTeamMember.ParentId)){
                        CaseTeamMember addWishTeamMember = new CaseTeamMember(MemberId = createWishTeamMember.MemberId,TeamRoleId = createWishTeamMember.TeamRoleId,ParentId = addTeamMember.Id);
                        childWishTeamMembersList.add(addWishTeamMember);
                    }
                }
                if(addTeamMember.RecordTypeId == wishDeterminationRecordTypeId) {
                    if(wishDeterminationCases.containsKey(addTeamMember.Chapter_Name__c)) {
                        wishDeterminationCases.get(addTeamMember.Chapter_Name__c).add(addTeamMember);
                    } else {
                        wishDeterminationCases.put(addTeamMember.Chapter_Name__c, new List<Case>{addTeamMember});
                    }
                }
            }
            if(childWishTeamMembersList.size()>0) {
                insert childWishTeamMembersList;
            }
        }
        if(caseChapterIdsMap.size()>0) {
            List<Task> newTaskList = new List<Task>();
            Map<String,List<Chapter_Action_Track__c>> chapterActionTracksMap = new Map<string, List<Chapter_Action_Track__c>>();
            
            //Used to get chapter action details based on wish chapter
            for(Chapter_Action_Track__c chapterActions : [SELECT Id, Wish_Type__c, Assigned_To__c ,Due_Date__c,Recurring__c, Recurring_Frequency__c, Name, Chapter_Name__r.Name, Case_Type_Stage__c,Sort_Order__c,Task_Name__c FROM Chapter_Action_Track__c WHERE Chapter_Name__r.Name IN : chaptersWishMap.keySet() ORDER BY Sort_Order__c ASC]) {
                if(chapterActionTracksMap.containsKey(chapterActions.Wish_type__c)) {
                    chapterActionTracksMap.get(chapterActions.Wish_type__c).add(chapterActions);
                } else {
                    chapterActionTracksMap.put(chapterActions.Wish_type__c, new List<Chapter_Action_Track__c>{chapterActions});
                }
                
            }
            
            List<Task> taskList = new List<Task>();
            
            //Used to create new task for wish by looking into chapter action track object based on wish chapter, wish type and wish stage
            for(Case createTasks : caseChapterIdsMap.values()) {
                if(chapterActionTracksMap.containsKey(createTasks.Wish_type__c)) {
                    for(Chapter_Action_Track__c actionTrack : chapterActionTracksMap.get(createTasks.Wish_type__c)) {
                        if(createTasks.Wish_type__c == actionTrack.Wish_type__c && createTasks.Subject == actionTrack.Case_Type_Stage__c && createTasks.Chapter_Name__c == actionTrack.Chapter_Name__r.Name && actionTrack.Sort_Order__c == 1) {
                            Task newTask = new Task();
                            newTask.WhatId = createTasks.Id;
                            newTask.WhoId = createTasks.ContactId;
                            newTask.Subject = actionTrack.Task_Name__c;
                            newTask.ActivityDate = System.today() + Integer.valueOf(actionTrack.Due_Date__c);
                            newTask.Sort_Order__c = actionTrack.Sort_Order__c;
                            newTask.TaskVolunteerRole__c = actionTrack.Assigned_To__c;
                            taskList.add(newTask);
                        }
                    } 
                }
            }
            if(taskList.size()>0) {
                insert taskList;
            }
        }
    }    
    
    //Used to create child wish for Parent wish
    public static void createChildWish (List<Case> childCreationWishList, String wishType) {
        Constant_AC  constant = new Constant_Ac(); 
        Id parentWishRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(constant.parentWishRT).getRecordTypeId();
        Id wishDeterminationRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(constant.wishDeterminationRT).getRecordTypeId();
        
        List<Case> newWishList = new List<Case>();
        for(Case wishDetails : childCreationWishList) {
            if(wishDetails.RecordTypeId == parentWishRecordTypeId) {
                Case newWish = new Case(Chapter_Name__c = wishDetails.Chapter_Name__c, Wish_Type__c ='Standard', Subject = wishType.split('-')[0], ParentId = wishDetails.Id, AccountId=wishDetails.AccountId,ContactId=wishDetails.ContactId,Origin = 'Web',RecordTypeId=wishType.split('-')[1], OwnerId = wishDetails.OwnerId);
                newWishList.add(newWish);
            } else{
                Case newWish = new Case(Chapter_Name__c = wishDetails.Chapter_Name__c, Wish_Type__c = wishDetails.Wish_type__c ,Subject = wishType.split('-')[0], ParentId = wishDetails.ParentId, AccountId=wishDetails.AccountId,ContactId=wishDetails.ContactId,Origin = 'Web',RecordTypeId=wishType.split('-')[1], OwnerId = wishDetails.OwnerId);
                newWishList.add(newWish);
            }
        }
        if(newWishList.size()>0) {
            insert newWishList;
        }
    }
    
    //Used to submit parent wish for approval once the required volunteer assigend to Wish
    public static void submitForApproval(List<Case> wishListForApproval) {
        List<Approval.ProcessSubmitRequest> approvalRequestList = new List<Approval.ProcessSubmitRequest>();
        for(Case wishForApproval : wishListForApproval) {
            Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();
            approvalRequest.setComments('Parent Wish Approval');
            approvalRequest.setObjectId(wishForApproval.id);
            approvalRequest.setProcessDefinitionNameOrId('Wish_Approval');
            approvalRequest.setSkipEntryCriteria(true);
            approvalRequestList.add(approvalRequest);
        }
        if(approvalRequestList.size()>0) {
            List<Approval.ProcessResult> resultList = Approval.process(approvalRequestList);
        }
    }
    // When the case status is updated the corresponding lead status should be update.
    public static void UpdateLeadStatus(List<Case> caseList){
     Map<Id,Case> caseMap = new Map<Id,Case>();
     List<Lead> updateLeadList = new List<Lead>();
      for(Case processdbcaseList : caseList){
            caseMap.Put(processdbcaseList.Lead__c,processdbcaseList);
            system.debug('@@@@@ caseMap @@@@@@@'+caseMap.Values());
      }
      
      if(caseMap.size() > 0){
          for(Lead dbLeads: [SELECT Id,Status,Sub_Status__c  FROM Lead WHERE Id in: caseMap.KeySet()]){
              if(caseMap.get(dbLeads.Id).Status == 'In progress')
              {
                  dbLeads.Sub_Status__c = 'Local';
              }
              
              if(caseMap.get(dbLeads.Id).Status == 'Escalated')
              {
                   system.debug('@@@@@ caseMap @@@@@@@'+caseMap.get(dbLeads.Id).Status);
                   dbLeads.Sub_Status__c = 'National';
              }
              
               if(caseMap.get(dbLeads.Id).Status == 'Medical Eligible')
              {
                  dbLeads.Status = 'Qualified';
              }
              
               if(caseMap.get(dbLeads.Id).Status == 'Denied')
              {
                  dbLeads.Status = 'DNQ';
              }
              
              updateLeadList.add(dbLeads);
              system.debug('@@@@@ updateLeadList @@@@@@@'+updateLeadList);
          }
         
      }
      
      if(updateLeadList.size() > 0)
      update updateLeadList;
    }
    
    
    public static void UpdateVolunteerWishGranted(Set<Id> wishIds)
    {
    
      List<Contact> updateContactList = new List<Contact>();
      for(Volunteer_Opportunity__c currVolOpp : [SELECT id,Volunteer_Name__c, Volunteer_Name__r.Number_of_wishes_active__c,
                                                 Volunteer_Name__r.Number_of_wishes_granted__c FROM Volunteer_Opportunity__c WHERE Wish__c IN :wishIds AND Volunteer_Name__c != Null])
      {
          
          if(currVolOpp.Volunteer_Name__c != Null)
          {
         
          Contact updateContact = new Contact();
          updateContact.id = currVolOpp.Volunteer_Name__c;
          if(currVolOpp.Volunteer_Name__r.Number_of_wishes_active__c > 0)
            updateContact.Number_of_wishes_active__c = currVolOpp.Volunteer_Name__r.Number_of_wishes_active__c - 1;
          if(currVolOpp.Volunteer_Name__r.Number_of_wishes_granted__c > 0)
            updateContact.Number_of_wishes_granted__c = currVolOpp.Volunteer_Name__r.Number_of_wishes_granted__c + 1;
          updateContactList.add(updateContact);
          }
      
      }
      if(updateContactList.size() > 0)
        Update updateContactList;
       
    }
}