make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External RE record Id for upserting</description>
        <externalId>true</externalId>
        <inlineHelpText>External RE record Id for upserting</inlineHelpText>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birth_Day__c</fullName>
        <description>It will hold the day value of the Birth day</description>
        <label>Birth Day</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Birth_Month__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Birth_Month__c</fullName>
        <description>It will hold the month value of the DOB</description>
        <label>Birth Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Birth_Year__c</fullName>
        <description>It will capture the volunteer birth year value</description>
        <label>Birth Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>It holds the id value of External System.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Hidden_Country__c</fullName>
        <description>This field is used as hidden to update the contact country  from volunteer portal</description>
        <label>Hidden Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Email__c</fullName>
        <description>This field is used as hidden to update the contact email from volunteer portal</description>
        <label>Hidden Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hidden_First_Name__c</fullName>
        <description>This field is used as hidden to update the contact first name from volunteer portal</description>
        <label>Hidden First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Last_Name__c</fullName>
        <description>This field is used as hidden to update the contact last name from volunteer portal</description>
        <label>Hidden Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Phone__c</fullName>
        <description>This field is used as hidden to update the contact phone from volunteer portal</description>
        <label>Hidden Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_State__c</fullName>
        <description>Hidden State Value</description>
        <label>Hidden State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Street__c</fullName>
        <description>This field is used as hidden to update the contact Street from volunteer portal</description>
        <label>Hidden Street</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_city__c</fullName>
        <description>This field is used as hidden to update the contact city from volunteer portal</description>
        <label>Hidden City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <description>It will be display volunteer roles, able to select more than one values</description>
        <inlineHelpText>This field should remain blank for Migrated Records.</inlineHelpText>
        <label>Volunteer Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundraising – Assist</fullName>
                </value>
                <value>
                    <fullName>Office – Assist</fullName>
                </value>
                <value>
                    <fullName>Speaker’s Bureau</fullName>
                </value>
                <value>
                    <fullName>Special Events</fullName>
                </value>
                <value>
                    <fullName>Translator/Interpreter</fullName>
                </value>
                <value>
                    <fullName>Wish Granter</fullName>
                </value>
                <value>
                    <fullName>Airport Greeter</fullName>
                </value>
                <value>
                    <fullName>Celebrity Host</fullName>
                </value>
                <value>
                    <fullName>Medical Outreach Volunteer</fullName>
                </value>
                <value>
                    <fullName>Wish Assist Phone Greeter</fullName>
                </value>
                <value>
                    <fullName>Water Handler</fullName>
                </value>
                <value>
                    <fullName>Wish Family Welcome Volunteer</fullName>
                </value>
                <value>
                    <fullName>Wish Assist Volunteer</fullName>
                </value>
                <value>
                    <fullName>Translator &amp; Interpreter</fullName>
                </value>
                <value>
                    <fullName>Office Volunteer</fullName>
                </value>
                <value>
                    <fullName>Skill Based Volunteer</fullName>
                </value>
                <value>
                    <fullName>Fundraising Volunteer</fullName>
                </value>
                <value>
                    <fullName>Special Events - Committee Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>is_Application__c</fullName>
        <description>Hidden field is using in Application page.</description>
        <label>Hidden is Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submit</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Partial Submit</fullName>
                </value>
                <value>
                    <fullName>Fully Submit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/External_ID__c.object
<CustomObject>
    <description>This object will contain External ID references to other systems that hold corresponding / matching records.  This object will allow these ids to persist on surviving records of a record merging process.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Captures the External ID used by matching records in an external system.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>External ID</label>
    <nameField>
        <displayFormat>E.ID-{00000}</displayFormat>
        <label>External ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Office__c.object
<CustomObject>
    <description>This Object is used to store the office details.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field is used to store the value of Zip Code.</description>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Zip_Code__c.object
<CustomObject>
    <description>This object is used to store the value of the zip code.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id used for Mulesoft upsert.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of office.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Zip Code</relationshipLabel>
        <relationshipName>Zip_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ContactTrigger_AT_Test.cls
/***************************************************************************************************
Author      : MST Solutions
CreatedBy   : Kanagaraj
Date        : 28/06/2016
Description : ContactTrigger_AT_Test is used to increase the code coverage for contact_AT trigger and contactTriggerHandler.
*****************************************************************************************************/

@isTest
public class ContactTrigger_AT_Test{
 /*This setup method is used to create a chapter user and systemAdmin users*/
    
        @testSetup static void setup(){   
         OrientationandTrainingUtil.createChapterUser();
         OrientationandTrainingUtil.createrSystemAdminUser();
         }
     /*This setup method is used to create a community user records*/
     
         public testmethod static void createCommunityUser(){  
         User chapterUser = [SELECT Id,UserName,ProfileId,Profile.Name,Email FROM User WHERE Email  =: 'test123@gmail.com'];
         System.runAs(chapterUser){
         Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
         try{
         OrientationandTrainingUtil.createVolunteerContact(chapterAccount.id);}
         catch(exception ex){
         }
        }
     }
     
  
     /*This method is used to update the application status to submit*/
     
     public testmethod static void UpdateApplicationStatustoSubmit(){ 
         Constant_AC  constant = new Constant_AC(); 
         Id volunteerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.volunteerRT).getRecordTypeId();
         user systemAdmin = [select id from user where id =:userinfo.getuserid()];
         system.runAs(systemAdmin){
         Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
         Contact VolunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.id);
         OrientationandTrainingUtil.CreateAffiliation(VolunteerContact.Id);
         Contact dbcontact = [SELECT Id,FirstName,LastName,AccountId,Birth_Month__c ,Birth_Day__c,is_Application__c, Birth_Year__c,RecordTypeId FROM Contact Where RecordTypeId =: volunteerRecordTypeId Limit 1];
         dbcontact .Birth_Day__c = '21';
         dbcontact .Birth_Month__c = 'March';
         dbcontact .Birth_Year__c = '1986';
         dbcontact .is_Application__c = 'Submit';
         update dbcontact;
         }
     }
     /*This method is used to update the application status to complete*/
     
     public testmethod static void UpdateApplicationStatustoComplete(){ 
         Constant_AC  constant = new Constant_AC(); 
         Id volunteerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.volunteerRT).getRecordTypeId();
         user systemAdmin = [select id from user where id =:userinfo.getuserid()];
         system.runAs(systemAdmin){
         Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
         Contact VolunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.id);
         OrientationandTrainingUtil.CreateAffiliation(VolunteerContact.Id);
         Contact dbcontact = [SELECT Id,FirstName,LastName,AccountId,Birth_Month__c ,Birth_Day__c,is_Application__c, Birth_Year__c,RecordTypeId FROM Contact Where RecordTypeId =: volunteerRecordTypeId Limit 1];
         dbcontact .Birth_Day__c = '21';
         dbcontact .Birth_Month__c = 'March';
         dbcontact .Birth_Year__c = '1986';
         dbcontact .is_Application__c =  'Complete';
         update dbcontact;
         }
     }
     
     
     /*This method is used to update the application status to reject*/
     
     public testmethod static void UpdateApplicationStatustoReject(){ 
         Constant_AC  constant = new Constant_AC(); 
         Id volunteerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.volunteerRT).getRecordTypeId();
          user systemAdmin = [select id from user where id =:userinfo.getuserid()];
         system.runAs(systemAdmin){
         Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
         Contact VolunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.id);
         OrientationandTrainingUtil.CreateAffiliationwithAccount(VolunteerContact.Id,chapterAccount.id);
         Role__c WishRole = OrientationandTrainingUtil.createRole();
         Chapter_Role__c chapterRole = OrientationandTrainingUtil.createChapter(chapterAccount.id,WishRole.Id);
         Contact dbcontact = [SELECT Id,FirstName,LastName,AccountId,Birth_Month__c ,Birth_Day__c,is_Application__c, Birth_Year__c,RecordTypeId FROM Contact Where RecordTypeId =: volunteerRecordTypeId Limit 1];
         dbcontact .Birth_Day__c = '21';
         dbcontact .Birth_Month__c = 'March';
         dbcontact .Birth_Year__c = '1986';
         dbcontact .is_Application__c =  'Rejected';
         dbcontact.Volunteer_Role__c = 'Wish Granting';
         update dbcontact;
         }
     }
     /*This method is used to create a task record when zipcode is update*/
     
     public testmethod static void CreateZipcodeUpdateTask(){
     user systemAdmin = [select id from user where id =:userinfo.getuserid()];
         system.runAs(systemAdmin){
         Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
         Account chapterAccount1 = OrientationandTrainingUtil.createVolunteerAccount();
         Contact VolunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.id);
         Office__c  officeRec = OrientationandTrainingUtil.createOffice(chapterAccount1.Id);
         officeRec.External_Id__c = 'R123';
         insert officeRec;
         Zip_Code__c  zipcodeRec = OrientationandTrainingUtil.createZipcode(officeRec.Id);
         zipcodeRec.Name = '32401';
         zipCodeRec.office__c = officeRec.id;
         zipCodeRec.External_Id__c = 'R123';
         insert zipCodeRec;
         OrientationandTrainingUtil.CreateAffiliationwithAccount(VolunteerContact.Id,chapterAccount.id);
         contact dbContact = [SELECT Id,MailingPostalCode  FROM Contact WHERE Id =:VolunteerContact.Id];
         dbContact.MailingPostalCode  = '32401';
         update dbContact;
       }
     }
     
     public testmethod static void updatewishChildContactInfo(){
         
        Contact childCon = OrientationandTrainingUtil.CreateWishChildCon();
        
        Contact updateCon = new Contact();
        updateCon.Hidden_First_Name__c  = 'Chandra';
        updateCon.Hidden_Last_Name__c  = 'Sekar';
        updateCon.Hidden_Phone__c = '8056913402';
        updateCon.Hidden_Email__c  = 'testmst@gmail.com';
        updateCon.Hidden_Street__c = 'North Street';
        updateCon.Hidden_city__c = 'Chennai';
        updateCon.Hidden_State__c = 'Alabama';
        updateCon.Hidden_Country__c =  'United States';
        updateCon.Hidden_Zip_Code__c = '621010';
        updateCon.IsContactInfoUpdated__c = true;
        updateCon.Id = childCon.Id;
        update updateCon;
     }
     
      public testmethod static void RecallWishChildContactInfo(){
         
        Contact childCon = OrientationandTrainingUtil.CreateWishChildCon();
        Contact childFamily = OrientationandTrainingUtil.CreateWishFamily();
        npe4__Relationship__c  npcr = OrientationandTrainingUtil.CreateRelationshipRec(childCon.Id,childFamily.Id);
        
        Contact updateConFamily = new Contact();
        updateConFamily.Hidden_First_Name__c  = 'Chandra';
        updateConFamily.Hidden_Last_Name__c  = 'Sekar';
        updateConFamily.Hidden_Phone__c = '8056913402';
        updateConFamily.Hidden_Email__c  = 'testmst@gmail.com';
        updateConFamily.Hidden_Street__c = 'North Street';
        updateConFamily.Hidden_city__c = 'Chennai';
        updateConFamily.Hidden_State__c = 'Alabama';
        updateConFamily.Hidden_Country__c =  'United States';
        updateConFamily.Hidden_Zip_Code__c = '621010';
        updateConFamily.IsContactInfoUpdated__c = true;
        updateConFamily.Id = childFamily.Id;
       // update updateConFamily;
        
        
        Contact updateCon = new Contact();
        updateCon.Email = 'kanagu431@gmail.com';
        updateCon.IsContactInfoUpdated__c = true;
        updateCon.Id = childCon.Id;
        //update updateCon;
     }
     
     public testmethod static void updatewishChildRecall(){
         
        Contact childCon = OrientationandTrainingUtil.CreateWishChildCon();
        Contact childFamily = OrientationandTrainingUtil.CreateWishFamily();
        npe4__Relationship__c  npcr = OrientationandTrainingUtil.CreateRelationshipRec(childCon.Id,childFamily.Id);
        
        Contact updateCon = new Contact();
        updateCon.Hidden_First_Name__c  = 'Chandra';
        updateCon.Hidden_Last_Name__c  = 'Sekar';
        updateCon.Hidden_Phone__c = '8056913402';
        updateCon.Hidden_Email__c  = 'testmst@gmail.com';
        updateCon.Hidden_Street__c = 'North Street';
        updateCon.Hidden_city__c = 'Chennai';
        updateCon.Hidden_State__c = 'Alabama';
        updateCon.Hidden_Country__c =  'United States';
        updateCon.Hidden_Zip_Code__c = '621010';
        updateCon.IsRejected_Contact_Info__c = true;
        updateCon.Id = childCon.Id;
        update updateCon;
     }
     
      public testmethod static void RecallWishFamilyContactInfo(){
         
        Contact childCon = OrientationandTrainingUtil.CreateWishChildCon();
        Contact childFamily = OrientationandTrainingUtil.CreateWishFamily();
        npe4__Relationship__c  npcr = OrientationandTrainingUtil.CreateRelationshipRec(childCon.Id,childFamily.Id);
        
        Contact updateConFamily = new Contact();
        updateConFamily.Hidden_First_Name__c  = 'Chandra';
        updateConFamily.Hidden_Last_Name__c  = 'Sekar';
        updateConFamily.Hidden_Phone__c = '8056913402';
        updateConFamily.Hidden_Email__c  = 'testmst@gmail.com';
        updateConFamily.Hidden_Street__c = 'North Street';
        updateConFamily.Hidden_city__c = 'Chennai';
        updateConFamily.Hidden_State__c = 'Alabama';
        updateConFamily.Hidden_Country__c =  'United States';
        updateConFamily.Hidden_Zip_Code__c = '621010';
        updateConFamily.IsContactInfoUpdated__c = true;
        updateConFamily.Id = childFamily.Id;
        update updateConFamily;
        
        
        Contact updateCon = new Contact();
        updateCon.Email = 'kanagu431@gmail.com';
        updateCon.IsRejected_Contact_Info__c = true;
        updateCon.Id = childCon.Id;
        update updateCon;
     }
}