make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>It will holds the account email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>It holds the Expiration Date of Background check for volunteer.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hidden_Volunteer_Contact_Email__c</fullName>
        <description>This field is used as hidden field to store volunteer contact email in Background Check.</description>
        <label>Hidden Volunteer Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will tells the final result about the background check.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved w/ Conditions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role_O_T__c.object
<CustomObject>
    <description>This is a junction object that would join the Orientation &amp; Training objects and the Roles object.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associate with Chapter Role Object.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipName>O_T_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orientation_Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds orientation &amp; Training for chapter roles.</description>
        <label>Orientation &amp; Training</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please select Training Orientation.</errorMessage>
            <filterItems>
                <field>Orientation_Training__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Training</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Orientation_Training__c</referenceTo>
        <relationshipLabel>Chapter Roles O&amp;T</relationshipLabel>
        <relationshipName>O_T_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It will indicate this training is required or not.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Chapter Role O&amp;T</label>
    <nameField>
        <displayFormat>OTR-{000000}</displayFormat>
        <label>O&amp;T Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles O&amp;T</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check weather this conflict of interest is active or not.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>This field is used to store the value of expiration date.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hidden_Volunteer_Contact_Email__c</fullName>
        <description>This field is used as hidden field to store volunteer contact email in COI.</description>
        <label>Hidden Volunteer Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>B_C_Expiration_Date__c</fullName>
        <description>It holds the Background check expiration date</description>
        <label>B/C Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>It holds the License Expiration Date details.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Affiliation&apos;s Organization will be stored on the Contact record.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe5__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Out of Compliance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Orientation_Training__c.object
<CustomObject>
    <description>It will holds orientation &amp; training information records</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>It will capture the date information about the training started date</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Orientation &amp; Training</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orientation &amp; Trainings</pluralLabel>
    <recordTypes>
        <fullName>Interview</fullName>
        <active>true</active>
        <label>Interview</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>This record type associated with training page layout</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Hidden_Volunteer_Contact_Email__c</fullName>
        <description>This field is used to store the value of Volunteer contact email for email purpose.</description>
        <label>Hidden Volunteer Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It indicate different status of the volunteer opportunity.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to choose the name of the volunteer contact</description>
        <label>Volunteer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will hold the volunteer name and define chapter and role for this volunteer.</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/BackGroundCheckTriggerHandler.cls
/***************************************************************************
Author : MST Solutions
Created Date : 08/16/2016
Description : It will update the Volunteer Affiliation Status based on the Background status.
If it is approved, Affiliation Status would be updated  as "Pending/Active" based on the Training Required for chatper role.
****************************************************************************/

Public class BackGroundCheckTriggerHandler
{

    // If Interview Task is rejected, then update affiliation status as "Declined".
    public static void UpdateAffiliationStatusToDeclined(Set<Id> rejectedIds)
    {
      List<npe5__Affiliation__c> affiliationList = new List<npe5__Affiliation__c>();
      for(npe5__Affiliation__c dbAffiliationRec : [SELECT Id,npe5__Contact__c,npe5__Primary__c,npe5__Status__c,npe5__Organization__c FROM npe5__Affiliation__c WHERE npe5__Contact__c IN :rejectedIds AND npe5__Status__c != 'Active'])
      {
                    npe5__Affiliation__c  updateRec = new npe5__Affiliation__c();
                    updateRec.npe5__Status__c = 'Declined';
                    updateRec.id = dbAffiliationRec.id;
                    affiliationList.add(updateRec);
      }
                
        if(affiliationList.size() > 0){
            update affiliationList;
        }
    
    }
    
    // If Interview Task is approved, then update affiliation status as "Pending/Active" based on the training required.
    public static void UpdateAffiliationStatusToPending(Set<Id> approvedVolunteerIds)
    {   
        List<npe5__Affiliation__c> updateAffliationList = new List<npe5__Affiliation__c>();
        Set<Id> activeContactIdsSet = new Set<Id>();
        Constant_AC  constant = new Constant_Ac(); 
        Id triainingRecordTypeId = Schema.Sobjecttype.Orientation_Training__c.getRecordTypeInfosByName().get(constant.trainingRT).getRecordTypeId();  
        Set<Id> orientationTrainingId = new Set<Id>();
        Map<String, Set<String>> volunteerChapterRoleMap = new Map<String, Set<String>>();
        Set<Id> chapterRolesSet = new Set<Id>();
        for(Volunteer_Roles__c currRole : [SELECT Id,Name,Chapter_Role__c,Volunteer_Name__c FROM Volunteer_Roles__c  WHERE Volunteer_Name__c  IN :approvedVolunteerIds])
        {
            chapterRolesSet.add(currRole.Chapter_Role__c);
            if(volunteerChapterRoleMap.containsKey(currRole.Volunteer_Name__c))
                volunteerChapterRoleMap.get(currRole.Volunteer_Name__c).add(currRole.Chapter_Role__c); 
            else
                volunteerChapterRoleMap.put(currRole.Volunteer_Name__c, new Set<String>{currRole.Chapter_Role__c}); 
        }
            
        Set<String> chapterRoleOandTsSet = new Set<String>();
        Map<String,Conflict_Of_Interest__c> coiMap = new Map<String,Conflict_Of_Interest__c>();
            
        for(Chapter_Role_O_T__c currChapterRole : [SELECT Id,Name,Orientation_Training__c,Orientation_Training__r.RecordTypeId,Required__c,Chapter_Role__c FROM Chapter_Role_O_T__c WHERE Chapter_Role__c IN :chapterRolesSet AND Required__c = TRUE AND Orientation_Training__r.RecordTypeId =:triainingRecordTypeId])
        {
            chapterRoleOandTsSet.add(currChapterRole.Chapter_Role__c);
        }
            
        for(Conflict_Of_Interest__c currCOI : [SELECT  id, Volunteer_Contact__c, Expiration_Date__c FROM Conflict_Of_Interest__c  WHERE Volunteer_Contact__c IN :approvedVolunteerIds AND Expiration_Date__c > : Date.Today()])
        {
             coiMap.put(currCOI.Volunteer_Contact__c, currCOI);
        }
            
        for(npe5__Affiliation__c dbAffiliationRec : [SELECT Id,npe5__Contact__c,npe5__Primary__c,npe5__Status__c,npe5__Organization__c FROM npe5__Affiliation__c WHERE npe5__Contact__c IN : approvedVolunteerIds AND npe5__Status__c != 'Active'])
        {
        
                npe5__Affiliation__c currAffiliation = new npe5__Affiliation__c();
                if(coiMap.containsKey(dbAffiliationRec.npe5__Contact__c))
                {
                    currAffiliation.npe5__Status__c = 'Active';
                }
                else
                {
                    currAffiliation.npe5__Status__c = 'Pending';
                }
                currAffiliation.id = dbAffiliationRec.id;    
            if(volunteerChapterRoleMap.containsKey(dbAffiliationRec.npe5__Contact__c)){
                for(String currChapterRole : volunteerChapterRoleMap.get(dbAffiliationRec.npe5__Contact__c))
                {
                    if(chapterRoleOandTsSet.contains(currChapterRole))
                    {
                        currAffiliation.npe5__Status__c = 'Pending';
                    }
                 
                }
            }
        
                if(currAffiliation.npe5__Status__c == 'Active')
                    activeContactIdsSet.add(dbAffiliationRec.npe5__Contact__c);
                updateAffliationList.add(currAffiliation);
        }
           
           if(updateAffliationList.size() > 0)
           {
               update updateAffliationList;
               if(activeContactIdsSet.size() > 0)
                   VolunteerOandTHandler.updateUser(activeContactIdsSet);
           }
            
    }
     
   // DeActivate Existing Background Check.
   
   public static void DeactivateExistingRecords(Set<Id> newRecordIds, Set<Id> volunteerIds)
   {
       List<Background_check__c> deactivateExRecords = new List<Background_check__c>();
        for(Background_check__c exRec : [SELECT id,current__c FROM Background_check__c WHERE current__c = True AND Id NOT IN :newRecordIds AND Volunteer__c IN :volunteerIds])
        {
                Background_check__c updateRec = new Background_check__c();
                updateRec.current__c = false;
                updateRec.id = exRec.id;
                deactivateExRecords.add(updateRec);
                
        }
        
        if(deactivateExRecords.size() > 0)
        {
            Update deactivateExRecords;
        }
   }

  // Update Hidden Email Field
  
  public static void UpdateHiddenEmailField(Set<Id> volunteerIds, List<Background_check__c> newRecords)
  {
     Map<Id, Contact> volunteerMap = new Map<Id, Contact>();
     for(Contact currRec : [SELECT Id,OwnerId,AccountId,Account.Name,Account.Phone,Account.Email__c, Email FROM Contact WHERE Id IN :volunteerIds])
     {
            volunteerMap.put(currRec.Id,currRec);
     }
   
     for(Background_check__c currRec : newRecords)
     {
             if(volunteerMap.containsKey(currRec.Volunteer__c)){
               currRec.Hidden_Volunteer_Contact_Email__c = volunteerMap.get(currRec.Volunteer__c).Email;
                 currRec.OwnerId = volunteerMap.get(currRec.Volunteer__c).OwnerId;
             }
     }
  }
   
   // Updating most recent BC Expiration Date on Volunteer Contact.
  public static void UpdateVolunteerExpirationDate(Map<Id,Background_check__c>   expirationDateMap)
  {
      List<Contact> volunteerListToUpdate = new List<Contact>();
      for(Background_check__c currBGRec : expirationDateMap.values())
      {
        if(currBGRec.volunteer__c != Null)
        {
          Contact updateVolunteer = new Contact();
          updatevolunteer.id = currBGRec.volunteer__c;
          updateVolunteer.B_C_Expiration_Date__c = currBGRec.Date__c;
          volunteerListToUpdate.add(updateVolunteer);
        }
      }
      
      if(volunteerListToUpdate.size() > 0)
        update volunteerListToUpdate;
  
   }
   
   //Update volunteer Opportunity and volunteer Role status.
   Public static void UpdateVOppAndVRoleStatus(Set<Id> volunteerContactIdSet,String objectName){
       if(volunteerContactIdSet.size() > 0){
       List<Volunteer_Opportunity__c> updateVolOpportunityList = new List<Volunteer_Opportunity__c>();
       List<Volunteer_Roles__c> updateVolunteerRoleList = new List<Volunteer_Roles__c>();
       Map<Id,Volunteer_Roles__c> VolunteerRoleMap = new Map<Id,Volunteer_Roles__c>();
       for(Volunteer_Opportunity__c dbVolOpportunity : [SELECT Id,Volunteer_Name__c,Status__c FROM Volunteer_Opportunity__c WHERE Volunteer_Name__c IN: volunteerContactIdSet]){
           
           Volunteer_Opportunity__c updateVolStatus = new Volunteer_Opportunity__c();
           updateVolStatus.Id = dbVolOpportunity.Id;
           updateVolStatus.Status__c  = 'Out of Compliance';
           updateVolOpportunityList.add(updateVolStatus);
          
       }
       
       for(Volunteer_Roles__c dbVolRole : [SELECT Id,Volunteer_Name__c,Status__c,Chapter_Role__c,Chapter_Role__r.Background_Check_Required__c FROM Volunteer_Roles__c Where Volunteer_Name__c IN: volunteerContactIdSet ]){
           
           Volunteer_Roles__c updateVolStatus = new Volunteer_Roles__c();
           updateVolStatus.Id = dbVolRole.Id;
           if(dbVolRole.Chapter_Role__r.Background_Check_Required__c == true && objectName == 'backgroundCheck'){
           updateVolStatus.Status__c = 'Out of Compliance';
           }
           if(objectName == 'COI'){
           updateVolStatus.Status__c = 'Out of Compliance';
           }
           
           VolunteerRoleMap.put(updateVolStatus.Id,updateVolStatus);
       }
       
       
       
       if(updateVolOpportunityList.size() > 0)
       update updateVolOpportunityList;
       
       if(VolunteerRoleMap.size() > 0)
       update VolunteerRoleMap.values();
     }
   }

}