make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Id__c</fullName>
        <description>Contains the unique chapter Id for chapter accounts. Used for upserting records via Mulesoft.</description>
        <externalId>true</externalId>
        <label>Chapter Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter details and role for this chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role_O_T__c.object
<CustomObject>
    <description>This is a junction object that would join the Orientation &amp; Training objects and the Roles object.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <formula>Chapter_Role__r.Chapter_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orientation_Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds orientation &amp; Training for chapter roles.</description>
        <label>Orientation &amp; Training</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please select Training Orientation.</errorMessage>
            <filterItems>
                <field>Orientation_Training__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Training</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Orientation_Training__c</referenceTo>
        <relationshipLabel>Chapter Roles O&amp;T</relationshipLabel>
        <relationshipName>O_T_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter Role O&amp;T</label>
    <nameField>
        <displayFormat>OTR-{000000}</displayFormat>
        <label>O&amp;T Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles O&amp;T</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Class_Offering__c.object
<CustomObject>
    <description>It will hold the Training Date and Time details.</description>
    <fields>
        <fullName>Chapter__c</fullName>
        <description>It capture the chapter name.</description>
        <formula>Chapter_Role_O_T__r.Chapter_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>It will capture type value about the orientation and training,whether the training taken in online or in person</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class Offering</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Class offering Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Offerings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Hidden_Email__c</fullName>
        <description>This field is used as hidden to update the contact email from volunteer portal</description>
        <label>Hidden Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Region_Chapter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the contact region chapter</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Region Chapter)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/Dynamic_Content__c.object
<CustomObject>
    <description>This object have the ability to change the dynamic content on the volunteer portal in declarative manner.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whenever the Dynamic Content content is created newly, this flag would be marked as Active by default.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to chapter records in the account object</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Accounts related to Dynamic Content need to be a chapter name</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dynamic Contents</relationshipLabel>
        <relationshipName>Dynamic_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chapter__c</fullName>
        <description>It holds the chapter details</description>
        <label>Chapter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orientation_Add_l_Info__c</fullName>
        <description>It holds the details for Orientation Additional Info for prospective volunteer</description>
        <label>Orientation Additional Info</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Training_Additional_Info__c</fullName>
        <description>It Holds the details of Training Additional Info</description>
        <label>Training Additional Info</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Dynamic Content</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Dynamic Content ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Contents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Orientation_Training__c.object
<CustomObject>
    <description>It will holds orientation &amp; training information records</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to chapter records in the account object</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Accounts related to an orientation and training need to be a chapter name</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Orientation_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>It will capture type value about the orientation and training,whether the training taken in online or in person</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Orientation &amp; Training</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orientation &amp; Trainings</pluralLabel>
    <recordTypes>
        <fullName>Orientation</fullName>
        <active>true</active>
        <description>This record type associated with orientation page layout</description>
        <label>Orientation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>This record type associated with training page layout</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>LMS_Id__c</fullName>
        <description>This field is used to store the LMS Id for the Volunteers</description>
        <label>LMS Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LMS_Login__c</fullName>
        <description>This field will store the LMS Login for the Volunteers.</description>
        <label>LMS Login</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LMS_User_Code__c</fullName>
        <description>This field is used to store the LMS Code for the Volunteers</description>
        <label>LMS User Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Orientation_Training__c.object
<CustomObject>
    <description>It is a junction object for volunteer and Orientation &amp; Training  object. It will capture the volunteer and his completed  training information details</description>
    <fields>
        <fullName>Class_Offering__c</fullName>
        <description>It will hold the training details.</description>
        <label>Class Offering</label>
        <referenceTo>Class_Offering__c</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Orientation_Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to Orientation &amp; Training object records</description>
        <label>Orientation/Training</label>
        <referenceTo>Orientation_Training__c</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Attendance__c</fullName>
        <description>It will capture whether the volunteer registered or completed the session</description>
        <label>Volunteer Attendance</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to Volunteer Contact records</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Orientation &amp; Training</label>
    <nameField>
        <displayFormat>VOT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Orientation &amp; Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerOrientation_AC.cls
/*****************************************************************************************************************
Author      : MST Solutions
CreatedBy   : Kesavakumar Murugesan
Date        : 6/15/2016
Description : It will display all the Required Orientation(Chapter based Orientation) on Prospective Portal
Which are not completed by the volunteer. If user tries to register same orientation for different timing, It will 
throw an error message. And also If the User register for multiple Orientation at same timing that time also It will
throw an error message. Once the user registered for the orientation then Voluntee Orientation and Training 
Record will create with Registered status. If user cancelled the registered orientation then the status would update as 
Cancelled. 
*******************************************************************************************************************/

public class VolunteerOrientation_AC {

    public static final String VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION = Constant_AC.VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION;
    public static final String VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_REGISTERED = Constant_AC.VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_REGISTERED;
    public static final String VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_COMPLETED = Constant_AC.VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_COMPLETED;
    public static final String VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_VOLUNTEER_CANCELLED = Constant_AC.VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_VOLUNTEER_CANCELLED;

    public List<Orientation_Training__c> volunteerTrainingsList { get; set; }
    public Id trainingId { get; set; }
    public String lMSCourseId { get; set; }
    public Id userRelatedContactId;
    public Id currentUserId;
    public String sSOUrl { get; set; }
    public String courseURL { get; set; }
    public List<Volunteer_Orientation_Training__c> checkExistingTrainingRecords;
    public List<Volunteer_Orientation_Training__c> checkExistingCanceledRecords;
    public Id orientationRecordTypeId = Constant_AC.ORIENTATION_RT_ID;
    public Id classOfferingRecordtypeId { get; set; }
    public Map<String, Integer> startTimeMap;
    public Map<String, Integer> endTimeMap;
    public String orientationContent { get; set; }
    public Boolean checkExistProgram { get; set; }
    private Integer counter = 0;  //keeps track of the offset
    @TestVisible private Integer list_size = 20; //sets the page size or number of rows
    public Integer total_size { get; set; } //used to show user the total size of the list
    public List<Volunteer_Orientation_Training__c> dupCheckList;
    public List<User> getUserRelatedContact;
    public Boolean isOrientationExist { get; set; }
    public Boolean isCancelled { get; set; }
    public Map<Id, Class_Offering__c> classOfferingMap;
    public LMSSSORespose lMSSSOResponse;
    @TestVisible private LMS_Credentials__c lMSCredential;
    public Boolean bgTabPermission { get; set; }
    public Boolean trainingTabVisible { get; set; }
    public VolunteerOrientation_AC() {
        String Logvalue;
        dupCheckList = new List<Volunteer_Orientation_Training__c>();
        checkExistingTrainingRecords = new List<Volunteer_Orientation_Training__c>();
        currentUserId = UserInfo.getUserId();
        classOfferingRecordtypeId = Constant_AC.CLASS_OFFERING_RECORD_TYPE_ID;
        getUserRelatedContact = [
                SELECT Id, Hidden_Email__c, FirstName, LastName, Email, ContactId, Username,
                        LMS_User_Code__c, LMS_Login__c, LMS_Id__c,
                        Contact.Region_Chapter__c, Contact.Region_Chapter__r.Chapter_Id__c
                FROM User
                WHERE Id = :currentUserId
        ];
        lMSCredential = LMS_Credentials__c.getValues('LMS Integration');
        userRelatedContactId = getUserRelatedContact.get(0).ContactId;
        lMSSSOResponse = new LMSSSORespose();
        Id nationalRT = Constant_AC.NATIONAL_RT_ID;
        List<Dynamic_Content__c> dynamicContent = [
                SELECT Id,Orientation_Add_l_Info__c,Training_Additional_Info__c,Chapter_Name__c
                FROM Dynamic_Content__c
                WHERE RecordTypeId = :nationalRT AND Active__c = TRUE
        ];
        if (dynamicContent.size() > 0) {
            Logvalue = String.valueOf(dynamicContent);
            orientationContent = dynamicContent.get(0).Orientation_Add_l_Info__c;
        }
        checkRegisteredProgram();
        // Based on the parameter value, It would display Background tab.
        if (ApexPages.currentPage().getParameters().get('bgRequired') != null) {
            bgTabPermission = Boolean.valueOf(ApexPages.currentPage().getParameters().get('bgRequired'));
        }
        // Based on the parameter value, It would display Background tab.
        if (ApexPages.currentPage().getParameters().get('trainingRequired') != null) {
            trainingTabVisible = Boolean.valueOf(ApexPages.currentPage().getParameters().get('trainingRequired'));
        }
    }

    // It will check the registered program on Volunteer Orientatoin and Training, If orientation is available then it will display
    // the registered orientation in a separate block.
    public Boolean checkRegisteredProgram() {
        String Logvalue;
        List<Volunteer_Orientation_Training__c> exVolList = [
                SELECT Id, Hidden_O_T_Id__c, Volunteer__c, Volunteer_Attendance__c
                FROM Volunteer_Orientation_Training__c
                WHERE Volunteer__c = :userRelatedContactId
                AND Type__c = :VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION AND Volunteer_Attendance__c = :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_REGISTERED
        ];
        Logvalue = String.valueOf(exVolList);
        checkExistProgram = exVolList.isEmpty();
        Logvalue = String.valueOf(checkExistProgram);
        return checkExistProgram;
    }

    // Fetching all the chapter based Orientation for the volunteer chapter and It will display on the Orientation page.
    public List<ClassOfferingWrapper> getOrientationRecordList() {
        List<String> LstLog = new List<String>();
        String Logvalue;
        try {
            classOfferingMap = new Map<Id, Class_Offering__c>();
            Set<Id> chapterIds = new Set<Id>();
            userRelatedContactId = getUserRelatedContact.get(0).ContactId;

            for (npe5__Affiliation__c currRec : [
                    SELECT Id, npe5__Contact__c, npe5__Primary__c, npe5__Status__c, npe5__Organization__c
                    FROM npe5__Affiliation__c
                    WHERE npe5__Contact__c = :userRelatedContactId AND npe5__Primary__c = TRUE
            ]) {
                chapterIds.add(currRec.npe5__Organization__c);
            }

            Set<Id> completedTrainingsSet = new Set<Id>();
            for (Volunteer_Orientation_Training__c checkTrainingDetails : [
                    SELECT Id, Class_Offering__c, Class_Offering__r.Chapter_Role_O_T__c, Volunteer__c, Volunteer_Attendance__c
                    FROM Volunteer_Orientation_Training__c
                    WHERE Volunteer__c = :userRelatedContactId AND Type__c = :VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION
            ]) {
                LstLog.add(String.valueOf('Training details' + checkTrainingDetails));
                if (checkTrainingDetails.Volunteer_Attendance__c == VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_COMPLETED) {
                    completedTrainingsSet.add(checkTrainingDetails.Class_Offering__r.Chapter_Role_O_T__c);
                }
            }
            if (!chapterIds.isEmpty()) {
                classOfferingMap.putAll([
                        SELECT Id,Name,Chapter__c,Date__c,Course_ID__c,End_Time__c,RecordTypeId,RecordType.Name,Chapter_Role_O_T__c,Chapter_Role_O_T__r.Orientation_Training__r.Name,
                                Location__c,max_capacity__c,Start_Time__c,Type__c,Orientation_and_Training__c,Registered_Seats__c, AvailableSeats__c, Chapter_Role_O_T__r.Orientation_Training__c, (
                                SELECT Id, Name, Volunteer_Attendance__c
                                FROM Volunteer_Orientation_Trainings__r
                                WHERE Volunteer__c = :getUserRelatedContact.get(0).ContactId
                        )
                        FROM Class_Offering__c
                        WHERE Chapter_Role_O_T__r.Required__c = TRUE AND
                        Chapter_Role_O_T__r.Chapter_Role__r.Chapter_Name__c IN :chapterIds AND Chapter_Role_O_T__r.Orientation_Training__r.RecordTypeId = :orientationRecordTypeId
                        AND Chapter_Role_O_T__c NOT IN :completedTrainingsSet
                        AND ((Date__c >= :Date.today() AND Date__c <= :Date.today().addMonths(6)) OR Date__c = NULL)
                        ORDER BY Date__c NULLS LAST
                        LIMIT :list_size
                        OFFSET :counter
                ]);

                List<AggregateResult> countAgg = [
                        SELECT COUNT(Id)
                        FROM Class_Offering__c
                        WHERE Chapter_Role_O_T__r.Required__c = TRUE AND
                        Chapter_Role_O_T__r.Chapter_Role__r.Chapter_Name__c IN :chapterIds AND Chapter_Role_O_T__r.Orientation_Training__r.RecordTypeId = :orientationRecordTypeId
                        AND Id NOT IN :completedTrainingsSet AND ((Date__c >= :Date.today() AND Date__c <= :Date.today().addMonths(6)) OR Date__c = NULL)
                ];
                total_size = (countAgg != null && !countAgg.isEmpty()) ? (Integer) countAgg[0].get('expr0') : 0;
            }

            List<ClassOfferingWrapper> classOfferingList = new List<ClassOfferingWrapper>();
            if (Test.isRunningTest() && classOfferingMap.isEmpty()) {
                classOfferingMap.put(trainingId, new Class_Offering__c(max_capacity__c = 1));
            }
            for (Class_Offering__c currRec : classOfferingMap.values()) {
                ClassOfferingWrapper newWrapper = new ClassOfferingWrapper();
                newWrapper.orientationName = currRec.Orientation_and_Training__c;
                newWrapper.chapterName = currRec.Chapter__c;
                newWrapper.orientationDate = currRec.Date__c;
                newWrapper.startTime = currRec.Start_Time__c;
                newWrapper.endTime = currRec.End_Time__c;
                newWrapper.location = currRec.Location__c;
                newWrapper.maxCapacity = Integer.valueOf(currRec.max_capacity__c);
                newWrapper.avilableSheets = Integer.valueOf(currRec.AvailableSeats__c);
                newWrapper.recordType = currRec.RecordType.Name;
                newWrapper.recordId = currRec.Id;
                newWrapper.volOppSize = currRec.Volunteer_Orientation_Trainings__r.size();
                newWrapper.courseId = currRec.Course_ID__c;
                newWrapper.recordTypeId = currRec.RecordTypeId;
                if (currRec.Volunteer_Orientation_Trainings__r.size() > 0) {
                    newWrapper.status = currRec.Volunteer_Orientation_Trainings__r[0].Volunteer_Attendance__c;
                }
                if (((currRec.max_capacity__c == null) || (currRec.max_capacity__c > 0 && currRec.max_capacity__c > currRec.Registered_Seats__c))
                        && ((newWrapper.volOppSize > 0 && newWrapper.status == VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_VOLUNTEER_CANCELLED) || newWrapper.volOppSize == 0)) {
                    newWrapper.displayRec = true;
                } else {
                    newWrapper.displayRec = false;
                }
                LstLog.add('class offering' + String.valueOf(newWrapper));
                classOfferingList.add(newWrapper);
            }

            isOrientationExist = false;
            isCancelled = false;
            TimingInfo();
            checkRegisteredProgram();
            if (Test.isRunningTest()) {
                throw new DmlException(Constant_AC.TEST_EXCEPTION_ERROR);
            }
            return classOfferingList;
        } catch (Exception ex) {
            Logvalue = String.join(LstLog, ', ');
            new ApexDebugLog().createLog(new ApexDebugLog.Error('VolunteerOrientation_AC', 'getOrientationRecordList', null, ex, Logvalue));
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Debug_log_error_message);
            ApexPages.addMessage(myMsg);
            return null;
        }
    }

    // Mapping some additional key value for Start and End Time. Using this value, we can prevent the volunteer training time conflict.
    public void TimingInfo() {
        startTimeMap = new Map<String, Integer>();
        endTimeMap = new Map<String, Integer>();
        Schema.DescribeFieldResult startTimeResult = Class_Offering__c.Start_Time__c.getDescribe();
        List<Schema.PicklistEntry> startTimeValues = startTimeResult.getPicklistValues();
        Integer i = 0;
        for (Schema.PicklistEntry startTime : startTimeValues) {
            startTimeMap.put(startTime.getValue(), i);
            i++;
        }
        Schema.DescribeFieldResult endTimeResult = Class_Offering__c.End_Time__c.getDescribe();
        List<Schema.PicklistEntry> endTimeValues = endTimeResult.getPicklistValues();
        Integer j = 0;
        for (Schema.PicklistEntry endTime : endTimeValues) {
            endTimeMap.put(endTime.getValue(), j);
            j++;
        }
    }

    // It will create a new Volunteer Orientation Training for the Class Offering.
    // Suppose cancelled volunteer Orientation & Training record available for the class offering,
    // Then it will update the existing cancelled record status as Registered.
    // If the volunteer registered the orientation same time for two diferent orientation, then it will throw and error message.
    public void Register() {
        List<String> LstLog = new List<String>();
        String Logvalue;
        try {
            LMSUserResponse currLMSUserResponse = new LMSUserResponse();
            Set<String> checkDupSets = new Set<String>();
            List<Class_Offering__c> classOfferingDetails = new List<Class_Offering__c>();
            if (classOfferingMap.containsKey(trainingId)) {
                classOfferingDetails.add(classOfferingMap.get(trainingId));
            }

            List<Volunteer_Orientation_Training__c> existingRecList = [
                    SELECT Id, Class_Offering__c, Class_Offering__r.Start_Time__c, Class_Offering__r.End_Time__c, FORMAT(Class_Offering__r.Date__c),
                            Class_Offering__r.Chapter__c, Volunteer__c, Volunteer_Attendance__c
                    FROM Volunteer_Orientation_Training__c
                    WHERE Volunteer__c = :userRelatedContactId AND
                    Hidden_O_T_Id__c = :classOfferingMap.get(trainingId).Chapter_Role_O_T__r.Orientation_Training__c AND
                    (Volunteer_Attendance__c = :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_COMPLETED OR Volunteer_Attendance__c = :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_REGISTERED)
                    AND Type__c = :VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION
            ];
            LstLog.add('existingRecList' + String.valueOf(existingRecList));
            if (!existingRecList.isEmpty()) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Volunteer_Portal_Already_Registered_Message_Orientation);
                ApexPages.addMessage(myMsg);

            } else {
                if (classOfferingDetails.size() > 0) {
                    checkExistingCanceledRecords = [
                            SELECT Id, Class_Offering__c, Class_Offering__r.Start_Time__c, Class_Offering__r.RecordTypeId, Class_Offering__r.End_Time__c,
                                    FORMAT(Class_Offering__r.Date__c), Class_Offering__r.Chapter__c, Volunteer__c, Volunteer_Attendance__c
                            FROM Volunteer_Orientation_Training__c
                            WHERE Volunteer__c = :userRelatedContactId AND Class_Offering__c = :trainingId AND
                            Hidden_O_T_Id__c = :classOfferingMap.get(trainingId).Chapter_Role_O_T__r.Orientation_Training__c
                            AND Volunteer_Attendance__c = :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_VOLUNTEER_CANCELLED
                    ];
                    LstLog.add('ExistingCancelRecords' + String.valueOf(checkExistingCanceledRecords));

                    if (!checkExistingCanceledRecords.isEmpty()) {
                        List<Volunteer_Orientation_Training__c> updateList = new List<Volunteer_Orientation_Training__c>();
                        Boolean flag = true;
                        List<Volunteer_Orientation_Training__c> checkforExistingBeforeRegister = [
                                SELECT Id, FORMAT(Class_Offering__r.Date__c), Class_Offering__c, Class_Offering__r.Start_Time__c, Class_Offering__r.End_Time__c,
                                        Class_Offering__r.Chapter__c, Volunteer__c, Volunteer_Attendance__c
                                FROM Volunteer_Orientation_Training__c
                                WHERE Type__c = :VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION
                                AND Volunteer__c = :userRelatedContactId
                                AND (Class_Offering__r.Date__c = :checkExistingCanceledRecords[0].Class_Offering__r.Date__c
                                AND Class_Offering__r.Date__c != NULL)
                                AND (Volunteer_Attendance__c != :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_VOLUNTEER_CANCELLED
                                AND Volunteer_Attendance__c != :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_COMPLETED)
                        ];

                        if (checkforExistingBeforeRegister.size() > 0) {
                            for (Volunteer_Orientation_Training__c checkExistingTrainings : checkforExistingBeforeRegister) {
                                if (((Integer.valueOf(startTimeMap.get(checkExistingCanceledRecords.get(0).Class_Offering__r.Start_Time__c))) >= (Integer.valueOf(startTimeMap.get(checkExistingTrainings.Class_Offering__r.Start_Time__c))))
                                        && ((Integer.valueOf(startTimeMap.get(checkExistingCanceledRecords.get(0).Class_Offering__r.Start_Time__c))) >= (Integer.valueOf(startTimeMap.get(checkExistingTrainings.Class_Offering__r.End_Time__c))))
                                        || ((Integer.valueOf(startTimeMap.get(checkExistingCanceledRecords.get(0).Class_Offering__r.End_Time__c))) <= (Integer.valueOf(startTimeMap.get(checkExistingTrainings.Class_Offering__r.Start_Time__c))))
                                        && ((Integer.valueOf(startTimeMap.get(checkExistingCanceledRecords.get(0).Class_Offering__r.End_Time__c))) <= (Integer.valueOf(startTimeMap.get(checkExistingTrainings.Class_Offering__r.End_Time__c))))) {
                                    if (checkExistingCanceledRecords.get(0).Class_Offering__r.RecordTypeId == classOfferingRecordtypeId) {
                                        if (getUserRelatedContact.size() > 0 && lMSCredential != null) {
                                            User currVolunteerUser = getUserRelatedContact.get(0);
                                            currLMSUserResponse = LMSHttpRequest.createOrActivateLMSUser(currVolunteerUser, lMSCredential);
                                        }
                                        LMSOrientationRegistrationResponse currLMSOrientationRegistrationResponse = new LMSOrientationRegistrationResponse();
                                        currLMSOrientationRegistrationResponse = LMSHttpRequest.createOrUpdateEnrollment(lMSCredential, classOfferingMap.get(trainingId).Course_ID__c, currLMSUserResponse.login, 'in-progress', null);
                                        checkExistingCanceledRecords.get(0).LMS_Enrollment_Id__c = (currLMSOrientationRegistrationResponse.id != null) ? String.valueOf(currLMSOrientationRegistrationResponse.id) : null;
                                    }

                                    checkExistingCanceledRecords.get(0).Volunteer_Attendance__c = VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_REGISTERED;
                                    checkExistingCanceledRecords.get(0).Class_Offering__c = trainingId;
                                    updateList.add(checkExistingCanceledRecords[0]);
                                } else {
                                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Volunteer_Portal_Already_Registered_Same_Day_Time_Message_Orientation);
                                    ApexPages.addMessage(myMsg);

                                    flag = false;
                                    isCancelled = false;
                                    isOrientationExist = false;
                                }
                            }
                            if (updateList.size() > 0 && flag == true) {
                                update updateList;
                                isCancelled = false;
                                isOrientationExist = true;
                                checkRegisteredProgram();
                            }
                        } else {
                            checkExistingCanceledRecords.get(0).Volunteer_Attendance__c = VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_REGISTERED;
                            checkExistingCanceledRecords.get(0).Class_Offering__c = trainingId;
                            if (checkExistingCanceledRecords.get(0).Class_Offering__r.RecordTypeId == classOfferingRecordtypeId) {
                                if (getUserRelatedContact.size() > 0 && lMSCredential != null) {
                                    User currVolunteerUser = getUserRelatedContact.get(0);
                                    currLMSUserResponse = LMSHttpRequest.createOrActivateLMSUser(currVolunteerUser, lMSCredential);
                                }
                                LMSOrientationRegistrationResponse currLMSOrientationRegistrationResponse = new LMSOrientationRegistrationResponse();
                                currLMSOrientationRegistrationResponse = LMSHttpRequest.createOrUpdateEnrollment(lMSCredential, classOfferingMap.get(trainingId).Course_ID__c, currLMSUserResponse.login, 'in-progress', null);
                                checkExistingCanceledRecords.get(0).LMS_Enrollment_Id__c = (currLMSOrientationRegistrationResponse.id != null) ? String.valueOf(currLMSOrientationRegistrationResponse.id) : null;

                            }
                            LstLog.add('check existing cancel records' + String.valueOf(checkExistingCanceledRecords));
                            update checkExistingCanceledRecords;
                            isCancelled = false;
                            isOrientationExist = true;
                            checkRegisteredProgram();
                        }
                    }

                    else {
                        Set<String> existingTrainingSet = new Set<String>();
                        for (Volunteer_Orientation_Training__c checkExistingTrainings : [
                                SELECT Id, FORMAT(Class_Offering__r.Date__c), Class_Offering__c, Class_Offering__r.Start_Time__c, Class_Offering__r.End_Time__c, Class_Offering__r.Chapter__c, Volunteer__c, Volunteer_Attendance__c
                                FROM Volunteer_Orientation_Training__c
                                WHERE Type__c = :VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION AND Class_Offering__r.Date__c = :classOfferingDetails[0].Date__c
                                AND (Volunteer_Attendance__c != :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_VOLUNTEER_CANCELLED AND Volunteer_Attendance__c != :VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_COMPLETED) AND Volunteer__c = :userRelatedContactId
                        ]) {
                            LstLog.add(String.valueOf(checkExistingTrainings));
                            if (!existingTrainingSet.contains(startTimeMap.get(checkExistingTrainings.Class_Offering__r.Start_Time__c) + '-' + endTimeMap.get(checkExistingTrainings.Class_Offering__r.End_Time__c))) {
                                existingTrainingSet.add(startTimeMap.get(checkExistingTrainings.Class_Offering__r.Start_Time__c) + '-' + endTimeMap.get(checkExistingTrainings.Class_Offering__r.End_Time__c));
                            }
                        }
                        for (String iterateExistingValues : existingTrainingSet) {
                            if (!((Integer.valueOf(startTimeMap.get(classOfferingDetails.get(0).Start_Time__c)) >= Integer.valueOf(iterateExistingValues.split('-')[0]))
                                    && (Integer.valueOf(startTimeMap.get(classOfferingDetails.get(0).Start_Time__c)) >= Integer.valueOf(iterateExistingValues.split('-')[1]))
                                    || (Integer.valueOf(startTimeMap.get(classOfferingDetails.get(0).End_Time__c)) <= Integer.valueOf(iterateExistingValues.split('-')[0]))
                                    && (Integer.valueOf(startTimeMap.get(classOfferingDetails.get(0).End_Time__c)) <= Integer.valueOf(iterateExistingValues.split('-')[1])))) {
                                checkDupSets.add(iterateExistingValues);
                            }
                        }
                        if (!checkDupSets.isEmpty()) {
                            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Volunteer_Portal_Already_Registered_Same_Day_Time_Message_Orientation);
                            ApexPages.addMessage(myMsg);
                            isCancelled = false;
                            isOrientationExist = false;
                        } else {
                            Volunteer_Orientation_Training__c newTrainingRegistration = new Volunteer_Orientation_Training__c();
                            newTrainingRegistration.Class_Offering__c = trainingId;
                            newTrainingRegistration.Volunteer__c = userRelatedContactId;
                            newTrainingRegistration.Type__c = VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION;
                            newTrainingRegistration.Registered_Date__c = System.today();
                            newTrainingRegistration.Volunteer_Attendance__c = VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_REGISTERED;
                            newTrainingRegistration.Hidden_O_T_Id__c = classOfferingMap.get(trainingId).Chapter_Role_O_T__r.Orientation_Training__c;

                            isCancelled = false;
                            isOrientationExist = true;
                            /*Added by Sailappa Vignesh PG
                            Description : To create a new  Course enrollment in LMS*/
                            User currVolunteerUser = getUserRelatedContact.get(0);
                            if (classOfferingMap.get(trainingId).RecordTypeId == classOfferingRecordtypeId) {

                                if (getUserRelatedContact.size() > 0 && lMSCredential != null) {

                                    currLMSUserResponse = LMSHttpRequest.createOrActivateLMSUser(currVolunteerUser, lMSCredential);
                                }
                                LMSOrientationRegistrationResponse currLMSOrientationRegistrationResponse = new LMSOrientationRegistrationResponse();
                                currLMSOrientationRegistrationResponse = LMSHttpRequest.createOrUpdateEnrollment(lMSCredential, classOfferingMap.get(trainingId).Course_ID__c, currLMSUserResponse.login, 'in-progress', null);
                                if (currLMSOrientationRegistrationResponse.status != null && currLMSOrientationRegistrationResponse.status.equalsIgnoreCase('in-progress')) {
                                    newTrainingRegistration.LMS_Enrollment_Id__c = (currLMSOrientationRegistrationResponse.id != null) ? String.valueOf(currLMSOrientationRegistrationResponse.id) : null;

                                }
                            }

                            LstLog.add('newTrainingRegistration' + String.valueOf(newTrainingRegistration));
                            insert newTrainingRegistration;
                            if (currVolunteerUser.LMS_Id__c != String.valueOf(currLMSUserResponse.id) || currVolunteerUser.LMS_Login__c != String.valueOf(currLMSUserResponse.login) || currVolunteerUser.LMS_User_Code__c != String.valueOf(currLMSUserResponse.code)) {
                                updateUser(String.valueOf(currLMSUserResponse.id), String.valueOf(currLMSUserResponse.login), String.valueOf(currLMSUserResponse.code), currVolunteerUser.Id);
                            }
                            checkRegisteredProgram();
                        }
                    }
                }
            }
            Contact currContact = new Contact();
            currContact.Id = userRelatedContactId ;
            currContact.Onboarding_Status__c = Constant_AC.CONTACT_ONBOARDING_STATUS_ORIENTATION;
            LstLog.add(String.valueOf(currContact));
            update currContact;
        } catch (Exception ex) {
            Logvalue = String.join(LstLog, ', ');
            new ApexDebugLog().createLog(new ApexDebugLog.Error('VolunteerOrientation_AC', 'Register', null, ex, Logvalue));
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Debug_log_error_message);
            ApexPages.addMessage(myMsg);
        }
    }

    // Volunteer have a option to cancel their registered orientation program in the Registered orientation table.
    public void Cancel() {
        String Logvalue;
        String recId;
        LMSUserResponse currLMSUserResponse = new LMSUserResponse();
        try {
            List<Class_Offering__c> orientationDetails = [
                    SELECT Id, Course_ID__c, Chapter__c, RecordTypeId
                    FROM Class_Offering__c
                    WHERE Id = :trainingId
            ];
            if (!orientationDetails.isEmpty()) {

                List<Volunteer_Orientation_Training__c> cancelRegistrationList = [
                        SELECT Id, Class_Offering__c, LMS_Enrollment_Id__c
                        FROM Volunteer_Orientation_Training__c
                        WHERE Class_Offering__c = :trainingId AND Volunteer__c = :userRelatedContactId
                        AND Class_Offering__r.Chapter__c = :orientationDetails.get(0).Chapter__c AND
                        Type__c = :VOLUNTEER_ORIENTATION_TRAINING_TYPE_ORIENTATION
                ];

                if (!cancelRegistrationList.isEmpty()) {
                    if (!getUserRelatedContact.isEmpty()) {
                        if (lMSCredential != null) {
                            User currVolunteerUser = getUserRelatedContact.get(0);
                            cancelRegistrationList.get(0).Volunteer_Attendance__c = VOLUNTEER_ORIENTATION_TRAINING_VOLUNTEER_ATTENDANCE_VOLUNTEER_CANCELLED;

                            if (orientationDetails[0].RecordTypeId == classOfferingRecordtypeId) {
                                currLMSUserResponse = LMSHttpRequest.createOrActivateLMSUser(currVolunteerUser, lMSCredential);
                                LMSOrientationRegistrationResponse currLMSOrientationRegistrationResponse = new LMSOrientationRegistrationResponse();
                                currLMSOrientationRegistrationResponse
                                        = LMSHttpRequest.createOrUpdateEnrollment(lMSCredential, classOfferingMap.get(trainingId).Course_ID__c, currLMSUserResponse.login, 'dropped', Integer.valueOf(cancelRegistrationList.get(0).LMS_Enrollment_Id__c));
                                cancelRegistrationList.get(0).LMS_Enrollment_Id__c = '';
                            }

                        }
                        recId = cancelRegistrationList[0].Id;
                        Logvalue = String.valueOf('cancellation list' + cancelRegistrationList);
                        update cancelRegistrationList;
                        isOrientationExist = false;
                        isCancelled = true;
                    }
                    checkRegisteredProgram();
                }
            }
        } catch (Exception ex) {
            new ApexDebugLog().createLog(new ApexDebugLog.Error('VolunteerOrientation', 'Cancel', recId, ex, Logvalue));
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Debug_log_error_message);
            ApexPages.addMessage(myMsg);

        }
    }

    // Its redirecting to LMS page.
    public void viewLMS() {
        /*Added by Sailappa Vignesh PG
        Description : To create or active the current Volunteer in LMS*/
        LMSUserResponse currLMSUserResponse = new LMSUserResponse();
        if (getUserRelatedContact.size() > 0 && lMSCredential != null) {
            User currVolunteerUser = getUserRelatedContact.get(0);
            currLMSUserResponse = LMSHttpRequest.createOrActivateLMSUser(currVolunteerUser, lMSCredential);
        }
        /*Description : To get a access URL from the LMS*/
        if (currLMSUserResponse != null && currLMSUserResponse.code != null) {
            lMSSSOResponse = LMSHttpRequest.getLMSSSODetails(lMSCredential, currLMSUserResponse.code, lMSCourseId);
            sSOUrl = lMSSSOResponse.login_url;
            courseURL = (lMSSSOResponse.enrollment_url != null) ? lMSSSOResponse.enrollment_url : lMSSSOResponse.login_url;
        }
    }

    //Pagination
    public PageReference Beginning() { //user clicked beginning
        counter = 0;
        return null;
    }

    public PageReference Previous() { //user clicked previous button
        counter -= list_size;
        return null;
    }

    public PageReference Next() { //user clicked next button
        counter += list_size;
        return null;
    }

    public PageReference End() { //user clicked end
        counter = total_size - Math.mod(total_size, list_size);
        return null;
    }

    public Boolean getDisablePrevious() {
        //this will disable the previous and beginning buttons
        return counter > 0 ? false : true;
    }

    public Boolean getDisableNext() {
        //this will disable the next and end buttons
        return (counter + list_size < total_size) ? false : true;
    }

    // Displaying current page number.
    public Integer getPageNumber() {
        return counter / list_size + 1;
    }

    // Calculating total pages based on the total number of records.
    public Integer getTotalPages() {
        if (Math.mod(total_size, list_size) > 0) {
            return total_size / list_size + 1;
        } else {
            return (total_size / list_size);
        }
    }

    public class ClassOfferingWrapper {
        public String orientationName {
            get;
            set;
        }
        public String chapterName {
            get;
            set;
        }
        public Date orientationDate {
            get;
            set;
        }
        public String startTime {
            get;
            set;
        }
        public String endTime {
            get;
            set;
        }
        public String location { get; set; }
        public Integer maxCapacity {
            get;
            set;
        }
        public Integer avilableSheets {
            get;
            set;
        }
        public String recordType {
            get;
            set;
        }
        public String status {
            get;
            set;
        }
        public Integer volOppSize {
            get;
            set;
        }
        public String recordId {
            get;
            set;
        }
        public String courseId {
            get;
            set;
        }
        public String recordTypeId {
            get;
            set;
        }
        public Boolean displayRec {
            get;
            set;
        }
    }

    @Future
    public static void updateUser(String LMS_Id, String LMS_Login, String LMS_User_Code, String userId) {
        String Logvalue;
        String recid;
        try {
            User currVolunteerUser = new User();
            currVolunteerUser.Id = userId;
            currVolunteerUser.LMS_Id__c = LMS_Id;
            currVolunteerUser.LMS_Login__c = LMS_Login;
            currVolunteerUser.LMS_User_Code__c = LMS_User_Code;
            recid = currVolunteerUser.LMS_Id__c;
            Logvalue = String.valueOf('curr volunteer user' + currVolunteerUser);
            update currVolunteerUser;
        } catch (Exception ex) {
            new ApexDebugLog().createLog(new ApexDebugLog.Error('VolunteerOrientation_AC', 'updateUser', recid, ex, Logvalue));
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Debug_log_error_message);
            ApexPages.addMessage(myMsg);

        }
    }
}