make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This field holds the state name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field will be used to know the progress(Current status) of the wish</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age Expiration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign in Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss of Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Viewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refused</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wish_type__c</fullName>
        <description>It holds the details about the  type of wish</description>
        <label>Wish type</label>
        <picklist>
            <picklistValues>
                <fullName>Cruise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GKTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter details and role for this chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the role name and chapters assigned for this role.</description>
        <label>Role Name</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of the chapter role.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Non-Wish &amp; Events</relationshipLabel>
        <relationshipName>Non_Wish_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <fields>
        <fullName>isWishRole__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identify whether the role is wish or non wish</description>
        <label>isWishRole</label>
        <type>Checkbox</type>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Chapter_Role_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field look up with Chapter Role</description>
        <label>Chapter Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Chapter_Role__c.Chapter_Name__c</field>
                <operation>equals</operation>
                <valueField>$Source.Chapter_Name__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used when the to identify whether the volunteer opportunity is active or not.</description>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Wish_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It hold the record of each event</description>
        <label>Name</label>
        <referenceTo>Non_Wish_Events__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_Inactive__c</fullName>
        <description>This field is get the values when the volunteer contact is removed form the volunteer Name field.</description>
        <label>Reason Inactive</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Moved</fullName>
                </value>
                <value>
                    <fullName>Non-responsive</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It will display the role name</description>
        <formula>Chapter_Role_Opportunity__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It indicate different status of the volunteer opportunity.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <description>This field store the role name.</description>
        <formula>Chapter_Role__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will hold the volunteer name and define chapter and role for this volunteer.</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isWishRole__c</fullName>
        <description>This field is used to store the wish role.</description>
        <formula>Chapter_Role__r.Role_Name__r.isWishRole__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isWishRole</label>
        <type>Checkbox</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerWorkItems_AC_Test.cls
@isTest
public class VolunteerWorkItems_AC_Test {

	@testSetup static void setup() {
		trac_TriggerHandlerBase.blockTrigger = true;
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		acc.Name = 'Primary Account';
		insert acc;

		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
		insert new List<Contact>{
				con, wishChild
		};

		insert OrientationandTrainingUtil.createAffiliation(con.id);

		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createActiveVolunteerUser(con.id);
			insert currUser;
		}

		Role__c currRole = OrientationandTrainingUtil.createRole();
		Role__c currNonWishRole = OrientationandTrainingUtil.createNonWishRole();
		insert new List<Role__C>{
				currRole, currNonWishRole
		};

		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.Id);
		Chapter_Role__c currNonWishChapRole = OrientationandTrainingUtil.createChapter(acc.id, currNonWishRole.Id);
		insert new List<Chapter_Role__c>{
				currChapRole, currNonWishChapRole
		};

		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(currUser.ContactId, currChapRole.Id);
		insert currVolRole;

		Case newParentWish = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
		newParentWish.Sub_Status__c = 'Abandoned';
		insert newParentWish;

		Non_Wish_Events__c nonWishEvent = OrientationandTrainingUtil.CreateEvent(acc.Id);
		insert nonWishEvent;

		Volunteer_Opportunity__c wishVolunteerOpportunity = OrientationandTrainingUtil.CreateNewWishVolunteerOpportunity(acc.Id, currChapRole.Id, newParentWish.Id);
		Volunteer_Opportunity__c wishVolunteerOpportunity1 = OrientationandTrainingUtil.CreateNewWishVolunteerOpportunity(acc.Id, currChapRole.Id, newParentWish.Id);
		Volunteer_Opportunity__c duplicateWishVolunteerOpportunity = OrientationandTrainingUtil.createDuplicateNewWishVolunteerOpportunity(acc.Id, currChapRole.Id, newParentWish.Id);
		Volunteer_Opportunity__c nonWishVolunteerOpportunity = OrientationandTrainingUtil.CreateNonWishVolunteerOpportunity(acc.Id, currChapRole.Id, nonWishEvent.Id);
		Volunteer_Opportunity__c nonWishVolunteerOpportunity1 = OrientationandTrainingUtil.CreateNonWishVolunteerOpportunity(acc.Id, currChapRole.Id, nonWishEvent.Id);
		Volunteer_Opportunity__c duplicateNonWishVolunteerOpportunity = OrientationandTrainingUtil.CreateNonWishDuplicateVolunteerOpportunity(acc.Id, currChapRole.Id, nonWishEvent.Id);
		Volunteer_Opportunity__c nonWishEventVolunteerOpportunity = OrientationandTrainingUtil.CreateNonWishVolunteerOpportunity(acc.Id, currChapRole.Id, nonWishEvent.Id);
		Volunteer_Opportunity__c nonWishEventVolunteerOpportunity1 = OrientationandTrainingUtil.CreateNonWishVolunteerOpportunity(acc.Id, currChapRole.Id, nonWishEvent.Id);
		Volunteer_Opportunity__c wishEventVolunteerOpportunity = OrientationandTrainingUtil.CreateNonWishVolunteerOpportunity(acc.Id, currChapRole.Id, nonWishEvent.Id);
		Volunteer_Opportunity__c wishEventVolunteerOpportunity1 = OrientationandTrainingUtil.CreateNonWishVolunteerOpportunity(acc.Id, currChapRole.Id, nonWishEvent.Id);
		wishVolunteerOpportunity.RecordTypeId = duplicateWishVolunteerOpportunity.RecordTypeId = wishVolunteerOpportunity1.RecordTypeId = Constant_AC.REGISTERED_WISH_ID;
		wishVolunteerOpportunity.Volunteer_Name__c = duplicateWishVolunteerOpportunity.Volunteer_Name__c = wishVolunteerOpportunity1.Volunteer_Name__c = currUser.ContactId;

		wishVolunteerOpportunity.Inactive__c = true;
		wishVolunteerOpportunity.Inactivated_or_Rejected_Date__c = System.now().date();
		wishVolunteerOpportunity.Reason_Inactive__c = 'Test';

		duplicateWishVolunteerOpportunity.Status__c = 'Pending';
		duplicateWishVolunteerOpportunity.Inactivated_or_Rejected_Date__c = System.now().date();

		wishVolunteerOpportunity1.Status__c = 'Approved';

		nonWishVolunteerOpportunity.RecordTypeId = duplicateNonWishVolunteerOpportunity.RecordTypeId = nonWishVolunteerOpportunity1.RecordTypeId = Constant_AC.REGISTERED_NON_WISH_ID;
		nonWishVolunteerOpportunity.Volunteer_Name__c = duplicateNonWishVolunteerOpportunity.Volunteer_Name__c = nonWishVolunteerOpportunity1.Volunteer_Name__c = currUser.ContactId;

		nonWishVolunteerOpportunity.Inactive__c = true;
		nonWishVolunteerOpportunity.Inactivated_or_Rejected_Date__c = System.now().date();
		nonWishVolunteerOpportunity.Reason_Inactive__c = 'Test';

		duplicateNonWishVolunteerOpportunity.Status__c = 'Pending';
		duplicateNonWishVolunteerOpportunity.Inactivated_or_Rejected_Date__c = System.now().date();

		nonWishVolunteerOpportunity1.Status__c = 'Approved';

		nonWishEventVolunteerOpportunity.RecordTypeId = nonWishEventVolunteerOpportunity1.RecordTypeId = Constant_AC.NON_WISH_EVENT_RT_ID;
		nonWishEventVolunteerOpportunity.Wish__c = nonWishEventVolunteerOpportunity1.Wish__c = newParentWish.Id;

		wishEventVolunteerOpportunity.RecordTypeId = wishEventVolunteerOpportunity1.RecordTypeId = Constant_AC.WISH_VOLUNTEER_OPPORTUNITY_ID;
		wishEventVolunteerOpportunity.Wish__c = wishEventVolunteerOpportunity1.Wish__c = newParentWish.Id;
		insert new List<Volunteer_Opportunity__c>{
				wishVolunteerOpportunity, duplicateWishVolunteerOpportunity, nonWishVolunteerOpportunity,
				wishVolunteerOpportunity1, duplicateNonWishVolunteerOpportunity, nonWishVolunteerOpportunity1,
				nonWishEventVolunteerOpportunity, nonWishEventVolunteerOpportunity1,
				wishEventVolunteerOpportunity, wishEventVolunteerOpportunity1
		};
		/*Case ParentWish = OrientationandTrainingUtil.CreateParentCaseWithTravel(wishChild.Id);
		Volunteer_Opportunity__c closewishVolunteerOpportunity = OrientationandTrainingUtil.CreateNewWishVolunteerOpportunity(acc.Id,currChapRole.Id,ParentWish.Id);
		closewishVolunteerOpportunity.Volunteer_Name__c = con.Id;
		update closewishVolunteerOpportunity;*/
		trac_TriggerHandlerBase.blockTrigger = false;
	}

	public static testMethod void volunteerWishEvents() {
		test.startTest();
		Account chapterAcc = [
				SELECT Id
				FROM Account
				WHERE Name = 'Primary Account'
		];
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;

		Role__c currRole = OrientationandTrainingUtil.createRole();
		Role__c currNonWishRole = OrientationandTrainingUtil.createNonWishRole();
		currRole.isWishRole__c = currNonWishRole.isWishRole__c = false;
		insert new List<Role__c>{
				currRole, currNonWishRole
		};

		Chapter_Role__c currNonWishChapRole = OrientationandTrainingUtil.createChapter(acc.id, currNonWishRole.Id);
		insert currNonWishChapRole;

		User currUser = [
				SELECT Id,UserName, ContactId
				FROM User
				WHERE UserName = :'joathanedwards@gmail.com'
		];
		Case dbCase = [
				SELECT Id,Status,Wish_Type__c
				FROM Case
				WHERE Wish_Type__c = :'Disney World'
		];

		Volunteer_Opportunity__c dbOpp = [
				SELECT Id,Wish__c,Non_Wish_Event__C,Hidden_VolunteerCount_Desc__c,Chapter_Role_Opportunity__c
				FROM Volunteer_Opportunity__c
				WHERE Wish__c = :dbCase.id
				Limit 1
		];
		List<Volunteer_Opportunity__c> voloppList = new List<Volunteer_Opportunity__c>([
				SELECT Id,Wish__c,Non_Wish_Event__C,Hidden_VolunteerCount_Desc__c,Role__c,
						Chapter_Role_Opportunity__r.Role_Name__c,Chapter_Name__r.Name, Reason_Inactive__c,
						Status__c
				FROM Volunteer_Opportunity__c
				WHERE Role__c = 'Wish Granter'
		]);
		voloppList[0].Status__c = 'Pending';
		voloppList[0].Inactive__c = false;
		voloppList[0].Reason_Inactive__c = null;
		update voloppList;
		Volunteer_Roles__c volRole = [
				SELECT Id, Status__c, Volunteer_Name__c
				FROM Volunteer_Roles__c
				LIMIT 1
		];
		volRole.Status__c = 'Pending';
		volRole.Sub_status__c = 'Missing Requirement';
		volRole.Volunteer_Name__c = currUser.ContactId;
		update volRole;
		System.RunAs(currUser) {

			PageReference pageref = Page.MyAssignment_VF;
			Test.setCurrentPageReference(pageref);
			VolunteerWorkItems_AC volunteerWorkitem = new VolunteerWorkItems_AC(new ApexPages.StandardController(dbOpp));
			VolunteerWorkItems_AC volunteerWorkitems = new VolunteerWorkItems_AC();
			volunteerWorkitems.volunteerOpportunityRecordId = dbOpp.Id;
			volunteerWorkitems.volunteerChaptersSet = new Set<Id>();
			volunteerWorkitems.volunteerChaptersSet.add(chapterAcc.Id);
			volunteerWorkitems.CurrentWish();
			volunteerWorkitems.HistoricalWish();
			volunteerWorkitems.getVolunteerAssignedWishEvents();
			volunteerWorkitems.getVolunteerAssignedNonWishEvents();
			volunteerWorkitems.getWishEvents();
			volunteerWorkitems.getNonWishEvents();
			volunteerWorkitems.volunteerOpportunityRecordId = voloppList[0].Id;
			volunteerWorkitems.RegisterWishEvents();
			volunteerWorkitems.registrationConfirmation();
			volunteerWorkitems.getChapterRoleOanTStatus(currNonWishChapRole.id);
			volunteerWorkitems.allowRegisteration(voloppList);
			volunteerWorkitems.RedirecttoVolOpportunity();
			test.stopTest();
		}
	}
	public static testMethod void volunteerClosedWish() {
		Test.startTest();
		user currUser = [
				SELECT Id,UserName
				FROM User
				WHERE UserName = :'joathanedwards@gmail.com'
		];

		Case dbCase = [
				SELECT Id,Status,Wish_Type__c
				FROM Case
				WHERE Wish_Type__c = :'Disney World'
		];
		dbCase.Status = 'Closed';
		//update closedCase;

		System.RunAs(currUser) {

			PageReference pageref = Page.MyAssignment_VF;
			Test.setCurrentPageReference(pageref);
			VolunteerWorkItems_AC volunteerWorkitems = new VolunteerWorkItems_AC();
			volunteerWorkitems.CurrentWish();
			volunteerWorkitems.HistoricalWish();
			volunteerWorkitems.getClosedWish();
			volunteerWorkitems.RegisterWishEvents();
			// volunteerWorkitems.allowRegisteration();

		}
		test.stopTest();
	}
	public static testMethod void volunteerClosedNonWish() {
		Test.startTest();
		user currUser = [
				SELECT Id,UserName
				FROM User
				WHERE UserName = :'joathanedwards@gmail.com'
		];
		Non_Wish_Events__c closedNonWish = [
				SELECT Id,Event_Text__c
				FROM Non_Wish_Events__c
				WHERE Event_Text__c = 'Sending Wish Child'
		];
		closedNonWish.Event_Date__c = system.today() - 3;
		update closedNonWish;
		System.RunAs(currUser) {
			PageReference pageref = Page.MyAssignment_VF;
			Test.setCurrentPageReference(pageref);
			VolunteerWorkItems_AC volunteerWorkitems = new VolunteerWorkItems_AC();
			volunteerWorkitems.CurrentWish();
			volunteerWorkitems.HistoricalWish();
			volunteerWorkitems.getClosedNonWishEvents();
			volunteerWorkitems.RegisterWishEvents();
			//volunteerWorkitems.allowRegisteration();

		}
		test.stopTest();
	}

	public static testMethod void volunteerRegisteredNonWish() {
		Test.startTest();
		user currUser = [
				SELECT Id,UserName
				FROM User
				WHERE UserName = :'joathanedwards@gmail.com'
		];
		Non_Wish_Events__c dbNonWish = [
				SELECT Id,Event_Text__c
				FROM Non_Wish_Events__c
				WHERE Event_Text__c = 'Sending Wish Child'
		];
		Volunteer_Opportunity__c dbOpp = [
				SELECT Id,Chapter_Name__r.Name,Non_Wish_Event__C,Chapter_Role_Opportunity__r.Role_Name__c
				FROM Volunteer_Opportunity__c
				WHERE Non_Wish_Event__C = :dbNonWish.Id
				Limit 1
		];
		System.RunAs(currUser) {
			PageReference pageref = Page.MyAssignment_VF;
			Test.setCurrentPageReference(pageref);
			VolunteerWorkItems_AC volunteerWorkitems = new VolunteerWorkItems_AC();
			volunteerWorkitems.volunteerOpportunityRecordId = dbOpp.Id;
			volunteerWorkitems.RegisterWishEvents();
			//volunteerWorkitems.allowRegisteration();
			// volunteerWorkitems.RegisterNonWishEvents();

		}
		Test.stopTest();
	}
}