make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer manager</description>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_is_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It activates when the volunteer becomes inactive or all affiliations records are inactive status.</description>
        <label>Hidden Volunteer is Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Constituent_Code__c.object
<CustomObject>
    <label>Constituent Code</label>
    <nameField>
        <label>Constituent Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituent Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Hidden_Status__c</fullName>
        <description>It store the Affiliation Object  Status field value</description>
        <label>Hidden Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>Constituent_Code__c</fullName>
        <description>It stores the value of Constituent Code</description>
        <label>Constituent Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wish Child</fullName>
                </value>
                <value>
                    <fullName>Wish Family</fullName>
                </value>
                <value>
                    <fullName>Celebrity</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Volunteer Leadership</fullName>
                </value>
                <value>
                    <fullName>Medical Professional</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Referral Source</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Intern</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Out of Compliance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the chapter named of Account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used when the to identify whether the volunteer opportunity is active or not.</description>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to choose the name of the volunteer contact</description>
        <label>Volunteer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Affiliation_OnAfterUpdateTriggerHelper.cls
public class Affiliation_OnAfterUpdateTriggerHelper
{
     // Used to add a user to chatter group based on their chapter when the volunter become active.
    public static void addUserToChaptterGroup(Set<Id> volunteerContactIdsSet, Set<Id> affiliationsIdsSet,List<npe5__Affiliation__c> exceptionList)
    {
        try{
            Map<Id,String> volunteerChaptersMap = new Map<Id,String>();
            Set<String> chapterNamesSet = new Set<String>();
            Map<Id, Id> volunteerUsersMap = new Map<Id,Id>();
            Map<String,Id> chatterGroupNameIdsMap = new Map<String,Id>();
            List<CollaborationGroupMember> chatterGroupMembersList = new List<CollaborationGroupMember>();
            
            for(npe5__Affiliation__c getChapters : [SELECT Id, npe5__Organization__r.Name, npe5__Contact__c FROM npe5__Affiliation__c WHERE npe5__Contact__c IN : volunteerContactIdsSet AND Id IN : affiliationsIdsSet]) 
            {
                if(!chapterNamesSet.contains(getChapters.npe5__Organization__r.Name)) 
                {
                    chapterNamesSet.add(String.valueOf(getChapters.npe5__Organization__r.Name).removeStart('Make-A-Wish '));
                }
                volunteerChaptersMap.put(getChapters.npe5__Contact__c, String.valueOf(getChapters.npe5__Organization__r.Name).removeStart('Make-A-Wish '));
            }
            
            System.debug('ChapterName Set'+ chapterNamesSet);
            // Used to get volunteer user id and volunteer contact id
            for(User relatedUsers : [SELECT Id, ContactId FROM User WHERE ContactId IN : volunteerContactIdsSet])
            {
                volunteerUsersMap.put(relatedUsers.ContactId ,relatedUsers.Id);
            }        
            if(chapterNamesSet.size()>0)
            {
                // Used to get the group name based on the chapter names
                for(CollaborationGroup getgroupId : [SELECT Id, Name FROM CollaborationGroup WHERE Name IN : chapterNamesSet]) 
                {
                    chatterGroupNameIdsMap.put(getgroupId.Name,getgroupId.Id);
                }
            }
            System.debug('chatterGroupNameIdsMap>>>'+chatterGroupNameIdsMap);
            Set<String> chatterGroupsMembersSet = new Set<String>();
            for(CollaborationGroupMember chatterGroupMemberExistCheck : [SELECT Id, MemberId, CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId IN : volunteerUsersMap.values()])  
            {
                chatterGroupsMembersSet.add(chatterGroupMemberExistCheck.CollaborationGroupId+'-'+chatterGroupMemberExistCheck.MemberId);
            }
            //Used to check whether a user exists in the chatter group before adding the user to group
            for(Id volunteerContact : volunteerContactIdsSet) 
            {
                if(volunteerChaptersMap.containsKey(volunteerContact) && chatterGroupNameIdsMap.containsKey(volunteerChaptersMap.get(volunteerContact)) && volunteerChaptersMap.containsKey(volunteerContact)) 
                {
                    if(!chatterGroupsMembersSet.contains(chatterGroupNameIdsMap.get(volunteerChaptersMap.get(volunteerContact))+'-'+volunteerUsersMap.get(volunteerContact)))
                    {
                        chatterGroupMembersList.add(new CollaborationGroupMember (CollaborationGroupId = chatterGroupNameIdsMap.get(volunteerChaptersMap.get(volunteerContact)), MemberId = volunteerUsersMap.get(volunteerContact)));
                    }
                }            
            }
            if(chatterGroupMembersList.size()>0) 
            {
                if(!Test.isRunningTest()) 
                {
                    insert chatterGroupMembersList; // adding members to the group.
                }
            }
        }
         catch(Exception ex){
            for(npe5__Affiliation__c currRec : exceptionList){
                ErrorMessage_AC.createdebugRec('Affiliation_OnAfterUpdateTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'addUserToChaptterGroup',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            for(npe5__Affiliation__c currRec : exceptionList){
                currRec.addError(Label.Debug_log_error_message);
            } 
        }
    }
     public Static void createTaskforVolunteerManager(Set<Id> userList,List<npe5__Affiliation__c> exceptionList){
        
        try{
            Map<Id,Id> volunteerManagerId = new Map<Id,Id>();
            List<Volunteer_Opportunity__c> VolunteerOpportunityActive=new List<Volunteer_Opportunity__c>([SELECT id,Chapter_Name__r.Volunteer_Manager__c,Volunteer_Name__c  FROM Volunteer_Opportunity__c WHERE Volunteer_Name__c IN: userList AND Inactive__c =False]);
            for(Volunteer_Opportunity__c  currRec:VolunteerOpportunityActive){
                   volunteerManagerId.put(currRec.Volunteer_Name__c,currRec.Chapter_Name__r.Volunteer_Manager__c);
                   system.debug('*********'+currRec.Volunteer_Name__c+'*****');
            }
            if(volunteerManagerId.size() >0){
                List<Task> ActiveTask=new List<Task>();
                Task newTask;
                for(Id currRec:volunteerManagerId.keyset()){
                    newTask=new Task();
                    if(volunteerManagerId.containsKey(currRec) && volunteerManagerId.get(currRec) != null) {
                        newTask.OwnerId=volunteerManagerId.get(currRec);
                    }                    
                    newTask.WhoId=currRec;
                    newTask.Subject='Inactive Volunteer - review volunteer opportunities';
                    newTask.SystemGeneratedTask__c = TRUE;
                    ActiveTask.add(newTask);
                    system.debug('@@@@@@@@@@@'+currRec+'*****');     
                }
                Insert ActiveTask;
            }
        }
       // updateBCandCOIVolunteerInactive(userList,True);
       catch(Exception ex){
            for(npe5__Affiliation__c currRec : exceptionList){
                ErrorMessage_AC.createdebugRec('Affiliation_OnAfterUpdateTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'createTaskforVolunteerManager',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            for(npe5__Affiliation__c currRec : exceptionList){
                currRec.addError(Label.Debug_log_error_message);
            } 
        }
    }
     public static void inactiveAffiliations(Set<Id> volunteerIdSet,List<npe5__Affiliation__c> exceptionList)
     {
        try{
            Set<Id> inactiveVolunteerIdSet = new set<Id>();
            for(npe5__Affiliation__c currAff : [SELECT id,npe5__Status__c,npe5__Contact__c  FROM npe5__Affiliation__c WHERE  npe5__Contact__c IN :volunteerIdSet])
            {
                   
                   if(currAff.npe5__Status__c != 'Active')
                   {
                       inactiveVolunteerIdSet.add(currAff.npe5__Contact__c); 
                   }
                   else if(currAff.npe5__Status__c == 'Active' && inactiveVolunteerIdSet.Contains(currAff.npe5__Contact__c))
                   {
                       inactiveVolunteerIdSet.Remove(currAff.npe5__Contact__c);
                   }
            }
            if(inactiveVolunteerIdSet.Size() > 0)
            {
                    updateBCandCOIVolunteerInactive(inactiveVolunteerIdSet,True,exceptionList);
             }
             
         }catch(Exception ex){
            for(npe5__Affiliation__c currRec : exceptionList){
                ErrorMessage_AC.createdebugRec('Affiliation_OnAfterUpdateTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'inactiveAffiliations',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            for(npe5__Affiliation__c currRec : exceptionList){
                currRec.addError(Label.Debug_log_error_message);
            } 
        }
     }
       public static void activeAffiliations(Set<Id> volunteerIdsSet,List<npe5__Affiliation__c> exceptionList)
     {
        try{
            Set<Id> activeVolunteerIdSet = new set<Id>();
            Set<Id> volunteerIdSet = new Set<Id>();
            for(npe5__Affiliation__c currAff : [SELECT id,npe5__Status__c,npe5__Contact__c  FROM npe5__Affiliation__c WHERE  npe5__Contact__c IN :volunteerIdsSet])
            {  
                   if(currAff.npe5__Status__c == 'Active')
                   {
                       volunteerIdSet.add(currAff.npe5__Contact__c); 
                   }   
            }
            if(volunteerIdSet.Size() > 0)
            {
                    For(User currUser : [SELECT Id,ContactId FROM User Where contactId IN :volunteerIdSet AND isActive = True])
                    {
                        activeVolunteerIdSet.add(currUser.ContactId);
                    }
                    if(activeVolunteerIdSet.Size() > 0)
                    {
                        updateBCandCOIVolunteerInactive(activeVolunteerIdSet,False,exceptionList);
                    }
             }
         }
         catch(Exception ex){
            for(npe5__Affiliation__c currRec : exceptionList){
                ErrorMessage_AC.createdebugRec('Affiliation_OnAfterUpdateTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'activeAffiliations',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            for(npe5__Affiliation__c currRec : exceptionList){
                currRec.addError(Label.Debug_log_error_message);
            } 
        }
     }
     public static void updateBCandCOIVolunteerInactive(Set<Id> inactiveVolunteerIdSet,Boolean isInactiveVolunteer,List<npe5__Affiliation__c> exceptionList)
      {
            try{
                List<Background_check__c> updateBCList = New List<Background_check__c>();
                List<Conflict_Of_Interest__c> updateCOIList = New List<Conflict_Of_Interest__c>();
                for(Background_check__c currBC : [SELECT Id,Volunteer_is_Inactive__c FROM Background_check__c WHERE Volunteer__c IN :inactiveVolunteerIdSet AND Volunteer_is_Inactive__c !=: isInactiveVolunteer])
                {
                    currBc.Volunteer_is_Inactive__c = isInactiveVolunteer;
                    updateBCList.add(currBc);
                }
                
                if(updateBCList.Size() > 0)
                {
                     Update updateBCList;
                }
                for(Conflict_Of_Interest__c currCOI : [SELECT Id,Volunteer_is_Inactive__c FROM Conflict_Of_Interest__c WHERE Volunteer_Contact__c IN : inactiveVolunteerIdSet AND Volunteer_is_Inactive__c !=: isInactiveVolunteer])
                {
                    currCOI.Volunteer_is_Inactive__c = isInactiveVolunteer;
                    updateCOIList.add(currCOI);
                }
                if(updateCOIList.Size() > 0)
                {
                    Update updateCOIList;
                }
            }
            catch(Exception ex){
            for(npe5__Affiliation__c currRec : exceptionList){
                ErrorMessage_AC.createdebugRec('Affiliation_OnAfterUpdateTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'updateBCandCOIVolunteerInactive',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            for(npe5__Affiliation__c currRec : exceptionList){
                currRec.addError(Label.Debug_log_error_message);
            } 
        }
            
    }
        //used to update the status field in contact for reporting purpose
    public static void updateContact(Map<id,npe5__Affiliation__c> contactMap, Set<Id> affiliationIds,List<npe5__Affiliation__c> exceptionList)
    {
        try{
            RecursiveTriggerHandler.isFirstTime = false;
            Constant_AC  constant = new Constant_AC();
            Id volunteerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.volunteerRT).getRecordTypeId();
            Id wichChildRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.contactWishChildRT).getRecordTypeId();
            Id familyContactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.wishFamilyRT).getRecordTypeId();
            Id MedicalProfContactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.MedicalProfessionalRT).getRecordTypeId();
            Id boardMemberRT = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.boardMemberRT).getRecordTypeId();
            Id chapterRT = Schema.SObjectType.Account.getRecordTypeInfosByName().get(constant.chapterRT).getRecordTypeId();
            List<Contact> conList=[SELECT id,Hidden_Status__c, RecordTypeId, RecordType.Name  from contact where id IN :contactMap.keyset()];
            Map<Id,Account> accountMap = new Map<Id,Account>([SELECT id,recordtypeid FROM Account WHERE Id IN :affiliationIds]);
            Map<String,integer> recordTypeOrder = new Map<String, integer>();
            recordTypeOrder.put('Board Member',1);
            recordTypeOrder.put('Volunteer',2);
            recordTypeOrder.put('Medical Professional',3);
            recordTypeOrder.put('Wish Child',4);
            recordTypeOrder.put('Wish Family',5);
            Map<String,String> recordTypeNames = new Map<String, String>();
            recordTypeNames.Put(volunteerRecordTypeId,'Volunteer');
            recordTypeNames.Put(wichChildRecordTypeId,'Wish Child');
            recordTypeNames.Put(familyContactRecordTypeId,'Wish Family');
            recordTypeNames.Put(MedicalProfContactRecordTypeId ,'Medical Professional');
            recordTypeNames.Put(boardMemberRT,'Board Member');
            Map<String,String> recordTypes = new Map<String, String>();
            recordTypes.put('Volunteer',volunteerRecordTypeId);
            recordTypes.put('Wish Child',wichChildRecordTypeId);
            recordTypes.put('Wish Family',familyContactRecordTypeId);
            recordTypes.put('Medical Professional',MedicalProfContactRecordTypeId );
            recordTypes.put('Board Member',boardMemberRT);
            for(Contact currContact : conList)
            {
                npe5__Affiliation__c currAffiliation =  contactMap.get(currContact.id);
                currContact.Hidden_Status__c=currAffiliation.npe5__Status__c;
                
                if(currAffiliation.Constituent_code__c != Null && recordTypeNames.containsKey(currContact.recordTypeId))
                {
                    if(currAffiliation.Constituent_code__c != recordTypeNames.get(currContact.recordTypeId))
                    {
                        if(recordTypeOrder.get(currAffiliation.Constituent_code__c) < recordTypeOrder.get(recordTypeNames.get(currContact.recordTypeId)))
                        {
                            if(recordTypes.containsKey(currAffiliation.Constituent_code__c) && accountMap.get(currAffiliation.npe5__Organization__c).recordTypeId == chapterRT)
                                currContact.RecordTypeId =recordTypes.get(currAffiliation.Constituent_code__c);  
                        }
                    }
                }
            } 
            update conList;
        }
        catch(Exception ex){
            for(npe5__Affiliation__c currRec : exceptionList){
                ErrorMessage_AC.createdebugRec('Affiliation_OnAfterUpdateTriggerHelper',String.valueof(currRec),String.valueOf(ex.getCause()),'updateContact',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            for(npe5__Affiliation__c currRec : exceptionList){
                currRec.addError(Label.Debug_log_error_message);
            } 
        }
    }
    // Used to add a user to group based on their affilaition when the affilaition created. 
    @future 
    public static void insertGroupMember(Set<string> vlounteerNameSet,Set<String> chapterNameSet,set<id> affiliationSet ,Map<Id,String> exceptionMap)
    {
        try{
        system.debug('@@@@@@@@@@ methodcalled @@@@@@@'+vlounteerNameSet);
        Map<id,User> userMap = new Map<id,user>();
        Map<Id, String> chapterNameMap = new Map<Id, String>();
        map<string,id> publicGroupMap = new map<string,id>();
        List<GroupMember> groupMemberList = new List<GroupMember>();
        if(vlounteerNameSet.size() > 0)
        {
            for(User currentUser : [SELECT ID,ContactID FROM User WHERE ContactID IN: vlounteerNameSet])
            {
                userMap.put(currentUser.ContactID,currentUser);
            }
        }
        if(chapterNameSet.size() > 0)
        {
            for(Account currentAccount :[SELECT Id,Name FROM Account WHERE Id IN: chapterNameSet])
            {
                String chapterNameTrim = currentAccount.Name.removeStart('Make-A-Wish ');
                chapterNameMap.put(currentAccount.Id, chapterNameTrim);
            }
        }
        for(Group currentGroup : [SELECT Id, Name FROM Group WHERE Type = 'Regular'])
        {
            publicGroupMap.put(currentGroup.Name, currentGroup.id);
        }
        for(npe5__Affiliation__c currentRec : [SELECT ID,Name,npe5__Organization__c,npe5__Contact__c FROM npe5__Affiliation__c WHERE ID IN: affiliationSet])
        {
            if(userMap.containsKey(currentRec.npe5__Contact__c) && chapterNameMap.containsKey(currentRec.npe5__Organization__c))
            {
                
                GroupMember newGroupMem = new GroupMember();
                newGroupMem.GroupId= publicGroupMap.get(chapterNameMap.get(currentRec.npe5__Organization__c));
                newGroupMem.UserOrGroupId = userMap.get(currentRec.npe5__Contact__c).id;
                groupMemberList.add(newGroupMem);
            }
        }
        if(groupMemberList.size() > 0)
        {
            insert groupMemberList;
        }
        }
        catch(Exception ex){
            for(Id currRec : exceptionMap.keyset()){
            ErrorMessage_AC.createdebugRec('Affiliation_OnAfterUpdateTriggerHelper',exceptionMap.get(currRec),String.valueOf(ex.getCause()),'updateContact',currRec,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            for(npe5__Affiliation__c currRec : [SELECT Id FROM npe5__Affiliation__c WHERE Id IN :exceptionMap.keyset()]){
                currRec.addError(Label.Debug_log_error_message);
            } 
        }
    }
}