make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This field holds the state name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Region_Chapter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the contact region chapter</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Region Chapter)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Backup/src/objects/Contact.object
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>It will hold the value of Chapter name</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/objects/In_Kind_Donation_Reimbursement__c.object
<CustomObject>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to the parent wish records</description>
        <label>Wish</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wish</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipName>In_Kind_Donation_Reimbursement</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>In-Kind Donation &amp; Reimbursement</label>
    <nameField>
        <displayFormat>IKR-{0000}</displayFormat>
        <label>In-Kind Donation &amp; Reimbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>In-Kind Donation &amp; Reimbursement</pluralLabel>
    <recordTypes>
        <fullName>Reimbursement</fullName>
        <active>true</active>
        <description>This record type associated with reimbursement page layout</description>
        <label>Reimbursement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This Field hold the name of the state.</description>
        <formula>&apos;Make-A-Wish &apos;+State</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donation Received</description>
        <label>Donation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for the chapter named of Account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DelegatedApproverController_AC.cls
/**************************************************************************************
Author : MST Solutions
Description : This class referred in the DelegatedApprover_VF. It display the all record approval processes . 
This will allow chapter staff to see visibility into their colleagues approval's needed when they are covering for each other.
****************************************************************************************/

public class DelegatedApproverController_AC{
    Constant_AC  constant = new Constant_Ac();   
    Id parentWishRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(constant.parentWishRT).getRecordTypeId();
    Id wishPlanningRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(constant.wishPlanningAnticipationRT).getRecordTypeId();
    Id volunteerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.volunteerRT).getRecordTypeId();
    Id wichChildRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.contactWishChildRT).getRecordTypeId();
    Id inKindDonorsAccountRecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(constant.inKindAccount).getRecordTypeId();
    Id boardMemberRT = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.boardMemberRT).getRecordTypeId();
    
    Public Boolean isErrorFree{get;set;}
    Transient public Map<String,List<ProcessInstance>> approvalMap{get;set;}
    public Transient  String selectedprocessName{get;set;}
    public Transient  String selectedChapter{get;set;}
    public Transient  String selectedApprover{get;set;}
    public Transient  String selectedStatus{get;set;}
    public Transient  String selectedCompltedBy{get;set;}
    public Transient  Set<String> StringSet;
    public List<SelectOption> processItems {get;set;}
    public List<SelectOption> chapterItems {get;set;}   
    public List<SelectOption> approvedByItems {get;set;}  
    //public List<SelectOption> completedByItems {get;set;}
    public List<SelectOption> statusItems {get;set;}   
    Public Transient Map<Id, String> chapterMap {get;set;}
    public Map<Id,String> wishChildNameMap {get;set;}
    Set<Id> volOppIdSet;
    Set<Id> conIdSet;
    Set<Id> caseIdSet;
    Set<Id> accIdSet;
    Set<Id> inKindSet;
    Set<String> approverSet;
    public DelegatedApproverController_AC(){
        isErrorFree = true;
        volOppIdSet = new Set<Id>();
        conIdSet = new Set<Id>();
        caseIdSet = new Set<Id>();
        accIdSet = new Set<Id>();
        inKindSet = new Set<Id>();
        chapterMap = new Map<Id, String>();
        wishChildNameMap = new Map<Id,String>();
        approverSet = new Set<String>();
        approvedByItems = new List<SelectOption>();
        approvedByItems.add(new selectOption('','--Select--'));
        processItems= new List<SelectOption>();
        //processItems.add(new SelectOption('','--Select--'));
        chapterItems = new List<SelectOption>();
        chapterItems.add(new SelectOption('','--Select--'));
        statusItems = new List<SelectOption>();
        statusItems.add(new SelectOption('','--Select--'));
        statusItems.add(new SelectOption('Approved','Approved'));
        statusItems.add(new SelectOption('Pending','Pending'));       
        statusItems.add(new SelectOption('Rejected','Rejected'));       
        statusItems.sort();    
        approvalMap = new Map<String,List<ProcessInstance>>();
        
        //This get all chapter name from custom setting.
        //for(Chapter_Vs_Role__c currChapter :Chapter_Vs_Role__c.getAll().values()){
        //if(currChapter.Chapter_Name__c != 'Make-A-Wish America')
        //chapterItems.add( new SelectOption(currChapter.Role_Name__c,currChapter.Chapter_Name__c));
        //chapterItems.add( new SelectOption(currChapter.Role_Name__c,currChapter.Chapter_Name__c));
        //}
        for(Account chapterAccount : [SELECT Id, Name FROM Account WHERE RecordType.Name = 'Chapter' AND Name != 'Alabama']) {
            chapterItems.add( new SelectOption(chapterAccount.Name,chapterAccount.Name));
        }
        chapterItems.sort();
        
        loadData();
    }
    
    public void loadData() {
        
       for(ProcessDefinition process :[SELECT Id, Name from ProcessDefinition WHERE Name != 'KBWorkflow' AND Name != 'KBTranslationSubWorkflow' AND Name != 'KBTranslationSubWorkflow' AND Name != 'Wish Approval' AND State = 'Active']){
            if(process.Name == 'Account:In Kind Donors Approval'){
                processItems.add(new SelectOption(process.Name,'In Kind Donors Account Approval'));
            }
            else if(process.Name == 'Case:Budget Approval Form'){
                processItems.add(new SelectOption(process.Name,'Wish Expense Budget Approval'));
            }
            else if(process.Name == 'In Kind Donation&Reimbursement Approval'){
                processItems.add(new SelectOption(process.Name,'In Kind Donation Approval'));
            }
            else if(process.Name == 'Reimbursement Approval To Wish Owner'){
                processItems.add(new SelectOption(process.Name,'Reimbursement Approval'));
            }
            else if(process.Name == 'Update Contact Info Process'){
                processItems.add(new SelectOption(process.Name,'Update Contact Info Approval'));
            }
            else if(process.Name == 'Volunteer Contact Process'){
                processItems.add(new SelectOption(process.Name,'Volunteer Application Approval'));
            }
            else if(process.Name == 'Volunteer Role Approval Process'){
                processItems.add(new SelectOption(process.Name,'Volunteer Opportunity Approval'));
            }
            else if(process.Name == 'Wish Forms'){
                processItems.add(new SelectOption(process.Name,'Wish Forms Approval'));
            }
            else
                processItems.add(new SelectOption(process.Name,process.Name));
        }
        //Sort the process item list based on the select option label
        
         Map<String, Selectoption> mapping = new Map<String, Selectoption>();
        // Suffix to avoid duplicate values like same labels or values are in inbound list 
        Integer suffix = 1;
        for (Selectoption opt : processItems) {
            
                mapping.put(    // Done this cryptic to save scriptlines, if this loop executes 10000 times
                                // it would every script statement would add 1, so 3 would lead to 30000.
                             (opt.getLabel() + suffix++), // Key using Label + Suffix Counter  
                             opt);   
         }
         List<String> sortKeys = new List<String>();
        sortKeys.addAll(mapping.keySet());
        sortKeys.sort();
        // clear the original collection to rebuilt it
        processItems.clear();
        processItems.add(new SelectOption('','--Select--'));
        for (String key : sortKeys) {
            processItems.add(mapping.get(key));
        }                    
                             
        
        for(ProcessInstance process : [SELECT Id,status,ProcessDefinition.Name,TargetObject.Name,TargetObject.Id,SubmittedBy.userRole.Name,TargetObject.Type,CreatedBy.Name,SubmittedBy.Account.Name,SubmittedBy.Name,completedDate,CreatedDate
                                       , (SELECT Id,Actor.Name,OriginalActor.Name,ActorId FROM StepsandWorkItems order by Id desc LIMIT 1)FROM ProcessInstance WHERE ProcessDefinition.Name != 'KBWorkflow' Order by CreatedDate Desc LIMIT 10000]){
                                           
                                           if(approvalMap.containsKey(process.ProcessDefinition.Name))
                                               approvalMap.get(process.ProcessDefinition.Name).add(process);
                                           else{
                                               approvalMap.put(process.ProcessDefinition.Name,new List<ProcessInstance>{process});   
                                               //processItems.add(new SelectOption(process.ProcessDefinition.Name,process.ProcessDefinition.Name));
                                           }
                                           
                                           if(!approverSet.Contains(process.StepsandWorkItems[0].Actor.Name) && (!Test.isRunningTest())){
                                               approverSet.add(process.StepsandWorkItems[0].Actor.Name);
                                               approvedByItems.add(new SelectOption(process.StepsandWorkItems[0].Actor.Name,process.StepsandWorkItems[0].Actor.Name));
                                           }
                                           if(!approverSet.Contains(process.StepsandWorkItems[0].OriginalActor.Name) && (!Test.isRunningTest())){
                                               approverSet.add(process.StepsandWorkItems[0].OriginalActor.Name);
                                               approvedByItems.add(new SelectOption(process.StepsandWorkItems[0].OriginalActor.Name,process.StepsandWorkItems[0].OriginalActor.Name));
                                           }
                                           
                                           if(process.TargetObject.Type == 'Volunteer_Opportunity__c') {
                                               volOppIdSet.add(process.TargetObject.Id);
                                           }
                                           if(process.TargetObject.Type == 'Case') {
                                               caseIdSet.add(process.TargetObject.Id);
                                           }
                                           if(process.TargetObject.Type == 'Contact') {
                                               conIdSet.add(process.TargetObject.Id);
                                           }
                                           if(process.TargetObject.Type == 'Account') {
                                               accIdSet.add(process.TargetObject.Id);
                                           }
                                           if(process.TargetObject.Type == 'In_Kind_Donation_Reimbursement__c') {
                                               inKindSet.add(process.TargetObject.Id);
                                           }
                                       }
        approvedByItems.sort();
       // processItems.Sort();
        //recChapterInfo();
        for(Volunteer_Opportunity__c volOpp : [SELECT Id, Chapter_Name__r.Name,Wish__C,Wish__r.Contact.Name FROM Volunteer_Opportunity__c WHERE Id IN : volOppIdSet]) {
            
            if(volOpp.Chapter_Name__r.Name != null) {
                chapterMap.put(volOpp.Id, volOpp.Chapter_Name__r.Name);
            } else {
                chapterMap.put(volOpp.Id, '-');
            }
            
            if(volOpp.Wish__c != Null){
                 wishChildNameMap.put(volOpp.Id,volOpp.Wish__r.Contact.Name);      
            }
            else{
               wishChildNameMap.put(volOpp.Id,'-');     
            }
        }
        
        for(Case caseInfo : [SELECT Id, ChapterName__r.Name, Parent.ChapterName__r.Name,Contact.Name,Parent.Contact.Name,RecordTypeId FROM Case WHERE Id IN : caseIdSet]) {
            if(caseInfo.RecordTypeId == wishPlanningRecordTypeId) {
                if(caseInfo.Parent.ChapterName__r.Name != null) {
                    chapterMap.put(caseInfo.Id,caseInfo.Parent.ChapterName__r.Name);
                    
                } else {
                    chapterMap.put(caseInfo.Id, '-');
                }
                wishChildNameMap.put(caseInfo.Id,caseInfo.Parent.Contact.Name);
                
            } else if(caseInfo.RecordTypeId == parentWishRecordTypeId) {
                if(caseInfo.ChapterName__r.Name != null) {
                    chapterMap.put(caseInfo.Id,caseInfo.ChapterName__r.Name);
                } else {
                    chapterMap.put(caseInfo.Id, '-');
                }
                wishChildNameMap.put(caseInfo.Id,caseInfo.Contact.Name);
            }
        }
        
        for(Contact conInfo : [SELECT Id, RecordTypeId, Account.Name, Region_Chapter__r.Name FROM Contact WHERE Id IN : conIdSet]) {
            if(conInfo.RecordTypeId == volunteerRecordTypeId) {
                if(conInfo.Account.Name != null) {
                    chapterMap.put(conInfo.Id,conInfo.Account.Name);
                } else {
                    chapterMap.put(conInfo.Id,'-');
                }
                
            } else if(conInfo.RecordTypeId == wichChildRecordTypeId || conInfo.RecordTypeId == boardMemberRT) {
                
                if(conInfo.Region_Chapter__r.Name != null) {
                    chapterMap.put(conInfo.Id,conInfo.Region_Chapter__r.Name);
                } else {
                    chapterMap.put(conInfo.Id,'-');
                }
            }
             wishChildNameMap.put(conInfo.Id,'-');
        }
        
        for(Account inkaccinfo : [SELECT Id, Chapter_Name__r.Name FROM Account WHERE Id IN : accIdSet]) {
            
            if(inkaccinfo.Chapter_Name__r.Name != null && inkaccinfo.RecordTypeId == inKindDonorsAccountRecordTypeId) {
                chapterMap.put(inkaccinfo.Id,inkaccinfo.Chapter_Name__r.Name);
            } else {
                chapterMap.put(inkaccinfo.Id, '-');
            }
            wishChildNameMap.put(inkaccinfo.Id,'-');
        }
        
        for(In_Kind_Donation_Reimbursement__c ikRemInfo : [SELECT Id, Wish__c,Wish__r.Contact.Name, Wish__r.ChapterName__r.Name FROM In_Kind_Donation_Reimbursement__c WHERE Id IN : inKindSet ]) {
            
            if(ikRemInfo.Wish__r.ChapterName__r.Name != null) {
                chapterMap.put(ikRemInfo.Id,ikRemInfo.Wish__r.ChapterName__r.Name);
            } else {
                chapterMap.put(ikRemInfo.Id, '-');
            }
            wishChildNameMap.put(ikRemInfo.Id,ikRemInfo.Wish__r.Contact.Name);
        }
        if(chapterMap.size() != approvalMap.size()) {
            System.debug(chapterMap.size() +'>>>>>>'+approvalMap.size());
            isErrorFree = false;
        }
    }
    public void recChapterInfo() {
        
        
    }
    
    public void viewProcess(){
         approvalMap = new Map<String,List<ProcessInstance>>();
        chapterMap = new Map<Id, String>();
        processItems.clear();
        loadData();
        /*    String Query ='SELECT Id,status,ProcessDefinition.Name,TargetObject.Name,SubmittedBy.userRole.Name,TargetObject.Type,CreatedBy.Name,SubmittedBy.Account.Name,SubmittedBy.Name,completedDate,CreatedDate,(SELECT Id,Actor.Name,ActorId FROM StepsandWorkItems)FROM ProcessInstance';
// List<sObject> processList =  Database.query(Query );
for(ProcessInstance process :  Database.query(Query)){
if(approvalMap.containsKey(process.ProcessDefinition.Name))
approvalMap.get(process.ProcessDefinition.Name).add(process);
else{
approvalMap.put(process.ProcessDefinition.Name,new List<ProcessInstance>{process});   
// Items.add(new SelectOption(process.ProcessDefinition.Name,process.ProcessDefinition.Name));
}                        
}*/
    }
}