make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MAC_Email__c</fullName>
        <description>This filed is used to store the value of MAC Email.</description>
        <label>Hidden MAC Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MAC_Email__c</fullName>
        <description>This field is used to store the MAC email values from Account.</description>
        <label>Chapter Medical Advisor Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/dsfs__DocuSign_Status__c.object
<CustomObject>
    <description>DocuSign Status is the foundation Custom Object for integration of DocuSign and Salesforce.</description>
    <label>DocuSign Status</label>
    <nameField>
        <displayFormat>DSX-{0000000}</displayFormat>
        <label>Envelope#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/SendEmailToMacTeam_AC_Test.cls
@isTest
public class SendEmailToMacTeam_AC_Test {
    
    static testmethod void callSendEmailToMac(){
        Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
        Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
        Contact newContact = OrientationandTrainingUtil.CreateMedicalProfContact();
        Case newDiagnosis = OrientationandTrainingUtil.CreateDiagnosisNewCase();
        dsfs__DocuSign_Status__c newDocusign = OrientationandTrainingUtil.CreateDocusignRecord();
        OrientationandTrainingUtil.CreateAttachmentRecord();
        SendEmailToMacTeam_AC.sendEmailToMac(newContact.id, newLead.id, newDiagnosis.id, 'Local', newDiagnosis.MAC_Email__c);
    }
    
    static testmethod void callSendEmai(){
        Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
        Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
        Contact newContact = OrientationandTrainingUtil.CreateMedicalProfContact();
        Case newDiagnosis = OrientationandTrainingUtil.CreateDiagnosisNewCase();
        dsfs__DocuSign_Status__c newDocusign = OrientationandTrainingUtil.CreateDocusignRecord();
        OrientationandTrainingUtil.CreateAttachmentRecord();
        SendEmailToMacTeam_AC.sendEmailToMac(newContact.id, newLead.id, newDiagnosis.id, 'National', newDiagnosis.MAC_Email__c);
    }
    
    
}