make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External RE record Id for upserting</description>
        <externalId>true</externalId>
        <inlineHelpText>External RE record Id for upserting</inlineHelpText>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>It holds the id value of External System.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/External_ID__c.object
<CustomObject>
    <description>This object will contain External ID references to other systems that hold corresponding / matching records.  This object will allow these ids to persist on surviving records of a record merging process.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Captures the External ID used by matching records in an external system.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>External ID</label>
    <nameField>
        <displayFormat>E.ID-{00000}</displayFormat>
        <label>External ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Office__c.object
<CustomObject>
    <description>This Object is used to store the office details.</description>
    <fields>
        <fullName>Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of the Account.</description>
        <label>Chapter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Office</relationshipLabel>
        <relationshipName>Office</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field is used to store the value of Zip Code.</description>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Zip_Code__c.object
<CustomObject>
    <description>This object is used to store the value of the zip code.</description>
    <fields>
        <fullName>Chapter__c</fullName>
        <description>This field is used to store the account value.</description>
        <formula>Office__r.Chapter__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id used for Mulesoft upsert.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of office.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Zip Code</relationshipLabel>
        <relationshipName>Zip_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/CommunitiesSelfRegControllerTest.cls
/**
 * An apex page controller that supports self registration of users in communities that allow self registration
 */
@IsTest 
public with sharing class CommunitiesSelfRegControllerTest 
{
  
   /* validate with empty values */
    public static testmethod void testCommunitiesSelfRegController() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.registerUser();
    } 
   /** LastName validation */
    public static testmethod void LastNameValidation() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.Email = 'test@gmail.com';
       selfRegCtrl.registerUser();
    } 
    /* First name as blank */
    public static testmethod void firstNameValidation() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.registerUser();
    } 
     /* zipCode as blank */
    public static testmethod void zipCodeValidation() 
    {
       TestClassUtil.createDynamicContent();
      
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.registerUser();
    } 
     /* Enter email as blank */
    public static testmethod void EmailValidation() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.lastName = 'test';
       selfRegCtrl.registerUser();
    } 
      /* zipcode greater than 5 */
    public static testmethod void zipCodeSizeValidation() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='350043';
       selfRegCtrl.registerUser();
    } 
    
    /* Fill Username */
   public static testmethod void usernameValidation() 
    {
       TestClassUtil.createDynamicContent();
      
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test';
       selfRegCtrl.registerUser();
    } 
    // Captuing password valiation.
    public static testmethod void passwordValidation() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.registerUser();
    } 
    //  Capturing confirm password validation.
    public static testmethod void confirmPasswordValidation() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.password = 'abcded';
       selfRegCtrl.registerUser();
    } 
    // Capturing voluteer age valiation.
    public static testmethod void volunteerAgeValidation() 
    {
       TestClassUtil.createDynamicContent();
      
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.password = 'abcded';
       selfRegCtrl.confirmPassword = 'abcded';
       selfRegCtrl.registerUser();
    } 
    
    public static testmethod void coverStatePicklist() 
    {
       TestClassUtil.createDynamicContent();
     
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.password = 'abcded';
       selfRegCtrl.confirmPassword = 'abcded';
       selfRegCtrl.isOver18YearsOld = True;
       selfRegCtrl.registerUser();
       selfRegCtrl.getStates();
       
    } 
    public static testmethod void validateBelow18Year() 
    {
       TestClassUtil.createDynamicContent();
       
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.password = 'abcded';
       selfRegCtrl.confirmPassword = 'abcded';
        selfRegCtrl.isOver18YearsOld = false;
       selfRegCtrl.registerUser();
    } 
    // Sign up with valid details.
    public static testmethod void CreateUserwithValidData() 
    {
       TestClassUtil.createDynamicContent();
      
        Account chapterAccount = TestClassUtil.createChapter();
        Office__c newOffice = TestClassUtil.createOffice();
        newOffice.Chapter__c = chapterAccount.Id;
        newOffice.External_Id__c = 'Test123';
        insert newOffice;
        Zip_Code__c newZipCode = TestClassUtil.createZipCode();
        newZipCode.Office__c = newOffice.Id;
        newZipCode.Name = '35004';
        newZipCode.External_Id__c = 'Test123';
        insert newZipCode;
        
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.password = 'abcded';
       selfRegCtrl.confirmPassword = 'abcded';
       selfRegCtrl.isOver18YearsOld = True;
       selfRegCtrl.registerUser();
       selfRegCtrl.getStates();
    } 
    
    // Sign up with valid details.
    public static testmethod void CreateDupUser() 
    {
        Constant_AC  constant = new Constant_AC(); 
        Id volunteerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(constant.volunteerRT).getRecordTypeId();
        TestClassUtil.createDynamicContent();
      
        Account chapterAccount = TestClassUtil.createChapter();
        Office__c newOffice = TestClassUtil.createOffice();
        newOffice.Chapter__c = chapterAccount.Id;
        newOffice.External_Id__c = 'Test123';
        insert newOffice;
        Zip_Code__c newZipCode = TestClassUtil.createZipCode();
        newZipCode.Office__c = newOffice.Id;
        newZipCode.Name = '35004';
        newZipCode.External_Id__c = 'Test123';
        insert newZipCode;
        
        Contact con = new Contact();
        con.LastName = 'Test';
        con.RecordTypeId = volunteerRecordTypeId;
        con.Email = 'test@gmail.com';
        con.accountId = chapterAccount.id;
        insert con;
        
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.password = 'abcded';
       selfRegCtrl.confirmPassword = 'abcded';
       selfRegCtrl.isOver18YearsOld = True;
       selfRegCtrl.registerUser();
       selfRegCtrl.getStates();
    } 
    
    // Sign up with valid details.
    public static testmethod void chapterListBlank() 
    {
       TestClassUtil.createDynamicContent();
       TestClassUtil.createVolunteerAccount();
      
      
        Zip_Code__c newZipCode = TestClassUtil.createZipCode();
        newZipCode.Name = '35004';
        newZipCode.external_Id__c = 'test2356';
        insert newZipCode;
        
       CommunitiesSelfRegController selfRegCtrl=new CommunitiesSelfRegController();
       selfRegCtrl.email= 'test@gmail.com';
       selfRegCtrl.lastName='a';
       selfRegCtrl.firstName='a';
       selfRegCtrl.zipCode='35004';
       selfRegCtrl.username='test@username.com';
       selfRegCtrl.password = 'abcded';
       selfRegCtrl.confirmPassword = 'abcded';
       selfRegCtrl.isOver18YearsOld = True;
       selfRegCtrl.registerUser();
       selfRegCtrl.getStates();
    } 
    
   
}