make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alert_for_Unassigned_Wishes__c</fullName>
        <description>This filed will indicate how long the wish can be unassigned</description>
        <inlineHelpText>In terms of number of days</inlineHelpText>
        <label>Alert for Unassigned Wishes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of the chapter role.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Non-Wish &amp; Events</relationshipLabel>
        <relationshipName>Non_Wish_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>It store the event date field</description>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <fields>
        <fullName>isWishRole__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identify whether the role is wish or non wish</description>
        <label>isWishRole</label>
        <type>Checkbox</type>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Chapter_Role_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field look up with Chapter Role</description>
        <label>Chapter Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Chapter_Role__c.Chapter_Name__c</field>
                <operation>equals</operation>
                <valueField>$Source.Chapter_Name__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>Event date indicated when the event started</description>
        <formula>Non_Wish_Event__r.Event_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Non_Wish_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It hold the record of each event</description>
        <label>Name</label>
        <referenceTo>Non_Wish_Events__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It will display the role name</description>
        <formula>Chapter_Role_Opportunity__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/UpdateWishAssignmentBatchTest_AC.cls
/*****************************************************************************
Author : MST Solutions
CreateDate : 05/5/2017
Description : This test class used for unit test and code coverage
Modification Log: 
28/03/2018 - Kanagaraj
******************************************************************************/

/**
 * WLP-322
 * Class being tested is commented out, commenting the test class as well as its useless
 */
@IsTest
public class UpdateWishAssignmentBatchTest_AC {
	// This test class used to create volunteer opportunity
//	static testMethod void createVolunteerOpportunity() {
//		String CRON_EXP = '0 0 1 * * ? *';
//		Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
//		insert chapterAccount;
//		chapterAccount.Alert_for_Unassigned_Wishes__c = 0;
//		update chapterAccount;
//		Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
//		insert wishChild;
//		Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
//		insert volunteerContact;
//		Case parentCase = OrientationandTrainingUtil.ParentCasetoAddCaseMember(wishChild.Id);
//		insert parentCase;
//		parentCase.ChapterName__c = chapterAccount.Id;
//		update parentCase;
//		Role__c roleName = OrientationandTrainingUtil.createRole();
//		insert roleName;
//		Role__c newRole = new Role__c();
//		newRole.Name = 'Wish Granter';
//		newRole.isWishRole__c = true;
//		insert newRole;
//		Chapter_Role__c chapterRole = OrientationandTrainingUtil.createChapter(chapterAccount.Id, newRole.Id);
//		insert chapterRole;
//		Non_Wish_Events__c nonWishEvent = OrientationandTrainingUtil.CreateEventRec(chapterRole.Id, chapterAccount.Id);
//		insert nonWishEvent;
//		nonWishEvent.Event_Date__c = Date.today().addDays(-5);
//		update nonWishEvent;
//		Id wishVolunteerOpportunityRecordTypeId = Constant_AC.WISH_VOLUNTEER_OPPORTUNITY_ID;
//		Volunteer_Opportunity__c newOpp = new Volunteer_Opportunity__c();
//		newOpp.Volunteer_Name__c = volunteerContact.Id;
//		newOpp.Non_Wish_Event__c = nonWishEvent.Id;
//		newOpp.Chapter_Role_Opportunity__c = chapterRole.Id;
//		newOpp.Wish__c = parentCase.Id;
//		newOpp.RecordTypeId = wishVolunteerOpportunityRecordTypeId;
//		insert newOpp;
//
//		Test.startTest();
//		String jobId = System.schedule('lastWishAssignment', CRON_EXP, new UpdateWishAssignmentBatchSchedule_AC());
//		CronTrigger ct = [
//				SELECT Id, CronExpression, TimesTriggered, NextFireTime
//				FROM CronTrigger
//				WHERE Id = :jobId
//				LIMIT 50000
//		];
//		System.assertEquals(CRON_EXP,
//				ct.CronExpression, 'Compare Cron Expression');
//		System.assertEquals(0, ct.TimesTriggered, 'Compare Time Trigger');
//		Test.stopTest();
//	}
}