make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External RE record Id for upserting</description>
        <externalId>true</externalId>
        <inlineHelpText>External RE record Id for upserting</inlineHelpText>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Intake_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will the intake manager of the chapter.</description>
        <label>Intake Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Intake_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>It holds the id value of External System.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>It will hold the gender information.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Self-describe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate the wish Child Family aware of Referral at MAWA.</description>
        <label>Is Family Aware Of Referral?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wish referrer.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture the referrer Email.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It capture the wish referrer Zip code.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/External_ID__c.object
<CustomObject>
    <description>This object will contain External ID references to other systems that hold corresponding / matching records.  This object will allow these ids to persist on surviving records of a record merging process.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Captures the External ID used by matching records in an external system.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>External ID</label>
    <nameField>
        <displayFormat>E.ID-{00000}</displayFormat>
        <label>External ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Any_medical_reason_for_moving_quickly__c</fullName>
        <description>Is there a medical reason why we need to move quickly?</description>
        <inlineHelpText>Is there a medical reason why we need to move quickly?</inlineHelpText>
        <label>Any medical reason for moving quickly?</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Child_Age__c</fullName>
        <description>It would capture the child of the age.</description>
        <label>Child Age</label>
        <picklist>
            <picklistValues>
                <fullName>Under 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18 &amp; Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Child_Middle_Initial__c</fullName>
        <description>It will hold the Child Middle name details</description>
        <label>Child Middle Initial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_this_child_ever_received_prior_wish__c</fullName>
        <description>Has this child ever received a prior wish from MAW or any other wish granting organization?</description>
        <inlineHelpText>Has this child ever received a prior wish from MAW or any other wish granting organization?</inlineHelpText>
        <label>Has this child ever received prior wish?</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Medical_Provider_Category__c</fullName>
        <description>It will hold the value of Medical Provider Category.</description>
        <label>Medical Provider Category</label>
        <picklist>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Life Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse Practitioner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_First_Name__c</fullName>
        <description>It hold the First name of wish&apos;s parent.</description>
        <label>Parent First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Last_Name__c</fullName>
        <description>It hold the last name of Wish&apos;s parent.</description>
        <label>Parent Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wih&apos;s parent.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture email address of wish parent from referral form.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It will hold the firstname of the child.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It will capture the zipcode of wish&apos;s parent.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_child__c</fullName>
        <description>This field is used to store the relationship of the person who submits the Wish Kid details</description>
        <label>Relationship to child</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Member/Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

make-a-wish-salesforce/src/objects/Office__c.object
<CustomObject>
    <description>This Object is used to store the office details.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field is used to store the value of Zip Code.</description>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Zip_Code__c.object
<CustomObject>
    <description>This object is used to store the value of the zip code.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id used for Mulesoft upsert.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of office.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Zip Code</relationshipLabel>
        <relationshipName>Zip_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/WishReferralForm_AC_Test.cls
@isTest
public class WishReferralForm_AC_Test {

	public static testMethod void relationshipNone() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.warningMsg = 'test';
		controller.displayWarningPopup = true;
		controller.CreateLead();
		controller.currLead.Child_Age__c = 'Under 2.5';

		controller.getlanguage();
		controller.getdiaYear();
		controller.getNoOfSiblings();
		controller.getSelfRequiredFields();
		controller.getNonMedicalReqFields();
		controller.getMedicalRequiredFields();

		WishReferralForm_AC.siblingWrapper sw = new WishReferralForm_AC.siblingWrapper();
		String fname = sw.fname;
		String lname = sw.lname;
		String age = sw.age;
	}

	public static testMethod void relationshipSelf() {
		Account chapterAccount = OrientationandTrainingUtil.CreateAmericaAccount();
		chapterAccount.Intake_Manager__c = UserInfo.getUserId();
		insert chapterAccount;

		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = 'Self';
		controller.CreateLead();
		controller.CopyReferralInfo();
		controller.currLead.Child_Age__c = '5';

	}

	public static testMethod void relationshipSelf1() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');

		Account chapterAccount = OrientationandTrainingUtil.CreateAmericaAccount();
		chapterAccount.Intake_Manager__c = UserInfo.getUserId();
		insert chapterAccount;

		Office__c office = OrientationandTrainingUtil.createOffice(chapterAccount.Id);
		insert office;

		Zip_Code__c zipCode = new Zip_Code__c();
		zipCode.Name = '90210';
		zipCode.External_Id__c = '1234567890';
		zipCode.Office__c = office.Id;
		insert zipCode;

		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = 'Self';
		controller.currLead.Referrer_FirstName__c = 'Testing';
		controller.currLead.Referrer_Last_Name__c = 'Testing';
		controller.currLead.Referrer_Phone__c = '8220708920';
		controller.currLead.Referrer_Email__c = 'mcavennila@gmail.com';
		controller.currLead.Referrer_City__c = 'karur';
		controller.currLead.Referrer_Zip__c = '35004';
		controller.currLead.Medical_Provider_Category__c = 'Physician';
		controller.currLead.is_Family_Aware_of_Referral__c = 'yes';
		controller.currLead.FirstName = 'Testing1';
		controller.currLead.Child_Middle_Initial__c = 'Testing2';
		controller.lastName = 'Testing2';
		controller.currLead.Gender__c = 'Male';
		controller.currLead.Child_Age__c = '16';
		controller.currLead.DOB__c = Date.valueOf('2000-09-11');
		controller.currLead.Parent_First_Name__c = 'Testing3';
		controller.currLead.Parent_Last_Name__c = 'Testing3';
		controller.currLead.Street = 'Karur';
		controller.currLead.City = 'Karur';
		controller.currLead.state = 'Arizona';
		controller.currLead.PostalCode = zipCode.Name;
		controller.currLead.Email = 'mcavennila@gmail.com';
		controller.currLead.Phone = '8220708920';
		controller.currLead.What_is_the_family_s_primary_spoken_lang__c = 'English';
		controller.diagnosisFilter = 'c00';
		controller.selectedDiagnosis = 'Malignant Neoplasm';
		controller.currLead.Hospital_Treatment_Facility_Treating__c = 'Malignant Neoplasm';
		controller.currLead.Treating_Medical_Professional_First_Name__c = 'Treaing 1';
		controller.currLead.Treating_Medical_Professional_Last_Name__c = 'Treaing 1';
		controller.currLead.Treating_Medical_Professional_Phone__c = '8220708921';
		controller.currLead.Treating_Medical_Professional_Email__c = 'mcavennila@gmail.com';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'yes';
		controller.currList = new List<WishReferralForm_AC.SiblingWrapper>{
				new WishReferralForm_AC.SiblingWrapper()
		};
		controller.currList[0].fName = 'Test';
		controller.currList[0].lName = 'Test';
		controller.currList[0].age = '10';
		controller.CreateLead();
		controller.CopyReferralInfo();

	}

	public static testMethod void relationshipSelf2() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		Contact con = WishReferralForm_AC_Test.createContact();
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Medical_Provider_Category__c = 'Physician';
		controller.currLead.Relationship_To_Child__c = 'Self';
		controller.currLead.Referrer_FirstName__c = 'Testing';
		controller.currLead.Referrer_Last_Name__c = 'Testing';
		controller.currLead.Referrer_Phone__c = '8220708920';
		controller.currLead.Referrer_Email__c = 'mcavennila@gmail.com';
		controller.currLead.Referrer_City__c = 'karur';
		controller.currLead.Referrer_Zip__c = '35004';
		controller.currLead.is_Family_Aware_of_Referral__c = 'yes';
		controller.currLead.FirstName = 'Testing1';
		controller.currLead.Child_Middle_Initial__c = 'Testing2';
		controller.lastName = 'Testing2';
		controller.currLead.Gender__c = 'Male';
		controller.currLead.Child_Age__c = '16';
		controller.currLead.DOB__c = Date.valueOf('2000-09-11');
		controller.currLead.Parent_First_Name__c = 'Testing3';
		controller.currLead.Parent_Last_Name__c = 'Testing3';
		controller.currLead.Street = 'Karur';
		controller.currLead.City = 'Karur';
		controller.currLead.state = 'Arizona';
		controller.currLead.PostalCode = '35004';
		controller.currLead.Email = 'mcavennila@gmail.com';
		controller.currLead.Phone = '8220708920';
		controller.currLead.What_is_the_family_s_primary_spoken_lang__c = 'English';
		controller.diagnosisFilter = 'c00';
		controller.selectedDiagnosis = 'Malignant Neoplasm';
		controller.currLead.Hospital_Treatment_Facility_Treating__c = 'Malignant Neoplasm';
		controller.currLead.Treating_Medical_Professional_First_Name__c = 'Treaing 1';
		controller.currLead.Treating_Medical_Professional_Last_Name__c = 'Treaing 1';
		controller.currLead.Treating_Medical_Professional_Phone__c = '8220708921';
		controller.currLead.Treating_Medical_Professional_Email__c = 'mcavennila@gmail.com';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'yes';
		controller.diagnosisYear = '2000';
		controller.diagnosisMonth = '01';
		controller.CreateLead();
		controller.CopyReferralInfo();
	}

	public static testMethod void relationshipSelf3() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		Contact con = WishReferralForm_AC_Test.createContact();

		ICD_Codes__c icdCode = new ICD_Codes__c();
		icdCode.Name = 'c00';
		insert icdCode;

		Lead dupeLead = new Lead();
		dupeLead.is_Family_Aware_of_Referral__c = 'Yes';
		dupeLead.PD_ICD_Code__c = icdCode.Id;
		dupeLead.Status = 'Referred';
		dupeLead.Diagnosis_Given_By_Referrer__c = 'Referrer';
		dupeLead.Hospital_Treatment_Facility__c = 'Treating Facility';
		dupeLead.Hospital_Treatment_Facility_Treating__c = 'Treating Facility';
		dupeLead.Treating_Medical_Professional_Last_Name__c = 'Treating Professional';
		dupeLead.Gender__c = 'Male';
		dupeLead.Company = 'Test Company';
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Medical_Provider_Category__c = 'Physician';
		controller.currLead.Referrer_FirstName__c = 'Testing';
		controller.currLead.Referrer_Last_Name__c = 'Testing';
		controller.currLead.Referrer_Phone__c = '8220708920';
		controller.currLead.Referrer_Email__c = 'mcavennila@gmail.com';
		controller.currLead.Referrer_City__c = 'karur';
		controller.currLead.Referrer_Zip__c = '35004';
		controller.currLead.Relationship_To_Child__c = 'Parent/Guardian';
		controller.currLead.is_Family_Aware_of_Referral__c = 'yes';
		controller.currLead.FirstName = dupeLead.FirstName = 'Testing1';
		controller.currLead.LastName = dupeLead.LastName = 'Testing2';
		controller.currLead.Child_Middle_Initial__c = 'Testing2';
		controller.currLead.Gender__c = 'Male';
		controller.currLead.Child_Age__c = '16';
		controller.currLead.DOB__c = dupeLead.DOB__c = Date.valueOf('2000-09-11');
		controller.currLead.Parent_First_Name__c = 'Testing3';
		controller.currLead.Parent_Last_Name__c = 'Testing3';
		controller.currLead.Street = dupeLead.Street = 'Karur';
		controller.currLead.City = dupeLead.City = 'Karur';
		controller.currLead.state = dupeLead.State = 'Arizona';
		controller.currLead.PostalCode = dupeLead.PostalCode = '35004';
		controller.currLead.Email = dupeLead.Email = 'mcavennila@gmail.com';
		controller.currLead.Phone = dupeLead.Phone = '8220708920';
		controller.currLead.What_is_the_family_s_primary_spoken_lang__c = 'English';
		controller.diagnosisFilter = icdCode.Name;
		controller.selectedDiagnosis = 'Malignant Neoplasm';
		controller.currLead.Hospital_Treatment_Facility_Treating__c = 'Malignant Neoplasm';
		controller.currLead.Treating_Medical_Professional_First_Name__c = 'Treaing 1';
		controller.currLead.Treating_Medical_Professional_Last_Name__c = 'Treaing 1';
		controller.currLead.Treating_Medical_Professional_Phone__c = '8220708921';
		controller.currLead.Treating_Medical_Professional_Email__c = 'mcavennila@gmail.com';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'yes';

		Lead dupeLead2 = dupeLead.clone();
		dupeLead2.Status = 'Inquiry';
		Lead dupeLead3 = dupeLead.clone();
		dupeLead3.Status = 'Other';
		insert new List<Lead>{
				dupeLead, dupeLead2, dupeLead3
		};
		controller.CreateLead();
		controller.CopyReferralInfo();
	}

	public static testMethod void relationshipOther() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = 'Other';
		controller.CreateLead();

	}

	public static testMethod void relationshipMedicalProfessional() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = Constant_AC.MEDICAL_PROFESSIONAL_RT_LABEL;
		controller.currLead.Medical_Provider_Category__c = 'Nurse Practitioner';
		controller.CreateLead();
	}

	public static testMethod void medicalFirstNameblank() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = Constant_AC.MEDICAL_PROFESSIONAL_RT_LABEL;
		controller.currLead.LastName = 'Test';
		controller.diagnosisYear = '2000';
		controller.diagnosisMonth = '01';
		controller.CreateLead();
	}

	public static testMethod void relationshipFamily() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = 'Parent/Guardian';
		controller.currLead.LastName = 'Test';
		controller.currLead.DOB__c = Date.Today() - 1050;
		controller.currlead.Child_Age__c = '16';
		controller.CreateLead();
	}

	public static testMethod void relationshipSibling() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = 'Parent/Guardian';
		controller.currLead.LastName = 'Test';
		controller.currLead.DOB__c = Date.Today() - 1050;
		controller.currlead.Of_Siblings__c = '2';
		controller.getSiblingList();
		controller.CreateLead();
		controller.getStates();
		controller.copyReferrerInfo = True;
		controller.CopyReferralInfo();
		controller.getRelationships();
		controller.getNoOfSiblings();
		WishReferralForm_AC.searchDiagnosis('c00');
		WishReferralForm_AC.searchCondition('Mali');
		WishReferralForm_AC.searchDiagnosis(NULL);
		WishReferralForm_AC.searchCondition(NULL);
		controller.currLead.is_Family_Aware_of_Referral__c = 'Yes';
		controller.disPlayChildForm();
	}

	public static testMethod void relationshipSibling2() {
		PageReference pageRef = Page.WishReferralForm_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('isSuccess', 'Test');
		WishReferralForm_AC controller = new WishReferralForm_AC();
		controller.currLead.Has_this_child_ever_received_prior_wish__c = 'Yes';
		controller.currLead.Any_medical_reason_for_moving_quickly__c = 'Yes';
		controller.currLead.Relationship_To_Child__c = 'Self';
		controller.currLead.LastName = 'Test';
		controller.currLead.DOB__c = Date.Today() - 1050;
		controller.currlead.Of_Siblings__c = '2';
		controller.getSiblingList();
		controller.CreateLead();
		controller.getStates();
		controller.copyReferrerInfo = True;
		controller.CopyReferralInfo();
		controller.getRelationships();
		controller.getNoOfSiblings();
		WishReferralForm_AC.searchDiagnosis('c00');
		WishReferralForm_AC.searchCondition('Mali');
		WishReferralForm_AC.searchDiagnosis(NULL);
		WishReferralForm_AC.searchCondition(NULL);
		controller.currLead.is_Family_Aware_of_Referral__c = 'Yes';
		controller.disPlayChildForm();
	}

	public static testmethod void callmethods() {
		WishReferralForm_AC obj = new WishReferralForm_AC();
		obj.getNonMedicalReqFields();
		obj.getMedicalRequiredFields();
		obj.getSelfRequiredFields();
		obj.getRelationshipsToChild();
		obj.getHereAboutMAW();
		obj.getdiaYear();
		obj.getCommunication();
	}

	static contact createContact() {
		Contact currCon = new Contact();
		currcon.FirstName = 'Testing1';
		currcon.lastName = 'Testing2';
		currCon.Birthdate = Date.valueOf('2000-09-11');
		currCon.Phone = '8220708920';
		currCon.Email = 'mcavennila@gmail.com';
		currCon.Diagnosis__c = 'Test';
		insert currCon;
		return currCon;
	}
}