make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alert_for_Unassigned_Wishes__c</fullName>
        <description>This filed will indicate how long the wish can be unassigned</description>
        <inlineHelpText>In terms of number of days</inlineHelpText>
        <label>Alert for Unassigned Wishes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer manager</description>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/cg__Lead_File__c.object
<CustomObject>
    <fields>
        <fullName>cg__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Lead Files</relationshipLabel>
        <relationshipName>Lead_Files_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lead File</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Lead File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>unique_wish_identifier__c</fullName>
        <description>To store the unique wish identifier</description>
        <label>unique wish identifier</label>
        <length>20</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/classes/DVMedicalSummaryAttachment_AC_Test.cls
/*****************************************************************************************************************
Created By : MST Solutions
Created Date : 1/23/2017
Description : This test class used to perform unit testing for the DV Medical Summary Attachment

Modification Log:
09/10/2019 - Manik - WLP-423
*******************************************************************************************************************/
@IsTest
public class DVMedicalSummaryAttachment_AC_Test {

    private final static Id CHAPTER_RECORD_TYPE_ID = Constant_AC.CHAPTER_RT_ID;

    @TestSetup
    public static void setup() {
        User currUser = [
                SELECT Id
                FROM User
                WHERE Id = :UserInfo.getUserId()
                LIMIT 1
        ];
        List<Account> accounts = TestDataFactory.createAccount(1);
        Account account = accounts.get(0);
        account.Name = 'Make-A-Wish Arizona';
        account.RecordTypeId = CHAPTER_RECORD_TYPE_ID;
        account.Volunteer_Manager__c = currUser.Id;
        account.Alert_for_Unassigned_Wishes__c = 1;
        insert accounts;
        List<ICD_Codes__c> icdCodes = TestDataFactory.createIcdCode(1);
        insert icdCodes;
        List<Lead> leadsDataFactory = TestDataFactory.createLead(1);
        Lead lead = leadsDataFactory.get(0);
        lead.ChapterName__c = accounts[0].Id;
        lead.FirstName = 'Jack';
        lead.LastName = 'Smith';
        lead.unique_wish_identifier__c = '059-17-12367';
        lead.is_Family_Aware_of_Referral__c = 'Yes';
        lead.Diagnosis_Given_By_Referrer__c = 'Test Diagnosis';
        lead.PD_ICD_Code__c = icdCodes[0].Id;
        lead.Company = 'MAWA';
        insert leadsDataFactory;
        List<cg__Lead_File__c> leadFilesDataFactory = TestDataFactory.createLeadFile(1);
        cg__Lead_File__c leadFile = leadFilesDataFactory.get(0);
        leadFile.cg__Lead__c = lead.Id;
        insert leadFilesDataFactory;
    }

	//Attachment for Diagnosis Verification
    @IsTest
	public static void getAttachmentWhenSaved() {
		Lead lead = [
				SELECT Id
				FROM Lead
                WHERE Name = 'Jack Smith'
		];
		List<cg__Lead_File__c> leadFile = [
				SELECT Id
				FROM cg__Lead_File__c
                WHERE cg__Lead__c = :lead.Id
		];
		Test.startTest();
		PageReference pageRef = Page.DVMedicalSummaryAttachment_VF;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id', lead.Id);
		ApexPages.currentPage().getParameters().put('saved', 'true');
		DVMedicalSummaryAttachment_AC currDiagnosisVerificationDupe = new DVMedicalSummaryAttachment_AC();
		currDiagnosisVerificationDupe.getAttachments();
		Attachment attach = new Attachment();
		attach.Name = 'Wish Child Medical Summary';
		Blob bodyBlob = Blob.valueOf('Medical Summary Wish Child');
		attach.Body = bodyBlob;
		currDiagnosisVerificationDupe.newAttachment = attach;
		currDiagnosisVerificationDupe.save();
		currDiagnosisVerificationDupe.Refresh();
		currDiagnosisVerificationDupe.attachmentId = leadFile[0].Id;
		currDiagnosisVerificationDupe.removeAttachment();
		Test.stopTest();
	}

    //Attachment for Diagnosis Verification
    @IsTest
    public static void getAttachmentWhenDeleted() {
        Lead lead = [
                SELECT Id
                FROM Lead
                WHERE Name = 'Jack Smith'
        ];
        List<cg__Lead_File__c> leadFile = [
                SELECT Id
                FROM cg__Lead_File__c
                WHERE cg__Lead__c = :lead.Id
        ];
        Test.startTest();
        PageReference pageRef = Page.DVMedicalSummaryAttachment_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', lead.Id);
        ApexPages.currentPage().getParameters().put('deleted', 'true');
        DVMedicalSummaryAttachment_AC currDiagnosisVerificationDupe = new DVMedicalSummaryAttachment_AC();
        currDiagnosisVerificationDupe.getAttachments();
        Attachment attach = new Attachment();
        attach.Name = 'Wish Child Medical Summary';
        Blob bodyBlob = Blob.valueOf('Medical Summary Wish Child');
        attach.Body = bodyBlob;
        currDiagnosisVerificationDupe.newAttachment = attach;
        currDiagnosisVerificationDupe.save();
        currDiagnosisVerificationDupe.Refresh();
        currDiagnosisVerificationDupe.attachmentId = leadFile[0].Id;
        currDiagnosisVerificationDupe.removeAttachment();
        Test.stopTest();
    }
}