make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Name_Setting__mdt.object
<CustomObject>
    <description>This is used to avoid convert leads.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>Used to store chapter names</description>
        <label>Chapter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chapter Name Settings</label>
    <pluralLabel>Chapter Name Settings</pluralLabel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Name_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This holds the chapter names whose Leads won&apos;t be converted when the lead status is updated Qualified.</description>
    <label>Chapter Name Settings</label>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Any_medical_reason_for_moving_quickly__c</fullName>
        <description>Is there a medical reason why we need to move quickly?</description>
        <inlineHelpText>Is there a medical reason why we need to move quickly?</inlineHelpText>
        <label>Any medical reason for moving quickly?</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <description>This Field hold the name of the state.</description>
        <formula>&apos;Make-A-Wish &apos;+State</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chapter Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_in_a_Comatose_Vegetative_State__c</fullName>
        <description>It will hold whether the child is comatose or vegetative state? or not</description>
        <label>Is in a Comatose/Vegetative State?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Lead_OnAfterUpdateTriggerHandler.cls
/***************************************************************************************************
Author      : MST Solutions
CreatedBy   : Kanagaraj
Date        : 26/05/2016
Description : Lead_OnAfterUpdateTriggerHandler is Invoked when the Lead record is update from LeadTrigger_AT

Modification Log:
1. 06/04/2018 - Vignesh SM - IME 9 - Line No. 44-53, 64-66
*****************************************************************************************************/
Public class Lead_OnAfterUpdateTriggerHandler {

    /*******************************************************************************************
When the Lead status is updated as 'Qualified' then it will call the leadConvertion(). And if
the lead status is updated as 'DNQ' then the Task will created under the lead.
IME- 69 -->Lead will not convert for the specific chapterName.
********************************************************************************************/

    private static Integer numRuns = 0;

    public static void onAfterUpdate(Map<Id, Lead> newLeadMap, Map<Id, Lead> oldLeadMap) {
        Map<Id, Lead> qualifiedLeadMap = new Map<Id, Lead>();
        List<Lead> newLeadList = new List<Lead>();
        List<Lead> approvalList = new List<Lead>();
        set<Id>LeadIdSet = new set<Id>();
        //IME-69
        Set<String> chapterSet = new Set<String>();
        Map<Id, Boolean> rushLeadMap = new Map<Id, Boolean>(); //IME 9

        /*for(Chapter_Name_Settings__c chapter : Chapter_Name_Settings__c.getAll().Values()){
            chapterSet.add(chapter.Name);
        }*/
        //STT-225
        for (Chapter_Name_Setting__mdt chapters : [SELECT Id, Chapter_Name__c FROM Chapter_Name_Setting__mdt LIMIT 50000]) {
            chapterSet.add(chapters.Chapter_Name__c);
        }
        Map<Id, Account> chapterAccountMap = new Map<Id, Account>([SELECT ID FROM Account WHERE Name IN :chapterSet LIMIT 50000]);

        //Map<Lead,Id> lead_IntakUserIdMap = new Map<Lead,Id>(); //Commented for IME-2
        if (RecursiveTriggerHandler.isFirstTime == true) {
            for (Lead newLead : newLeadMap.values()) {
                //Commented for IME-2
                /*if(newLead.Status == 'DNQ' && oldLeadMap.get(newLead.Id).Status != newLead.Status && newLead.ChapterName__c != Null){
lead_IntakUserIdMap.put(newLead,newLead.ChapterName__c);
}*/
                //IME- 69 - added chapter name check criteria
                if (!newLead.isConverted && newLead.Status == 'Qualified' && oldLeadMap.get(newLead.id).Status != 'Qualified' && (!chapterAccountMap.containsKey(newLead.ChapterName__c))) {
                    qualifiedLeadMap.put(newLead.id, newLead);
                }

                if ((newLead.Is_in_a_Comatose_Vegetative_State__c == 'Yes' && newLead.status == 'Eligibility Review' && oldLeadMap.get(newLead.Id).Status != 'Eligibility Review') ||
                        (newLead.Is_in_a_Comatose_Vegetative_State__c == 'Yes' && oldLeadMap.get(newLead.Id).Is_in_a_Comatose_Vegetative_State__c != 'Yes' && newLead.status == 'Eligibility Review')) {
                    LeadIdSet.add(newLead.Id);
                }

                //IME 9
                String medicalReason = newLead.Any_medical_reason_for_moving_quickly__c;
                String oldMedicalReason = oldLeadMap.get(newLead.id).Any_medical_reason_for_moving_quickly__c;
                if (medicalReason != null && newLead.Status == 'Eligibility Review') {
                    if (medicalReason.contains('Yes') && (oldMedicalReason == null || !oldMedicalReason.contains('Yes'))) {
                        rushLeadMap.put(newLead.Id, true);
                    }
                    else if (!medicalReason.contains('Yes') && (oldMedicalReason == null || oldMedicalReason.contains('Yes'))) {
                        rushLeadMap.put(newLead.Id, false);
                    }

                }

            }

        }

        if (qualifiedLeadMap.size() > 0) {
            Lead_OnAfterUpdateTriggerHandlerHelper leadAfterUpdate = new Lead_OnAfterUpdateTriggerHandlerHelper();
            Lead_OnAfterUpdateTriggerHandlerHelper.leadConvertion(qualifiedLeadMap);
        }
        if (rushLeadMap.size() > 0) {
            Lead_OnAfterUpdateTriggerHandlerHelper.updateRushInDVCase(rushLeadMap);
        }
        if (LeadIdSet.size() > 0) {
            Lead_OnAfterUpdateTriggerHandlerHelper.updateDvCaseStatus(LeadIdSet);
        }
        //Commented for IME-2
        /*if(lead_IntakUserIdMap.Size() > 0)
Lead_OnAfterUpdateTriggerHandlerHelper.createTaskforDNQLeads(lead_IntakUserIdMap);
*/
    }
}