make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Relationship_type__c</fullName>
        <description>It will capture the relationship information</description>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Step-mother</fullName>
                </value>
                <value>
                    <fullName>Step-father</fullName>
                </value>
                <value>
                    <fullName>Step-sister</fullName>
                </value>
                <value>
                    <fullName>Step-brother</fullName>
                </value>
                <value>
                    <fullName>Half-sister</fullName>
                </value>
                <value>
                    <fullName>Half-brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
                <value>
                    <fullName>Granddaughter</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <description>This field will used to store all related contact  in the relationship object record of the wish child</description>
        <label>Hidden Parent/Legal Guardian</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>This field is used to specify the relationship to wish child.</description>
        <label>Relationship Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>It will hold the relationship infromation</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Stepsister</fullName>
                </value>
                <value>
                    <fullName>Stepbrother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbour</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Contact__c</fullName>
        <label>Hidden Type of Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referring</fullName>
                </value>
                <value>
                    <fullName>Parent/Guardian</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Qualifing</fullName>
                </value>
                <value>
                    <fullName>Referrer&amp;Treating</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wish_Child_Id_Hidden__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field holds the ID of the Wish Child</description>
        <label>Wish Child Id Hidden</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe01__WorkEmail__c</fullName>
        <description>See Preferred Email field.</description>
        <inlineHelpText>See Preferred Email field.</inlineHelpText>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Relationship_to_child__c</fullName>
        <description>This field is used to store the relationship of the person who submits the Wish Kid details</description>
        <label>Relationship to child</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Member/Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wish_Family_ContactId__c</fullName>
        <description>It is an hidden field. Storing the original Wish Family Contact Id. So while converting the lead, we can create a relationship under this wish Family Record instead of creating dup wish family. we are capturing value for this field on Find Duplicate page.</description>
        <label>Wish Family ContactId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Best_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Best Contact for Treating Healthcare Provider</inlineHelpText>
        <label>Best Contact for Treating MP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <defaultValue>false</defaultValue>
        <description>describe Parent or Legal Guardian of wish child</description>
        <label>Parent/Legal Guardian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe4__Type__c</fullName>
        <description>Field that describes how the Related Contact is connected to the Contact.</description>
        <inlineHelpText>Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Wish Child(Self)</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Step Sister</fullName>
                </value>
                <value>
                    <fullName>Step Brother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbor</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/RelationshipServiceTest.cls
@IsTest
public class RelationshipServiceTest {

	@TestSetup
	public static void setup() {
		trac_TriggerHandlerBase.blockTrigger = true;

		Account azAccount = TestDataFactory.createAccount(1)[0];
		azAccount.Name = 'Make-A-Wish Arizona';
		azAccount.RecordTypeId = Constant_AC.CHAPTER_RT_ID;
		insert azAccount;

		ICD_Codes__c icdCode = TestDataFactory.createIcdCode(1)[0];
		icdCode.Name = 'Q917';
		insert icdCode;

		Contact wishChild = new Contact();
		wishChild.FirstName = 'Jacky';
		wishChild.LastName = 'Johnson';
		wishChild.RecordTypeId = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
		wishChild.AccountId = azAccount.Id;

		List<Contact> contactList = TestDataFactory.createContact(7);
		Contact medHolland = contactList.get(0);
		medHolland.FirstName = 'Francis';
		medHolland.LastName = 'Holland';
		medHolland.RecordTypeId = Constant_AC.MEDICAL_PROFESSIONAL_RT_ID;
		medHolland.AccountId = azAccount.Id;
		Contact medWatson = contactList.get(1);
		medWatson.FirstName = 'Jessica';
		medWatson.LastName = 'Watson';
		medWatson.RecordTypeId = Constant_AC.MEDICAL_PROFESSIONAL_RT_ID;
		medWatson.Type_of_Contact__c = 'Referrer&Treating';
		medWatson.npe01__WorkEmail__c = 'nurse.watson@email.com';
		medWatson.AccountId = azAccount.Id;
		Contact medSmith = contactList.get(2);
		medSmith.FirstName = 'Jacobi';
		medSmith.LastName = 'Smith';
		medSmith.RecordTypeId = Constant_AC.MEDICAL_PROFESSIONAL_RT_ID;
		medSmith.AccountId = azAccount.Id;
		Contact medJohnson = contactList.get(3);
		medJohnson.FirstName = 'Pam';
		medJohnson.LastName = 'Johnson';
		medJohnson.RecordTypeId = Constant_AC.MEDICAL_PROFESSIONAL_RT_ID;
		medJohnson.AccountId = azAccount.Id;
		Contact famGeorge = contactList.get(4);
		famGeorge.FirstName = 'William';
		famGeorge.LastName = 'George';
		famGeorge.RecordTypeId = Constant_AC.WISH_FAMILY_RT_ID;
		famGeorge.AccountId = azAccount.Id;
		famGeorge.Type_of_Contact__c = Constant_AC.CONTACT_TYPE_REFERRING;
		famGeorge.Email = 'william@george.com';
		famGeorge.Phone = '520-830-8978';
		famGeorge.Relationship_Type__c = Constant_AC.CONTACT_TYPE_PARENT_LEGAL_GUARDIAN;
		famGeorge.Wish_Child_Id_Hidden__c = wishChild.Id;
		famGeorge.Relationship__c = 'Father';
		Contact famGeorge2 = contactList.get(5);
		famGeorge2.FirstName = 'Natalie';
		famGeorge2.LastName = 'George';
		famGeorge2.RecordTypeId = Constant_AC.WISH_FAMILY_RT_ID;
		famGeorge2.AccountId = azAccount.Id;
		famGeorge2.Type_of_Contact__c = Constant_AC.CONTACT_TYPE_SIBLING;
		famGeorge2.Relationship_Type__c = Constant_AC.CONTACT_TYPE_SIBLING;
		famGeorge2.Wish_Child_Id_Hidden__c = wishChild.Id;
		insert contactList;

		Lead qualifiedLead = TestDataFactory.createQualifiedLead(azAccount.Id, icdCode.Id);
		qualifiedLead.FirstName = 'Fred';
		qualifiedLead.LastName = 'George';
		qualifiedLead.Referring_MP__c = medWatson.Id;
		qualifiedLead.Treating_MP__c = medHolland.Id;
		qualifiedLead.Best_Contact__c = famGeorge.Id;
		qualifiedLead.Alt_1_MP__c = medSmith.Id;
		qualifiedLead.Alt_2_MP__c = medJohnson.Id;
		qualifiedLead.Wish_Family_ContactId__c = famGeorge.Id;
		qualifiedLead.Hidden_Additional_Parent_Id__c = famGeorge2.Id;
		insert qualifiedLead;

		Database.LeadConvert leadConvert = new Database.LeadConvert();
		leadConvert.setLeadId(qualifiedLead.Id);
		leadConvert.setConvertedStatus('Qualified');
		leadConvert.setDoNotCreateOpportunity(true);
		Database.convertLead(leadConvert);

		trac_TriggerHandlerBase.blockTrigger = false;
	}

	@IsTest
	public static void buildLeadConvertRelationships() {
		Lead lead = [
				SELECT Id, ConvertedContactId, Referring_MP__c, Treating_MP__c, Best_Contact__c, Alt_1_MP__c, Alt_2_MP__c,
						Hidden_DV_form_Medical_professional_Type__c, Wish_Family_ContactId__c,
						Hidden_Additional_Parent_Id__c, Relationship_to_child__c,
						Additional_Parent_Relationship_to_Child__c, Parent_Relationship_to_Child__c
				FROM Lead
		];
		Test.startTest();
		RelationshipService.buildLeadConvertRelationships(lead);
		Test.stopTest();
	}

	@IsTest
	public static void buildLeadConvertRelationshipFamily() {
		List<Contact> familyContacts = [
				SELECT Id, FirstName, LastName, RecordTypeId, Type_of_Contact__c, Email, Phone, Wish_Child_Id_Hidden__c,
                        Relationship__c, Relationship_Type__c
				FROM Contact
				WHERE Name IN ('William George', 'Natalie George')
				ORDER BY Name DESC
		];

		Test.startTest();
		List<npe4__Relationship__c> famRelation = RelationshipService.buildWishFamilyLeadConvertRelationship(familyContacts);
		Test.stopTest();

		System.assertEquals(true, famRelation[0].Parent_Legal_Guardian__c);
		System.assertEquals(Constant_AC.CONTACT_TYPE_SIBLING, famRelation[1].npe4__Type__c);
	}
}