make-a-wish-salesforce/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to chapter account</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <filterItems>
                <field>$User.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Account.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Active Volunteer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>It displays the name of the state in which the account belongs.</description>
        <label>Chapter</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Broadcast__c.object
<CustomObject>
    <description>This object is storing the policy details.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will category the broadcast message based on the chatper.</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Chapter Name should be chapter record type</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Broadcast</relationshipLabel>
        <relationshipName>Broadcast</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Broadcast</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Broadcast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broadcast</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/BroadcastValidationTest.cls
@IsTest
public class BroadcastValidationTest {

	@TestSetup
	public static void setUp() {
		trac_TriggerHandlerBase.blockTrigger = true;

		List<Account> accounts = TestDataFactory.createAccount(1);
		Account account1 = accounts.get(0);
		account1.Name = 'Make-A-Wish Arizona';
		account1.RecordTypeId = Constant_AC.CHAPTER_RT_ID;
		insert accounts;

		String profileName = 'Full Access National Staff';
		String portalRole = 'Manager';
		Id userRoleId = [
				SELECT Id
				FROM UserRole
				WHERE Name = 'National Staff'
		].Id;

		List<User> users = TestDataFactory.createUser(1);
		User nationalStaffUser = users.get(0);
		System.runAs(Utils.currentUser) {
			Profile profile = [
					SELECT Id,Name
					FROM Profile
					WHERE Name = :profileName
					LIMIT 1
			];
			nationalStaffUser.ProfileId = profile.Id;
			nationalStaffUser.PortalRole = portalRole;
			nationalStaffUser.UserRoleId = userRoleId;
			insert users;
		}

		Chapter_Vs_Role__c createRec = new Chapter_Vs_Role__c();
		createRec.Chapter_Name__c = 'Make-A-Wish Arizona';
		createRec.Role_Name__c = 'Arizona - Chapter';
		createRec.Name = 'Make-A-Wish Arizona';
		insert createRec;

		List<Broadcast__c> broadcasts = TestDataFactory.createBroadcast(1);
		Broadcast__c broadcast = broadcasts.get(0);
		broadcast.Chapter_Name__c = nationalStaffUser.AccountId;
		broadcast.OwnerId = nationalStaffUser.Id;
		insert broadcasts;

		trac_TriggerHandlerBase.blockTrigger = false;
	}

	@IsTest
	public static void shouldValidatePermission() {
		Account account = [
				SELECT Id, Chapter_Name__c
				FROM Account
				LIMIT 1
		];
		List<Broadcast__c> broadcasts = [
				SELECT Id, Chapter_Name__c
				FROM Broadcast__c
		];

		Test.startTest();
		BroadcastValidation.validatePermission(new Set<Id>{account.Id}, broadcasts);
		Test.stopTest();
	}
}