make-a-wish-salesforce/src/objects/Awards_Recognition__c.object
<CustomObject>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This describes the Chapter Name</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Awards &amp; Recognitions</relationshipLabel>
        <relationshipName>Awards_Recognitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Awards &amp; Recognition</label>
    <nameField>
        <displayFormat>AW-{0000}</displayFormat>
        <label>Awards &amp; Recognition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards &amp; Recognitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/AwardsRecognition_OnAfterInsertHandler.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 10/15/2016
Description : AwardsRecognition_OnAfterInsertTriggerHandler is used to call the Helper class when a
              new Awards & Recognitionrecord is created.
              
              Modification Log
              ------------------
              WVC-1887    Pavithra G  07/03/2018
              
*****************************************************************************************************/
Public class AwardsRecognition_OnAfterInsertHandler{    
    /*******************
       This method is handle all logic for after inserting the Awards and Recognition record Event.
       **********************/
    public static void OnAfterInsert(List<Awards_Recognition__c> AwardsRecognitionList){
          Map<Id,Awards_Recognition__c> awardsRecgMap = new Map<Id,Awards_Recognition__c>();
          for(Awards_Recognition__c  currRec :AwardsRecognitionList){ 
              If ( currRec.Chapter_Name__C != Null){
                  awardsRecgMap.put(currRec.Id,currRec);
                  
              }
          }
          If(awardsRecgMap.Size() > 0 )
              AwardsRecognition_OnAfterInsertHelper.showErrorMismatchedRole(awardsRecgMap);
    }
}