make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <description>It will capture the background check process completed date.</description>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>It holds the Expiration Date of Background check for volunteer.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will tells the final result about the background check.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved w/ Conditions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>This field is used to store the value of expiration date.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Out of Compliance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/UpdatAffiliationAsInactiveBatch_Test.cls
/*************************************************************************
Created by : Vennila Paramasivam
Author : MST Solutions
CreatedDate : 07/25/2016
Description : Unit Test for UpdatAffiliationAsInactiveBatch_AC.
**************************************************************************/
@isTest
public class UpdatAffiliationAsInactiveBatch_Test
{
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    static testmethod void UpdateInactiveStatus()
    {
       TestClassUtil.createVolunteerContact();
       TestClassUtil.createVolunteerAccount();
       npe5__Affiliation__c affiliation = TestClassUtil.createorgAffiliation();
       affiliation.npe5__Status__c = 'Active';
       update affiliation;
       
       Background_check__c  createExpiredBC = new Background_check__c();
       createExpiredBC.Volunteer__c = affiliation.npe5__Contact__c;
       createExpiredBC.Status__c= 'Approved';
       createExpiredBC.Date__c = Date.Today().addDays(-5);
       createExpiredBc.Date_Completed__c = Date.Today();
       insert createExpiredBC;
       
       Conflict_Of_Interest__c newCOI = new Conflict_Of_Interest__c();
       newCOI.Volunteer_Contact__c = affiliation.npe5__Contact__c;
       newCOI.Expiration_Date__c = Date.Today().addDays(-5);
       insert newCOI;
       
       // Schedule the test job
          String jobId = System.schedule('UpdatAffiliationAsInactiveSchedule_AC',
                            CRON_EXP, 
                            new UpdatAffiliationAsInactiveSchedule_AC());
             
          // Get the information from the CronTrigger API object
          CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
             NextFireTime
             FROM CronTrigger WHERE id = :jobId];
    
          // Verify the expressions are the same
          System.assertEquals(CRON_EXP, 
             ct.CronExpression);
    
          // Verify the job has not run
          System.assertEquals(0, ct.TimesTriggered);
    
          // Verify the next time the job will run
          System.assertEquals('2022-03-15 00:00:00', 
             String.valueOf(ct.NextFireTime));
             
             
          Test.startTest();
            UpdatAffiliationAsInactiveBatch_AC batchAffiliation = new UpdatAffiliationAsInactiveBatch_AC();
            Database.executeBatch(batchAffiliation, 200);
          Test.stopTest();
       
    }
    
  
   static testmethod void UpdateActiveStatus()
    {
       TestClassUtil.createVolunteerContact();
       TestClassUtil.createVolunteerAccount();
       npe5__Affiliation__c affiliation = TestClassUtil.createorgAffiliation();
       affiliation.npe5__Status__c = 'inActive';
       update affiliation;
       
       Background_check__c  createExpiredBC = new Background_check__c();
       createExpiredBC.Volunteer__c = affiliation.npe5__Contact__c;
       createExpiredBC.Status__c= 'Approved';
       createExpiredBC.Date__c = Date.Today().addDays(5);
       createExpiredBc.Date_Completed__c = Date.Today();
       insert createExpiredBC;
       
       Conflict_Of_Interest__c newCOI = new Conflict_Of_Interest__c();
       newCOI.Volunteer_Contact__c = affiliation.npe5__Contact__c;
       newCOI.Expiration_Date__c = Date.Today().addDays(5);
       insert newCOI;
       
       // Schedule the test job
          String jobId = System.schedule('UpdatAffiliationAsInactiveSchedule_AC',
                            CRON_EXP, 
                            new UpdatAffiliationAsInactiveSchedule_AC());
             
          // Get the information from the CronTrigger API object
          CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
             NextFireTime
             FROM CronTrigger WHERE id = :jobId];
    
          // Verify the expressions are the same
          System.assertEquals(CRON_EXP, 
             ct.CronExpression);
    
          // Verify the job has not run
          System.assertEquals(0, ct.TimesTriggered);
    
          // Verify the next time the job will run
          System.assertEquals('2022-03-15 00:00:00', 
             String.valueOf(ct.NextFireTime));
             
             
          Test.startTest();
            UpdatAffiliationAsInactiveBatch_AC batchAffiliation = new UpdatAffiliationAsInactiveBatch_AC();
            Database.executeBatch(batchAffiliation, 200);
          Test.stopTest();
       
    }

}