make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <description>It will capture the background check process completed date.</description>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>It holds the Expiration Date of Background check for volunteer.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will tells the final result about the background check.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved w/ Conditions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/BackGroundCheck_OnBeforeInsertHandler.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 
Description : BackGroundCheck_OnBeforeInsertHandler is used to call the Helper class when the
              new BackGroundCheck record is created.
              
              Modification Log
              ------------------
              WVC-1866    Pavithra G  05/08/2018
              
*****************************************************************************************************/
public class BackGroundCheck_OnBeforeInsertHandler{

     public static void OnBeforeInsert(List<Background_check__c> newBCList){
         Set<Id> volunteerIds = new Set<Id>();
         Map<Id,Contact> conMap = new Map<Id, Contact>();
         for(Background_check__c  currRec : newBCList)
         {
             if(Bypass_Triggers__c.getValues(userInfo.getUserId()) == Null)
             {
                 if(!Test.isRunningTest())
                 {
                     if(currRec.Date_Completed__c != null && (currRec.Status__c != Null))
                         currRec.current__c = True;
                 }
                 volunteerIds.add(currRec.Volunteer__c);
             }
             if(currRec.Date_Completed__c != null)
             {
                 currRec.Date__c = currRec.Date_Completed__c.addYears(3);
             }
         }
         
         if(volunteerIds.size() > 0)
         {
             BackGroundCheck_OnBeforeInsertHelper.UpdateHiddenEmailField(volunteerIds,newBCList);
         }
     }
}