make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <description>It will capture the background check process completed date.</description>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>It holds the Expiration Date of Background check for volunteer.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will tells the final result about the background check.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved w/ Conditions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Background_Check_File__c.object
<CustomObject>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>Background_check__c</referenceTo>
        <relationshipLabel>Background Check Files</relationshipLabel>
        <relationshipName>Background_Check_Files</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WIP__c</fullName>
        <defaultValue>true</defaultValue>
        <label>WIP</label>
        <type>Checkbox</type>
    </fields>
    <label>Background Check File</label>
    <nameField>
        <displayFormat>A-{0000}&quot;</displayFormat>
        <label>Background Check File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Check Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Background_CheckBeforeDelete_Test.cls
@isTest
private class Background_CheckBeforeDelete_Test{

    static testMethod void triggerTest1()
    {
        test.starttest();
        Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
        Contact volunteerContact = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.Id);
      
        
        Background_check__c backCheck = new Background_check__c();
        backCheck.Date__c = system.today();
        backCheck.Volunteer__c = volunteerContact.id;
        backCheck.current__c = True;
        backCheck.Status__c = 'Approved';
        backCheck.Date_Completed__c = Date.Today();
        insert backCheck;

        Background_Check_File__c aFile=new Background_Check_File__c();
        aFile.File_Name__c='Test File';
        aFile.WIP__c=false;
        aFile.Parent__c=backCheck.Id;
        insert aFile;

        try
        {
            delete backCheck;
           // system.assert(false);
        }
        catch(Exception e)
        {
            //system.assert(true);
        }
        test.stoptest();
    }
}