make-a-wish-salesforce/src/objects/Background_check__c.object
<CustomObject>
    <description>This objects will contains the background check process details for the volunteers who submit the application to become a volunteer.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>It will be used to store the account  name</description>
        <formula>Volunteer__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>It holds the Expiration Date of Background check for volunteer.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will tells the final result about the background check.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved w/ Conditions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will lookup to the volunteer contact</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The value should be volunteer contact</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Background Checks</relationshipLabel>
        <relationshipName>Background_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Background Check</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Background check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Background_Check_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to verify whether the background check is required or not</description>
        <label>Background Check Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This Field is used as hidden field in COI Email template</description>
        <label>Hidden Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check weather this conflict of interest is active or not.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will hold the volunteer name and define chapter and role for this volunteer.</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/COI_OnAfterInsertTriggerHelper.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 
Description : COI_OnBeforeInsertTriggerHandler is used to call the Helper class when the
new COI record is created.

Modification Log
------------------
WVC-1888    Pavithra G  06/13/2018

*****************************************************************************************************/
public class COI_OnAfterInsertTriggerHelper{
    /********************************************************************************************
This method is used to create a task when the lead record is created. And share the lead
record based on the chapter.
*********************************************************************************************/
    public static void UpdateExistingRecords(List<Conflict_Of_Interest__c > newCOIList,Set<Id> recordIds,Set<Id> volunteerIds){
        try{
            List<Conflict_Of_Interest__c>  recordsToUpdate = new List<Conflict_Of_Interest__c>();
            for(Conflict_Of_Interest__c currRec : [SELECT id from Conflict_Of_Interest__c WHERE Volunteer_Contact__c IN :volunteerIds AND Id NOT IN :recordIds AND current__c = True])
            {
                Conflict_Of_Interest__c newRec = new Conflict_Of_Interest__c();
                newRec.id = currRec.id;
                newRec.current__c = false;
                recordsToUpdate.add(newRec);
                
            }
            
            if(recordsToUpdate.size() > 0)
                update recordsToUpdate;
            if(Test.isRunningTest()){
                throw new CommonTriggerException('Test Class execution');
            }
        }
        Catch(Exception ex){
            for(Conflict_Of_Interest__c  currRec : newCOIList){
                ErrorMessage_AC.createdebugRec('COI_OnAfterInsertTriggerHelper',String.valueof(currRec),String.valueOf(ex),'UpdateExistingRecords',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            
            if(!Test.isRunningTest()){
                for(Conflict_Of_Interest__c  currRec : newCOIList){
                    currRec.addError(Label.Debug_log_error_message);
                }
            }
            
        }
    }
    
    public Static Void COIRecordSharing(Set<Id> ownerIds, List<Conflict_Of_Interest__c> coiList)
    {
        try{
            Map<Id,String> userRoleMap = UserRoleUtility.getUserRole(ownerIds);
            Map<String, List<Conflict_Of_Interest__c>> coiMap = new Map<String, List<Conflict_Of_Interest__c>>();
            
            for(Conflict_Of_Interest__c currCOI : coiList)
            {
                if(currCOI.Account_Name__c != Null && userRoleMap.get(currCOI.OwnerId) == 'National Staff')
                {
                    if(coiMap.containsKey(currCOI.Account_Name__c))
                    {
                        coiMap.get(currCOI.Account_Name__c).add(currCOI);
                    }
                    else
                        coiMap.put(currCOI.Account_Name__c, new List<Conflict_Of_Interest__c>{currCOI});
                }
            }
            
            if(coiMap.size() > 0)
                ChapterStaffRecordSharing_AC.COIRecordSharing(coiMap);
            if(Test.isRunningTest()){
                throw new CommonTriggerException('Test Class execution');
            }
        }
        Catch(Exception ex){
            for(Conflict_Of_Interest__c  currRec : coiList){
                ErrorMessage_AC.createdebugRec('COI_OnAfterInsertTriggerHelper',String.valueof(currRec),String.valueOf(ex),'COIRecordSharing',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            
            if(!Test.isRunningTest()){
                for(Conflict_Of_Interest__c  currRec : coiList){
                    currRec.addError(Label.Debug_log_error_message);
                }
            }
            
        }
    }
    public Static Void updateVolunteerRole(Set<Id> voluunteerIdSet, List<Conflict_Of_Interest__c> coiList)
    {
        try{
            Set<Id> expiredBCVolunteerIdSet = new Set<Id>();
            List<Volunteer_Roles__c> updateVolunteerRoleList = new List<Volunteer_Roles__c>(); //
            for(Background_check__c currRec : [SELECT Id,Current__c,Date__c,Volunteer__c FROM Background_check__c WHERE Volunteer__c IN : voluunteerIdSet AND Current__c = True AND Date__c < TODAY]){
                expiredBCVolunteerIdSet.add(currRec.Volunteer__c);
            }
            for(Volunteer_Roles__c currRole : [SELECT Id,Name,Status__c,Hidden_Previous_Status__c,Sub_Status__C,Hidden_Previous_Sub_Status__c,Chapter_Role__c,Volunteer_Name__c,Chapter_Role__r.Background_Check_Required__c FROM Volunteer_Roles__c  WHERE Volunteer_Name__c  IN :voluunteerIdSet AND Status__c = 'Out of Compliance']){
                    if((currRole.Chapter_Role__r.Background_Check_Required__c == True && !(expiredBCVolunteerIdSet.contains(currRole.Volunteer_Name__c))) || (currRole.Chapter_Role__r.Background_Check_Required__c == False)){
                    Volunteer_Roles__c updateRole = new Volunteer_Roles__c();
                    updateRole.Id = currRole.Id;
                    updateRole.Status__c = currRole.Hidden_Previous_Status__c;
                    updateRole.Sub_Status__c = currRole.Hidden_Previous_Sub_Status__c;                     
                    updateRole.Hidden_Previous_Status__c = '';
                    updateRole.Hidden_Previous_Sub_Status__c = '';
                    updateVolunteerRoleList.add(updateRole);                    
                }       
            }
            
            If(updateVolunteerRoleList.Size() > 0)
                Update updateVolunteerRoleList;
            
        
         if(Test.isRunningTest()){
                throw new CommonTriggerException('Test Class execution');
            }

        
        
        }
         Catch(Exception ex){
            for(Conflict_Of_Interest__c  currRec : coiList){
                ErrorMessage_AC.createdebugRec('COI_OnAfterInsertTriggerHelper',String.valueof(currRec),String.valueOf(ex),'updateVolunteerRole',currRec.Id,ex.getStackTraceString()+'   '+ex.getMessage(),'Error');
            }
            
            if(!Test.isRunningTest()){
                for(Conflict_Of_Interest__c  currRec : coiList){
                    currRec.addError(Label.Debug_log_error_message);
                }
            }
            
        }
    }
    
    
    
}