make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Condition_Description__c.object
<CustomObject>
    <label>Condition Description</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Description</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <fields>
        <fullName>Condition_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It has one to many relationship with Condition Description.</description>
        <label>Condition Description</label>
        <referenceTo>Condition_Description__c</referenceTo>
        <relationshipLabel>ICD Codes</relationshipLabel>
        <relationshipName>ICD_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SD1_Condition_Description__c</fullName>
        <description>It holds the condition description for Secoundary Diagnosis 1</description>
        <label>SD1 Condition Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SD1_ICD_Code__c</fullName>
        <description>It contains ICD code for Secondary Diagnosis 1</description>
        <label>SD1 ICD Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SD2_Condition_Description__c</fullName>
        <description>It holds the condition description for Secoundary Diagnosis 2</description>
        <label>SD2 Condition Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SD2_ICD_Code__c</fullName>
        <description>It contains ICD code for Secondary Diagnosis 2</description>
        <label>SD2 ICD Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SD3_Condition_Description__c</fullName>
        <description>It holds the condition description for Secoundary Diagnosis 3</description>
        <label>SD3 Condition Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SD3_ICD_Code__c</fullName>
        <description>It contains ICD code for Secondary Diagnosis 3</description>
        <label>SD3 ICD Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SD4_Condition_Description__c</fullName>
        <description>It holds the condition description for Secondary Diagnosis 4</description>
        <label>SD4 Condition Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SD4_ICD_Code__c</fullName>
        <description>It contains ICD code for Secondary Diagnosis 4</description>
        <label>SD4 ICD Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/QualifyingDiagnosisLC_AC.cls
/***************************************************************************************************
Author      : MST Solutions
CreatedBy   : Pradeep Kumar
Date        : 20/03/2018
Description : Class contains AURA enbaled utility methods used by the QualifyingDiagnosis component
*****************************************************************************************************/

public class QualifyingDiagnosisLC_AC {
    
    /********************************************************************************************
Get the neccessary lead information for further process of sending diagnosis verfication    
***********************************************************************************************/
    @AuraEnabled
    public static Case getMedicalInformation(Id caseId){
        Case data = [SELECT Id, 
                     lead__r.PD_Condition_Description__c,
                     lead__r.PD_ICD_Code__r.Name,
                     lead__r.SD1_Condition_Description__c,
                     lead__r.SD1_ICD_Code__r.Name,
                     lead__r.SD2_Condition_Description__c,
                     lead__r.SD2_ICD_Code__r.Name,
                     lead__r.SD3_Condition_Description__c,
                     lead__r.SD3_ICD_Code__r.Name,
                     lead__r.SD4_Condition_Description__c,
                     lead__r.SD4_ICD_Code__r.Name
                     FROM Case WHERE Id = :caseId LIMIT 1];
        
        return data;
    }
    
    /********************************************************************************************
Get the neccessary lead information for further process of sending diagnosis verfication    
***********************************************************************************************/
    @AuraEnabled
    public static String updateQualifyingDiagnosis(String Qualifying_Diagnosis, Id Qualifying_ICD, Id leadId, String mawName){
        String result;
        Lead data = [SELECT Id, 
                     PD_Condition_Description__c,
                     PD_ICD_Code__r.Id,
                     SD1_Condition_Description__c,
                     SD1_ICD_Code__r.Id,
                     SD2_Condition_Description__c,
                     SD2_ICD_Code__r.Id,
                     SD3_Condition_Description__c,
                     SD3_ICD_Code__r.Id,
                     SD4_Condition_Description__c,
                     SD4_ICD_Code__r.Id,
                     Qualifying_Diagnosis__c,
                     Qualifying_ICD__c,
                     PR_Diagnosis__c
                     FROM Lead WHERE Id = :leadId LIMIT 1];
        
        data.Qualifying_Diagnosis__c = Qualifying_Diagnosis;
        data.Qualifying_ICD__c= Qualifying_ICD;
        data.PR_Diagnosis__c = mawName;
        System.debug('Result Data = ' + data);
        update data;
        result = 'UPDATED';
        return result;
    }
    
/********************************************************************************************
Get the neccessary icd code information for further process  
***********************************************************************************************/
    @AuraEnabled
    public static Id getIcdCodeInfo(String icdCodeName){
           return [SELECT Id,Name FROM ICD_Codes__c WHERE Name = :icdCodeName LIMIT 1].Id;
          
    }
    
/********************************************************************************************
Get the neccessary condition description information for further process  
***********************************************************************************************/
    @AuraEnabled
    public static String getConditionDescInfo(String qc_Diagnosis){
        	String mawName;
        	List<Condition_Description__c> descriptionList = [SELECT Id, PR_Diagnosis__c
                                                                          FROM Condition_Description__c WHERE Name = :qc_Diagnosis limit 1];
            mawName = (descriptionList.size() > 0) ? descriptionList[0].PR_Diagnosis__c : '';
           //System.debug('mawName = ' + mawName);
           return mawName;
          
    }
    
}