make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the value of the chapter role.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Non-Wish &amp; Events</relationshipLabel>
        <relationshipName>Non_Wish_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Time_sheet__c.object
<CustomObject>
    <description>This object is used to track the time spent by the volunteer contact to close the wish or Non Wish &amp; Event</description>
    <fields>
        <fullName>Hours_spent__c</fullName>
        <description>This field is used to track how many hours the volunteer have spent for the volunteer opportunity.</description>
        <inlineHelpText>Please enter two digits on decimal place.</inlineHelpText>
        <label>Hours spent</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <description>This field is used to store the volunteer opportunity records.</description>
        <label>Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Time sheet</relationshipLabel>
        <relationshipName>Time_sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time sheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Non_Wish_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It hold the record of each event</description>
        <label>Name</label>
        <referenceTo>Non_Wish_Events__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It will display the role name</description>
        <formula>Chapter_Role_Opportunity__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/TimeSheetTrigger_AT_Test.cls
/*****************************************************************************************************************
Author      : MST Solutions
CreatedBy   : Kanagaraj
Date        : 5/23/2016
Description : This TimeSheetTrigger_AT_Test is used to calculate the total hours spent by volunteer to close the wish and 
Non-wish & Event.
*******************************************************************************************************************/
@isTest
public class TimeSheetTrigger_AT_Test {
       
       /*Create Wish volunteer Opportunity time sheet*/
      public testmethod static void InsertWishTimeSheet(){
        Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();   
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild(); 
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Role__c  roleName = OrientationandTrainingUtil.createRole();
        Chapter_Role__c  chapterRole = OrientationandTrainingUtil.createChapter(chapterAccount.Id,roleName.id);
        List<Volunteer_Opportunity__c> wishVolunteerOpportunityList =OrientationandTrainingUtil.NewWishVolunteerOpportunityList(chapterAccount.id,chapterRole.id,parentCase.id,2);
        OrientationandTrainingUtil.crateWishTimeSheet(wishVolunteerOpportunityList);
        OrientationandTrainingUtil.crateWishTimeSheet(wishVolunteerOpportunityList );
        List<Time_sheet__c> updateTimeSheetList = new List<Time_sheet__c>();
        List<Time_sheet__c> timeSheetList = [SELECT Id,Volunteer_Opportunity__c,Volunteer_Opportunity__r.Wish__c,Hours_spent__c  FROM Time_sheet__c WHERE Volunteer_Opportunity__r.Wish__c =: parentCase.Id];
        for(Time_sheet__c processTimeSheetRec : timeSheetList){
            processTimeSheetRec.Hours_spent__c = 10.30;
            updateTimeSheetList.add(processTimeSheetRec);
        }
        
        update updateTimeSheetList;
        
        delete updateTimeSheetList;
      }
      
      /*Create Non Wish Volunteer Opportunity time sheet*/
       public testmethod static void InsertNonWishTimeSheet(){
        Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();   
        Non_Wish_Events__c nonWishEventId = OrientationandTrainingUtil.CreateEvent(chapterAccount.Id);
        Role__c  roleName = OrientationandTrainingUtil.createRole();
        Chapter_Role__c  chapterRole = OrientationandTrainingUtil.createChapter(chapterAccount.Id,roleName.id);
        List<Volunteer_Opportunity__c> nonWishVolunteerOpportunityList =OrientationandTrainingUtil.NewnonWishVolunteerOpportunityList(chapterAccount.id,chapterRole.id,nonWishEventId.id,1);
        OrientationandTrainingUtil.crateNonWishTimeSheet(nonWishVolunteerOpportunityList,2);
        OrientationandTrainingUtil.crateNonWishTimeSheet(nonWishVolunteerOpportunityList,2);
       
        List<Time_sheet__c> updateTimeSheetList = new List<Time_sheet__c>();
        List<Time_sheet__c> timeSheetList = [SELECT Id,Volunteer_Opportunity__c,Volunteer_Opportunity__r.Non_Wish_Event__c,Hours_spent__c  FROM Time_sheet__c WHERE Volunteer_Opportunity__r.Wish__c =: nonWishEventId.Id];
        for(Time_sheet__c processTimeSheetRec : timeSheetList){
            processTimeSheetRec.Hours_spent__c = 10.45;
            updateTimeSheetList.add(processTimeSheetRec);
        }
        
        update updateTimeSheetList;
        
        delete updateTimeSheetList;
      }
     
   }