make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Expense__c.object
<CustomObject>
    <description>This object will be used to store budgeting information</description>
    <fields>
        <fullName>Budget_Cash__c</fullName>
        <description>It will capture the $ of Budget Cash information</description>
        <label>Budget Cash</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_In_Kind__c</fullName>
        <description>It will capture the $ of Budget In Kind information</description>
        <label>Budget In Kind</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Wish Case for which these expenses are being incurred.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Wish Expenses</relationshipLabel>
        <relationshipName>Wish_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish_Expense_Transaction_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wish Expense Transaction Code</label>
        <referenceTo>Wish_Expense_Transaction_Code__c</referenceTo>
        <relationshipLabel>Wish Expenses</relationshipLabel>
        <relationshipName>Wish_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish_Expense_Type__c</fullName>
        <description>This field will be used to select the wish expense type</description>
        <label>Wish Expense Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airfare</fullName>
                </value>
                <value>
                    <fullName>Car Rental</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Wish Expense</label>
    <nameField>
        <displayFormat>WE-{00000}</displayFormat>
        <label>Wish Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Expense_Transaction_Code__c.object
<CustomObject>
    <fields>
        <fullName>Wish_Expense_Type__c</fullName>
        <label>Wish Expense Type</label>
        <referenceTo>Wish_Expense_Type__c</referenceTo>
        <relationshipLabel>Wish Expense Transaction Codes</relationshipLabel>
        <relationshipName>Wish_Expense_Transaction_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wish Expense Transaction Code</label>
    <nameField>
        <label>Wish Expense Transaction Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wish Expense Transaction Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Expense_Type__c.object
<CustomObject>
    <label>Wish Expense Type</label>
    <nameField>
        <label>Wish Expense Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wish Expense Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/WishBudgetForm_AC_Test.cls
@isTest
public class WishBudgetForm_AC_Test{
   
    public static testMethod void testmethodLoad(){
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c obj = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert obj;
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',parentCase.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
        wishBudget.DeptDiv='10,20,30';
        wishBudget.getWishExpenceTypes();
        wishBudget.getDeptDivisions();
        wishBudget.getAccountDescs();
        wishBudget.showDeptDiv();
        wishBudget.closePopup();
        wishBudget.closePopup1();        
        WishBudgetForm_AC.ApprovalStepWrapper appStep= new WishBudgetForm_AC.ApprovalStepWrapper ();
        System.assertEquals(parentCase.Id,planAntiCase.ParentId,'Planning case does not a parent Id');
        System.assert(parentCase.ContactId != Null,'wish does not have child recored');
    }
    /************************************************************
    This methos is used to cover the unit test and incease the code coverage for add the wish type in budget form.
    *************************************************************/
     public static testMethod void testmethodAddExpenseType(){      
        
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c expense = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert expense;
        ApexPages.StandardController sc = new ApexPages.StandardController(expense);
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',expense.Case__c);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
        Wish_Expense_Type__c wishExpenseType= OrientationandTrainingUtil.CreateWishExpenseTypeRecord();
        insert wishExpenseType;
        Wish_Expense_Transaction_Code__c currtransactionCode = OrientationandTrainingUtil.CreateWishExpenseTransactionCodeRecord(wishExpenseType.Id);
        insert currtransactionCode;
        wishBudget.TransCodesWrap.put('Airfare', new List<Wish_Expense_Transaction_Code__c>{currtransactionCode});
        wishBudget.newExpenseType ='Airfare';
        wishBudget.addExpenseType();
        System.assertEquals(wishBudget.newExpenseType,'Airfare','Wish expese type is mismatched');
        System.assert(wishBudget.newExpenseType == 'Airfare','Wish expese type is mismatched');  
   }
   
    /************************************************************
    This methos is used to cover the unit test and incease the code coverage for add the wish expense data.
    *************************************************************/
    public static testMethod void testmethodAddExpense(){
       
        //Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c expense = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert expense;
        ApexPages.StandardController sc = new ApexPages.StandardController(expense);
        
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',expense.Case__c);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
        Wish_Expense_Type__c wishExpenseType= OrientationandTrainingUtil.CreateWishExpenseTypeRecord();
        insert wishExpenseType;
        Wish_Expense_Transaction_Code__c currtransactionCode = OrientationandTrainingUtil.CreateWishExpenseTransactionCodeRecord(wishExpenseType.Id);
        insert currtransactionCode;
        wishBudget.TransCodesWrap.put('Airfare', new List<Wish_Expense_Transaction_Code__c>{currtransactionCode});
        Wish_Expense__c expenseData = new Wish_Expense__c();
        expenseData.Wish_Expense_Transaction_Code__c=currtransactionCode.Id;
        expenseData.Budget_Cash__c=10;
        expenseData.Budget_In_Kind__c=20;
        wishBudget.wishExpensewrap.put('Airfare', new List<Wish_Expense__c>{expenseData});
        wishBudget.expenseType ='Airfare';
        wishBudget.addExpense();
        System.assertEquals(wishBudget.expenseType ,'Airfare','Wish expese type is mismatched');
        System.assert(expenseData.Budget_Cash__c != 20,'Expense data is mismatched');    
   }
    /**************************************************************************************************************************
    This methos is used to cover the unit test and incease the code coverage for submit the approval process for wish budget form.
    ******************************************************************************************************************************/
    public static testMethod void testmethodsubmitForApproval(){       
        //Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c expense = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert expense;
        ApexPages.StandardController sc = new ApexPages.StandardController(expense);
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',expense.Case__c);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
        Wish_Expense_Type__c wishExpenseType= OrientationandTrainingUtil.CreateWishExpenseTypeRecord();
        insert wishExpenseType;
        Wish_Expense_Transaction_Code__c currtransactionCode = OrientationandTrainingUtil.CreateWishExpenseTransactionCodeRecord(wishExpenseType.Id);
        insert currtransactionCode;
        wishBudget.TransCodesWrap.put('Airfare', new List<Wish_Expense_Transaction_Code__c>{currtransactionCode});
        Wish_Expense__c expenseData = new Wish_Expense__c();
        expenseData.Wish_Expense_Transaction_Code__c=currtransactionCode.Id;
        expenseData.Budget_Cash__c=10;
        expenseData.Budget_In_Kind__c=20;
        wishBudget.wishExpensewrap.put('Airfare', new List<Wish_Expense__c>{expenseData});
        wishBudget.expenseType ='Airfare';
        //User userInfo=OrientationandTrainingUtil.createrSystemAdminUser();
        wishBudget.approverId = userInfo.getUserId();
        wishBudget.getPlanningAnticipationCase.add(planAntiCase) ;
        wishBudget.submitForApproval(); 
        System.assertEquals(wishBudget.approverId ,userInfo.getUserId(),'Approver is not a active user');
        System.assert(expenseData.Budget_Cash__c != 20,'Expense data is mismatched');   
   } 
    /**************************************************************************************************************************
    This methos is used to cover the unit test and incease the code coverage for display the approval process list for wish budget form for corressponding wish.
    ******************************************************************************************************************************/
   public static testMethod void testmethodUserListForApproval(){
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c obj = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert obj;
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',parentCase.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
        wishBudget.getUserListForApproval();
        System.assertEquals(wishBudget.CaseId,parentCase.Id,'Budget form does not equal to wish');
        System.assert(wishBudget.getUserListForApproval().size() != 0,'No Approval is available');
    }
    /**************************************************************************************************************************
    This methos is used to cover the unit test and incease the code coverage for load the templates from the wish budget form.
    ******************************************************************************************************************************/
     public static testMethod void testmethodLoadTemplates(){
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c obj = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert obj;
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',parentCase.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
         Wish_Expense_Type__c wishExpenseType= OrientationandTrainingUtil.CreateWishExpenseTypeRecord();
        insert wishExpenseType;
        Wish_Expense_Transaction_Code__c currtransactionCode = OrientationandTrainingUtil.CreateWishExpenseTransactionCodeRecord(wishExpenseType.Id);
        insert currtransactionCode;
        wishBudget.TransCodesWrap.put('Airfare', new List<Wish_Expense_Transaction_Code__c>{currtransactionCode});
        wishBudget.LoadTemplates();
        System.assertEquals(wishBudget.CaseId,parentCase.Id,'Budget form does not equal to wish');
        System.assert(wishBudget.CaseId == parentCase.Id,'Budget form does not equal to wish');
    } 
    /**************************************************************************************************************************
    This methos is used to cover the unit test and incease the code coverage for save the wish expenses.
    ******************************************************************************************************************************/
    public static testMethod void testmethodSaveExpenses(){
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c obj = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert obj;
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',parentCase.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
        Wish_Expense_Type__c wishExpenseType= OrientationandTrainingUtil.CreateWishExpenseTypeRecord();
        insert wishExpenseType;
        Wish_Expense_Transaction_Code__c currtransactionCode = OrientationandTrainingUtil.CreateWishExpenseTransactionCodeRecord(wishExpenseType.Id);
        insert currtransactionCode;
        wishBudget.TransCodesWrap.put('Airfare', new List<Wish_Expense_Transaction_Code__c>{currtransactionCode});
        Wish_Expense__c expenseData = new Wish_Expense__c();
        expenseData.Wish_Expense_Transaction_Code__c=currtransactionCode.id;
        expenseData.Budget_Cash__c=10;
        expenseData.Budget_In_Kind__c=20;
        wishBudget.wishExpensewrap.put('Airfare', new List<Wish_Expense__c>{expenseData});
        wishBudget.expenseType ='Airfare';
        wishBudget.SaveExpenses();
        System.assertEquals(wishBudget.expenseType ,'Airfare','Wish expese type is mismatched');
        System.assert(expenseData.Budget_Cash__c != 20,'Expense data is mismatched');  
    }
    /**************************************************************************************************************************
    This methos is used to cover the unit test and incease the code coverage for remove the expenses from the list.
    ******************************************************************************************************************************/
    public static testMethod void testmethodRemoveExpense(){
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Case planAntiCase = OrientationandTrainingUtil.createWishPlanningCase(wishChild.Id, parentCase.Id);
        Wish_Expense__c obj = OrientationandTrainingUtil.createWishExpenceRecord(parentCase.Id);
        insert obj;
        PageReference pageRef = Page.WishBudgetForm_VF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('CaseId',parentCase.Id);
        ApexPages.currentPage().getParameters().put('index','0');
        ApexPages.currentPage().getParameters().put('expenType','Airfare');
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        WishBudgetForm_AC wishBudget = new WishBudgetForm_AC(sc);
        Wish_Expense_Type__c wishExpenseType= OrientationandTrainingUtil.CreateWishExpenseTypeRecord();
        insert wishExpenseType;
        Wish_Expense_Transaction_Code__c currtransactionCode = OrientationandTrainingUtil.CreateWishExpenseTransactionCodeRecord(wishExpenseType.Id);
        insert currtransactionCode;
        wishBudget.TransCodesWrap.put('Airfare', new List<Wish_Expense_Transaction_Code__c>{currtransactionCode});
        Wish_Expense__c expenseData = new Wish_Expense__c();
        expenseData.Wish_Expense_Transaction_Code__c=currtransactionCode.Id;
        expenseData.Budget_Cash__c=10;
        expenseData.Budget_In_Kind__c=20;
        wishBudget.wishExpensewrap.put('Airfare', new List<Wish_Expense__c>{expenseData});
        wishBudget.expenseList= wishBudget.wishExpensewrap.get('Airfare');
        wishBudget.removeExpense();
        System.assert(currtransactionCode.Wish_Expense_Type__c == wishExpenseType.Id,'Wish Expense Type is mismatched in Wish Expense Transaction Code');
        System.assertEquals(currtransactionCode.Wish_Expense_Type__c, wishExpenseType.Id,'Wish Expense Type is mismatched in Wish Expense Transaction Code');
    }
    
}