make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IsLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used to lock the record when the sub status is &quot;Abandoned&quot;.</description>
        <label>IsLocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field will be used to know the progress(Current status) of the wish</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age Expiration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign in Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss of Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Viewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refused</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wish_type__c</fullName>
        <description>It holds the details about the  type of wish</description>
        <label>Wish type</label>
        <picklist>
            <picklistValues>
                <fullName>Cruise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GKTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Closed_Case_Editing_Security_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Lists which profiles and user are not able to edit closed case records.</description>
    <fields>
        <fullName>Restrict_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If &apos;TRUE&apos; the user or profile or user listed will not be able to edit a closed case record.</description>
        <label>Restrict Access</label>
        <type>Checkbox</type>
    </fields>
    <label>Closed Case Editing Security Settings</label>
</CustomObject>

make-a-wish-salesforce/src/objects/UserSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting holds the list of users to edit the wish records when the status is &quot;Abandoned&quot;</description>
    <label>Update Abandoned Wishes</label>
</CustomObject>

make-a-wish-salesforce/src/classes/CaseValidationsTest.cls
/**
 * @description
 * @author Steve Doucette, Traction on Demand
 * @date 5/27/2020
 */
@IsTest
private class CaseValidationsTest {

    @TestSetup
    static void setup() {
        trac_TriggerHandlerBase.blockTrigger = true;

        insert new Closed_Case_Editing_Security_Settings__c(SetupOwnerId = UserInfo.getUserId(), Restrict_Access__c = true);
        insert new UserSetting__c(SetupOwnerId = UserInfo.getUserId());

        Account account = TestDataFactory.createAccount(1)[0];
        insert account;

        Contact wishChild = TestDataFactory.createContact(1)[0];
        wishChild.AccountId = account.Id;
        insert wishChild;

        Case validationCase = TestDataFactory.createCase(1)[0];
        validationCase.RecordTypeId = Constant_AC.WISH_RT_ID;
        validationCase.ContactId = wishChild.Id;
        validationCase.AccountId = account.Id;
        insert validationCase;

        trac_TriggerHandlerBase.blockTrigger = false;
    }

    @IsTest
    static void testWishTypeNull() {
        Case newCase = getTestCase();
        Case oldCase = newCase.clone(true, true, true, true);
        newCase.Status = Constant_AC.CASE_STATUS_WISH_DETERMINED;

        CaseValidations.beforeUpdateValidations(newCase, oldCase);
    }

    @IsTest
    static void testReopenCase() {
        Case newCase = getTestCase();
        Case oldCase = newCase.clone(true, true, true, true);
        oldCase.Status = Constant_AC.CASE_STATUS_CLOSED;
        newCase.Status = Constant_AC.CASE_STATUS_NEW;

        CaseValidations.beforeUpdateValidations(newCase, oldCase);
    }

    @IsTest
    static void testLockedAdoptableCase() {
        Case newCase = getTestCase();
        Case oldCase = newCase.clone(true, true, true, true);
        newCase.IsLocked__c = oldCase.IsLocked__c = true;
        newCase.Status = Constant_AC.CASE_STATUS_CLOSED;
        newCase.Closed_Date__c = Date.today();
        newCase.Adopted_By__c = 'Smiths';

        trac_TriggerHandlerBase.blockTrigger = true;
        update newCase;
        trac_TriggerHandlerBase.blockTrigger = false;

        Boolean valid = CaseValidations.beforeUpdateValidations(getTestCase(), oldCase);
        System.assertEquals(false, valid);
    }

    @IsTest
    static void testNoEditPermission() {
        Case newCase = getTestCase();
        Case oldCase = newCase.clone(true, true, true, true);
        newCase.IsLocked__c = oldCase.IsLocked__c = true;
        newCase.Status = Constant_AC.CASE_STATUS_CLOSED;
        newCase.Closed_Date__c = Date.today();

        trac_TriggerHandlerBase.blockTrigger = true;
        update newCase;
        UserSetting__c usc = UserSetting__c.getInstance();
        usc.All_Closed_Cases_except_Abandoned__c = true;
        update usc;
        trac_TriggerHandlerBase.blockTrigger = false;

        Boolean valid = CaseValidations.beforeUpdateValidations(getTestCase(), oldCase);
        System.assertEquals(false, valid);
    }

    @IsTest
    static void testLockedAndAdopted() {
        Case newCase = getTestCase();
        Case oldCase = newCase.clone(true, true, true, true);
        newCase.IsLocked__c = oldCase.IsLocked__c = true;
        newCase.Adopted_By__c = 'Smiths';
        oldCase.Status = Constant_AC.CASE_STATUS_CLOSED;
        newCase.Closed_Date__c = Date.today();

        trac_TriggerHandlerBase.blockTrigger = true;
        update oldCase;
        UserSetting__c usc = UserSetting__c.getInstance();
        usc.All_Closed_Cases_except_Abandoned__c = true;
        usc.Edit_Abandoned_Cases__c = true;
        update usc;
        trac_TriggerHandlerBase.blockTrigger = false;

        Boolean valid = CaseValidations.beforeUpdateValidations(newCase, getTestCase());
        System.assertEquals(false, valid);
    }

    @IsTest
    static void testAbandonedError() {
        Case newCase = getTestCase();
        Case oldCase = newCase.clone(true, true, true, true);
        newCase.Sub_Status__c = Constant_AC.CASE_SUB_STATUS_ABANDONED;
        oldCase.Status = Constant_AC.CASE_STATUS_GRANTED;

        Boolean valid = CaseValidations.beforeUpdateValidations(newCase, oldCase);
        System.assertEquals(false, valid);
    }

    @IsTest
    static void testPass() {
        Case newCase = getTestCase();
        Case oldCase = newCase.clone(true, true, true, true);

        Boolean valid = CaseValidations.beforeUpdateValidations(newCase, oldCase);
        System.assertEquals(true, valid);
    }

    private static Case getTestCase() {
        return [
                SELECT Id, AccountId, ContactId, Status, RecordTypeId, IsClosed,
                        Wish_Type__c, IsLocked__c, Sub_Status__c,
                        Adopted_By__c, Adopted__c, Adoptable__c
                FROM Case
        ];
    }
}