make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ICD_Given_By_Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to hold the ICD given by referrer</description>
        <label>ICD Given By Referrer</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts (ICD Given By Referrer)</relationshipLabel>
        <relationshipName>Contacts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region_Chapter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the contact region chapter</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Region Chapter)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/dsfs__DocuSign_Status__c.object
<CustomObject>
    <description>DocuSign Status is the foundation Custom Object for integration of DocuSign and Salesforce.</description>
    <fields>
        <fullName>dsfs__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>DocuSign_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DocuSign Status</label>
    <nameField>
        <displayFormat>DSX-{0000000}</displayFormat>
        <label>Envelope#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Child_Age__c</fullName>
        <description>It would capture the child of the age.</description>
        <label>Child Age</label>
        <picklist>
            <picklistValues>
                <fullName>Under 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18 &amp; Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Override_Dupe_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to bypass the duplicate validation.</description>
        <label>No Duplicate Found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>unique_wish_identifier__c</fullName>
        <description>To store the unique wish identifier</description>
        <label>unique wish identifier</label>
        <length>20</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/classes/LeadWishFamilyDupe_Test.cls
@IsTest
public class LeadWishFamilyDupe_Test {

	@TestSetup
	private static void setup() {
		trac_TriggerHandlerBase.blockTrigger = true;
		insert new Bypass_Triggers__c(SetupOwnerId = UserInfo.getUserId());
	}

	static testMethod void createRecords() {
		Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
		Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
		Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
		newLead.Child_Age__c = '4';
		newLead.unique_wish_identifier__c = '123456';
		insert newLead;

		Test.startTest();
		String result = LeadWishFamilyDupe.FindFamilyContactDupe(newLead.id);
		Test.stopTest();
	}

	/*This method is used to increase the code coverage for findDuplicateRecords method */
	public testMethod static void findWishChildDupe() {

		Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
		Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
		Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
		newLead.unique_wish_identifier__c = '1234567';
		newLead.Child_Age__c = '4';
		insert newLead;
		Lead dupeLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
		dupeLead.Override_Dupe_Check__c = true;
		dupeLead.unique_wish_identifier__c = '123456';
		insert dupeLead;

		Test.startTest();
		String result = LeadWishFamilyDupe.FindLeadDupe(dupeLead.id);
		Test.stopTest();

		System.assertEquals(LeadWishFamilyDupe.DUPE_MESSAGE, result);
	}

	/*This method is used to increase the code coverage for findDuplicateRecords method */
	public testMethod static void findLeadDupe() {
		Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
		insert chapterAccount;

		Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
		newLead.unique_wish_identifier__c = '1234567';
		newLead.Child_Age__c = '4';
		newLead.State = 'Arizona';
		newLead.PostalCode = '35004';
		newLead.Street = 'test';
		newLead.Phone = '8220708920';
		insert newLead;
		Lead dupeLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
		dupeLead.LastName = 'John';
		dupeLead.City = 'Karur';
		dupeLead.State = 'Arizona';
		dupeLead.PostalCode = '35004';
		dupeLead.Street = 'test';
		dupeLead.Phone = '8220708920';
		dupeLead.Override_Dupe_Check__c = true;
		dupeLead.unique_wish_identifier__c = '123456';
		insert dupeLead;

		String result = LeadWishFamilyDupe.FindLeadDupe(dupeLead.id);
		LeadWishFamilyDupe.resetDVMedicalSummary(dupeLead.id);

		System.assertEquals(LeadWishFamilyDupe.DUPE_MESSAGE, result);

		// Covering other blocks of the FindLeadDupe method
		Test.startTest();
		dupeLead.FirstName = dupeLead.LastName = 'Test FN';
		dupeLead.DOB__c = newLead.DOB__c;
		dupeLead.Street = 'Test St.';
		update dupeLead;
		result = LeadWishFamilyDupe.FindLeadDupe(dupeLead.id);

		dupeLead.FirstName = newLead.FirstName;
		dupeLead.State = 'Colorado';
		dupeLead.City = 'Denver';
		dupeLead.PostalCode = '12345';
		dupeLead.Phone = '1234567890';
		dupeLead.Email = 'Test@test.com';
		update dupeLead;
		result = LeadWishFamilyDupe.FindLeadDupe(dupeLead.id);
		delete newLead;

		Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
		wishChildContact.FirstName = newLead.FirstName;
		wishChildContact.LastName = newLead.LastName;
		wishChildContact.Region_Chapter__c = newLead.ChapterName__c;
		insert wishChildContact;
		result = LeadWishFamilyDupe.FindLeadDupe(dupeLead.id);

		wishChildContact.Birthdate = newLead.DOB__c;
		wishChildContact.Phone = newLead.Phone;
		wishChildContact.Email = newLead.Email;
		update wishChildContact;
		result = LeadWishFamilyDupe.FindLeadDupe(dupeLead.id);
		Test.stopTest();
	}

	public testMethod static void sendDVWithICDCode() {

		Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
		Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
		Lead dupeLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
		dupeLead.LastName = 'John';
		dupeLead.city = 'Karur';
		dupeLead.State = 'Arizona';
		dupeLead.PostalCode = '35004';
		dupeLead.street = 'test';
		dupeLead.Phone = '8220708920';
		dupeLead.Override_Dupe_Check__c = true;
		dupeLead.unique_wish_identifier__c = '123456';
		dupeLead.ICD_Given_By_Referrer__c = dupeLead.PD_ICD_Code__c;
		insert dupeLead;

		Test.startTest();
		LeadWishFamilyDupe.resetDVMedicalSummary(dupeLead.id);
		Test.stopTest();

		Lead result = [
				SELECT LastName
				FROM Lead
		];
		System.assertEquals('John', result.LastName);
	}

	/*
	 * Chris Shinnimin, Traction on Demand:
	 * Additional tests to increase code coverage.
	 * Jira ticket WLP-322
	 */
	@IsTest
	private static void testDocusignDeleteList() {
		Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
		Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
		Lead dupeLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
		dupeLead.LastName = 'John';
		dupeLead.city = 'Karur';
		dupeLead.State = 'Arizona';
		dupeLead.PostalCode = '35004';
		dupeLead.street = 'test';
		dupeLead.Phone = '8220708920';
		dupeLead.Override_Dupe_Check__c = true;
		dupeLead.unique_wish_identifier__c = '123456';
		dupeLead.ICD_Given_By_Referrer__c = dupeLead.PD_ICD_Code__c;
		insert dupeLead;

		dsfs__DocuSign_Status__c dsStatus = new dsfs__DocuSign_Status__c(
				dsfs__Lead__c = dupeLead.id
		);
		insert dsStatus;

		Attachment att = new Attachment(
				ParentId = dsStatus.Id,
				Name = 'Some attachment',
				Body = Blob.valueOf('Some body')
		);
		insert att;

		Case caseToDelete = new Case(
				Lead__c = dupeLead.Id,
				RecordTypeId = Constant_AC.DIAGNOSIS_RT_ID
		);
		insert caseToDelete;

		Test.startTest();
		LeadWishFamilyDupe.resetDVMedicalSummary(dupeLead.id);
		Test.stopTest();

		List<dsfs__DocuSign_Status__c> dsStatuses = [
				SELECT Id
				FROM dsfs__DocuSign_Status__c
		];
		List<Attachment> attachments = [
				SELECT Id
				FROM Attachment
		];

		System.assertEquals(0, dsStatuses.size());
		System.assertEquals(0, attachments.size());
	}
}