make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <description>It will holds the wish child birthday date.</description>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>It will hold the value of middle name.</description>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <description>This field will used to store all related contact  in the relationship object record of the wish child</description>
        <label>Hidden Parent/Legal Guardian</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Residing_with_Wish_child__c</fullName>
        <description>It will indicate that participant is residing with wish child or not.</description>
        <label>Residing With Wish Child</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>It will hold the state information.</description>
        <label>Hidden State</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>It will hold the value of the street name.</description>
        <label>Street</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_Shirt_Size__c</fullName>
        <description>It will capture the wish child T.Shirt size</description>
        <label>T-Shirt Size</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>npe01__WorkPhone__c</fullName>
        <description>See &apos;Preferred Phone&apos; field.</description>
        <inlineHelpText>See &apos;Preferred Phone&apos; field.</inlineHelpText>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Hidden_isparentFirst__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hidden isparentFirst</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <defaultValue>false</defaultValue>
        <description>describe Parent or Legal Guardian of wish child</description>
        <label>Parent/Legal Guardian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residing_with_Wish_child__c</fullName>
        <description>It will define wish child residing with wish child or not. FLS removed 2019-09-13 as the information in this field is now housed on the Wish Affiliation object.</description>
        <label>Residing with Wish child</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Wish_Forms__c</fullName>
        <defaultValue>false</defaultValue>
        <description>FLS removed 2019-09-13 as the information in this field is now housed on the Wish Affiliation object.</description>
        <label>Send Wish Forms to</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wish_Participant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Described Wish Participants</description>
        <label>Wish Participant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe4__Contact__c</fullName>
        <description>Related Contact is this Contact's ______.</description>
        <inlineHelpText>Related Contact is this Contact's ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe4__RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe4__Type__c</fullName>
        <description>Field that describes how the Related Contact is connected to the Contact.</description>
        <inlineHelpText>Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Wish Child(Self)</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Step Sister</fullName>
                </value>
                <value>
                    <fullName>Step Brother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbor</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Child_Form__c.object
<CustomObject>
    <description>It will hold the value of Wish Child, Wish Info and Wish Family values.</description>
    <fields>
        <fullName>BirthDate__c</fullName>
        <description>Wish Child DOB</description>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It lookup to case record</description>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wish</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipName>Wish_Child_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>It will hold wish child&apos;s city detail.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Wish child&apos;s Email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Emergency_Relationship__c</fullName>
        <label>Emergency Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Other Family</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbour</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>Wish Child First Name</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Same_as_Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hidden Same as Family</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Wish Child Last Name</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>Wish Child Middle Name</description>
        <label>Middle Name</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>It will hold wish child&apos;s state detail</description>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>it will hold child&apos;s address details(about street)</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_Shirt_Size__c</fullName>
        <description>Wish Child T-Shirt Size</description>
        <label>T-Shirt Size</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>It will hold wish child zip code detail.</description>
        <label>Zip Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mobilePhone__c</fullName>
        <description>Wish child&apos;s mobile phone</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <label>Wish Paperwork Packet</label>
    <nameField>
        <displayFormat>WC-{00}</displayFormat>
        <label>Wish Child Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Paperwork Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Zip_Code__c.object
<CustomObject>
    <description>This object is used to store the value of the zip code.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/BatchRelationshipRecUpdate.cls
global class BatchRelationshipRecUpdate implements Database.Batchable<SObject> {

	global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([
				SELECT Id, ContactId
				FROM Case
				WHERE RecordType.Name = 'Wish' AND Status != 'Completed'
		]);
	}

	global void execute(Database.BatchableContext BC, List<Case> caseList) {
		Id familyContactRecordTypeId = Constant_AC.WISH_FORM_FAMILY_ID;
		Map<Id, Id> wishFormMap = new Map<Id, Id>();
		Map<Id, Id> caseMap = new Map<Id, Id>();
		List<Wish_Child_Form__c> dbWishChildFormList = new List<Wish_Child_Form__c >();
		Set<Id> caseIdSet = new Set<Id>();
		for (Case dbProcess : caseList) {
			caseIdSet.add(dbProcess.Id);
		}

		for (Wish_Child_Form__c dbWishChild : [
				SELECT Id,RecordTypeId,RecordType.Name,Case__c,Contact__c,Case__r.contactId
				FROM Wish_Child_Form__c
				WHERE RecordType.Name = :'Wish Form Family' AND Contact__c != Null
				AND Case__c IN:caseIdSet
		]) {

			wishFormMap.put(dbWishChild.Contact__c, dbWishChild.Case__r.contactId);
			caseMap.put(dbWishChild.Case__r.contactId, dbWishChild.Case__c);
		}
		/**
		  * JIRA: WLP-291
		  * Author: Gustavo Mayer
		  * Update: Non-Comped, Medical_Needs, Send_Wish_Forms__c and Residing_with_Wish_child__c
		  * to reside on Wish Affiliation object and to be removed from npe4__Relationship__c.
		  */
		for (npe4__Relationship__c currRel : [
				SELECT Id, npe4__RelatedContact__c, Parent_Legal_Guardian__c, Wish_Participant__c, npe4__RelatedContact__r.FirstName,
						npe4__RelatedContact__r.LastName, npe4__RelatedContact__r.Email, Hidden_isparentFirst__c,
						npe4__RelatedContact__r.Phone, npe4__RelatedContact__r.Middle_Name__c,
						npe4__RelatedContact__r.MailingCity, npe4__RelatedContact__r.MailingStreet,
						npe4__RelatedContact__r.MailingState, npe4__RelatedContact__r.MailingPostalCode,
						npe4__Type__c, npe4__RelatedContact__r.HomePhone, npe4__RelatedContact__r.npe01__WorkPhone__c,
						npe4__RelatedContact__r.MobilePhone, npe4__RelatedContact__r.BirthDate,
//						npe4__RelatedContact__r.Residing_with_Wish_child__c,
						npe4__RelatedContact__r.T_Shirt_Size__c,npe4__RelatedContact__r.RecordType.Name,
						npe4__Contact__c,npe4__Contact__r.RecordTypeId, npe4__Contact__r.RecordType.Name
				FROM npe4__Relationship__c
				WHERE npe4__Contact__r.RecordType.Name = :Constant_AC.CONTACT_WISH_CHILD_RT_LABEL AND
				npe4__RelatedContact__r.RecordType.Name = :Constant_AC.WISH_FAMILY_RT_LABEL AND npe4__Contact__c IN:caseMap.KeySet()
		]) {

			if ((!wishFormMap.containsKey(currRel.npe4__RelatedContact__c)) && (caseMap.containsKey(currRel.npe4__Contact__c))) {

				Wish_Child_Form__c newWishFormRec = new Wish_Child_Form__c();
				newWishFormRec.FirstName__c = currRel.npe4__RelatedContact__r.FirstName;
				newWishFormRec.Middle_Name__c = currRel.npe4__RelatedContact__r.Middle_Name__c;
				newWishFormRec.LastName__c = currRel.npe4__RelatedContact__r.LastName;
				newWishFormRec.mobilePhone__c = currRel.npe4__RelatedContact__r.MobilePhone;
				newWishFormRec.BirthDate__c = currRel.npe4__RelatedContact__r.BirthDate;
				newWishFormRec.Email__c = currRel.npe4__RelatedContact__r.Email;
				newWishFormRec.city__c = currRel.npe4__RelatedContact__r.Mailingcity;
				newWishFormRec.Street__c = currRel.npe4__RelatedContact__r.Mailingstreet;
				newWishFormRec.State__c = currRel.npe4__RelatedContact__r.MailingState;
				newWishFormRec.Zip_code__c = currRel.npe4__RelatedContact__r.MailingPostalCode;
				newWishFormRec.Emergency_Relationship__c = currRel.npe4__Type__c;
				newWishFormRec.Home_Phone__c = currRel.npe4__RelatedContact__r.HomePhone;
				newWishFormRec.TelePhone__c = currRel.npe4__RelatedContact__r.npe01__WorkPhone__c;
				newWishFormRec.T_Shirt_Size__c = currRel.npe4__RelatedContact__r.T_Shirt_Size__c;
				newWishFormRec.Case__c = caseMap.get(currRel.npe4__Contact__c);
				newWishFormRec.RecordTypeId = familyContactRecordTypeId;
				newWishFormRec.Contact__c = currRel.npe4__RelatedContact__c;
				if (currRel.Wish_Participant__c == true && currRel.Parent_Legal_Guardian__c == false)
					newWishFormRec.IsParticipant__c = true;
				if (currRel.Parent_Legal_Guardian__c == true && currRel.Wish_Participant__c == true)
					newWishFormRec.Hidden_Same_as_Family__c = true;
//				newWishFormRec.Residing_With_Wish_Child__c = currRel.npe4__RelatedContact__r.Residing_with_Wish_child__c;
				dbWishChildFormList.add(newWishFormRec);
			}

		}

		if (dbWishChildFormList.size() > 0)
			insert dbWishChildFormList;
	}

	global void finish(Database.BatchableContext BC) {

	}
}