make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Wish_type__c</fullName>
        <description>It holds the details about the  type of wish</description>
        <label>Wish type</label>
        <picklist>
            <picklistValues>
                <fullName>Cruise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GKTW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Diagnosis_Given_By_Referrer__c</fullName>
        <description>Used to hold the diagnosis given by referrer</description>
        <label>Diagnosis Given By Referrer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>It will hold the gender information.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Self-describe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate the wish Child Family aware of Referral at MAWA.</description>
        <label>Is Family Aware Of Referral?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Guardian_Name__c</fullName>
        <description>This field holds the name of the Parent/Guardian Name</description>
        <label>Parent/Guardian Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wish referrer.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture the referrer Email.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It capture the wish referrer Zip code.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/dsfs__DocuSign_Status__c.object
<CustomObject>
    <description>DocuSign Status is the foundation Custom Object for integration of DocuSign and Salesforce.</description>
    <fields>
        <fullName>Docusign_Hidden_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store contact value to update the confilict of interest when insert from landing page.</description>
        <label>Docusign Hidden Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DocuSign Status - Volunteer</relationshipLabel>
        <relationshipName>DocuSign_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish_Required_Signature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Wish Required Signature record.</description>
        <label>Wish Required Signature</label>
        <referenceTo>Wish_Required_Signature__c</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>DocuSign_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>R00N80000002vw3fEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>DocuSign_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>DocuSign_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__Subject__c</fullName>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Status</label>
    <nameField>
        <displayFormat>DSX-{0000000}</displayFormat>
        <label>Envelope#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>I_am_Recognized_To_Practice_As_a__c</fullName>
        <description>It will hold which type of practice she/he is going to get</description>
        <label>I am Recognized To Practice As a</label>
        <picklist>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse Practitioner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Life Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Guardian_Name__c</fullName>
        <description>This field will hold the Parent name / Guardian name of the Wish kid</description>
        <label>Parent/Guardian Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFI_Form_Info_Hidden__c</fullName>
        <description>In hold the RFI form status level. And this field is hidden field for preventing dup criteria while creating new lead from RFI.</description>
        <label>RFI Form Info Hidden</label>
        <picklist>
            <picklistValues>
                <fullName>Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wih&apos;s parent.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture email address of wish parent from referral form.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It will hold the firstname of the child.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It will capture the zipcode of wish&apos;s parent.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Required_Signature__c.object
<CustomObject>
    <description>The Wish Required Signature stores information about signatures that are required (from a legal and/or logistical standpoint) for a wish to proceed. It is linked to the Wish (Case) and to the person signing the form (Contact). It includes information about the Wish Signature Form. It tracks the life-cycle of each signature: the date it is sent out to be signed, the date it is signed and received, and (if applicable) the date on which the signature changes from valid to invalid.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>The primary statuses for the WRS should be: not sent, sent, signed, voided, and expired. Note that some of these statuses come from DocuSign as per https://support.docusign.com/en/guides/ndse-user-guide-document-status.</description>
        <inlineHelpText>Primary statuses are: not sent, sent, signed, voided, and expired; the others are DocuSign statuses.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Delivery Failure</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <label>Signed</label>
                </value>
                <value>
                    <fullName>Not Sent - Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Wish Required Signature</label>
    <nameField>
        <displayFormat>WRS-{000000}</displayFormat>
        <label>Wish Required Signature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Required Signatures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DocusignStatusTrigger_AT_Test.cls
/***************************************************************************************************
Author      : MST Solutions
CreatedBy   : Kanagaraj
Date        : 28/06/2016
Description : DocusignStatusTrigger_AT_Test is used to increase the code coverage for Application_AC controller.
*****************************************************************************************************/
@IsTest
public class DocusignStatusTrigger_AT_Test {
    
    @TestSetup 
    static void setUp() {
        trac_TriggerHandlerBase.blockTrigger = true;
        
        Account accountAzChapter = TestDataFactory.createAccount(1)[0];
        accountAzChapter.Name = 'Make-A-Wish Arizona';
        accountAzChapter.RecordTypeId = Constant_AC.CHAPTER_RT_ID;
        insert accountAzChapter;
        
        List<Contact> contactList = TestDataFactory.createContact(2);
        Contact volunteerHector = contactList.get(0);
        volunteerHector.RecordTypeId = Constant_AC.VOLUNTEER_RT_ID;
        volunteerHector.AccountId = accountAzChapter.Id;
        volunteerHector.FirstName = 'Hector';
        volunteerHector.LastName = 'Sol';
        volunteerHector.Email = 'h.sol@email.com';
        Contact wishChildAnthony = contactList.get(1);
        wishChildAnthony.FirstName = 'Anthony';
        wishChildAnthony.LastName = 'Edwards';
        wishChildAnthony.Parent_Guardian_Name__c = 'Jonathan Edwards';
        wishChildAnthony.RecordTypeId = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
        wishChildAnthony.Birthdate = Date.today().addDays(+21);
        wishChildAnthony.Birthdate = wishChildAnthony.Birthdate.addYears(-5);
        wishChildAnthony.MailingPostalCode = '94105-5188';
        wishChildAnthony.MailingStreet = '7540 E Gold Dust Ave';
        wishChildAnthony.MailingCountry = 'United States';
        wishChildAnthony.MailingState = 'Arizona';
        wishChildAnthony.MailingCity = 'Scottsdale';
        wishChildAnthony.MailingLatitude = -24.355798;
        wishChildAnthony.MailingLongitude = 69.830469;
        insert contactList;
        
        Case wishChildCase = TestDataFactory.createCase(1)[0];
        wishChildCase.RecordTypeId = Constant_AC.WISH_RT_ID;
        wishChildCase.ChapterName__c = accountAzChapter.Id;
        wishChildCase.Subject = 'Parent Wish';
        wishChildCase.Interview_date__c = System.today();
        wishChildCase.Wish_Type__c = 'Disney World';
        wishChildCase.Start_Date__c = System.today();
        wishChildCase.End_Date__c = System.today();
        wishChildCase.ContactId = wishChildAnthony.Id;
        wishChildCase.Status = 'New';
        wishChildCase.Start_Date__c = System.today();
        wishChildCase.LiabilitySignerMapKeyPair__c = 'Vennila';
        wishChildCase.Budget_Submitted_Date__c = System.today();
        wishChildCase.Budget_Approved_Date__c = System.today();
        insert wishChildCase;
        
        Lead referredLead = TestDataFactory.createLead(1)[0];
        referredLead.FirstName = 'Thomas';
        referredLead.LastName = 'Naranja';
        referredLead.Company = 'MAWA';
        referredLead.Street = '123 Cactus Road';
        referredLead.State = 'Arizona';
        referredLead.StateCode = 'AZ';
        referredLead.City = 'Phoenix';
        referredLead.Postalcode = '85264';
        referredLead.CountryCode = 'US';
        referredLead.Gender__c = 'Male';
        referredLead.Phone = '7600467559';
        referredLead.ChapterName__c = accountAzChapter.Id;
        referredLead.DOB__c = System.today() - 1435;
        referredLead.is_Family_Aware_of_Referral__c = 'Yes';
        referredLead.Referrer_FirstName__c = 'Janet';
        referredLead.Referrer_Last_Name__c = 'Evans';
        referredLead.Referrer_Email__c = 'janet.evans.test@gmail.com';
        referredLead.Referrer_Phone__c = '0600467559';
        referredLead.Referrer_City__c = 'Phoenix';
        referredLead.Referrer_Zip__c = '85264';
        referredLead.PD_Condition_Description__c = 'Malignant Melanoma';
        referredLead.Diagnosis_Given_By_Referrer__c = 'Malignant Melanoma';
        referredLead.I_am_Recognized_To_Practice_As_a__c = 'Physician';
        referredLead.Status = Constant_AC.LEAD_STATUS_REFERRED;
        referredLead.RFI_Form_Info_Hidden__c = Constant_AC.LEAD_RFI_FORM_INFO_QUALIFIED;
        insert referredLead;
        
        List<dsfs__DocuSign_Status__c> docusignStatusList = TestDataFactory.createDocusignStatus(3);
        dsfs__DocuSign_Status__c dsfsVolunteer = docusignStatusList.get(0);
        dsfsVolunteer.Docusign_Hidden_Contact__c = volunteerHector.Id;
        dsfsVolunteer.dsfs__Contact__c = volunteerHector.Id;
        dsfs__DocuSign_Status__c dsfsLead = docusignStatusList.get(1);
        dsfsLead.dsfs__Lead__c = referredLead.Id;
        dsfs__DocuSign_Status__c dsfsCase = docusignStatusList.get(2);
        dsfsCase.dsfs__Case__c = wishChildCase.Id;
        dsfsCase.dsfs__Subject__c = Constant_AC.DOCUSIGN_STATUS_SUBJECT_SIGNATURE_REQUIRED_WISH_CLEARANCE_FORM;
        insert docusignStatusList;
        
        Attachment attachment = TestDataFactory.createAttachments(1, dsfsVolunteer.Id)[0];
        insert attachment;
        
        Wish_Signature_Forms__c wishForm = TestDataFactory.createWishSignatureForm(1)[0];
        insert wishForm;     
        
        Wish_Required_Signature__c wishSignature = TestDataFactory.createWishRequiredSignature(1)[0];
        wishSignature.Wish_Case__c = wishChildCase.Id;
        wishSignature.Wish_Signature_Form__c = wishform.Id;
        insert wishSignature;
        
        trac_TriggerHandlerBase.blockTrigger = false;
    }
    
    /*This method is used to update the isConflict status as true when the envelop status is completed.*/
    @IsTest
    public static void updateIsConfilictToTrue() {
        dsfs__DocuSign_Status__c dsfs = [
            SELECT Id, Docusign_Hidden_Contact__c
            FROM dsfs__DocuSign_Status__c 
            WHERE Docusign_Hidden_Contact__r.Name = 'Hector Sol'
        ];
        dsfs.dsfs__Envelope_Status__c = Constant_AC.DOCUSIGN_ENVELOPE_STATUS_COMPLETED;
        dsfs.isConflict__c = true;
        Test.startTest();
        update dsfs;
        Test.stopTest();
        List<Conflict_Of_Interest__c> newCOIs = [
            SELECT Id, Volunteer_Contact__c 
            FROM Conflict_Of_Interest__c
            WHERE Volunteer_Contact__c = :dsfs.Docusign_Hidden_Contact__c
        ];
        System.assert(newCOIs.size() == 1);
    }
    
    /*This method is used to update the isConfilict status as false when the envelop status is completed.*/
    @IsTest
    public static void updateIsConfilictToFalse() {
        dsfs__DocuSign_Status__c dsfs = [
            SELECT Id, Docusign_Hidden_Contact__c
            FROM dsfs__DocuSign_Status__c 
            WHERE Docusign_Hidden_Contact__r.Name = 'Hector Sol'
        ];
        dsfs.dsfs__Envelope_Status__c = Constant_AC.DOCUSIGN_ENVELOPE_STATUS_COMPLETED;
        dsfs.isConflict__c = false;
        Test.startTest();
        update dsfs;
        Test.stopTest();
        Contact volunteerUpdated = [
            SELECT Id, is_Application__c 
            FROM Contact 
            WHERE Id = :dsfs.Docusign_Hidden_Contact__c
        ];
        System.assert(volunteerUpdated.is_Application__c == 'Approved');
    }
    
    /*This method is used to convert the lead when the docusign status is completed.*/
    @IsTest
    public static void convertLead() {
        Lead referredLead = [
            SELECT Id, Sub_Status__c 
            FROM Lead 
            WHERE Name = 'Thomas Naranja'
        ];
        referredLead.Sub_Status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
        update referredLead;
        dsfs__DocuSign_Status__c dsfs = [
            SELECT Id, dsfs__Lead__c, dsfs__Envelope_Status__c
            FROM dsfs__DocuSign_Status__c 
            WHERE dsfs__Lead__c = :referredLead.Id
        ];
        dsfs.dsfs__Envelope_Status__c = Constant_AC.DOCUSIGN_ENVELOPE_STATUS_COMPLETED;
        Test.startTest();
        update dsfs;
        Test.stopTest();
        Lead leadUpdated = [
            SELECT Id, Status 
            FROM Lead 
            WHERE Id = :referredLead.Id
        ];
        System.assert(leadUpdated.Status == Constant_AC.LEAD_STATUS_QUALIFIED);
    }
    
    @IsTest
    public static void convertLeadStatusNotQualified() {
        Lead referredLead = [
            SELECT Id, Sub_Status__c 
            FROM Lead 
            WHERE Name = 'Thomas Naranja'
        ];
        referredLead.Sub_Status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
        referredLead.RFI_Form_Info_Hidden__c = Constant_AC.LEAD_RFI_FORM_INFO_NOT_QUALIFIED;
        update referredLead;
        dsfs__DocuSign_Status__c dsfs = [
            SELECT Id, dsfs__Lead__c, dsfs__Envelope_Status__c
            FROM dsfs__DocuSign_Status__c 
            WHERE dsfs__Lead__c = :referredLead.Id
        ];
        dsfs.dsfs__Envelope_Status__c = Constant_AC.DOCUSIGN_ENVELOPE_STATUS_COMPLETED;
        Test.startTest();
        update dsfs;
        Test.stopTest();
        Lead leadUpdated = [
            SELECT Id, Status 
            FROM Lead 
            WHERE Id = :referredLead.Id
        ];
        System.assert(leadUpdated.Status == Constant_AC.LEAD_STATUS_ELIGIBILITY_REVIEW);
    }
    
    @IsTest
    public static void insertAttachment() {
        Contact wishChild = [
            SELECT Id 
            FROM Contact 
            WHERE Name = 'Anthony Edwards'
        ];
        dsfs__DocuSign_Status__c dsfs = [
            SELECT Id
            FROM dsfs__DocuSign_Status__c 
            WHERE dsfs__Contact__r.Name = 'Hector Sol'
        ];
        dsfs.dsfs__Contact__c = wishChild.Id;
        dsfs.dsfs__Subject__c = Constant_AC.DOCUSIGN_SUBJECT_DIAGNOSIS_VERIFICATION_FORM;
        Test.startTest();
        update dsfs;
        Test.stopTest();
        List<Attachment> attachmentList = [
            SELECT Id 
            FROM Attachment 
            WHERE ParentId = :wishChild.Id
        ];
        System.assert(!attachmentList.isEmpty());
    }
    
    @IsTest
    public static void sendWishClearance() {
        dsfs__DocuSign_Status__c dsfs = [
            SELECT Id, dsfs__Case__c
            FROM dsfs__DocuSign_Status__c 
            WHERE dsfs__Case__c != null
        ];
        dsfs.dsfs__Envelope_Status__c = Constant_AC.DOCUSIGN_ENVELOPE_STATUS_COMPLETED;
        Test.startTest();
        update dsfs;
        Test.stopTest();
        Case updatedCase = [
            SELECT Id, Wish_Clearance_Received_Date__c 
            FROM Case 
            WHERE Id = :dsfs.dsfs__Case__c
        ];
        System.assert(updatedCase.Wish_Clearance_Received_Date__c == System.today());
    }
    
    @IsTest
    public static void updateWishSignature() {
        Wish_Required_Signature__c wishSignature = [
            SELECT Id 
            FROM Wish_Required_Signature__c 
            LIMIT 1
        ];
        dsfs__DocuSign_Status__c dsfsWishSignature = TestDataFactory.createDocusignStatus(1)[0];
        dsfsWishSignature.Wish_Required_Signature__c = wishSignature.Id;
        Test.startTest();
        insert dsfsWishSignature;
        Test.stopTest();
        Wish_Required_Signature__c wishSignatureUpdated = [
            SELECT Id, Status__c, Sent_Date__c
            FROM Wish_Required_Signature__c 
            WHERE Id = :wishSignature.Id
        ];
        System.assert(wishSignatureUpdated.Status__c == Constant_AC.WISH_REQUIRED_SIGNATURE_STATUS_SENT);
        System.assert(wishSignatureUpdated.Sent_Date__c == System.today());
    }
}