make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field will be used to know the progress(Current status) of the wish</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age Expiration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign in Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Delay Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss of Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Viewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refused</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Part_A_Received__c</fullName>
        <description>This field will capture the date when the status is changed Part A Sent to Eligibility Review/Qualified</description>
        <label>Diagnosis Verification Received</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Part_A_Received__c</fullName>
        <description>This field will capture the date when the status is changed Part A Sent to Eligibility Review/Qualified</description>
        <label>Diagnosis Verification Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referred_Date__c</fullName>
        <description>This field will capture the date value when the lead is is referred</description>
        <label>Referred Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/WishJourneyController_Test.cls
@isTest
public class WishJourneyController_Test {
    public static testMethod void caseCreation() {
        PageReference pageRef = Page.WishJourney;
        Test.setCurrentPage(pageRef);
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCaseWithoutInterviewDate(wishChild.id);
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(parentCase));
        obj.wishId = 'CaseId';
        obj.anticipationId = 'AnticipationId';
        obj.assitId = 'AssitId';
        obj.effectId = 'EffectId';
        obj.grantId = 'garntId';
        obj.determinationId = 'determinationId';
        obj.inActive = true;
        obj.escalated = false;
        obj.onHold = true;
        obj.granted = true;
        obj.newStatus = true;
        obj.completed = true;
        obj.closed = true;
        obj.readytoAssign = true;
        obj.wishDetermined = true;
        obj.getCases();
    }
    
    public static testMethod void caseWithInactive() {
        String wishRecTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Wish Assist').getRecordTypeId();
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Inactive';
        currentCase.Origin = 'Email';
        currentCase.RecordTypeId = wishRecTypeId;
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
        
    }
    
    public static testMethod void caseWithOnhold() {
        String wishRecTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Wish Determination').getRecordTypeId();
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'On Hold';
        currentCase.Origin = 'Email';
        currentCase.RecordTypeId = wishRecTypeId;
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
        
    }
    
    public static testMethod void caseWitEscalated() {
        Constant_AC newConstant = new Constant_AC();
        String wishRecTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get(newConstant.wishEffectRT).getRecordTypeId();
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Escalated';
        currentCase.Origin = 'Email';
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
        
    }
    
    public static testMethod void caseWitGranted() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Granted';
        currentCase.Origin = 'Email';
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }
    public static testMethod void caseWitQualified() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Qualified';
        currentCase.Origin = 'Email';
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }
    
    public static testMethod void caseWitReadytoAssign() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Ready to Assign';
        currentCase.Sub_Status__c = 'Test';
        currentCase.Origin = 'Email';
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }
    
    public static testMethod void caseWitWishDetermined() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Wish Determined';
        currentCase.Origin = 'Email';
        currentCase.Meet_PWL_Criteria__c = 'Test';
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }
    
    public static testMethod void caseWitWishNew() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'New';
        currentCase.Origin = 'Email';
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }
    
    public static testMethod void caseWitWishCompleted() {
        Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
        Lead currLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
        currLead.Part_A_Received__c = Date.today();
        currLead.Referred_Date__c = Date.today();
        insert currLead;
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Completed';
        currentCase.Origin = 'Email';
        currentCase.Lead__c = currLead.Id;
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }

    
    public static testMethod void caseWitWishClosed() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        currentCase.Status = 'Closed';
        currentCase.Origin = 'Email';
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }
    
    public static testMethod void caseWitWishChild() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.CreateParentCaseWithoutInterviewDate(wishChild.id);
        currentCase.Status = 'Closed';
        currentCase.Origin = 'Email';
        currentCase.ParentId = parentCase.Id;
        insert currentCase;
        WishJourneyController obj = new WishJourneyController(new ApexPages.StandardController(currentCase));
    }
    
}