make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>It will hold the value of middle name.</description>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>It will hold the relationship infromation</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Stepsister</fullName>
                </value>
                <value>
                    <fullName>Stepbrother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbour</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe01__WorkPhone__c</fullName>
        <description>See &apos;Preferred Phone&apos; field.</description>
        <inlineHelpText>See &apos;Preferred Phone&apos; field.</inlineHelpText>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/dsfs__DocuSign_Recipient_Status__c.object
<CustomObject>
    <description>Information about a Recipient on a DocuSign Envelope. This is a child object of DocuSign Status</description>
    <label>DocuSign Recipient Status</label>
    <nameField>
        <label>DocuSign Recipient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Recipient Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/dsfs__DocuSign_Status__c.object
<CustomObject>
    <description>DocuSign Status is the foundation Custom Object for integration of DocuSign and Salesforce.</description>
    <fields>
        <fullName>Associated_Childeren__c</fullName>
        <label>Associated Childeren</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <description>This field is used to store the corresponding attachment to the docusign status record.</description>
        <label>AttachmentId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <description>This field is used to identify the which for has been sent.</description>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minor_Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Minor Participant</label>
        <referenceTo>Minor_Participant__c</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>DocuSign_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient_names__c</fullName>
        <description>This field is used to store the DocuSign recipient name for each envelop</description>
        <label>Recipient Names</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>dsfs__Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>R00N80000002vw3fEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__DocuSign_Envelope_ID__c</fullName>
        <label>DocuSign Envelope ID</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Status</label>
    <nameField>
        <displayFormat>DSX-{0000000}</displayFormat>
        <label>Envelope#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Minor_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Childeren__c</fullName>
        <label>Associated Childeren</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <label>AttachmentId</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Minor Participants</relationshipLabel>
        <relationshipName>Minor_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Path__c</fullName>
        <description>This field is used to store the file path for an attached document from FormTracker Dashboard page.</description>
        <label>File Path</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_City__c</fullName>
        <label>Combo City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_DOB__c</fullName>
        <label>Combo DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_Email__c</fullName>
        <label>Combo Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_FirstName__c</fullName>
        <label>Combo First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_HomePhone__c</fullName>
        <label>Combo HomePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_LastName__c</fullName>
        <label>Combo LastName</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_MiddleName__c</fullName>
        <label>Combo Middle Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_MobilePhone__c</fullName>
        <label>Combo MobilePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_Relationship__c</fullName>
        <label>Combo Relationship</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_State__c</fullName>
        <label>Combo State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_Street__c</fullName>
        <label>Combo Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_TelePhone__c</fullName>
        <label>Combo TelePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_Combo_Zipcode__c</fullName>
        <label>Combo Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Minor Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Minor Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minor Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/MinorParticipantTrigger_Helper.cls
Public class MinorParticipantTrigger_Helper{
    static Id wishClearenceRecordTypeId= Constant_AC.WISH_CLEARANCE_ATTACHMENT_ID;
    public static void updateAttachmentPath(Map<Id,Minor_Participant__c> minorParticipantMap){
        integer i = 1;
        //List<Case> updateCaseList = new List<Case>();
        Map<Id,Case> updateCaseMap = new Map<Id,Case>();
        case updatecase = new case();
        for(Minor_Participant__c  dbMinor : [SELECT Id,Case__c,File_Path__c,Form_Name__c,AttachmentId__c,RecordTypeId FROM Minor_Participant__c WHERE 
                                             Case__c IN: minorParticipantMap.KeySet() AND RecordTypeId =: wishClearenceRecordTypeId]){
            
            if(minorParticipantMap.containsKey(dbMinor.Case__c)){
                
                updatecase.Id = dbMinor.Case__c;
                if(updatecase.File_Path__c == Null){
                 updatecase.File_Path__c = i +'-'+' '+dbMinor.File_Path__c+'<br><br>';
                 }
                else
                {
                 updatecase.File_Path__c = updatecase.File_Path__c + i +'-'+' '+dbMinor.File_Path__c+'<br><br>';
                 
                }
               i++;
                updateCaseMap.put(updatecase.Id,updatecase);
            }
           
        }
        
        if(updateCaseMap.size() > 0)
        update updateCaseMap.values();
    
    }
    
    /*When the user updates the values Parentgurdian informationfrom combo form then 
it will update the corresponding wish family contact records.*/
    public static void updateWishFamilyContact(Map<String,Minor_Participant__c> comboWishFamilyMap){
        
        List<Contact> updateWishFamilyList = new List<Contact>();
        for(Contact dbFamilyContact : [SELECT Id,FirstName,LastName,Middle_Name__c,Email,MailingStreet,MailingCity,
                                       MailingState,MailingPostalCode,Birthdate,HomePhone,MobilePhone,
                                       Relationship__c,npe01__WorkPhone__c FROM Contact 
                                       WHERE Id IN: comboWishFamilyMap.KeySet()]){
                                           
                                           IF(comboWishFamilyMap.containsKey(dbFamilyContact.Id)){
                                               
                                               dbFamilyContact.FirstName = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_FirstName__c; 
                                               dbFamilyContact.LastName = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_LastName__c; 
                                               dbFamilyContact.Middle_Name__c = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_MiddleName__c; 
                                               dbFamilyContact.Email = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_Email__c; 
                                               dbFamilyContact.Birthdate = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_DOB__c;
                                               dbFamilyContact.HomePhone = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_HomePhone__c; 
                                               dbFamilyContact.MobilePhone = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_MobilePhone__c; 
                                               dbFamilyContact.npe01__WorkPhone__c = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_TelePhone__c; 
                                               dbFamilyContact.MailingStreet = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_Street__c; 
                                               dbFamilyContact.MailingCity = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_City__c; 
                                               dbFamilyContact.MailingState = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_State__c; 
                                               dbFamilyContact.MailingPostalCode = comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_Zipcode__c;
                                               dbFamilyContact.Relationship__c= comboWishFamilyMap.get(dbFamilyContact.Id).Hidden_Combo_Relationship__c;
                                               updateWishFamilyList.add(dbFamilyContact);
                                               
                                           }
                                           
                                       }
        if(updateWishFamilyList.size() > 0){
            update updateWishFamilyList;
        }
    } 
    
     public static void updateDocusignRecipientName(Map<String,String> comboEnvelopMap,Set<Id> comboRecIdSet){
        
        List<dsfs__DocuSign_Recipient_Status__c> updateRecipientList = new List<dsfs__DocuSign_Recipient_Status__c>();
        List<dsfs__DocuSign_Status__c> updateStatusRec  = new List<dsfs__DocuSign_Status__c>();
        String name;
       
        for(dsfs__DocuSign_Status__c dbStatusRec : [SELECT Id,Associated_Childeren__c,dsfs__DocuSign_Envelope_ID__c,dsfs__Case__c,(SELECT Id,Name FROM 
                                                                                                                                   R00NS0000000WUO2MAO),Recipient_names__c,Minor_Participant__c FROM dsfs__DocuSign_Status__c WHERE 
                                                    dsfs__DocuSign_Envelope_ID__c =: comboEnvelopMap.KeySet() AND
                                                    Minor_Participant__c IN: comboRecIdSet Limit 1]){
                                                        if(comboEnvelopMap.containsKey(dbStatusRec.dsfs__DocuSign_Envelope_ID__c)){            
                                                            
                                                            for(dsfs__DocuSign_Recipient_Status__c dbRecipient : dbStatusRec.R00NS0000000WUO2MAO){
                                                                dbRecipient.Name = comboEnvelopMap.get(dbStatusRec.dsfs__DocuSign_Envelope_ID__c);
                                                                name = comboEnvelopMap.get(dbStatusRec.dsfs__DocuSign_Envelope_ID__c);
                                                                updateRecipientList.add(dbRecipient);
                                                            }
                                                            dbStatusRec.Recipient_names__c  = name;
                                                            updateStatusRec.add(dbStatusRec);
                                                          
                                                        }
                                                    }
        if(updateRecipientList.size() > 0 && updateStatusRec.size() > 0){
            update updateRecipientList;
            update updateStatusRec;
         }
          
    } 
  }