make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/dsfs__DocuSign_Recipient_Status__c.object
<CustomObject>
    <description>Information about a Recipient on a DocuSign Envelope. This is a child object of DocuSign Status</description>
    <fields>
        <fullName>dsfs__Recipient_Status__c</fullName>
        <description>The last status reported by the DocuSign System for this recipient</description>
        <label>Recipient Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Recipient Status</label>
    <nameField>
        <label>DocuSign Recipient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Recipient Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/dsfs__DocuSign_Status__c.object
<CustomObject>
    <description>DocuSign Status is the foundation Custom Object for integration of DocuSign and Salesforce.</description>
    <fields>
        <fullName>dsfs__Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>R00N80000002vw3fEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__DocuSign_Envelope_ID__c</fullName>
        <label>DocuSign Envelope ID</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dsfs__Envelope_Status__c</fullName>
        <label>Envelope Status</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dsfs__Subject__c</fullName>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isConflict__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used as hidden field when volunterr click the ok button on volunteer landing page.</description>
        <label>isConflict</label>
        <type>Checkbox</type>
    </fields>
    <label>DocuSign Status</label>
    <nameField>
        <displayFormat>DSX-{0000000}</displayFormat>
        <label>Envelope#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Child_Form__c.object
<CustomObject>
    <description>It will hold the value of Wish Child, Wish Info and Wish Family values.</description>
    <label>Wish Paperwork Packet</label>
    <nameField>
        <displayFormat>WC-{00}</displayFormat>
        <label>Wish Child Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Paperwork Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DocusignRecipientTrigger_AT_Test.cls
/*****************************************************************************************************************
Author      : MST Solutions
Date        : 11/14/2016
Created By  : Mariyappan Sivathanu.
Description : 
1.This testClass is used to Relationship_AT for Relationship Contact.
2.Create Record for child wishes.
3.Submits parent wish for approval once the required number of volunteers added to the parent wish team.
4.Add parent wish team members to child wish team.
*****************************************************************************************************************/
@isTest
public class DocusignRecipientTrigger_AT_Test {

	static testMethod void dsfsStatusRec() {
		Account chapterAcc = OrientationandTrainingUtil.createchapterAccount();
		insert chapterAcc;

		Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
		insert wishChild;

		Case caseRec = OrientationandTrainingUtil.CreateParentCase(wishChild.id);
		insert caseRec;

		Contact parentGurdianContact = OrientationandTrainingUtil.CreateWishFamily();
		Contact participantContact = OrientationandTrainingUtil.CreateWishFamilyparticipant();
		insert new List<Contact>{
				parentGurdianContact, participantContact
		};

		Test.startTest();
		npe4__Relationship__c gurdianRelationShipRec = OrientationandTrainingUtil.ParentLegualGuardianRelation(wishChild.Id, parentGurdianContact.Id);
		npe4__Relationship__c participantRelationShipRec = OrientationandTrainingUtil.ParticipantRelationShip(wishChild.Id, participantContact.Id);
		insert new List<npe4__Relationship__c>{
				gurdianRelationShipRec, participantRelationShipRec
		};

		Contact volunterCon = OrientationandTrainingUtil.createVolunteerContact(chapterAcc.id);
		Contact volunterConTwo = OrientationandTrainingUtil.createVolunteerContactwithOtherPhone(chapterAcc.id);
		insert new List<Contact>{
				volunterCon, volunterConTwo
		};

		RecursiveTriggerHandler.blockBeforeUpdate = true;
		case wish = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
		insert wish;
		case wishDetermination = OrientationandTrainingUtil.childWishWithConChapter(wish.Id);
		insert wishDetermination;

		CaseTeamRole roleRec = [
				SELECT Id
				FROM CaseTeamRole
				WHERE Name = 'Wish Granter'
				LIMIT 1
		];
		CaseTeamMember caseTeamMeber = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterCon.id, roleRec.id);
		CaseTeamMember caseTeamMebertwo = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterConTwo.id, roleRec.id);
		insert new List<CaseTeamMember>{
				caseTeamMeber, caseTeamMebertwo
		};

		List<Wish_Child_Form__c> wishChildFormIns = OrientationandTrainingUtil.createWishChildForm(wish.id, wishChild, parentGurdianContact, participantContact);
		insert wishChildFormIns;

		npe4__Relationship__c npe4Rec = OrientationandTrainingUtil.relationshipChild(parentGurdianContact.Id, wishChild.Id);
		insert npe4Rec;

		dsfs__DocuSign_Status__c dsfsStatus = OrientationandTrainingUtil.createDocusignStatuswithCase(caseRec.id);
		insert dsfsStatus;
		dsfs__DocuSign_Status__c updatedsfsSubJect = new dsfs__DocuSign_Status__c();
		updatedsfsSubJect.Id = dsfsStatus.Id;
		updatedsfsSubJect.dsfs__Subject__c = 'Signature Required - Wish Form & Liability And Publicity Release Form';
		update updatedsfsSubJect;
		Test.StopTest();
		dsfs__DocuSign_Recipient_Status__c dsfsRecipient = OrientationandTrainingUtil.CreatedsfsRec(dsfsStatus.Id);
		insert dsfsRecipient;

		system.AssertEquals(dsfsRecipient.dsfs__Recipient_Status__c, 'Completed');
	}

	static testMethod void dsfsStatusRecWithName() {

		Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
		insert chapterAccount;
		Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
		Contact parentGurdianContact = OrientationandTrainingUtil.CreateWishFamily();
		Contact participantContact = OrientationandTrainingUtil.CreateWishFamilyparticipant();
		Contact volunterCon = OrientationandTrainingUtil.createVolunteerContact(chapterAccount.id);
		Contact volunterConTwo = OrientationandTrainingUtil.createVolunteerContactwithOtherPhone(chapterAccount.id);
		insert new List<Contact>{
				wishChild, parentGurdianContact, participantContact, volunterCon, volunterConTwo
		};
		Case caseRec = OrientationandTrainingUtil.CreateParentCase(wishChild.id);
		insert caseRec;
		Test.startTest();
		npe4__Relationship__c gurdianRelationShipRec = OrientationandTrainingUtil.ParentLegualGuardianRelation(wishChild.Id, parentGurdianContact.Id);
		npe4__Relationship__c participantRelationShipRec = OrientationandTrainingUtil.ParticipantRelationShip(wishChild.Id, participantContact.Id);
		insert new List<npe4__Relationship__c>{
				gurdianRelationShipRec, participantRelationShipRec
		};
		RecursiveTriggerHandler.blockBeforeUpdate = true;
		case wish = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
		case wishDetermination = OrientationandTrainingUtil.childWishWithConChapter(wish.Id);
		insert new List<Case>{
				wish, wishDetermination
		};
		CaseTeamRole roleRec = [
				SELECT Id
				FROM CaseTeamRole
				WHERE Name = 'Wish Granter'
				LIMIT 1
		];
		CaseTeamMember caseTeamMeber = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterCon.id, roleRec.id);
		CaseTeamMember caseTeamMebertwo = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterConTwo.id, roleRec.id);
		insert new List<CaseTeamMember>{
				caseTeamMeber, caseTeamMebertwo
		};
		List<Wish_Child_Form__c> wishChildFormIns = OrientationandTrainingUtil.createWishChildForm(wish.id, wishChild, parentGurdianContact, participantContact);
		insert wishChildFormIns;
		npe4__Relationship__c npe4Rec = OrientationandTrainingUtil.relationshipChild(parentGurdianContact.Id, wishChild.Id);
		insert npe4Rec;
		dsfs__DocuSign_Status__c dsfsStatus = OrientationandTrainingUtil.createDocusignStatuswithCase(caseRec.id);
		insert dsfsStatus;
		Attachment newAttachment = OrientationandTrainingUtil.CreateAttachmentRecordWishChild(dsfsStatus.Id);
		insert newAttachment;

		dsfs__DocuSign_Recipient_Status__c dsfsRecipient = OrientationandTrainingUtil.CreatedsfsRecAsDeliver(dsfsStatus.Id);
		insert dsfsRecipient;

		dsfs__DocuSign_Recipient_Status__c updateRecipienttoComplete = new dsfs__DocuSign_Recipient_Status__c();
		updateRecipienttoComplete.Id = dsfsRecipient.Id;
		updateRecipienttoComplete .dsfs__Recipient_Status__c = 'Completed';
		update updateRecipienttoComplete;

		dsfs__DocuSign_Recipient_Status__c dsfsRecipientRec = OrientationandTrainingUtil.CreatedsfsRecAsDeliverRecord(dsfsStatus.Id);
        insert dsfsRecipientRec;

		dsfs__DocuSign_Recipient_Status__c updateRecipienttodelivered = new dsfs__DocuSign_Recipient_Status__c();
		updateRecipienttodelivered.Id = dsfsRecipientRec.Id;
		updateRecipienttodelivered.dsfs__Recipient_Status__c = 'Completed';
		update updateRecipienttodelivered;
		Test.StopTest();

		system.AssertEquals(updateRecipienttoComplete.dsfs__Recipient_Status__c, 'Completed');
	}

	/*  static testMethod void dsfsStatusRecwithLiability(){
		  Contact contactWishChild =   OrientationandTrainingUtil.CreateWishChild();
		  Case caseRec = OrientationandTrainingUtil.CreateParentCase(contactWishChild.id);
		  Account chapterAcc = OrientationandTrainingUtil.createchapterAccount();
		  Contact parentGurdianContact =  OrientationandTrainingUtil.CreateWishFamily();
		  Contact participantContact =  OrientationandTrainingUtil.CreateWishFamilyparticipant();
		  Test.startTest();
		  npe4__Relationship__c gurdianRelationShipRec = OrientationandTrainingUtil.ParentLegualGuardianRelation(contactWishChild.Id,parentGurdianContact.Id);
		  npe4__Relationship__c participantRelationShipRec = OrientationandTrainingUtil.ParticipantRelationShip(contactWishChild.Id,participantContact.Id);
		  Contact volunterCon = OrientationandTrainingUtil.createVolunteerContact(chapterAcc.id);
		  Contact volunterConTwo = OrientationandTrainingUtil.createVolunteerContactwithOtherPhone(chapterAcc.id);
		  RecursiveTriggerHandler.blockBeforeUpdate = true;
		  case wish = OrientationandTrainingUtil.CreateParentCase(contactWishChild.Id);
		  case wishDetermination = OrientationandTrainingUtil.childWishWithConChapter(wish.Id);
		  insert wishDetermination;


		  CaseTeamRole roleRec = [SELECT Id FROM CaseTeamRole WHERE Name = 'Wish Granter' LIMIT 1];
		  CaseTeamMember caseTeamMeber = OrientationandTrainingUtil.createCaseTeamMember(wish.id,volunterCon.id,roleRec.id);
		  CaseTeamMember caseTeamMebertwo = OrientationandTrainingUtil.createCaseTeamMember(wish.id,volunterConTwo.id,roleRec.id);
		  List<Wish_Child_Form__c> wishChildFormIns = OrientationandTrainingUtil.createWishChildForm(wish.id,contactWishChild,parentGurdianContact,participantContact);
		  insert  wishChildFormIns;

		  npe4__Relationship__c  npe4Rec = OrientationandTrainingUtil.relationshipChild(parentGurdianContact.Id,contactWishChild.Id);
		  dsfs__DocuSign_Status__c dsfsStatus = OrientationandTrainingUtil.createDocusignStatuswithCase(caseRec.id);
		//  dsfs__DocuSign_Recipient_Status__c dsfsRecipient = OrientationandTrainingUtil.CreatedsfsRec(dsfsStatus.Id);
		  dsfs__DocuSign_Recipient_Status__c dsfsRecipientsec = OrientationandTrainingUtil.CreatedsfsReccompleted(dsfsStatus.Id);
	   //   system.AssertEquals(dsfsRecipient.dsfs__Recipient_Status__c,'Completed');
		  Test.StopTest();
	  }*/

	//this is used to increase the code coveraage of Signature Required - Wish Form & Liability And Publicity Release Form
	static testMethod void dsfsWishForm() {
		Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
		Case caseRec = OrientationandTrainingUtil.CreateParentCase(wishChild.id);
		Account chapterAcc = OrientationandTrainingUtil.createchapterAccount();
		Contact parentGurdianContact = OrientationandTrainingUtil.CreateWishFamily();
		Contact participantContact = OrientationandTrainingUtil.CreateWishFamilyparticipant();
		Test.startTest();
		npe4__Relationship__c gurdianRelationShipRec = OrientationandTrainingUtil.ParentLegualGuardianRelation(wishChild.Id, parentGurdianContact.Id);
		npe4__Relationship__c participantRelationShipRec = OrientationandTrainingUtil.ParticipantRelationShip(wishChild.Id, participantContact.Id);
		Contact volunterCon = OrientationandTrainingUtil.createVolunteerContact(chapterAcc.id);
		Contact volunterConTwo = OrientationandTrainingUtil.createVolunteerContactwithOtherPhone(chapterAcc.id);
		RecursiveTriggerHandler.blockBeforeUpdate = true;
		case wish = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
		case wishDetermination = OrientationandTrainingUtil.childWishWithConChapter(wish.Id);
		insert wishDetermination;
		CaseTeamRole roleRec = [
				SELECT Id
				FROM CaseTeamRole
				WHERE Name = 'Wish Granter'
				LIMIT 1
		];
		CaseTeamMember caseTeamMeber = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterCon.id, roleRec.id);
		CaseTeamMember caseTeamMebertwo = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterConTwo.id, roleRec.id);
		List<Wish_Child_Form__c> wishChildFormIns = OrientationandTrainingUtil.createWishChildForm(wish.id, wishChild, parentGurdianContact, participantContact);
		insert wishChildFormIns;

		npe4__Relationship__c npe4Rec = OrientationandTrainingUtil.relationshipChild(parentGurdianContact.Id, wishChild.Id);
		// dsfs__DocuSign_Status__c dsfsStatus = OrientationandTrainingUtil.createDocusignStatuswithCase(caseRec.id);
		dsfs__DocuSign_Status__c dsfsStatus = NEW dsfs__DocuSign_Status__c();
		dsfsStatus .dsfs__DocuSign_Envelope_ID__c = '0204C9DD-B8B3-4D7D-B9C5-F88B921E1511';
		dsfsStatus .dsfs__Case__c = caseRec.Id;
		dsfsStatus .isConflict__c = false;
		dsfsStatus .dsfs__Envelope_Status__c = 'Sent';
		dsfsStatus .dsfs__Subject__c = 'Signature Required - Wish Form & Liability And Publicity Release Form';
		insert dsfsStatus ;
		Attachment newAttachment = OrientationandTrainingUtil.CreateAttachmentRecordWishChild(dsfsStatus .Id);
		insert newAttachment;
		dsfs__DocuSign_Recipient_Status__c dsfsRecipient = OrientationandTrainingUtil.CreatedsfsRecAsDeliver(dsfsStatus.Id);
		insert dsfsRecipient;
		dsfs__DocuSign_Recipient_Status__c updateRecipienttoComplete = new dsfs__DocuSign_Recipient_Status__c();
		updateRecipienttoComplete.Id = dsfsRecipient.Id;
		updateRecipienttoComplete .dsfs__Recipient_Status__c = 'Completed';
		update updateRecipienttoComplete;

		dsfs__DocuSign_Recipient_Status__c dsfsRecipientRec = OrientationandTrainingUtil.CreatedsfsRecAsDeliverRecord(dsfsStatus.Id);
		insert dsfsRecipientRec;

		dsfs__DocuSign_Recipient_Status__c updateRecipienttodelivered = new dsfs__DocuSign_Recipient_Status__c();
		updateRecipienttodelivered.Id = dsfsRecipientRec.Id;
		updateRecipienttodelivered.dsfs__Recipient_Status__c = 'Completed';
		update updateRecipienttodelivered;

		system.AssertEquals(updateRecipienttoComplete.dsfs__Recipient_Status__c, 'Completed');
		Test.StopTest();
	}

	//this is used to increase the code coveraage of Signature Required - Wish Form & Liability And Publicity Release Form
	static testMethod void dsfsWishFormWithoutContactName() {
		Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
		Case caseRec = OrientationandTrainingUtil.CreateParentCase(wishChild.id);
		Account chapterAcc = OrientationandTrainingUtil.createchapterAccount();
		Contact parentGurdianContact = OrientationandTrainingUtil.CreateWishFamily();
		Contact participantContact = OrientationandTrainingUtil.CreateWishFamilyparticipant();
		Test.startTest();
		npe4__Relationship__c gurdianRelationShipRec = OrientationandTrainingUtil.ParentLegualGuardianRelation(wishChild.Id, parentGurdianContact.Id);
		npe4__Relationship__c participantRelationShipRec = OrientationandTrainingUtil.ParticipantRelationShip(wishChild.Id, participantContact.Id);
		Contact volunterCon = OrientationandTrainingUtil.createVolunteerContact(chapterAcc.id);
		Contact volunterConTwo = OrientationandTrainingUtil.createVolunteerContactwithOtherPhone(chapterAcc.id);
		RecursiveTriggerHandler.blockBeforeUpdate = true;
		case wish = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
		case wishDetermination = OrientationandTrainingUtil.childWishWithConChapter(wish.Id);
		insert wishDetermination;
		CaseTeamRole roleRec = [
				SELECT Id
				FROM CaseTeamRole
				WHERE Name = 'Wish Granter'
				LIMIT 1
		];
		CaseTeamMember caseTeamMeber = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterCon.id, roleRec.id);
		CaseTeamMember caseTeamMebertwo = OrientationandTrainingUtil.createCaseTeamMember(wish.id, volunterConTwo.id, roleRec.id);
		List<Wish_Child_Form__c> wishChildFormIns = OrientationandTrainingUtil.createWishChildForm(wish.id, wishChild, parentGurdianContact, participantContact);
		insert wishChildFormIns;
		npe4__Relationship__c npe4Rec = OrientationandTrainingUtil.relationshipChild(parentGurdianContact.Id, wishChild.Id);
		// dsfs__DocuSign_Status__c dsfsStatus = OrientationandTrainingUtil.createDocusignStatuswithCase(caseRec.id);
		dsfs__DocuSign_Status__c dsfsStatus = NEW dsfs__DocuSign_Status__c();
		dsfsStatus .dsfs__DocuSign_Envelope_ID__c = '0204C9DD-B8B3-4D7D-B9C5-F88B921E1511';
		dsfsStatus .dsfs__Case__c = caseRec.Id;
		dsfsStatus .isConflict__c = false;
		dsfsStatus .dsfs__Envelope_Status__c = 'Sent';
		dsfsStatus .dsfs__Subject__c = 'Signature Required - Wish Form & Liability And Publicity Release Form';
		insert dsfsStatus ;
		Attachment newAttachment = OrientationandTrainingUtil.CreateAttachmentRecordWishChild(dsfsStatus .Id);
		insert newAttachment;
		dsfs__DocuSign_Recipient_Status__c dsfsRecipient = OrientationandTrainingUtil.CreatedsfsRecAsDeliver(dsfsStatus.Id);
		insert dsfsRecipient;
		dsfs__DocuSign_Recipient_Status__c updateRecipienttoComplete = new dsfs__DocuSign_Recipient_Status__c();
		updateRecipienttoComplete.Id = dsfsRecipient.Id;
		updateRecipienttoComplete .dsfs__Recipient_Status__c = 'Completed';
		update updateRecipienttoComplete;
		dsfs__DocuSign_Recipient_Status__c dsfsRecipientRec = OrientationandTrainingUtil.CreatedsfsRecAsDeliverRecord(dsfsStatus.Id);
		insert dsfsRecipientRec;
		dsfs__DocuSign_Recipient_Status__c updateRecipienttodelivered = new dsfs__DocuSign_Recipient_Status__c();
		updateRecipienttodelivered.Id = dsfsRecipientRec.Id;
		updateRecipienttodelivered.dsfs__Recipient_Status__c = 'Completed';
		update updateRecipienttodelivered;
		system.AssertEquals(updateRecipienttoComplete.dsfs__Recipient_Status__c, 'Completed');
		Test.StopTest();
	}
}