make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ICD_10_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold the ICD-10 code.</description>
        <label>Primary ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Budget__c.object
<CustomObject>
    <description>The Wish Budget captures all anticipated expenses for the Wish.</description>
    <fields>
        <fullName>Budget_Approval_Status__c</fullName>
        <description>This field is populated by the approval process.</description>
        <label>Budget Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Budget_Cash__c</fullName>
        <description>The total of the budgeted Cash values on the related Wish Expenses.</description>
        <label>Budget Cash</label>
        <summarizedField>Wish_Expense__c.Budget_Cash__c</summarizedField>
        <summaryForeignKey>Wish_Expense__c.Wish_Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Budget_In_Kind__c</fullName>
        <description>The total of the budgeted In Kind values on the related Wish Expenses.</description>
        <label>Budget In Kind</label>
        <summarizedField>Wish_Expense__c.Budget_In_Kind__c</summarizedField>
        <summaryForeignKey>Wish_Expense__c.Wish_Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Is_Active_Budget__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Only one budget may be active per wish. Defaults to True as this assumes that whenever a new budget is created, that budget supersedes any older ones.</description>
        <label>Is Active Budget</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wish_Case__c</fullName>
        <label>Wish Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Wish Budget</relationshipLabel>
        <relationshipName>Wish_Budget</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wish Budget</label>
    <nameField>
        <displayFormat>WBN-{0}</displayFormat>
        <label>Wish Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Expense__c.object
<CustomObject>
    <description>This object will be used to store budgeting information</description>
    <fields>
        <fullName>Budget_Approval_Status__c</fullName>
        <description>Deprecated 2019-09-11 as per WLP-477. FLS removed from all profiles. Removed from all custom report types.</description>
        <label>Budget Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Budget_Cash__c</fullName>
        <description>It will capture the $ of Budget Cash information</description>
        <label>Budget Cash</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_In_Kind__c</fullName>
        <description>It will capture the $ of Budget In Kind information</description>
        <label>Budget In Kind</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Wish Case for which these expenses are being incurred.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Wish Expenses</relationshipLabel>
        <relationshipName>Wish_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FE_Posted_Cash__c</fullName>
        <description>It will capture the FE Posted Cash information</description>
        <label>FE Posted Cash</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Projected_Approval_Status__c</fullName>
        <label>Projected Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Projected_Cash__c</fullName>
        <description>It will capture the  Projected Cash</description>
        <label>Projected Cash</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Projected_In_Kind__c</fullName>
        <description>It will capture the Projected budget amount of In Kind</description>
        <label>Projected In Kind</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wish_Budget__c</fullName>
        <description>Looks up to the Wish Budget, which is associated with the Wish Case.</description>
        <label>Wish Budget</label>
        <referenceTo>Wish_Budget__c</referenceTo>
        <relationshipLabel>Wish Expenses</relationshipLabel>
        <relationshipName>Wish_Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Wish Expense</label>
    <nameField>
        <displayFormat>WE-{00000}</displayFormat>
        <label>Wish Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Expenses</pluralLabel>
    <recordTypes>
        <fullName>Finance</fullName>
        <active>true</active>
        <label>Finance</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Wish_BudgetTest.cls
/**
 * @description Wish Budget Test Class
 * @author Mitali Nahar, Traction on Demand
 * @date 8/22/2019
 */
@IsTest
public with sharing class Wish_BudgetTest {

    private final static Id CHAPTER_RECORD_TYPE_ID = Constant_AC.CHAPTER_RT_ID;
    private final static Id WISH_RECORD_TYPE_ID = Constant_AC.WISH_RT_ID;
    private final static Id WISH_FAMILY_RECORD_TYPE_ID = Constant_AC.WISH_FAMILY_RT_ID;
    private final static Id HOUSEHOLD_RECORD_TYPE_ID = Constant_AC.HOUSEHOLD_RT_ID;
    private final static Id WISH_CHILD_RECORD_TYPE_ID = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
    private final static Id MEDICAL_PROF_RECORD_TYPE_ID = Constant_AC.MEDICAL_PROFESSIONAL_RT_ID;

    @TestSetup
    private static void insertTestData() {
        trac_TriggerHandlerBase.blockTrigger = true;

        List<Account> accountsDataFactory = TestDataFactory.createAccount(2);
        accountsDataFactory[0].RecordTypeId = HOUSEHOLD_RECORD_TYPE_ID;
        accountsDataFactory[1].RecordTypeId = CHAPTER_RECORD_TYPE_ID ;
        insert accountsDataFactory;

        ICD_Codes__c obj = new ICD_Codes__c();
        obj.Name = 'Q917';
        insert obj;
        List<Contact> contactsDataFactory = TestDataFactory.createContact(4);
        contactsDataFactory[0].RecordTypeId = WISH_CHILD_RECORD_TYPE_ID;
        contactsDataFactory[0].ICD_10_Code__c = obj.Id;
        contactsDataFactory[1].RecordTypeId = WISH_FAMILY_RECORD_TYPE_ID;
        contactsDataFactory[1].Birthdate = System.today().addYears(-20);
        contactsDataFactory[2].RecordTypeId = MEDICAL_PROF_RECORD_TYPE_ID;
        contactsDataFactory[3].RecordTypeId = WISH_FAMILY_RECORD_TYPE_ID;
        contactsDataFactory[3].Birthdate = System.today().addYears(-10);
        insert contactsDataFactory;

        List<Case> casesDataFactory = TestDataFactory.createCase(1);
        casesDataFactory[0].RecordTypeId = WISH_RECORD_TYPE_ID;
        casesDataFactory[0].ChapterName__c = accountsDataFactory[1].Id;
        casesDataFactory[0].AccountId = accountsDataFactory[0].Id;
        casesDataFactory[0].ContactId = contactsDataFactory[0].Id;
        casesDataFactory[0].Origin = 'Email';
        casesDataFactory[0].Status = 'Qualified';
        insert casesDataFactory;

        List<Wish_Budget__c> wishBudgetList = new List<Wish_Budget__c>();
        for (Wish_Budget__c objBud : TestDataFactory.createWishBudget(5, casesDataFactory[0].Id)) {
            objBud.Is_Active_Budget__c = true;
            wishBudgetList.add(objBud);
        }
        insert wishBudgetList;

        List<Wish_Expense__c> wishExpenseList = TestDataFactory.createWishExpense(1, wishBudgetList[0].Id);
        wishExpenseList[0].Case__c = casesDataFactory[0].Id;
        wishExpenseList[0].FE_Posted_Cash__c = 100;
        wishExpenseList[0].RecordTypeId = Schema.SObjectType.Wish_Expense__c.getRecordTypeInfosByDeveloperName().get('Finance').getRecordTypeId();
        insert wishExpenseList;

        trac_TriggerHandlerBase.blockTrigger = false;
    }

    @IsTest
    public static void deActivateBudgetsTest() {
        Case wishCase = [
                SELECT Id
                FROM Case
                LIMIT 1
        ];
        System.assertEquals(true, wishCase != null);
        Test.startTest();
        List<Wish_Budget__c> wishBudgetList = TestDataFactory.createWishBudget(1, wishCase.Id);
        wishBudgetList[0].Is_Active_Budget__c = true;
        insert wishBudgetList;
        Test.stopTest();
        List<Wish_Budget__c> wishBudgets = [
                SELECT Id, Is_Active_Budget__c
                FROM Wish_Budget__c
                WHERE Id NOT IN :wishBudgetList
        ];
        System.assertEquals(false, wishBudgets[2].Is_Active_Budget__c);
    }

    @IsTest
    public static void updateWishExpenseTest() {
        Case wishCase = [
                SELECT Id
                FROM Case
                LIMIT 1
        ];
        System.assertEquals(true, wishCase != null);
        Test.startTest();
        List<Wish_Budget__c> wishBudgetList = TestDataFactory.createWishBudget(1, wishCase.Id);
        wishBudgetList[0].Is_Active_Budget__c = true;
        insert wishBudgetList;
        Test.stopTest();
        List<Wish_Expense__c> wishExpenses = [
                SELECT Id
                FROM Wish_Expense__c
                WHERE Wish_Budget__c IN :wishBudgetList
        ];
        System.assertEquals(1, wishExpenses.size());
    }

    @IsTest
    public static void updateExpensesToApprovedTest() {
        List<Wish_Expense__c> wishExpenses = [
                SELECT Id,Wish_Budget__r.Budget_Approval_Status__c
                FROM Wish_Expense__c
        ];
        wishExpenses[0].Projected_Cash__c = 0;
        wishExpenses[0].Budget_Cash__c = 100;
        wishExpenses[0].Projected_In_Kind__c = 0;
        wishExpenses[0].Budget_In_Kind__c = 200;
        wishExpenses[0].Projected_Approval_Status__c = 'Submitted';
        update wishExpenses;
        Test.startTest();
        Wish_Budget__c budgets = [
                SELECT Id, Budget_Approval_Status__c
                FROM Wish_Budget__c
                LIMIT 1
        ];
        budgets.Budget_Approval_Status__c = 'Approved';
        update budgets;
        Test.stopTest();
        List<Wish_Expense__c> updatedwishExpenses = [
                SELECT Projected_Cash__c
                FROM Wish_Expense__c
        ];
        System.assertEquals(100, updatedwishExpenses[0].Projected_Cash__c);
    }

    @IsTest
    public static void coverEmptyList() {
        Wish_Budget__c budget = [
                SELECT Id, Budget_Approval_Status__c, Is_Active_Budget__c, Wish_Case__c
                FROM Wish_Budget__c
                LIMIT 1
        ];
        budget.Id = null;
        budget.Is_Active_Budget__c = false;
        insert budget;
    }
}