make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>It holds the name of the Event.</description>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>This Holds the value of event name</description>
        <formula>Non_Wish_Event__r.Event_Name__c</formula>
        <label>Non-WIsh/Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Wish_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It hold the record of each event</description>
        <label>Name</label>
        <referenceTo>Non_Wish_Events__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerActivities_AC_Test.cls
/************************************************************************************
Author : Mst Solutions
Created date: 11/21/2016
Description : This class is used to increase the code coverage for VolunteerActivities_AC
*************************************************************************************/
@isTest
public class VolunteerActivities_AC_Test {
    
    @testSetup static void setup(){  
        Account acc = OrientationandTrainingUtil.createVolunteerAccount();
        Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
        User VolcurrUser = OrientationandTrainingUtil.createActiveVolunteerUser(con.id);
    }
    
    //Wish open activities
    static testMethod void openWishActivities() {
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(parentCase.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Not Started';
        update newTask;
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getOpenActivities();
        }
    }
    
    //Non Wish open activities
    static testMethod void openNonActivities() {
        Constant_AC  constant = new Constant_Ac(); 
        Id nonWishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.nonWishEventRT).getRecordTypeId();
        Id wishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.wishVolunteerOpportunity).getRecordTypeId();
        
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Volunteer_Opportunity__c newWishOpportunity =  new Volunteer_Opportunity__c();
        newWishOpportunity.RecordTypeId = nonWishEvents;
        newWishOpportunity.Wish__c = parentCase.Id;
        insert newWishOpportunity;
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(newWishOpportunity.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Not Started';
        update newTask;
        
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getOpenActivities();
        }
    }
    
    //Non Wish open activities
    static testMethod void openNonWishActivities() {
        Constant_AC  constant = new Constant_Ac(); 
        Id nonWishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.nonWishEventRT).getRecordTypeId();
        Id wishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.wishVolunteerOpportunity).getRecordTypeId();
        
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Non_Wish_Events__c newWishOpportunity =  new Non_Wish_Events__c();
        newWishOpportunity.Event_Name__c = 'Test';
        insert newWishOpportunity;
        Volunteer_Opportunity__c volOpp =  new Volunteer_Opportunity__c();
        volOpp.RecordTypeId = nonWishEvents;
        volOpp.Non_Wish_Event__c = newWishOpportunity.Id;
        insert volOpp;
        
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(volOpp.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Not Started';
        update newTask;
        
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getOpenActivities();
        }
    }
    
    //Non Wish Event Activities
    static testMethod void openNonWishEventActivities() {
        Constant_AC  constant = new Constant_Ac(); 
        Id nonWishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.nonWishEventRT).getRecordTypeId();
        Id wishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.wishVolunteerOpportunity).getRecordTypeId();
        
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Non_Wish_Events__c newWishOpportunity =  new Non_Wish_Events__c();
        newWishOpportunity.Event_Name__c = 'Test';
        insert newWishOpportunity;
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(newWishOpportunity.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Not Started';
        update newTask;
        
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getOpenActivities();
        }
    }
    
    
    
    /* Completed Block */
    static testMethod void openWishActivities1() {
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        parentCase.Presentation_Date__c = System.today();
        update parentCase;
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(parentCase.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Completed';
        update newTask;
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getCloseActivities();
        }
    }
    
    //Non Wish open activities
    static testMethod void openNonActivities1() {
        Constant_AC  constant = new Constant_Ac(); 
        Id nonWishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.nonWishEventRT).getRecordTypeId();
        Id wishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.wishVolunteerOpportunity).getRecordTypeId();
        
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Volunteer_Opportunity__c newWishOpportunity =  new Volunteer_Opportunity__c();
        newWishOpportunity.RecordTypeId = nonWishEvents;
        newWishOpportunity.Wish__c = parentCase.Id;
        insert newWishOpportunity;
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(newWishOpportunity.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Completed';
        update newTask;
        
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getCloseActivities();
        }
    }
    
    //Non Wish open activities
    static testMethod void openNonWishActivities1() {
        Constant_AC  constant = new Constant_Ac(); 
        Id nonWishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.nonWishEventRT).getRecordTypeId();
        Id wishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.wishVolunteerOpportunity).getRecordTypeId();
        
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Non_Wish_Events__c newWishOpportunity =  new Non_Wish_Events__c();
        newWishOpportunity.Event_Name__c = 'Test';
        insert newWishOpportunity;
        Volunteer_Opportunity__c volOpp =  new Volunteer_Opportunity__c();
        volOpp.RecordTypeId = nonWishEvents;
        volOpp.Non_Wish_Event__c = newWishOpportunity.Id;
        insert volOpp;
        
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(volOpp.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Completed';
        update newTask;
        
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getCloseActivities();
        }
    }
    
    //Non Wish Event Activities
    static testMethod void openNonWishEventActivities1() {
        Constant_AC  constant = new Constant_Ac(); 
        Id nonWishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.nonWishEventRT).getRecordTypeId();
        Id wishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.wishVolunteerOpportunity).getRecordTypeId();
        
        User volUser = [SELECT Id, ContactId FROM User WHERE ContactId != null LIMIT 1];
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case parentCase = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        Non_Wish_Events__c newWishOpportunity =  new Non_Wish_Events__c();
        newWishOpportunity.Event_Name__c = 'Test';
        insert newWishOpportunity;
        Task newTask = OrientationandTrainingUtil.wishPresentationNotSet(newWishOpportunity.Id);
        newTask.OwnerId = volUser.Id;
        newTask.Status = 'Completed';
        update newTask;
        
        System.RunAs(volUser) {
            PageReference pageref = Page.VolunteerActivities_VF;
            Test.setCurrentPageReference(pageref);
            VolunteerActivities_AC volunteerWorkitems = new VolunteerActivities_AC();
            volunteerWorkitems.getCloseActivities();
        }
    }
    
    
        
}