make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Hidden_Volunteer_Contact_Email__c</fullName>
        <description>This field is used to store the value of Volunteer contact email for email purpose.</description>
        <label>Hidden Volunteer Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used when the to identify whether the volunteer opportunity is active or not.</description>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_Inactive__c</fullName>
        <description>This field is get the values when the volunteer contact is removed form the volunteer Name field.</description>
        <label>Reason Inactive</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Moved</fullName>
                </value>
                <value>
                    <fullName>Non-responsive</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It indicate different status of the volunteer opportunity.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the  related Case</description>
        <label>Wish</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolOpportunity_OnBefore_Update_Handler.cls
/*****************************************************************************************************************
Author      : MST Solutions
Date        : 5/27/2016
Description : When a new Volunteer Opportunity record updated then it will update the values to corresponding fields.
Modification Log: 
04/17/2018 - Kanagaraj - WVC-1885
*******************************************************************************************************************/

public class VolOpportunity_OnBefore_Update_Handler {

	private final static Id registeredWishRecordTypeId = Constant_AC.REGISTERED_WISH_ID;
	private final static Id registeredNonWishRecordTypeId = Constant_AC.REGISTERED_NON_WISH_ID;
	private final static Id wishVolunteerOpportunityRecordTypeId = Constant_AC.WISH_VOLUNTEER_OPPORTUNITY_ID;
	private final static Id nonWishRecordTypeId = Constant_AC.NON_WISH_EVENT_RT_ID;
	private final static Id wishRecordTypeId = Constant_AC.WISH_RT_ID;

	// This method is used to update the record type and vounteer Opportunity status and wish start date values.
	public static void onBeforeUpdate(Map<Id, Volunteer_Opportunity__c> newMap, Map<Id, Volunteer_Opportunity__c> oldMap) {
		Map<Id, String> volunteerContactMap = new Map<Id, String>();
		Set<Id> volunteerContactIdSet = new Set<Id>();
		Set<Id> dbWishSet = new Set<Id>();
		Set<Id> dbCaseSet = new Set<Id>();
		for (Volunteer_Opportunity__c currRec : newMap.values()) {
			if (currRec.Inactive__c == true && oldMap.get(currRec.Id).Inactive__c == false && currRec.Reason_Inactive__c != null) {
				currRec.Status__c = 'Inactive';
				currRec.Inactivated_or_Rejected_Date__c = Date.today();
			}
			if (currRec.Inactive__c == true && currRec.Status__c == 'Inactive' && currRec.Wish__c != null) {
				currRec.Wish_End_Date__c = Date.today();
			}
			if (currRec.Status__c == 'Pending' && currRec.Status__c != oldMap.get(currRec.Id).Status__c) {
				currRec.Inactivated_or_Rejected_Date__c = Date.today();
			}
			if (currRec.Volunteer_Name__c != null && currRec.Volunteer_Name__c != oldMap.get(currRec.Id).Volunteer_Name__c) {
				volunteerContactIdSet.add(currRec.Volunteer_Name__c);
			}
			if (currRec.Reason_Inactive__c != null) {
				currRec.Inactive__c = true;
			}
			if (currRec.RecordTypeId == wishVolunteerOpportunityRecordTypeId && currRec.Status__c == 'Approved'
					&& oldMap.get(currRec.Id).Status__c != currRec.Status__c && currRec.Wish__c != null) {
				currRec.RecordTypeId = registeredWishRecordTypeId;
				dbWishSet.add(currRec.Wish__c);
			}
			if (currRec.RecordTypeId == nonWishRecordTypeId && currRec.Status__c == 'Approved') {
				currRec.RecordTypeId = registeredNonWishRecordTypeId;

			}
			if (currRec.Status__c == 'Approved' && oldMap.get(currRec.Id).Status__c == 'Pending') {
				currRec.Inactivated_or_Rejected_Date__c = null;
			}
		}

		if (volunteerContactIdSet.size() > 0) {
			for (Contact volunteerContact : [
					SELECT Id,Email
					FROM Contact
					WHERE Id IN:volunteerContactIdSet
			]) {
				volunteerContactMap.put(volunteerContact.Id, volunteerContact.Email);
			}
		}
		if (dbWishSet.size() > 0) {
			for (Case dbCase : [
					SELECT Id,Status,RecordTypeId,IsClosed
					FROM Case
					WHERE Status != 'Granted'
					AND RecordTypeId = :wishRecordTypeId
					AND Id IN:dbWishSet
			]) {
				if (dbCase.IsClosed == false) {
					dbCaseSet.add(dbCase.Id);
				}
			}
		}
		if (volunteerContactMap.size() > 0 || dbCaseSet.size() > 0) {
			for (Volunteer_Opportunity__c currRec : newMap.values()) {
				if (currRec.Volunteer_Name__c != null && volunteerContactMap.containsKey(currRec.Volunteer_Name__c)) {
					currRec.Hidden_Volunteer_Contact_Email__c = volunteerContactMap.get(currRec.Volunteer_Name__c);
				}
				if (dbCaseSet.contains(currRec .Wish__c)) {
					currRec.Wish_Start_Date__c = System.today();
				}
			}
		}
	}
}