make-a-wish-salesforce/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Bringing_Own_Wheel_Chair__c</fullName>
        <description>It defines, participants who bring their own wheel chair.</description>
        <label>Bringing Own Wheel Chair</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <businessProcess>Parent Wish Support process</businessProcess>
        <description>It will display the child and  parent related information.</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <description>It will have Wish Child&apos;s Medical Condition details</description>
        <label>Primary Diagnosis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>It will hold the gender information.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Self-describe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>It will hold the value of middle name.</description>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race_Ethnicity__c</fullName>
        <description>It will be used for statistical purpose</description>
        <label>Race/Ethnicity</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaska Native</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian/Other Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>Not Reported</fullName>
                </value>
                <value>
                    <fullName>White or Caucasian</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_Shirt_Size__c</fullName>
        <description>It will capture the wish child T.Shirt size</description>
        <label>T-Shirt Size</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Child_Form__c.object
<CustomObject>
    <description>It will hold the value of Wish Child, Wish Info and Wish Family values.</description>
    <fields>
        <fullName>Availability_Time_Period_1__c</fullName>
        <label>Availability Time Period 1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Availability_Time_Period_2__c</fullName>
        <label>Availability Time Period 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Availability_Time_Period_3__c</fullName>
        <label>Availability Time Period 3</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bringing_Own_Wheel_Chair__c</fullName>
        <label>Bringing_Own_Wheel_Chair</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Case_Team_Member1__c</fullName>
        <description>It holds the updated case team member details.</description>
        <label>Case Team Member1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Team_Member2__c</fullName>
        <description>It will hold the updated Case Team Member details.</description>
        <label>Case Team Member2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It lookup to case record</description>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wish</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipName>Wish_Child_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <description>Wish child&apos;s medical condition</description>
        <label>Diagnosis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Driver_Details__c</fullName>
        <label>Driver Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Wish Child gender</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>I choose not to self-identify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hidden_Contact_Name__c</fullName>
        <description>This field is used to the contacts who are all signed the docusign document.</description>
        <label>Hidden Contact Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hidden_Same_as_Family__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hidden Same as Family</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hidden_Wish_Fmaily_Contact_Email__c</fullName>
        <description>This field is used to store the wish family contact name and email address from the wish family form.</description>
        <label>Hidden Wish Fmaily Contact Email</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hidden_Wish_Fmaily_Contact_Name__c</fullName>
        <description>This field is used to store the wish family contact name from wish child from.</description>
        <label>Hidden Wish Fmaily Contact Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Medication_require_refrigeration_name__c</fullName>
        <label>Medication_require_refrigeration_name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>Wish Child Middle Name</description>
        <label>Middle Name</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_wheelchair_collapsible__c</fullName>
        <label>Name_of_wheelchair_collapsible</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Names_for_receiving_nursing_care__c</fullName>
        <label>Names_for_receiving_nursing_care</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pariticipant_name_havingWheelchair_Power__c</fullName>
        <label>Pariticipant_name_havingWheelchair_Power</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Participant_Contacts__c</fullName>
        <label>Participant Contacts</label>
        <length>131000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Participant_Name__c</fullName>
        <description>This field is used to store the participant name with out their email address.</description>
        <label>Participant Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Participant_Name_for_Dietary_Restriction__c</fullName>
        <label>Participant_Name_for_Dietary_Restriction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Race_Ethnicity__c</fullName>
        <label>Race/Ethnicity</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaska Native</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian/Other Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>White or Caucasian</fullName>
                </value>
                <value>
                    <fullName>Middle Eastern</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>Hispanic, Latino or Spanish</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Participant_Name_forWheelchair__c</fullName>
        <label>Requested_Participant_Name_forWheelchair</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Requested_Participant_Name_for_Allergies__c</fullName>
        <label>Requested_Participant_Name_for_Allergies</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Requested_Participant_Name_for_OtherNeed__c</fullName>
        <label>Requested_Participant_Name_for_OtherNeed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Requested_Participant_Name_for_Oxygen__c</fullName>
        <label>Requested_Participant_Name_for_Oxygen</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>T_Shirt_Size__c</fullName>
        <description>Wish Child T-Shirt Size</description>
        <label>T-Shirt Size</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wish_Family_Contact__c</fullName>
        <label>Wish Family Contact</label>
        <length>131000</length>
        <type>Html</type>
    </fields>
    <label>Wish Paperwork Packet</label>
    <nameField>
        <displayFormat>WC-{00}</displayFormat>
        <label>Wish Child Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Paperwork Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/SignNow_AC.cls
/******************************************************************************************************************
Created by: Kanagaraj
Author : MST Solutions
CreateDate : 06/01/2016
Description : This SignNow_AC class is used to featch all the details given in the wish child form, 
wish family form and wish information form to display when the user sign the document usign electronic signature.
******************************************************************************************************************/
public Class SignNow_AC{
    public Contact currWishChildContact{get;set;}
    public WishChildFormUtil wcfUtil{get;set;}
    public Case currCase{get;set;}
    public Wish_Child_Form__c currWishChild{get;set;}
    public Id currentPageId;
    public Boolean isChildPart = false;
    public Boolean isParticipants {get;set;}
    public string queryString {get;set;}   
    public Map<string,string> wrapperClsMap {get;set;}  
    public Map<id,Wish_Child_Form__c> clonedMap{get;set;}
    public Map<id,Wish_Child_Form__c> objMap{get;set;}
    public List<String> ethnicityList{get;set;}
    public String Name{get;set;}
    public String participantsName{get;set;} 
    
    /*********************************************************************************************************
SignNow_AC this is the construcotr method it will load when the user trying to get electronic signature.
**********************************************************************************************************/
    public SignNow_AC(Apexpages.StandardController controller){
        currentPageId =  ApexPages.currentPage().getParameters().get('id');
        isChildPart = false ;
        isParticipants  = false;    
        if(wcfUtil == null)   
            wcfUtil = new WishChildFormUtil();
        ethnicityList = new List<String>();
        Name = '';
        currentPageId =  ApexPages.currentPage().getParameters().get('id');
        
        if(currentPageId != null){
            
            this.currCase = (Case)controller.getRecord();
            currWishChild = new Wish_Child_Form__c();  
            
            this.currCase = [SELECT id,Hidden_Email_List__c,ContactId,Contact.FirstName,Contact.LastName,Contact.Name,Contact.Middle_Name__c,
                             Contact.Diagnosis__c , Contact.Email, Contact.MobilePhone, Contact.Gender__C,
                             Contact.BirthDate, Contact.T_Shirt_Size__c, Contact.MailingStreet,
                             Contact.MailingCity, Contact.MailingState, Contact.MailingPostalCode
                             FROM Case WHERE Id = :this.currCase.id limit 1];
            
            List<CaseTeamMember> caseTeamMemberList = [SELECT id,Member.Name FROM CaseTeamMember WHERE ParentId =: this.currCase.id AND TeamRole.Name = 'Wish Granter' limit 2];
            if(caseTeamMemberList.size() > 0){
                wcfUtil.caseTeamMemberNo1 = caseTeamMemberList[0].Member.Name;
                if(caseTeamMemberList.size() > 1)
                    wcfUtil.caseTeamMemberNo2 = caseTeamMemberList[1].Member.Name;
            }
            
            //build wish child list
            if(this.currCase.Id != null){
                String caseId = this.currCase.id;
                String wishChildQuery = 'SELECT ';
                for(Schema.FieldSetMember f : wcfUtil.getWishChildFields()) {
                    wishChildQuery+= f.getFieldPath() + ', ';
                }
                wishChildQuery = WishchildQuery.removeEnd(', ');
                wishChildQuery+= ' from Wish_Child_Form__c' + ' WHERE Case__c = :'+'caseId'+ ' lIMIT 1';
                wcfUtil.wishChildList = Database.Query(wishChildQuery);
            }  
            //Build wishChild for SignNow List
            for(Wish_Child_Form__c wishChildForm : [SELECT Id,Name,Case__c,Hidden_Same_as_Family__c,ParentsParticipantsName__c ,Race_Ethnicity__c,Hidden_Contact_Name__c,Hidden_Wish_Fmaily_Contact_Email__c,Hidden_Wish_Fmaily_Contact_Name__c,Participant_Name__c FROM Wish_Child_Form__c WHERE
                                                    Case__c =: currentPageId]){
                                                        
                                                        if(wishChildForm.Hidden_Wish_Fmaily_Contact_Name__c != null) {  
                                                            for(String keys : wishChildForm.Hidden_Wish_Fmaily_Contact_Name__c.split('#')){
                                                                wcfUtil.SignNowList.add(keys.trim());
                                                                // wcfUtil.listofSenderName.add(keys.trim());
                                                                if(Name == '' || Name == Null)
                                                                    Name = keys;
                                                                else
                                                                    Name +=','+' '+Keys; 
                                                            } 
                                                            
                                                        }
                                                        if(wishChildForm.ParentsParticipantsName__c != null) {  
                                                            participantsName = wishChildForm.ParentsParticipantsName__c;
                                                            if(wishChildForm.ParentsParticipantsName__c.startsWith(',')){
                                                                participantsName = wishChildForm.ParentsParticipantsName__c.removeStart(',');
                                                            }
                                                            
                                                            if(wishChildForm.ParentsParticipantsName__c.startsWith('null')){
                                                                participantsName = wishChildForm.ParentsParticipantsName__c.removeStartIgnoreCase('null');
                                                            }
                                                            
                                                        }
                                                        if(wishChildForm.Participant_Name__c != Null){
                                                            for(String keys : wishChildForm.Participant_Name__c .split('#')){
                                                                if(Name == '' || Name == Null)
                                                                    Name = keys;
                                                                else
                                                                    Name +=','+' '+Keys; 
                                                            }
                                                        }
                                                        
                                                        if(wishChildForm.Hidden_Wish_Fmaily_Contact_Email__c!= Null){
                                                            List<String> proceessList = new List<String>();
                                                            for(String key : wishChildForm.Hidden_Wish_Fmaily_Contact_Email__c.split('#')){
                                                                proceessList.clear();
                                                                if(key.contains('::')){
                                                                    for(String sla : key.split('::')) {
                                                                        proceessList.add(sla);
                                                                    }
                                                                    if(proceessList.size() == 2 && key.contains('::')) {
                                                                        String name = key.split('::')[0];
                                                                        String email = key.split('::')[1];
                                                                        wcfUtil.listofSenderName.add(name.trim());
                                                                    }
                                                                }
                                                            } 
                                                        }  
                                                        
                                                        system.debug('$$$$ SignNow List $$$$$'+wcfUtil.SignNowList);                
                                                        //setting same as family from table
                                                        if( wishChildForm.Hidden_Same_as_Family__c ){
                                                            wcfUtil.sameParentGuardian = true;
                                                        }else{
                                                            wcfUtil.sameParentGuardian = false;
                                                        }
                                                        
                                                        if(wishChildForm.Race_Ethnicity__c != Null){
                                                            for(String mwa: wishChildForm.Race_Ethnicity__c .split(';'))
                                                            {
                                                                ethnicityList.add(mwa);
                                                            }
                                                        }
                                                    }
            
            if(wcfUtil.wishChildList.size() == 0){          
                //init(); 
            }
            else{
                currWishChild = wcfUtil.wishChildList[0]; 
                if(currWishChild.Case_Team_Member1__c != null)
                    wcfUtil.caseTeamMemberNo1 =  currWishChild.Case_Team_Member1__c;
                if(currWishChild.Case_Team_Member2__c != null)
                    wcfUtil.caseTeamMemberNo2 = currWishChild.Case_Team_Member2__c;  
                
                // Wish Family Parser--------------------------------------------- 
                if(currWishChild.Wish_Family_Contact__c != null){
                    String jsonString = currWishChild.Wish_Family_Contact__c;
                    
                    jsonString = jsonString.replace('&quot;', '"');
                    jsonString = jsonString.replace('&amp;', '&');
                    jsonString = jsonString.replace('&#39;', '\'');
                    
                    List<WishChildFormUtil.WrapperClass> wrapFamilyList = (List<WishChildFormUtil.WrapperClass>) System.JSON.deserialize(jsonString, List<WishChildFormUtil.WrapperClass>.class);
                    
                    for(WishChildFormUtil.WrapperClass  currRec : wrapFamilyList){
                        WishChildFormUtil.WrapperClass wrapCls;
                        if(wrapCls == null ){ 
                            wrapCls = new WishChildFormUtil.WrapperClass();
                        }
                        System.debug(wrapCls.sameParentGuardianFlag);
                        wrapCls.FirstName = (currRec.FirstName!=Null)?currRec.FirstName:'';
                        wrapCls.MiddleName = (currRec.MiddleName!=Null)?currRec.MiddleName:'';
                        wrapCls.lastName = (currRec.lastName!=Null)?currRec.lastName:'';
                        wrapCls.Relationship = (currRec.Relationship!=Null)?currRec.Relationship:'';
                        wrapCls.homeTelephone =  (currRec.homeTelephone!=Null)?currRec.homeTelephone:'';
                        wrapCls.workTelephone =  (currRec.workTelephone!=Null)?currRec.workTelephone:'';
                        wrapCls.mobileTelephone = (currRec.mobileTelephone!=Null)?currRec.mobileTelephone:'';
                        wrapCls.Email =  (currRec.Email!=Null)?currRec.Email:'';
                        wrapCls.City = (currRec.City!=Null)?currRec.City:'';
                        wrapCls.Street= (currRec.Street!=Null)?currRec.Street:'';
                        wrapCls.State= (currRec.State!=Null)?currRec.State:'';
                        wrapCls.PostalCode= (currRec.PostalCode!=Null)?currRec.PostalCode:'';
                        wrapCls.tshirtSize= (currRec.tshirtSize!=Null)?currRec.tshirtSize:'';
                        if(currRec.sameParentGuardianFlag == true)
                            wrapCls.sameParentGuardianFlag = true;
                        else
                            wrapCls.sameParentGuardianFlag = false;
                        wrapCls.residingWishMedical = (currRec.residingWishMedical !=Null)?currRec.residingWishMedical:'';
                        wcfUtil.emailMap.put((wrapCls.FirstName+' '+wrapCls.LastName),wrapCls.Email);
                        wrapCls.dob=  (currRec.dob);
                        wrapCls.relId = currRec.relId;
                        wcfUtil.wishFamilyWrapList.add(wrapCls);
                    }
                }
                if(currWishChild.Driver_Details__c != null){
                    String jsonString = currWishChild.Driver_Details__c;
                    jsonString = jsonString.replace('&quot;', '"');
                    jsonString = jsonString.replace('&amp;', '&');
                    jsonString = jsonString.replace('&#39;', '\'');
                    List<WishChildFormUtil.DriverWrapper> wrapDriverList = (List<WishChildFormUtil.DriverWrapper>) System.JSON.deserialize(jsonString, List<WishChildFormUtil.DriverWrapper>.class);
                    System.debug('WishChildFormUtil.wrapDriverList: '+wrapDriverList);
                    for(WishChildFormUtil.DriverWrapper currRec : wrapDriverList){
                        WishChildFormUtil.DriverWrapper wrapCls = new WishChildFormUtil.DriverWrapper();
                        wrapCls.driverName  = (currRec.driverName!=Null)?currRec.driverName :'';
                        wrapCls.licenseNum  = (currRec.licenseNum !=Null)?currRec.licenseNum :'';
                        wrapCls.state  = (currRec.state !=Null)?currRec.state :'';
                        wrapCls.expirationDate  = (currRec.expirationDate!=Null)? currRec.expirationDate:Null;
                        wrapCls.type =  (currRec.type!=Null)?currRec.type:'';
                        wcfUtil.driverWrapperCls.add(wrapCls);
                    }
                }
                if(currWishChild.Availability_Time_Period_1__c != null){
                    List<String> currString =  (currWishChild.Availability_Time_Period_1__c).split('/');
                    if(currString.size() > 0)
                        wcfUtil.availableMonth1 = currString[0];
                    if(CurrString.size() > 1)
                        wcfUtil.availableYear1 = currString[1];
                }
                if( currWishChild.Availability_Time_Period_2__c != null){
                    List<String> currString =  (currWishChild.Availability_Time_Period_2__c).split('/');
                    if(currString.size() > 0)
                        wcfUtil.availableMonth2 = currString[0];
                    if(CurrString.size() > 1)
                        wcfUtil.availableYear2 = currString[1];
                }
                if( currWishChild.Availability_Time_Period_3__c != null){
                    List<String> currString =  (currWishChild.Availability_Time_Period_3__c).split('/');
                    if(currString.size() > 0)
                        wcfUtil.availableMonth3 = currString[0];
                    if(CurrString.size() > 1)
                        wcfUtil.availableYear3 = currString[1];
                }  
                if(currWishChild.Participant_Name_for_Dietary_Restriction__c!= null){
                    
                    for(String s : (currWishChild.Participant_Name_for_Dietary_Restriction__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.righttDietaryNameList.add(s);
                        wcfUtil.currrentDietaryNameList.add(s);
                        wcfUtil.dietaryNamesSet.add(s);
                    }
                }
                if(currWishChild.Requested_Participant_Name_forWheelchair__c!= null){
                    for(String s : (currWishChild.Requested_Participant_Name_forWheelchair__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightWCNamesList.add(s);
                        wcfUtil.currentWCNamesList.add(s);
                        wcfUtil.WCNamesSet.add(s);
                    }                  
                }
                if(currWishChild.Requested_Participant_Name_for_OtherNeed__c!= null){
                    for(String s : (currWishChild.Requested_Participant_Name_for_OtherNeed__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.righttOtherNeedsList.add(s);
                        wcfUtil.currentOtherNeedsList.add(s);
                        wcfUtil.OtherNeedsSet.add(s);
                    }
                }
                if(currWishChild.Requested_Participant_Name_for_Oxygen__c!= null){
                    for(String s : (currWishChild.Requested_Participant_Name_for_Oxygen__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightOxygenNamesList.add(s);
                        wcfUtil.currentOxygenNamesList.add(s);
                        wcfUtil.OxygenNamesSet.add(s);
                    }                  
                }
                if(currWishChild.Requested_Participant_Name_for_Allergies__c!= Null){
                    for(String s : (currWishChild.Requested_Participant_Name_for_Allergies__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightAllergyNamesList.add(s);
                        wcfUtil.currentAllergyNamesList.add(s);
                        wcfUtil.AllergyNamesSet.add(s);
                    }                  
                }                  
                if(currWishChild.Bringing_Own_Wheel_Chair__c!= Null){
                    for(String s : (currWishChild.Bringing_Own_Wheel_Chair__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightOwnWheelChairList.add(s);
                        wcfUtil.currentOwnWheelChairList.add(s);
                        wcfUtil.ownWheelChairNamesSet.add(s);
                    }                  
                }                 
                if(currWishChild.Name_of_wheelchair_collapsible__c!= Null){
                    for(String s : (currWishChild.Name_of_wheelchair_collapsible__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightWCCollapsibleList.add(s);
                        wcfUtil.currentWCCollapsibleList.add(s);
                        wcfUtil.WCCollapsiblesSet.add(s);
                    }                  
                }
                if(currWishChild.Pariticipant_name_havingWheelchair_Power__c!= Null){
                    for(String s : (currWishChild.Pariticipant_name_havingWheelchair_Power__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightWCPowerList.add(s);
                        wcfUtil.currentWCPowerList.add(s);
                        wcfUtil.WCPowerNamesSet.add(s);
                    }                  
                }
                if(currWishChild.Medication_require_refrigeration_name__c!= Null) {
                    for(String s : (currWishChild.Medication_require_refrigeration_name__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightMedicationList.add(s);
                        wcfUtil.currentMedicationList.add(s);
                        wcfUtil.MedicationNamesSet.add(s);
                    }                  
                }
                if(currWishChild.Names_for_receiving_nursing_care__c!= Null){
                    for(String s : (currWishChild.Names_for_receiving_nursing_care__c).split(';')){
                        s.removeEnd(';');
                        wcfUtil.rightNursingCareList.add(s);
                        wcfUtil.currentNursingCareList.add(s);
                        wcfUtil.nursingCaresSet.add(s);
                    }                  
                }
                
                if(currWishChild.Participant_Contacts__c != null){  
                    String jsonString = currWishChild.Participant_Contacts__c;
                    jsonString = jsonString.replace('&quot;', '"');
                    jsonString = jsonString.replace('&amp;', '&');
                    jsonString = jsonString.replace('&#39;', '\'');
                    List<WishChildFormUtil.WrapperClass> wrapParticipantsList = (List<WishChildFormUtil.WrapperClass>) System.JSON.deserialize(jsonString, List<WishChildFormUtil.WrapperClass>.class);
                    System.debug('******jsonString:***** '+jsonString);             
                    List<Case> childAsPartList = [SELECT Contact.FirstName,Contact.LastName,Contact.Middle_Name__c,Contact.Email, Contact.MobilePhone,Contact.BirthDate, Contact.T_Shirt_Size__c FROM Case WHERE Id =: this.currCase.id limit 1 ] ;        
                    
                    Integer count = 0;
                    for(WishChildFormUtil.WrapperClass  currRec : wrapParticipantsList){
                        WishChildFormUtil.WrapperClass wrapCls;
                        if(wrapCls == null ){ 
                            wrapCls = new WishChildFormUtil.WrapperClass();
                        }
                        System.debug(wrapCls.sameParentGuardianFlag);
                        wrapCls.FirstName = (currRec.FirstName!=Null)?currRec.FirstName:'';
                        wrapCls.MiddleName = (currRec.MiddleName!=Null)?currRec.MiddleName:'';
                        wrapCls.lastName = (currRec.lastName!=Null)?currRec.lastName:'';
                        wrapCls.Relationship = (currRec.Relationship!=Null)?currRec.Relationship:'';
                        wrapCls.homeTelephone =  (currRec.homeTelephone!=Null)?currRec.homeTelephone:'';
                        wrapCls.workTelephone =  (currRec.workTelephone!=Null)?currRec.workTelephone:'';
                        wrapCls.mobileTelephone = (currRec.mobileTelephone!=Null)?currRec.mobileTelephone:'';
                        wrapCls.Email =  (currRec.Email!=Null)?currRec.Email:'';
                        wrapCls.City = (currRec.City!=Null)?currRec.City:'';
                        wrapCls.Street= (currRec.Street!=Null)?currRec.Street:'';
                        wrapCls.State= (currRec.State!=Null)?currRec.State:'';
                        wrapCls.PostalCode= (currRec.PostalCode!=Null)?currRec.PostalCode:'';
                        wrapCls.residingWishMedical= (currRec.residingWishMedical!=Null)?currRec.residingWishMedical:'';
                        wrapCls.medicalNeeds= (currRec.medicalNeeds!=Null)?currRec.medicalNeeds:'';
                        wrapCls.tshirtSize= (currRec.tshirtSize!=Null)?currRec.tshirtSize:'';
                        wrapCls.sameParentGuardianFlag = false;                         
                        wcfUtil.emailMap.put((wrapCls.FirstName+' '+wrapCls.LastName),wrapCls.Email);
                        wrapCls.dob=  (currRec.dob);
                        wcfUtil.wishParticipantList.add(wrapCls);
                    }
                }                 
            }
            if(wcfUtil.wishFamilyWrapList.size() == 0)
                wcfUtil.wishFamilyWrapList.add(new WishChildFormUtil.WrapperClass());
            if(wcfUtil.wishParticipantList.size() == 0)           
                wcfUtil.wishParticipantList.add(new WishChildFormUtil.WrapperClass()); 
            if(wcfUtil.driverWrapperCls.size() == 0)
                wcfUtil.driverWrapperCls.add(new WishChildFormUtil.DriverWrapper());  
        }      
    }
}