make-a-wish-salesforce/src/objects/cg__CaseFile__c.object
<CustomObject>
    <fields>
        <fullName>File_Path__c</fullName>
        <label>File Path</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>cg__Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Files</relationshipLabel>
        <relationshipName>Case_Files</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>cg__File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case File</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Case File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Minor_Participant__c.object
<CustomObject>
    <fields>
        <fullName>File_Path__c</fullName>
        <description>This field is used to store the file path for an attached document from FormTracker Dashboard page.</description>
        <label>File Path</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Minor Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Minor Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minor Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/CaseFileTriggerHandler_AC.cls
Public class CaseFileTriggerHandler_AC{

    Public static void onAfterUpdate(map<Id,cg__CaseFile__c> newCaseFileMap,map<Id,cg__CaseFile__c> oldcaseFileMap){
        Set<Id> caseIdSet = new Set<Id>();
        Map<String,String> caseFileMap = new Map<String,String>();
        List<Minor_Participant__c> minorParticipantList = new List<Minor_Participant__c>();
        
        for(cg__CaseFile__c newCaseFile : newCaseFileMap.Values()){
             if(newCaseFile.File_Path__c != Null){
                     caseIdSet.add(newCaseFile.cg__Case__c);
                     caseFileMap.put(newCaseFile.cg__File_Name__c,newCaseFile.File_Path__c);
               }
        }
        
        if(caseFileMap.size() > 0){
        CaseFileTriggerHelper_AC.updateFilePath(caseIdSet,caseFileMap);
        }
     }
}