make-a-wish-salesforce/src/objects/cg__CaseFile__c.object
<CustomObject>
    <fields>
        <fullName>cg__Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Files</relationshipLabel>
        <relationshipName>Case_Files</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case File</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Case File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/CaseFile_AT_Test.cls
/*****************************************************************************************************************
Author      : MST Solutions
Date        : 10/26/2016
Description : This class contains test method for CaseFile object
*******************************************************************************************************************/
@isTest
public class CaseFile_AT_Test {
    static testmethod void createCaseFile() {
        Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
        Contact wishChild = OrientationandTrainingUtil.CreateWishChildCon();
        Case newCase = OrientationandTrainingUtil.createParentCase(wishChild.Id);
        cg__CaseFile__c newFileRecord = OrientationandTrainingUtil.createCaseFileRecord(newCase.Id);
        system.AssertEquals(newCase.contactId,wishChild.Id,'Contact Id does not match');
        system.Assert(newCase.Id == newFileRecord.cg__Case__c,'Case Id does not match');
    }
}