make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the role name and chapters assigned for this role.</description>
        <label>Role Name</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ChapterRole_OnBeforeUpdateHandler.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 
Description : ChapterRole_OnBeforeUpdateHandler is used to update the role name when record is get update.
              
              Modification Log
              ------------------
              WVC-1889    Pavithra 07/11/2018
              
*****************************************************************************************************/
Public class ChapterRole_OnBeforeUpdateHandler {
     public static void onBeforeUpdate(List<Chapter_Role__c> newChapterRoleList,Map<Id,Chapter_Role__c> oldChapterRoleMap){
        Set<Id> roleIdSet = new Set<Id>();
        Map<Id,Role__c> roleMap = new Map<Id,Role__c>();
        for(Chapter_Role__c newChapterRole : newChapterRoleList){
            if(newChapterRole.Role_Name__c != Null && newChapterRole.Role_Name__c != oldChapterRoleMap.get(newChapterRole.Id).Role_Name__c){
                roleIdSet.add(newChapterRole.Role_Name__c);
            }
        }
        
        if(roleIdSet.size() > 0)
            ChapterRole_OnBeforeInsertHelper.populateRoleName(roleIdSet,newChapterRoleList);
    }
}