make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the role name and chapters assigned for this role.</description>
        <label>Role Name</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role_O_T__c.object
<CustomObject>
    <description>This is a junction object that would join the Orientation &amp; Training objects and the Roles object.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associate with Chapter Role Object.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipName>O_T_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It will indicate this training is required or not.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Chapter_Role__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <label>Chapter Role O&amp;T</label>
    <nameField>
        <displayFormat>OTR-{000000}</displayFormat>
        <label>O&amp;T Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles O&amp;T</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Class_Offering__c.object
<CustomObject>
    <description>It will hold the Training Date and Time details.</description>
    <fields>
        <fullName>Chapter_Role_O_T__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It associate with Chapter Role O &amp; T.</description>
        <label>Chapter Role O&amp;T</label>
        <referenceTo>Chapter_Role_O_T__c</referenceTo>
        <relationshipName>Class_offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class Offering</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Class offering Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Offerings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Orientation_Training__c.object
<CustomObject>
    <description>It is a junction object for volunteer and Orientation &amp; Training  object. It will capture the volunteer and his completed  training information details</description>
    <fields>
        <fullName>Class_Offering__c</fullName>
        <description>It will hold the training details.</description>
        <label>Class Offering</label>
        <referenceTo>Class_Offering__c</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Volunteer_Attendance__c</fullName>
        <description>It will capture whether the volunteer registered or completed the session</description>
        <label>Volunteer Attendance</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to Volunteer Contact records</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Orientation &amp; Training</label>
    <nameField>
        <displayFormat>VOT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Orientation &amp; Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Migrated_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It will indicate the record is imported from mulesoft or not.</description>
        <label>Migrated Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <description>This field store the role name.</description>
        <formula>Chapter_Role__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will hold the volunteer name and define chapter and role for this volunteer.</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_VolunteerRoleUpdate.cls
/**
 * JIRA: WLP-422
 * Author: Gustavo Mayer
 * Update: Changing the Volunteer_Roles status from 'Trained' to 'Active'
 */
global class batch_VolunteerRoleUpdate implements Database.Batchable<SObject> {

	private final static String VOLUNTEER_ROLE_STATUS_ACTIVE = Constant_AC.VOLUNTEER_ROLE_STATUS_ACTIVE;
	private final static String VOLUNTEER_ROLE_ATTENDANCE_COMPLETED = Constant_AC.VOLUNTEER_ROLE_ATTENDANCE_COMPLETED;
	private final static String VOLUNTEER_ROLE_STATUS_PENDING_TRAINING = Constant_AC.VOLUNTEER_ROLE_STATUS_PENDING_TRAINING;

	global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([
				SELECT Id, Status__c, Volunteer_Name__c, Role_Name__c, Chapter_Role__c
				FROM Volunteer_Roles__c
				WHERE Migrated_Record__c = TRUE
		]);
	}

	global void execute(Database.BatchableContext BC, List<Volunteer_Roles__c> scope) {
		Set<Id> volunteerContactIds = new Set<Id>();
		Map<Id, List<Volunteer_Roles__c>> volunteerRolesMap = new Map<Id, List<Volunteer_Roles__c>>();
		Map<Id, Volunteer_Roles__c> updateVolunteerRole = new Map<Id, Volunteer_Roles__c>();
		Map<Id, Boolean> volunteerTrainingMap = new Map<Id, Boolean>();
		Set<Id> chapterRoleIds = new Set<Id>();
		for (Volunteer_Roles__c volunteerRole : scope) {
			volunteerContactIds.add(volunteerRole.Volunteer_Name__c);
			chapterRoleIds.add(volunteerRole.Chapter_Role__c);
			if (!volunteerRolesMap.containsKey(volunteerRole.Volunteer_Name__c)) {
				volunteerRolesMap.put(volunteerRole.Volunteer_Name__c, new List<Volunteer_Roles__c>{
						volunteerRole
				});
			}
			volunteerRolesMap.get(volunteerRole.Volunteer_Name__c).add(volunteerRole);
		}
		for (Volunteer_Orientation_Training__c volunteerOT : [
				SELECT Id,Class_Offering__c,Class_Offering__r.Chapter_Role_O_T__r.Role_Name__c,
						Volunteer_Attendance__c,Volunteer__c
				FROM Volunteer_Orientation_Training__c
				WHERE Volunteer__c IN :volunteerContactIds
		]) {
			volunteerTrainingMap.put(volunteerOT.Volunteer__c, true);
			if (volunteerRolesMap.containsKey(volunteerOT.Volunteer__c)) {
				for (Volunteer_Roles__c volunteerRole : volunteerRolesMap.get(volunteerOT.Volunteer__c)) {
					Volunteer_Roles__c updateRec = new Volunteer_Roles__c();
					updateRec.Id = volunteerRole.Id;
					if (volunteerOT.Class_Offering__r.Chapter_Role_O_T__r.Role_Name__c == volunteerRole.Role_Name__c) {
						if (VOLUNTEER_ROLE_ATTENDANCE_COMPLETED.equals(volunteerOT.Volunteer_Attendance__c)) {
							updateRec.Status__c = VOLUNTEER_ROLE_STATUS_ACTIVE;
							updateVolunteerRole.put(updateRec.Id, updateRec);
						} else {
							if (updateVolunteerRole.containsKey(updateRec.Id)
									&& updateVolunteerRole.get(updateRec.Id).Status__c != VOLUNTEER_ROLE_STATUS_ACTIVE) {
								updateRec.Status__c = VOLUNTEER_ROLE_STATUS_PENDING_TRAINING;
								updateVolunteerRole.put(updateRec.Id, updateRec);
							} else {
								updateRec.Status__c = VOLUNTEER_ROLE_STATUS_PENDING_TRAINING;
								updateVolunteerRole.put(updateRec.Id, updateRec);
							}
						}
					} else {
						if (updateVolunteerRole.containsKey(updateRec.Id)
								&& updateVolunteerRole.get(updateRec.Id).Status__c != VOLUNTEER_ROLE_STATUS_ACTIVE) {
							updateRec.Status__c = VOLUNTEER_ROLE_STATUS_PENDING_TRAINING;
							updateVolunteerRole.put(updateRec.Id, updateRec);
						} else {
							updateRec.Status__c = VOLUNTEER_ROLE_STATUS_PENDING_TRAINING;
							updateVolunteerRole.put(updateRec.Id, updateRec);
						}
					}
				}
			}
		}
		Set<String> requiredTrainingCO = new Set<String>();
		for (Chapter_Role_O_T__c currCOT : [
				SELECT Id, Chapter_Role__c, Required__c
				FROM Chapter_Role_O_T__c
				WHERE Required__c = TRUE AND Chapter_Role__c IN :chapterRoleIds
		]) {
			requiredTrainingCO.add(currCOT.Chapter_Role__c);
		}

		for (Volunteer_Roles__c currRole : scope) {
			if (currRole.Volunteer_Name__c != null) {
				Volunteer_Roles__c updateRec = new Volunteer_Roles__c();
				updateRec.Id = currRole.Id;
				if (!(volunteerTrainingMap.containsKey(currRole.Volunteer_Name__c))
						&& requiredTrainingCO.contains(currRole.Chapter_Role__c)) {
					updateRec.Status__c = VOLUNTEER_ROLE_STATUS_PENDING_TRAINING;
				} else if (!((volunteerTrainingMap.containsKey(currRole.Volunteer_Name__c))
						&& requiredTrainingCO.contains(currRole.Chapter_Role__c))) {
					updateRec.Status__c = VOLUNTEER_ROLE_STATUS_ACTIVE;
				}
				updateVolunteerRole.put(updateRec.Id, updateRec);
			}
		}
		update updateVolunteerRole.values();
	}

	global void finish(Database.BatchableContext BC) {
	}
}