make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>It will display the role name</description>
        <formula>Chapter_Role_Opportunity__r.Role_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It indicate different status of the volunteer opportunity.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will hold the volunteer name and define chapter and role for this volunteer.</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerOpportunitySelection_AC_Test.cls
@isTest
private class VolunteerOpportunitySelection_AC_Test{

private static testmethod void createVolunterSelection(){
    
        Constant_AC  constant = new Constant_Ac(); 
        Id nonWishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.nonWishEventRT).getRecordTypeId();
        Id wishEvents = Schema.Sobjecttype.Volunteer_Opportunity__c.getRecordTypeInfosByName().get(constant.wishVolunteerOpportunity).getRecordTypeId();
        Account acc = OrientationandTrainingUtil.createVolunteerAccount();
        Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
        OrientationandTrainingUtil.createAffiliation(con.id);
       
        Role__c currRole = OrientationandTrainingUtil.createRole();
        Role__c currNonWishRole = OrientationandTrainingUtil.createNonWishRole();
        Chapter_Role__c  currChapRole = OrientationandTrainingUtil.createChapter(acc.id,currRole.Id);
        Chapter_Role__c  currNonWishChapRole = OrientationandTrainingUtil.createChapter(acc.id,currNonWishRole.Id);
        Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id,currChapRole.Id);
        Contact wishChild = OrientationandTrainingUtil.CreateWishChild();
        Case newParentWish = OrientationandTrainingUtil.CreateParentCase(wishChild.Id);
        User currUser;
        System.RunAs(new User(Id = UserInfo.getUserId())) {
           
            currUser = OrientationandTrainingUtil.createActiveVolunteerUser(con.id);
            
        }
         Volunteer_Opportunity__c wishVolunteerOpportunity = OrientationandTrainingUtil.CreateNewWishVolunteerOpportunity(acc.Id,currChapRole.Id,newParentWish.Id);
            Volunteer_Opportunity__c dbVolOpp = new Volunteer_Opportunity__c();
            dbVolOpp.Id = wishVolunteerOpportunity.Id;
            dbVolOpp.Volunteer_Name__c = con.Id;
            dbVolOpp.Status__c = 'Approved';
            update dbVolOpp;
            
           system.RunAs(currUser){
           VolunteerOpportunitySelection_AC volunteeerController = new VolunteerOpportunitySelection_AC();
            volunteeerController.createTimeSheet();
            volunteeerController.CreateNewTimeSheet();
            volunteeerController.DisplayError();
            VolunteerOpportunitySelection_AC.volunteerWrapper newWrapper = new VolunteerOpportunitySelection_AC.volunteerWrapper();
            newWrapper.recordSelected = false;
            newWrapper.volOpp = dbVolOpp;
            }
           
           
        
        //volunteeerController.volunteerWrapper();
      //volunteeerController.createTimeSheet();
        //volunteeerController.CreateNewTimeSheet();
}
}