make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Chapter_Role_O_T__c.object
<CustomObject>
    <description>This is a junction object that would join the Orientation &amp; Training objects and the Roles object.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associate with Chapter Role Object.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipName>O_T_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Orientation_Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds orientation &amp; Training for chapter roles.</description>
        <label>Orientation &amp; Training</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please select Training Orientation.</errorMessage>
            <filterItems>
                <field>Orientation_Training__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Training</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Orientation_Training__c</referenceTo>
        <relationshipLabel>Chapter Roles O&amp;T</relationshipLabel>
        <relationshipName>O_T_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter Role O&amp;T</label>
    <nameField>
        <displayFormat>OTR-{000000}</displayFormat>
        <label>O&amp;T Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles O&amp;T</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Class_Offering__c.object
<CustomObject>
    <description>It will hold the Training Date and Time details.</description>
    <fields>
        <fullName>Chapter_Role_O_T__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It associate with Chapter Role O &amp; T.</description>
        <label>Chapter Role O&amp;T</label>
        <referenceTo>Chapter_Role_O_T__c</referenceTo>
        <relationshipName>Class_offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>It will capture type value about the orientation and training,whether the training taken in online or in person</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class Offering</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Class offering Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Offerings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Constituent_Code__c.object
<CustomObject>
    <label>Constituent Code</label>
    <nameField>
        <label>Constituent Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituent Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/LMS_Credentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting contains LMS Credential details.</description>
    <label>LMS Credentials</label>
</CustomObject>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>Constituent_Code__c</fullName>
        <description>It stores the value of Constituent Code</description>
        <label>Constituent Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wish Child</fullName>
                </value>
                <value>
                    <fullName>Wish Family</fullName>
                </value>
                <value>
                    <fullName>Celebrity</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Volunteer Leadership</fullName>
                </value>
                <value>
                    <fullName>Medical Professional</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Referral Source</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Intern</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Affiliation&apos;s Organization will be stored on the Contact record.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe5__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Out of Compliance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Orientation_Training__c.object
<CustomObject>
    <description>It will holds orientation &amp; training information records</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>It will capture type value about the orientation and training,whether the training taken in online or in person</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Orientation &amp; Training</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orientation &amp; Trainings</pluralLabel>
    <recordTypes>
        <fullName>Orientation</fullName>
        <active>true</active>
        <description>This record type associated with orientation page layout</description>
        <label>Orientation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Orientation_Training__c.object
<CustomObject>
    <description>It is a junction object for volunteer and Orientation &amp; Training  object. It will capture the volunteer and his completed  training information details</description>
    <fields>
        <fullName>Class_Offering__c</fullName>
        <description>It will hold the training details.</description>
        <label>Class Offering</label>
        <referenceTo>Class_Offering__c</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Orientation_Training__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to Orientation &amp; Training object records</description>
        <label>Orientation/Training</label>
        <referenceTo>Orientation_Training__c</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_Date__c</fullName>
        <description>It will capture the volunteer  registered date for the orientation or training session</description>
        <label>Registered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>It will capture information about whether it is a orientation or training</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Orientation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Attendance__c</fullName>
        <description>It will capture whether the volunteer registered or completed the session</description>
        <label>Volunteer Attendance</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to Volunteer Contact records</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Orientation &amp; Training</label>
    <nameField>
        <displayFormat>VOT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Orientation &amp; Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerOrientation_AC_Test.cls
/*************************************************************************************************************
Author : Mst Solutions
Description : This class is used to increase the code coverage for VolunteerOrientation_AC controller
Modification Log
1. WVC-2205 - Kanagaraj - 08/08/2018 // line - 237,55,99,142,189 Previously the affilliation status 
                                       was "Prospective". Now we have updated as "Pending".
**************************************************************************************************************/

@IsTest
public class VolunteerOrientation_AC_Test {
	@TestSetup
	private static void setup() {
		trac_TriggerHandlerBase.blockTrigger = true;
	}

	static testMethod void coverMisc() {
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(null);
			insert currUser;
		}

		System.RunAs(currUser) {
			Account acc = OrientationandTrainingUtil.createVolunteerAccount();
			insert acc;
			Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
			insert con;
			OrientationandTrainingUtil.createAffiliation(con.id);
			Role__c currRole = OrientationandTrainingUtil.createRole();
			insert currRole;
			Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
			insert currChapRole;
			Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
			insert currVolRole;
			Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
			insert currOandT;
			Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
			insert currChapOandT;
			Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
			insert currOffering;

			Volunteer_Orientation_Training__c createVolOrientation = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.Id, currUser.ContactId, 'Completed');
			createVolOrientation.Volunteer_Attendance__c = 'Registered';

			update createVolOrientation;

			npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
			neworgAffiliation.npe5__Contact__c = currUser.ContactId;
			neworgAffiliation.npe5__Organization__c = acc.Id;
			neworgAffiliation.npe5__Primary__c = true;
			neworgAffiliation.npe5__Status__c = 'Pending';
			neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
			insert neworgAffiliation;

			System.assertEquals(currOffering.id, createVolOrientation.class_offering__c);
			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerTraining_VF;
			Test.setCurrentPage(pageRef);
			System.currentPageReference().getParameters().put('bgRequired', 'true');
			System.currentPageReference().getParameters().put('trainingRequired', 'true');
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.classOfferingMap.put(controller.trainingId, currOffering);
			controller.Register();
			controller.trainingId = currOffering.id;
			List<Orientation_Training__c> volunteerRelatedTrainingsList = controller.volunteerTrainingsList;
			Boolean bgTabPermission = controller.bgTabPermission;
			Boolean trainingTabVisible = controller.trainingTabVisible;
		}

		VolunteerOrientation_AC.classOfferingWrapper wrapper = new VolunteerOrientation_AC.classOfferingWrapper();
		wrapper.orientationName = 'x';
		wrapper.chapterName = 'x';
		wrapper.orientationDate = Date.today();
		wrapper.startTime = 'x';
		wrapper.endTime = 'x';
		wrapper.location = 'x';
		wrapper.maxCapacity = 1;
		wrapper.avilableSheets = 1;
		wrapper.recordType = 'x';
		wrapper.status = 'x';
		wrapper.volOppSize = 1;
		wrapper.recordId = 'x';
		wrapper.courseId = 'x';
		wrapper.recordTypeId = 'x';
		wrapper.displayRec = true;

		VolunteerOrientation_AC miscController = new VolunteerOrientation_AC();
		miscController.total_size = 4;
		miscController.list_size = 3;
		miscController.getTotalPages();
		miscController.total_size = 3;
		miscController.getTotalPages();
		miscController.End();
	}

	// Complete the Volunteer Orientation.
	static testMethod void CreatingCompletedOrientation() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		OrientationandTrainingUtil.createAffiliation(con.id);
		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;

		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		Volunteer_Orientation_Training__c createVolOrientation = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.Id, currUser.ContactId, 'Completed');

		Volunteer_Orientation_Training__c createVolOrientation2 = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.Id, currUser.ContactId, 'Completed');
		createVolOrientation2.Type__c = 'Orientation';
		createVolOrientation2.Volunteer_Attendance__c = 'No Show';
		update createVolOrientation2;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			System.assertEquals(currOffering.id, createVolOrientation.class_offering__c);
			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerTraining_VF;
			Test.setCurrentPage(pageRef);
			System.currentPageReference().getParameters().put('bgRequired', 'true');
			System.currentPageReference().getParameters().put('trainingRequired', 'true');
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			List<Orientation_Training__c> volunteerRelatedTrainingsList = controller.volunteerTrainingsList;
			Boolean bgTabPermission = controller.bgTabPermission;
			Boolean trainingTabVisible = controller.trainingTabVisible;
		}
	}
	// Display Class OFfering on Portal.
	static testMethod void VolunteerTrainingDisplay() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		//OrientationandTrainingUtil.createAffiliation(con.id);

		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		User currUser;
		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
			insert currUser;
		}
		Volunteer_Orientation_Training__c createVolOrientation = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.id, currUser.ContactId, 'Registered');
//		insert createVolOrientation;
		//System.RunAs(new User(Id = UserInfo.getUserId())) {
		System.RunAs(currUser) {

			System.assertEquals(currOffering.id, createVolOrientation.class_offering__c);

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);

			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			controller.Register();
		}
	}

	// Register for new Orientation.
	static testMethod void CreateNewTraining() {
		LMS_Credentials__c currLMSCredential = testClassUtil.createLMSCredentials();
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		//OrientationandTrainingUtil.createAffiliation(con.id);
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId())) {

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			controller.Register();
			VolunteerOrientation_AC.updateUser('volunteer@gmail.com', '3409379', 'volunteer@gmail.com', currUser.id);
		}
	}

	// Creating Orientation with Cancelled status.
	static testMethod void CreatingCancelledTraining() {
		LMS_Credentials__c currLMSCredential = testClassUtil.createLMSCredentials();
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		//OrientationandTrainingUtil.createAffiliation(con.id);
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		User currUser;
		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;
		Volunteer_Orientation_Training__c createVolOrientation = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.id, con.id, 'Volunteer Cancelled');
//        insert createVolOrientation;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}

		VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
		System.RunAs(new User(Id = UserInfo.getUserId())) {

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);

			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			VolunteerOrientation_AC.updateUser('volunteer@gmail.com', '3409379', 'volunteer@gmail.com', UserInfo.getUserId());
		}

		//
		// controller.Register();
	}
	// Cancel Registered Orientation.
	static testMethod void CancelTraining() {
		LMS_Credentials__c currLMSCredential = testClassUtil.createLMSCredentials();
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		//OrientationandTrainingUtil.createAffiliation(con.id);
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		User currUser;
		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;
		Volunteer_Orientation_Training__c createVolOrientation = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.id, con.id, 'Registered');

		createVolOrientation.Volunteer_Attendance__c = 'Volunteer Cancelled';
		update createVolOrientation;
		Volunteer_Orientation_Training__c createVolOrientation2 = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.id, con.id, 'Registered');
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId())) {

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);

			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();

			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			controller.Cancel();
			system.assertEquals('Volunteer Cancelled', createVolOrientation.Volunteer_Attendance__c);
			controller.Register();
		}

	}

	// Duplicate Orientation time prevention.
	static testMethod void BookingTrainingwithSameTime() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		//OrientationandTrainingUtil.createAffiliation(con.id);
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;

		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;
		Volunteer_Orientation_Training__c createVolOrientation = VolunteerOrientation_AC_Test.createVolOrientation(currOandT.id, currOffering.id, con.id, 'Registered');

		Orientation_Training__c currOandT1 = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT1;
		Chapter_Role_O_T__c currChapOandT1 = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT1.id);
		insert currChapOandT1;
		Class_Offering__c currOffering1 = OrientationandTrainingUtil.createClassOffering(currChapOandT1.id);
		insert currOffering1;
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId())) {

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);

			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.userRelatedContactId = con.Id;
			controller.getOrientationRecordList();
			controller.trainingId = currOffering1.id;
			controller.Register();
			controller.Next();
			controller.Beginning();
			controller.getPageNumber();
//                controller.getTotalPages();
//                controller.End();
			controller.getDisableNext();

		}
	}

	// Creating Volunteer Orientation for volunteer based on the input parameter.
	static Volunteer_Orientation_Training__c createVolOrientation(Id OrienationId, Id ClassOfferingId, Id volunteer, string status) {
		Volunteer_Orientation_Training__c createNewVol = new Volunteer_Orientation_Training__c();
		createNewVol.class_offering__c = ClassOfferingId;
		createNewVol.Hidden_O_T_Id__c = OrienationId;
		createNewVol.Registered_Date__c = Date.Today();
		createNewVol.Volunteer__c = volunteer;
		createNewVol.Volunteer_Attendance__c = status;
		createNewVol.Type__c = 'Orientation';
		insert createNewVol;
		return createNewVol;
	}

	static testMethod void CheckViewLMS() {
		Account acc;
		Contact con;
		LMS_Credentials__c currLMSCredential;
		User currUser;
		acc = OrientationandTrainingUtil.createVolunteerAccount();
		con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		currLMSCredential = testClassUtil.createLMSCredentials();
		OrientationandTrainingUtil.createAffiliation(con.id);
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			testClassUtil.createUser();
			//testClassUtil.createUser();
		}
		List<User> currUserLst = [
				SELECT ID
				FROM USER
				WHERE ID != :Userinfo.getUserId() AND isActive = True
		];
		System.RunAs(currUserLst[0]) {

			LMSCourseSyncMockImpl currLMSCourseSyncMockImpl = new LMSCourseSyncMockImpl();
			HttpResponse response = new HttpResponse();
			response.setStatus('OK');
			response.setStatusCode(200);
			LMSUserResponse currLMSUserResponse = new LMSUserResponse();
			currLMSUserResponse.id = 1234;
			currLMSUserResponse.login = 'test@test.com';
			currLMSUserResponse.code = 'test@test.com';
			currLMSUserResponse.first_name = 'test';
			currLMSUserResponse.last_name = 'test';
			currLMSUserResponse.last_name = 'test@test.com';
			currLMSUserResponse.is_active = true;
			currLMSUserResponse.last_login_at = '2016-08-04T19:20:05.407-04:00';
			String payload = JSON.serialize(currLMSUserResponse);
			response.setBody(payload);
			currLMSCourseSyncMockImpl.addResponse(response);
			Test.setMock(HttpCalloutMock.class, currLMSCourseSyncMockImpl);
		}
		Test.startTest();
		System.RunAs(currUserLst[1]) {
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.lMSCourseId = 'Test';
			controller.viewLMS();
			// updateUser();
			controller.Previous();
			controller.getDisablePrevious();
		}
		Test.stopTest();
	}

	static testMethod void CreateNewTrainingWithExistingCancelledRecords() {
		LMS_Credentials__c currLMSCredential = testClassUtil.createLMSCredentials();
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		//OrientationandTrainingUtil.createAffiliation(con.id);
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;

		Volunteer_Orientation_Training__c volunteerOrientationTraining = OrientationandTrainingUtil.createVolTraining(currOandT.Id, currOffering.Id, con.Id, 'Completed');
		insert volunteerOrientationTraining;

		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId())) {

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			controller.userRelatedContactId = con.Id;
			controller.classOfferingMap = new Map<Id, Class_Offering__c>();
			controller.classOfferingMap.put(currOffering.id, currOffering);
			controller.Register();
		}
	}

	static testMethod void CreateNewTrainingWithVolunteerCancelledRecords() {
		LMS_Credentials__c currLMSCredential = testClassUtil.createLMSCredentials();
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		currChapOandT.Orientation_Training__r = currOandT;
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;

		Volunteer_Orientation_Training__c volunteerOrientationTraining = OrientationandTrainingUtil.createVolTraining(currOandT.Id, currOffering.Id, con.Id, 'Volunteer Cancelled');
		insert volunteerOrientationTraining;

		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId())) {

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			controller.userRelatedContactId = con.Id;
			controller.classOfferingMap = new Map<Id, Class_Offering__c>();
			controller.classOfferingMap.put(currOffering.id, [
					SELECT Id, Chapter_Role_O_T__r.Orientation_Training__c
					FROM Class_Offering__c
					WHERE Id = :currOffering.Id
			]);
			controller.Register();
		}
	}

	/*
	static testMethod void CreateNewTrainingWithCheckForExistingBeforeRecords()
	{
		LMS_Credentials__c currLMSCredential = testClassUtil.createLMSCredentials();
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c  = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Pending';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;

		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c  currChapRole = OrientationandTrainingUtil.createChapter(acc.id,currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id,currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id,currOandT.id);
		currChapOandT.Orientation_Training__r = currOandT;
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;

		Volunteer_Orientation_Training__c volunteerOrientationTraining = OrientationandTrainingUtil.createVolTraining(currOandT.Id, currOffering.Id, con.Id, 'Volunteer Cancelled');
		insert volunteerOrientationTraining;

		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId()))
		{
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId()))
		{

			TestClassUtil.createDynamicContent();
			PageReference pageRef = Page.VolunteerOrientation_VF;
			Test.setCurrentPage(pageRef);
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.TimingInfo();
			controller.getOrientationRecordList();
			controller.trainingId = currOffering.id;
			controller.userRelatedContactId = con.Id;
			controller.classOfferingMap = new Map<Id,Class_Offering__c>();
			controller.classOfferingMap.put(currOffering.id, [SELECT Id, Chapter_Role_O_T__r.Orientation_Training__c FROM Class_Offering__c WHERE Id = :currOffering.Id]);
			controller.Register();
		}
	}
	*/

	@IsTest
	static void testCancelWithOrientationDetails() {
		Account chapterAcc = OrientationandTrainingUtil.createChapterAccount();
		insert chapterAcc;
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		currChapOandT.Orientation_Training__r = currOandT;
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;

		Volunteer_Orientation_Training__c volunteerOrientationTraining = OrientationandTrainingUtil.createVolTraining(currOandT.Id, currOffering.Id, con.Id, 'Volunteer Cancelled');
		volunteerOrientationTraining.Type__c = 'Orientation';
		insert volunteerOrientationTraining;

		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.trainingId = currOffering.id;
			controller.userRelatedContactId = con.Id;
			controller.lMSCredential = testClassUtil.createLMSCredentials();
			controller.Cancel();
		}
	}

	@IsTest
	static void testCancelWithOrientationDetailsWithoutCredential() {
		Account chapterAcc = OrientationandTrainingUtil.createChapterAccount();
		insert chapterAcc;
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		Role__c currRole = OrientationandTrainingUtil.createRole();
		insert currRole;
		Chapter_Role__c currChapRole = OrientationandTrainingUtil.createChapter(acc.id, currRole.id);
		insert currChapRole;
		Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id, currChapRole.id);
		insert currVolRole;
		Orientation_Training__c currOandT = OrientationandTrainingUtil.CreateVolunteerOrientationRecord();
		insert currOandT;
		Chapter_Role_O_T__c currChapOandT = OrientationandTrainingUtil.createChapterOandT(currChapRole.id, currOandT.id);
		currChapOandT.Orientation_Training__r = currOandT;
		insert currChapOandT;
		Class_Offering__c currOffering = OrientationandTrainingUtil.createClassOffering(currChapOandT.id);
		insert currOffering;

		Volunteer_Orientation_Training__c volunteerOrientationTraining = OrientationandTrainingUtil.createVolTraining(currOandT.Id, currOffering.Id, con.Id, 'Volunteer Cancelled');
		volunteerOrientationTraining.Type__c = 'Orientation';
		insert volunteerOrientationTraining;

		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
		}
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			VolunteerOrientation_AC controller = new VolunteerOrientation_AC();
			controller.trainingId = currOffering.id;
			controller.userRelatedContactId = con.Id;
			controller.Cancel();
		}
	}
}