make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter details and role for this chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the role name and chapters assigned for this role.</description>
        <label>Role Name</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Chapter Roles</relationshipLabel>
        <relationshipName>Chapter_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ChapterRoleTrigger_Test.cls
/* ---------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------*/
@isTest
public class ChapterRoleTrigger_Test{
   
   //Used to create a Chapter Role record for National Staff as Owner.
    private testmethod static void  createChapterRole(){
        Chapter_Vs_Role__c arizonaChap = OrientationandTrainingUtil.createArizonaChapter();
        Chapter_Vs_Role__c alabamaChap = OrientationandTrainingUtil.createAlabamaChapter();
        Insert alabamaChap;
        Insert arizonaChap;
             
        User currUser = [SELECT id from User where id = :Userinfo.getUserId() limit 1]; 
         User nationalStaff;
         System.RunAs(currUser)
         {     
             nationalStaff = OrientationandTrainingUtil.createUserWithRole([select Id from UserRole where Name='National Staff'].Id); 
         }
                  
         System.runAs(nationalStaff) {            
            Chapter_Role__c newChapRole = new Chapter_Role__c();
            newChapRole.Chapter_Name__c = OrientationandTrainingUtil.createchapterAccount().Id;
            newChapRole.Role_Name__c = OrientationandTrainingUtil.createRole().Id;
            newChapRole.OwnerId= nationalStaff.Id;
            insert newChapRole;
            System.assertEquals('National Staff',[SELECT UserRole.Name FROM User WHERE Id =:nationalStaff.Id].userRole.Name);
            System.assertEquals(nationalStaff.Id,[SELECT OwnerId FROM Chapter_Role__c WHERE Id =:newChapRole.Id].OwnerId);
             
          
         }
    }   
}