make-a-wish-salesforce/src/objects/Chapter_Action_Track__c.object
<CustomObject>
    <description>It holds list of tasks for child wishes</description>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It holds the Chapter Name</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chapter Action Tracks</relationshipLabel>
        <relationshipName>Chapter_Action_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter Action Track</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Action Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ChapterActionTrack_onBeforeInsertHelper.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 10/15/2016
Description : 
              
              Modification Log
              ------------------
              WVC-1887    Pavithra G  07/03/2018
              
*****************************************************************************************************/
Public class ChapterActionTrack_onBeforeInsertHelper{    
   /***************
       Show the error message when the current logged in user role and chapter name are diffrent. 
   ******************/
    public static void showErrorMessageDistinctRole(set<Id> chapterIdSet,Map<Id,Chapter_Action_Track__c> chapterActionTrackMap){
         Map<Id,String> chapterIdNameMap = New Map<Id,String>();
         chapterIdNameMap = ChapterStaffRecordSharing_AC.getChapterName(chapterIdSet);
         String userRole = [SELECT UserRole.Name FROM User WHERE id =:userInfo.getUserId() Limit 1].UserRole.Name; 
           for(Chapter_Action_Track__c currRec : chapterActionTrackMap.values()){
               if(Bypass_Triggers__c.getValues(userInfo.getUserId()) == Null && userRole != chapterIdNameMap.get(currRec.Chapter_Name__c) && !Test.isRunningTest()){
                   currRec.addError('You have no access to create Chapter Action Track records for other chapters');
               }
           }
    }
}