make-a-wish-salesforce/src/objects/Chapter_Role__c.object
<CustomObject>
    <description>This custom object stores the Roles that the Chapter offers.</description>
    <fields>
        <fullName>Role__c</fullName>
        <description>It holds the Role Name</description>
        <label>Hidden Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Chapter Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Chapter Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chapter Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Role__c.object
<CustomObject>
    <description>This custom object would store the Roles for the volunteer that the Chapter offers.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Chapter_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the chapter and role of the volunteer.</description>
        <label>Chapter Role</label>
        <referenceTo>Chapter_Role__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerRole_AT_Test.cls
/*--*****************************************************************************************************************
Author      : MST Solutions
CreatedBy   : Chandrasekar Nallusamy
Date        : 7/18/2016
Description : This test class used for unit test and code coverage
*******************************************************************************************************************/
@isTest
public class VolunteerRole_AT_Test{
    
    // Update Volunteer Role.
    static testmethod void createRecords()
    {
    
         Account acc = OrientationandTrainingUtil.createVolunteerAccount();
         Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
         OrientationandTrainingUtil.createAffiliation(con.id);
         Role__c currRole = OrientationandTrainingUtil.createRole();
         Chapter_Role__c  currChapRole = OrientationandTrainingUtil.createChapter(acc.id,currRole.id);
         Volunteer_Roles__c currVolRole = OrientationandTrainingUtil.createVolRole(con.id,currChapRole.id);
         currVolRole.Status__c = 'Pending Training';
         update currVolRole;
               
      
     
    }
 }