make-a-wish-salesforce/src/objects/Class_Offering__c.object
<CustomObject>
    <description>It will hold the Training Date and Time details.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>It will capture the date information about the training started date</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>It will capture the starting time information, about the orientation and training program</description>
        <label>End Time</label>
        <picklist>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>It will capture the starting time information, about the orientation and training program</description>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class Offering</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Class offering Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Offerings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ClassOffering_AT_Test.cls
@IsTest
public class ClassOffering_AT_Test {

	@IsTest
	public static void createClassOffering() {
		Class_Offering__c classOffering = new Class_Offering__c();
		classOffering.Date__c = Date.today() + 3;
		classOffering.Start_Time__c = '9:00 AM';
		classOffering.End_Time__c = '10:00 AM';
		insert classOffering;

		classOffering.Date__c = Date.today() + 4;
		classOffering.Start_Time__c = '10:00 AM';
		classOffering.End_Time__c = '11:00 AM';
		update classOffering;
	}

	@IsTest
	public static void createClassOfferingSameTime() {
		Class_Offering__c currOffering = new Class_Offering__c();
		currOffering.Date__c = Date.today() + 3;
		currOffering.Start_Time__c = '7:00 PM';
		currOffering.End_Time__c = '10:00 AM';
		Database.insert(currOffering, false);
	}

	@IsTest
	public static void validateClassOfferingStartTimeBlank() {
		Class_Offering__c currOffering = new Class_Offering__c();
		currOffering.Date__c = Date.today() + 3;
		currOffering.End_Time__c = '10:00 AM';
		Database.SaveResult result = Database.insert(currOffering, false);
		System.assertEquals('Please enter a valid Start Time', result.getErrors()[0].getMessage());
	}

	@IsTest
	public static void createClassOfferingAsNationalStaff() {
		User nationalStaff;
		System.runAs(Utils.currentUser) {
			Id roleId = [
					SELECT Id
					FROM UserRole
					WHERE Name = 'National Staff'
			].Id;

			Profile systemAdministrator = [
					SELECT Id
					FROM Profile
					WHERE Name = 'System Administrator'
			];
			nationalStaff = new User(firstname = 'JonJesu', lastName = 'EdwardsJo', email = 'jonemail@gma111il.com', Username = 'jonsamp0@gma11il.com',
					EmailEncodingKey = 'ISO-8859-1', Alias = 'jone', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
					LanguageLocaleKey = 'en_US', UserRoleId = roleId, ProfileId = systemAdministrator.Id, isActive = true, Statecode = 'AZ');
			insert nationalStaff;
		}
		System.runAs(nationalStaff) {
			Class_Offering__c classOffering = new Class_Offering__c();
			classOffering.Date__c = Date.today() + 3;
			classOffering.Start_Time__c = '9:00 AM';
			classOffering.End_Time__c = '10:00 AM';
			classOffering.OwnerId = Utils.currentUser.Id;
			insert classOffering;

			classOffering.Date__c = Date.today() + 4;
			classOffering.Start_Time__c = '10:00 AM';
			classOffering.End_Time__c = '11:00 AM';
			classOffering.OwnerId = nationalStaff.Id;
			update classOffering;
		}
	}
}