make-a-wish-salesforce/src/objects/Condition_Description__c.object
<CustomObject>
    <label>Condition Description</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Description</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <fields>
        <fullName>Condition_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It has one to many relationship with Condition Description.</description>
        <label>Condition Description</label>
        <referenceTo>Condition_Description__c</referenceTo>
        <relationshipLabel>ICD Codes</relationshipLabel>
        <relationshipName>ICD_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Child_Age__c</fullName>
        <description>It would capture the child of the age.</description>
        <label>Child Age</label>
        <picklist>
            <picklistValues>
                <fullName>Under 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18 &amp; Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hospital_Treatment_Facility_Treating__c</fullName>
        <description>It holds the information about Hospital/Treatment Facility of the wish kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_First_Name__c</fullName>
        <description>It hold the First name of wish&apos;s parent.</description>
        <label>Parent First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Last_Name__c</fullName>
        <description>It hold the last name of Wish&apos;s parent.</description>
        <label>Parent Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wih&apos;s parent.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture email address of wish parent from referral form.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It will hold the firstname of the child.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It will capture the zipcode of wish&apos;s parent.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Email__c</fullName>
        <description>This field will hold the Treating Medical Professional Email Address</description>
        <label>Treating Medical Professional Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the Treating Medical Professional First Name</description>
        <label>Treating Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Last_Name__c</fullName>
        <description>This field will hold the details about Treating Medical Professional Name</description>
        <label>Treating Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Phone__c</fullName>
        <description>This field will hold the Treating Medical Professional Phone number</description>
        <label>Treating Medical Professional Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_LeadChildAgeTest.cls
/******************************************************************************************
Author : MAWA
Created Date: 4/25/2019
Modification: 07/09/2019 - Samer - SIW-246
              Modified code for childDOB and childDOB2 to fix date calculation error.
*******************************************************************************************/
@isTest
public class batch_LeadChildAgeTest {

	@testSetup
	static void setup() {
		trac_TriggerHandlerBase.blockTrigger = true;
		Account chapterAccount = OrientationandTrainingUtil.CreateAmericaAccount();
		insert chapterAccount;

		Condition_Description__c descrip = OrientationandTrainingUtil.createConditionDesCription();
		insert descrip;

		ICD_Codes__c icdCode = OrientationandTrainingUtil.createICDCode(descrip.Id);
		insert icdCode;

		// date childDOB = Date.parse(String.valueOf(System.today().month())+'/'+String.valueOf(System.today().day())+'/'+String.valueOf(System.today().year()-2));
		// date childDOB2 = Date.parse(String.valueOf(System.today().month()+6)+'/'+String.valueOf(System.today().day())+'/'+String.valueOf(System.today().year()-3));

		Date runDate = Date.today();
		Date childDOB = runDate.addYears(-1).addMonths(-6);      // age 1.5
		Date childDOB2 = runDate.addYears(-2).addMonths(-6);     // age 2.5

		List<Lead> leadList = new List<Lead>();
		List<Lead> leadListNeg = new List<Lead>();

		//insert wish child leads where child age is 2.5 years old today and the field for Age Requirement should update
		for (Integer i = 0; i < 10; i++) {
			leadList.add(new Lead(firstName = 'Walter' + i, lastName = 'LastName' + i, child_age__c = 'Under 2.5', DOB__c = childDOB2, gender__c = 'Male', company = 'MAWA',
					is_Family_Aware_of_Referral__c = 'Yes', Phone = '9600467559', Email = 'testmawa' + i + '@gmail.com', State = 'Arizona',
					Treating_Medical_Professional_First_Name__c = 'Steve' + i, Treating_Medical_Professional_Last_Name__c = 'Waugh',
					Treating_Medical_Professional_Email__c = 'testmawa2' + i + '@gmail.com', Hospital_Treatment_Facility_Treating__c = 'Steve Smith AC',
					Treating_Medical_Professional_Phone__c = '9990467555', Parent_First_Name__c = 'Parent' + i, Parent_Last_Name__c = 'LastName' + i,
					Referrer_FirstName__c = 'Referrer' + i, Referrer_Last_Name__c = 'TestRef' + i, Referrer_Phone__c = '8880467556', Referrer_Email__c = 'referrer' + i + '@gmail.com',
					Referrer_City__c = 'Phoenix', Referrer_Zip__c = '85016', status = 'Inquiry', PD_ICD_Code__c = icdCode.Id, ICD_Given_By_Referrer__c = icdCode.id,
					Diagnosis_Given_By_Referrer__c = 'Test', ChapterName__c = chapterAccount.id, Street = '12' + i + 'Market St', postalcode = '85016', city = 'Phoenix', Age_Requirement_Met__c = false));
		}

		//insert wish child leads where child age is 1.5 years old and the field for Age Requirement should not update
		for (Integer i = 0; i < 10; i++) {
			leadListNeg.add(new Lead(firstName = 'NFirstName' + i, lastName = 'NLastName' + i, child_age__c = 'Under 2.5', DOB__c = childDOB, gender__c = 'Male', company = 'MAWA',
					is_Family_Aware_of_Referral__c = 'Yes', Phone = '9611467559', Email = 'Ntestmawa' + i + '@gmail.com', State = 'Arizona',
					Treating_Medical_Professional_First_Name__c = 'Chris' + i, Treating_Medical_Professional_Last_Name__c = 'Waugh',
					Treating_Medical_Professional_Email__c = 'Ntestmawa2' + i + '@gmail.com', Hospital_Treatment_Facility_Treating__c = 'Steve Smith AC',
					Treating_Medical_Professional_Phone__c = '9990498555', Parent_First_Name__c = 'Parent' + i, Parent_Last_Name__c = 'LastName' + i,
					Referrer_FirstName__c = 'NReferrer' + i, Referrer_Last_Name__c = 'NTestRef' + i, Referrer_Phone__c = '8818467556', Referrer_Email__c = 'Nreferrer' + i + '@gmail.com',
					Referrer_City__c = 'Phoenix', Referrer_Zip__c = '85016', status = 'Inquiry', PD_ICD_Code__c = icdCode.Id, ICD_Given_By_Referrer__c = icdCode.id,
					Diagnosis_Given_By_Referrer__c = 'Test', ChapterName__c = chapterAccount.id, Street = '125' + i + 'N Market St', postalcode = '85016', city = 'Phoenix', Age_Requirement_Met__c = false));
		}

		insert leadList;
		insert leadListNeg;
		trac_TriggerHandlerBase.blockTrigger = false;
	}

	//Call the batch_leadChildAge class
	static testmethod void testBatchLeadChildAge() {

		Test.startTest();

		//verify none of the leads entering the batch have the Age requirement field marked as true
		Lead[] leadsBeforeUpdateList = [
				SELECT Id, Age_Requirement_Met__c
				FROM Lead
				Where Age_Requirement_Met__c = true
		];
		System.AssertEquals(0, leadsBeforeUpdateList.size());

		//initialize the batch job
		batch_leadChildAge reminder = new batch_leadChildAge();
		id batchId = database.executeBatch(reminder);
		test.stopTest();

		//Assert that number of the leads that should have been updated have been updated
		Lead[] leadsUpdatedList = [
				SELECT Id, Age_Requirement_Met__c
				FROM Lead
				Where Age_Requirement_Met__c = true
		];
		if (leadsUpdatedList.size() > 0) {
			System.AssertEquals(true, leadsUpdatedList[0].Age_Requirement_Met__c);
			System.AssertEquals(10, leadsUpdatedList.size());
		}
	}

	//Test batch_leadChildAgeSchedule
	static testmethod void testschedule() {

		Test.startTest();

		String CRON_EXP = '0 0 13 * * ?';
		batch_leadChildAgeSchedule reminder = new batch_leadChildAgeSchedule();
		String jobID = System.schedule('Lead Child Age Req', CRON_EXP, reminder);
		CronTrigger ct = [
				Select id, cronExpression, TimesTriggered, NextFireTime
				from CronTrigger
				where id = :jobId
		];

		system.assertEquals(CRON_EXP, ct.CronExpression);
		system.assertEquals(0, ct.TimesTriggered);
		Test.stopTest();
	}
}