make-a-wish-salesforce/src/objects/Condition_Description__c.object
<CustomObject>
    <fields>
        <fullName>Group1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It hold the details about Group1.</description>
        <label>Group1</label>
        <type>Checkbox</type>
    </fields>
    <label>Condition Description</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Description</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Condition_Description__c.object
    <fields>
        <fullName>isEligible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify whether ICD is eligible and no need for medical question</description>
        <label>isEligible</label>
        <type>Checkbox</type>
    </fields>

make-a-wish-salesforce/src/objects/Diagnosis_Verification__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the condition description</description>
        <label>Condition Description</label>
        <referenceTo>Condition_Description__c</referenceTo>
        <relationshipLabel>Diagnosis Verification</relationshipLabel>
        <relationshipName>Diagnosis_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to hold the related contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Diagnosis Verification</relationshipLabel>
        <relationshipName>Diagnosis_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identified whether the give ICD or Condition Description is Group1 record</description>
        <label>Group1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ICD_Code__c</fullName>
        <description>It holds the ICD Code</description>
        <label>ICD Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds the lead</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Diagnosis Verification</relationshipLabel>
        <relationshipName>Diagnosis_Verification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isEligible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determine whether the wish is eligible</description>
        <label>Hidden isEligible</label>
        <type>Checkbox</type>
    </fields>
    <label>Diagnosis Verification</label>
    <nameField>
        <displayFormat>DV-{000}</displayFormat>
        <label>Diagnosis Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnosis Verification</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DiagnosisVerificationService.cls
/**
 * @description Diagnosis Verification Service, centralizes Diagnosis Verification business rules.
 * @author Gustavo Mayer, Traction on Demand
 * @createdDate 2/27/2020
 */
public class DiagnosisVerificationService {

	/**
	 * Find Diagnosis Verifications by Lead Id
	 * @param leadId
	 */
	public static List<Diagnosis_Verification__c> findByLeadId(Id leadId) {
		return [
				SELECT Id, ICD_Code__c, Condition_Description__c, Group1__c, isEligible__c
				FROM Diagnosis_Verification__c
				WHERE Lead__c = :leadId
				AND isEligible__c = TRUE
				LIMIT 1
		];
	}

	/**
	 * Delete Diagnosis Verifications found by Lead Id
	 * @param leadId
	 */
	public static void deleteByLeadId(Id leadId) {
		delete [
				SELECT Id
				FROM Diagnosis_Verification__c
				WHERE Lead__c = :leadId
		];
	}

	/**
	 * Update Contact on Diagnosis Verifications found by Lead Id
	 * @param leadMap
	 */
	public static void updateContact(Map<Id, Lead> leadMap) {
		List<Diagnosis_Verification__c> diagnosisList = new List<Diagnosis_Verification__c>();
		for (Diagnosis_Verification__c diagnosisInfo : [
				SELECT Id, Contact__c, Lead__c
				FROM Diagnosis_Verification__c
				WHERE Lead__c IN :leadMap.keySet()
		]) {
			diagnosisInfo.Contact__c = leadMap.get(diagnosisInfo.Lead__c).ConvertedContactId;
			diagnosisList.add(diagnosisInfo);
		}
		update diagnosisList;
	}
}