make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check weather this conflict of interest is active or not.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>This field is used to store the value of expiration date.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_CheckCOIExpiration_AC.cls
/***************************************************************************
Author : MST Solutions
Created Date : 05/10/2017
Description : This class is used to update Volunteer Opportunity and Volunteer Role
to "Out of Compliance" when the Conflict of Interest is expired
****************************************************************************/
global class batch_CheckCOIExpiration_AC implements Database.Batchable<sObject>  {
    
    global Database.QueryLocator start(Database.BatchableContext BC)  {
        return Database.getQueryLocator([SELECT id, Expiration_Date__c, Current__c, Volunteer_Contact__c FROM Conflict_Of_Interest__c WHERE Current__c = True AND Expiration_Date__c <= TODAY ]);
    }
    
    
    global void execute(Database.BatchableContext BC, List<Conflict_Of_Interest__c> coiExpiredList)  {
        
        Set<Id> volContactIdSet = new Set<Id>();
        for(Conflict_Of_Interest__c coiExpired : coiExpiredList) {
            volContactIdSet.add(coiExpired.Volunteer_Contact__c);
        }
        
        if(volContactIdSet.size() > 0) {
            BackGroundCheck_OnAfterUpdateHelper.UpdateVOppAndVRoleStatus(volContactIdSet, 'COI',coiExpiredList);
        }
        
    }   
    
    global void finish(Database.BatchableContext BC) {
        
    }
}