make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check weather this conflict of interest is active or not.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>This field is used to store the value of expiration date.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>COI_Expiration_Date__c</fullName>
        <description>It holds the Expiration Date of COI</description>
        <label>COI Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>It holds the License Expiration Date details.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/COI_OnAfterInsertTriggerHandler.cls
/***************************************************************************************************
Author      : MST Solutions
Date        : 
Description : COI_OnBeforeInsertTriggerHandler is used to call the Helper class when the
              new COI record is created.
              
              Modification Log
              ------------------
              WVC-1888    Pavithra G  06/13/2018
              WVC-2199    Pavithra G  08/10/2018
              
*****************************************************************************************************/
public class COI_OnAfterInsertTriggerHandler {
	/********************************************************************************************
	This method is used to create a task when the lead record is created. And share the lead
	record based on the chapter.
*********************************************************************************************/
	public static void OnAfterInsert(List<Conflict_Of_Interest__c > newCOIList) {
		Set<Id> recordIds = new Set<Id>();
		Set<Id> volunteerIdsCoiCurrent = new Set<Id>();
		Set<Id> updateVolunteerIdSet = new Set<Id>();
		Set<Id> ownerIds = new Set<Id>();
		List<Conflict_Of_Interest__c> updateVolRoleCOIList = new List<Conflict_Of_Interest__c>();
		List<Contact> updateVolunteerContact = new List<Contact>();
		Contact updateCon;
		for (Conflict_Of_Interest__c coi : newCOIList) {
			if (coi.Current__c == true) {
				recordIds.add(coi.Id);
				volunteerIdsCoiCurrent.add(coi.Volunteer_Contact__c);
			}
			ownerIds.add(coi.OwnerId);
			if (coi.Expiration_Date__c != null && coi.Volunteer_Contact__c != null) {
				//updateVolunteerContact.add(curr);
				updateCon = new Contact();
				updateCon.Id = coi.Volunteer_Contact__c;
				updateCon.COI_Expiration_Date__c = coi.Expiration_Date__c;
				updateVolunteerContact.add(updateCon);
			}
			/***** WVC-2199 *******/
			if (coi.Expiration_Date__c != null && coi.Volunteer_Contact__c != null && coi.Current__c == true) {
				updateVolunteerIdSet.add(coi.Volunteer_Contact__c);
				updateVolRoleCOIList.add(coi);
			}
			/***** WVC-2199 ****/
		}
		if (volunteerIdsCoiCurrent.size() > 0 && recordIds.size() > 0) {
			COI_OnAfterInsertTriggerHelper.UpdateExistingRecords(newCOIList, recordIds, volunteerIdsCoiCurrent);
		}
		if (updateVolunteerContact.size() > 0) {
			update updateVolunteerContact;
		}
		if (ownerIds.size() > 0) {
			COI_OnAfterInsertTriggerHelper.COIRecordSharing(ownerIds, newCOIList);
		}
		if (updateVolunteerIdSet.size() > 0) {
			COI_OnAfterInsertTriggerHelper.updateVolunteerRole(updateVolunteerIdSet, updateVolRoleCOIList);
		}
		/**
		 * WLP-619
		 * Process Volunteers to try to Activate its Volunteer Role, User and Organization Affiliation
		 */
		if (!volunteerIdsCoiCurrent.isEmpty()) {
			VolunteerJourneyService.processVolunteersChapterRequirements(volunteerIdsCoiCurrent);
		}
	}
}