make-a-wish-salesforce/src/objects/Conflict_Of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check weather this conflict of interest is active or not.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>This field is used to store the value of expiration date.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HiddenConflictExpire__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked when the conflict of Interest record get expire.</description>
        <label>Hidden Conflict Expire</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used store the value of the volunteer contact.</description>
        <label>Volunteer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Conflict Of Interest</relationshipLabel>
        <relationshipName>Conflict_Of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conflict Of Interest</label>
    <nameField>
        <displayFormat>COI -{0000}</displayFormat>
        <label>Conflict Of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Of Interest</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>COI_Expiration_Date__c</fullName>
        <description>It holds the Expiration Date of COI</description>
        <label>COI Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>It holds the License Expiration Date details.</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ConflictOfInterestDomain.cls
/**
 * @description Domain class for the Conflict Of Interest trigger
 * @author	Gustavo Mayer, Traction on Demand
 * @createdDate	3-18-2020
 */
public with sharing class ConflictOfInterestDomain extends trac_TriggerHandlerBase {

	List<Conflict_Of_Interest__c> newCOIList = (List<Conflict_Of_Interest__c>) newRecordsList;
	List<Conflict_Of_Interest__c> oldCOIList = (List<Conflict_Of_Interest__c>) oldRecordsList;
	Map<Id, Conflict_Of_Interest__c> newCOIMap = (Map<Id, Conflict_Of_Interest__c>) newRecordsMap;
	Map<Id, Conflict_Of_Interest__c> oldCOIMap = (Map<Id, Conflict_Of_Interest__c>) oldRecordsMap;

	/**
	 * Before insert of Conflict Of Interest
	 */
	public override void handleBeforeInsert() {
		ConflictOfInterestService.setAccount(newCOIList, oldCOIMap);
	}

	/**
	 * Before update of Conflict Of Interest
	 */
	public override void handleBeforeUpdate() {
		ConflictOfInterestService.setAccount(newCOIList, oldCOIMap);
	}

	/**
	 * After insert of Conflict Of Interest
	 */
	public override void handleAfterInsert() {
		Map<Id, Conflict_Of_Interest__c> volunteerIdCoiMap = new Map<Id, Conflict_Of_Interest__c>();
		Map<Id, Conflict_Of_Interest__c> ownerIdCoiMap = new Map<Id, Conflict_Of_Interest__c>();
		Map<Id, Conflict_Of_Interest__c> volunteerIdCoiExpirationMap = new Map<Id, Conflict_Of_Interest__c>();
		List<Contact> updateVolunteerContact = new List<Contact>();
		Contact updateCon;
		for (Conflict_Of_Interest__c coi : newCOIList) {
			ownerIdCoiMap.put(coi.OwnerId, coi);
			if (coi.Current__c == true) {
				volunteerIdCoiMap.put(coi.Volunteer_Contact__c, coi);
			}
			if (coi.Expiration_Date__c != null && coi.Volunteer_Contact__c != null) {
				updateCon = new Contact();
				updateCon.Id = coi.Volunteer_Contact__c;
				updateCon.COI_Expiration_Date__c = coi.Expiration_Date__c;
				updateVolunteerContact.add(updateCon);
			}
			if (coi.Expiration_Date__c != null && coi.Volunteer_Contact__c != null && coi.Current__c == true) {
				volunteerIdCoiExpirationMap.put(coi.Volunteer_Contact__c, coi);
			}
		}
		if (!volunteerIdCoiMap.isEmpty()) {
			ConflictOfInterestService.updateNonCurrentConflictOfInterest(volunteerIdCoiMap);
		}
		if (!updateVolunteerContact.isEmpty()) {
			update updateVolunteerContact;
		}
		if (!ownerIdCoiMap.isEmpty()) {
			ConflictOfInterestService.createRecordSharing(ownerIdCoiMap);
		}
		if (!volunteerIdCoiExpirationMap.isEmpty()) {
			VolunteerRoleService.updateNonCompliantByConflictOfInterest(volunteerIdCoiExpirationMap);
		}
		if (!volunteerIdCoiMap.isEmpty()) {
			VolunteerJourneyService.processVolunteersChapterRequirements(volunteerIdCoiMap.keySet());
		}
	}

	/**
	 * After update of Conflict Of Interest
	 */
	public override void handleAfterUpdate() {
		Map<Id, Conflict_Of_Interest__c> ownerIdCoiMap = new Map<Id, Conflict_Of_Interest__c>();
		Map<Id, Conflict_Of_Interest__c> volunteerIdCoiMap = new Map<Id, Conflict_Of_Interest__c>();
		Set<Id> volunteerContactIdSet = new Set<Id>();
		List<Contact> updateVolunteerContact = new List<Contact>();
		List<Conflict_Of_Interest__c> coiList = new List<Conflict_Of_Interest__c>();
		for (Conflict_Of_Interest__c coi : newCOIList) {
			if (coi.Expiration_Date__c != oldCOIMap.get(coi.Id).Expiration_Date__c
					&& coi.Expiration_Date__c != null) {
				if (coi.Volunteer_Contact__c != null) {
					Contact updateVolunteer = new Contact();
					updateVolunteer.Id = coi.Volunteer_Contact__c;
					updateVolunteer.COI_Expiration_Date__c = coi.Expiration_Date__c;
					updateVolunteerContact.add(updateVolunteer);
				}
			}
			coiList.add(coi);
			if (coi.HiddenConflictExpire__c == true && oldCOIMap.get(coi.Id).HiddenConflictExpire__c == false) {
				volunteerContactIdSet.add(coi.Volunteer_Contact__c);
			}
			if (coi.Current__c == true && oldCOIMap.get(coi.Id).Current__c == false) {
				volunteerIdCoiMap.put(coi.Volunteer_Contact__c, coi);
			}
			if (coi.OwnerId != oldCOIMap.get(coi.Id).OwnerId) {
				ownerIdCoiMap.put(coi.OwnerId, coi);
			}
		}
		if (!updateVolunteerContact.isEmpty()) {
			update updateVolunteerContact;
		}
		if (!ownerIdCoiMap.isEmpty()) {
			ConflictOfInterestService.createRecordSharing(ownerIdCoiMap);
		}
		if (!volunteerIdCoiMap.isEmpty()) {
			ConflictOfInterestService.updateNonCurrentConflictOfInterest(volunteerIdCoiMap);
		}
		if (!volunteerContactIdSet.isEmpty()) {
			BackgroundCheckService.updateVolunteerRoleHiddenStatus(volunteerContactIdSet, 'COI', coiList);
		}
		if (!volunteerIdCoiMap.isEmpty()) {
			VolunteerJourneyService.processVolunteersChapterRequirements(volunteerIdCoiMap.keySet());
		}
	}
}