make-a-wish-salesforce/src/objects/Constituent_Code__c.object
<CustomObject>
    <label>Constituent Code</label>
    <nameField>
        <label>Constituent Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituent Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Hospital_Treatment_Facility_Treating__c</fullName>
        <description>It holds the information about Hospital/Treatment Facility of the wish kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Contact_Id__c</fullName>
        <description>It is an hidden field. Storing the original Treating Medical Professional Contact Id. So while converting the lead, we can create a relationship under this Record instead of creating dup Treating  medical professional contact. we are capturing value for this field on Find Duplicate page.</description>
        <label>Treating Medical Professional Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>Constituent_Code__c</fullName>
        <description>It stores the value of Constituent Code</description>
        <label>Constituent Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wish Child</fullName>
                </value>
                <value>
                    <fullName>Wish Family</fullName>
                </value>
                <value>
                    <fullName>Celebrity</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Volunteer Leadership</fullName>
                </value>
                <value>
                    <fullName>Medical Professional</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Referral Source</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Intern</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Treating_Facility__c</fullName>
        <description>Ability to have multiple &quot;Current&quot; and/or multiple &quot;Previous&quot; facilities indicated in the case the child is being treated at multiple facilities</description>
        <label>Treating Facility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Previous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/AffiliationService.cls
/**
 * @description Affiliation Service, centralizes Affiliation business rules.
 * @author Gustavo Mayer, Traction on Demand
 * @createdDate 10/03/2020
 */
public class AffiliationService {

	private static final String TREATING_MED_PROFESSIONAL = Constant_AC.LEAD_DV_FORM_TYPE_TREATING_MEDICAL_PROFESSIONAL;
	private static final String BEST_CONTACT = Constant_AC.LEAD_DV_FORM_TYPE_BEST_CONTACT;
	private static final String ALT1_MED_PROFESSIONAL = Constant_AC.LEAD_DV_FORM_TYPE_ALTERNATE_1_MEDICAL_PROFESSIONAL;
	private static final String ALT2_MED_PROFESSIONAL = Constant_AC.LEAD_DV_FORM_TYPE_ALTERNATE_2_MEDICAL_PROFESSIONAL;
	private static final String CURRENT_TREATING_FACILITY = Constant_AC.ORG_AFFILIATION_TREATING_FACILITY_CURRENT;
	private final static Id HOSPITAL_TREATMENT_ID = Constant_AC.HOSPITAL_TREATMENT_ID;
	private final static String WISH_FAMILY_LABEL = Constant_AC.WISH_FAMILY_RT_LABEL;
	private final static String CONTACT_WISH_CHILD_LABEL = Constant_AC.CONTACT_WISH_CHILD_RT_LABEL;
	private final static String TREATING_FACILITY_CURRENT = Constant_AC.ORG_AFFILIATION_TREATING_FACILITY_CURRENT;

	/**
	 * Build Medical Affiliations
	 * @param convertedLead
	 * @param medicalAccountMap
	 * @return List of Affiliations
	 */
	public static List<npe5__Affiliation__c> buildHospitalMedicalAffiliations(Lead convertedLead,
			Map<String, Account> medicalAccountMap) {
		List<npe5__Affiliation__c> affiliationList = new List<npe5__Affiliation__c>();
		if (convertedLead.Hidden_DV_form_Medical_professional_Type__c != null) {
			npe5__Affiliation__c newAff = new npe5__Affiliation__c();
			newAff.npe5__Contact__c = convertedLead.ConvertedContactId;
			newAff.Treating_Facility__c = CURRENT_TREATING_FACILITY;
			if (convertedLead.Hidden_DV_form_Medical_professional_Type__c == ALT2_MED_PROFESSIONAL
					&& medicalAccountMap.containsKey(convertedLead.Alternate2HospitalTreatmentFacility__c)
					&& convertedLead.HiddenAlternate2MedProfessionalId__c == null) {
				if (medicalAccountMap.containsKey(convertedLead.Alternate2HospitalTreatmentFacility__c)) {
					newAff.npe5__Organization__c = medicalAccountMap.get(convertedLead.Alternate2HospitalTreatmentFacility__c).Id;
				}
				affiliationList.add(newAff);
			} else if (convertedLead.Hidden_DV_form_Medical_professional_Type__c == ALT1_MED_PROFESSIONAL
					&& medicalAccountMap.containsKey(convertedLead.Alternate1HospitalTreatmentFacility__c)
					&& convertedLead.HiddenAlternate1MedProfessionalId__c == null) {
				if (medicalAccountMap.containsKey(convertedLead.Alternate1HospitalTreatmentFacility__c)) {
					newAff.npe5__Organization__c = medicalAccountMap.get(convertedLead.Alternate1HospitalTreatmentFacility__c).Id;
				}
				affiliationList.add(newAff);
			} else if ((convertedLead.Hidden_DV_form_Medical_professional_Type__c == BEST_CONTACT
					|| convertedLead.Hidden_DV_form_Medical_professional_Type__c == TREATING_MED_PROFESSIONAL)
					&& medicalAccountMap.containsKey(convertedLead.Hospital_Treatment_Facility_Treating__c)
					&& convertedLead.Treating_Medical_Professional_Contact_Id__c == null) {
				if (medicalAccountMap.containsKey(convertedLead.Hospital_Treatment_Facility_Treating__c)) {
					newAff.npe5__Organization__c = medicalAccountMap.get(convertedLead.Hospital_Treatment_Facility_Treating__c).Id;
				}
				affiliationList.add(newAff);
			}
		}
		return affiliationList;
	}

	/**
	 * Build Affiliations from Lead
	 * @param existingMedicalProfIdMap
	 * @param wishChildContactMap
	 * @return List of Affiliations
	 */
	public static List<npe5__Affiliation__c> buildMedicalAndChildAffiliations(Map<Id, Lead> existingMedicalProfIdMap,
			Map<Id, Contact> wishChildContactMap){
		List<npe5__Affiliation__c> affiliationList = new List<npe5__Affiliation__c>();
		String wishFamilyRtLabel = WISH_FAMILY_LABEL;
		if (!existingMedicalProfIdMap.isEmpty() || !wishChildContactMap.isEmpty()) {
			for (npe5__Affiliation__c affiliation : [
					SELECT npe5__Organization__c, npe5__Organization__r.RecordTypeId, npe5__Contact__c, Constituent_Code__c
					FROM npe5__Affiliation__c
					WHERE (npe5__Organization__r.RecordTypeId = :HOSPITAL_TREATMENT_ID
					OR Constituent_Code__c = :wishFamilyRtLabel)
			]) {
				if (existingMedicalProfIdMap.containsKey(affiliation.npe5__Contact__c)
						&& affiliation.npe5__Organization__r.RecordTypeId == HOSPITAL_TREATMENT_ID) {
					npe5__Affiliation__c newAff = new npe5__Affiliation__c();
					newAff.npe5__Contact__c = existingMedicalProfIdMap.get(affiliation.npe5__Contact__c).ConvertedContactId;
					newAff.Treating_Facility__c = TREATING_FACILITY_CURRENT;
					newAff.npe5__Organization__c = affiliation.npe5__Organization__c;
					affiliationList.add(newAff);
				}
				if (wishChildContactMap.containsKey(affiliation.npe5__Contact__c) && affiliation.Constituent_Code__c == wishFamilyRtLabel) {
					affiliation.Constituent_Code__c = CONTACT_WISH_CHILD_LABEL;
					affiliationList.add(affiliation);
				}
			}
		}
		return affiliationList;
	}
}