make-a-wish-salesforce/src/objects/Constituent_Code__c.object
<CustomObject>
    <label>Constituent Code</label>
    <nameField>
        <label>Constituent Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituent Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>Constituent_Code__c</fullName>
        <description>It stores the value of Constituent Code</description>
        <label>Constituent Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wish Child</fullName>
                </value>
                <value>
                    <fullName>Wish Family</fullName>
                </value>
                <value>
                    <fullName>Celebrity</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Volunteer Leadership</fullName>
                </value>
                <value>
                    <fullName>Medical Professional</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Referral Source</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Intern</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Affiliation&apos;s Organization will be stored on the Contact record.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe5__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Out of Compliance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/CommunitiesLoginControllerTest.cls
/**
 * An apex page controller that exposes the site login functionality
 */
@IsTest
global class CommunitiesLoginControllerTest {

	// Login As Prospective User Profile
	static testmethod void loginAsProspectiveUser() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		npe5__Affiliation__c affiliation = OrientationandTrainingUtil.createAffiliation(con.id);
		insert affiliation;
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createProspectiveVolunteerUser(con.id);
			insert currUser;
		}
		System.RunAs(currUser) {
			CommunitiesLoginController controller = new CommunitiesLoginController();
			controller.userName = 'joathanedwards@gmail.com';
			controller.login();
		}
		System.assert(con.Id != Null, 'Id should not blank');
		System.assertEquals(currUser.ProfileId, label.Prospective_Volunteer_Profile, 'Id does not match');
	}

	// Login As Active User Profile
	static testmethod void loginAsActiveUser() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		npe5__Affiliation__c affiliation = OrientationandTrainingUtil.createAffiliation(con.id);
		insert affiliation;
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createActiveVolunteerUser(con.id);
			insert currUser;
		}
		System.RunAs(currUser) {
			CommunitiesLoginController controller = new CommunitiesLoginController();
			controller.userName = 'joathanedwards@gmail.com';
			controller.login();
		}
		System.assert(con.Id != Null, 'Id should not blank');
		System.assertEquals(currUser.ProfileId, label.Active_Volunteer_Profile, 'Id does not match');
	}

	// Creating custom setting values.
	static testmethod void createCustomSettingValueforActive() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Prospective';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createActiveVolunteerUser(con.id);
			insert currUser;
		}
		System.RunAs(currUser) {
			HoldCurrentChapter__c currVal = new HoldCurrentChapter__c();
			currVal.Name = currUser.id;
			currVal.CurrentChapter__c = acc.name;
			insert currVal;
			CommunitiesLoginController controller = new CommunitiesLoginController();
			controller.userName = 'joathanedwards@gmail.com';
			controller.login();
		}
		System.assert(con.Id != Null, 'Id should not blank');
		System.assertEquals(currUser.ProfileId, label.Active_Volunteer_Profile, 'Id does not macth');
	}

	static testmethod void withoutCustomSettingValueforActive() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		npe5__Affiliation__c neworgAffiliation = new npe5__Affiliation__c ();
		neworgAffiliation.npe5__Contact__c = con.Id;
		neworgAffiliation.npe5__Organization__c = acc.Id;
		neworgAffiliation.npe5__Primary__c = true;
		neworgAffiliation.npe5__Status__c = 'Prospective';
		neworgAffiliation.Constituent_code__c = Constant_AC.BOARD_MEMBER_RT_LABEL;
		insert neworgAffiliation;
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createActiveVolunteerUser(con.id);
			insert currUser;
		}
		System.RunAs(currUser) {
			CommunitiesLoginController controller = new CommunitiesLoginController();
			controller.userName = 'joathanedwards@gmail.com';
			controller.login();
		}
		System.assert(con.Id != Null, 'Id should not blank');
		System.assertEquals(currUser.ProfileId, label.Active_Volunteer_Profile, 'Id does not match');
	}

	// Login as wrong user.
	static testmethod void loginAsWrongUser() {
		Account acc = OrientationandTrainingUtil.createVolunteerAccount();
		insert acc;
		Contact con = OrientationandTrainingUtil.createVolunteerContact(acc.id);
		insert con;
		npe5__Affiliation__c affiliation = OrientationandTrainingUtil.createAffiliation(con.id);
		insert affiliation;
		User currUser;
		System.RunAs(new User(Id = UserInfo.getUserId())) {
			currUser = OrientationandTrainingUtil.createActiveVolunteerUser(con.id);
			insert currUser;
		}
		System.RunAs(currUser) {
			CommunitiesLoginController controller = new CommunitiesLoginController();
			controller.userName = 'vennila@gmail.com';
			controller.login();
		}
		System.assert(con.Id != Null, 'Id should not blank');
		// System.assertEquals(currUser.ProfileId,  label.Active_Volunteer_Profile);
	}
}