make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_last_engagement__c</fullName>
        <description>It capture the volunteer last engagement  date.</description>
        <label>Date Of Last Engagement</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>Event date indicated when the event started</description>
        <formula>Non_Wish_Event__r.Event_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_UpdateVolunteerLastEngage.cls
/**
* Updates volunteer date of last engagement to most recent non-wish event
*/
global class batch_UpdateVolunteerLastEngage implements Database.Batchable<AggregateResult>, Schedulable {
    
    private final static Id NON_WISH_EVENT_RT_ID = Constant_AC.NON_WISH_EVENT_RT_ID;
    
    global Iterable<AggregateResult> start(Database.BatchableContext bc) {
        return [
            SELECT Max(Event_date__c)eventDate, Volunteer_Name__c
            FROM Volunteer_Opportunity__c
            WHERE Event_date__c < :Date.today() AND RecordTypeId = :NON_WISH_EVENT_RT_ID
            GROUP BY Volunteer_Name__c
        ];
    }
    
    global void execute(Database.BatchableContext bc, List<AggregateResult> nonWishEventList) {
        List<Contact> updateContactList = new List<Contact>();
        Map<String, Date> eventDateMap = new Map<String, Date>();
        for(AggregateResult getRec : nonWishEventList) {
            String currVol = String.valueOf(getRec.get('Volunteer_Name__c'));
            Date eventDate = Date.valueOf(getRec.get('eventDate'));
            eventDateMap.put(currVol, eventDate);
        }
        
        for(Contact currCon : [
            SELECT Id, Date_of_last_engagement__c
            FROM Contact
            WHERE Id IN :eventDateMap.keySet()
        ]) {
            if(currCon.Date_of_last_engagement__c == null || eventDateMap.get(currCon.Id) > currCon.Date_of_last_engagement__c) {
                Contact currContact = new Contact();
                currContact.Id = currcon.Id;
                currContact.Date_of_last_engagement__c = eventDateMap.get(currCon.Id);
                updateContactList.add(currContact);
            }
        }
        update updateContactList;
    }
    
    global void finish(Database.BatchableContext bc) {
    }
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new batch_UpdateVolunteerLastEngage(), 25);
    }
}