make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Part_A_Received__c</fullName>
        <description>This field will capture the date when the status is changed Part A Sent to Eligibility Review/Qualified</description>
        <label>Diagnosis Verification Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Part_A_Sent__c</fullName>
        <description>This will capture the date when the lead status is changed from Referred to Part A Sent</description>
        <label>Diagnosis Verification Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Child_Age__c</fullName>
        <description>It would capture the child of the age.</description>
        <label>Child Age</label>
        <picklist>
            <picklistValues>
                <fullName>Under 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18 &amp; Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_this_child_ever_received_prior_wish__c</fullName>
        <description>Has this child ever received a prior wish from MAW or any other wish granting organization?</description>
        <inlineHelpText>Has this child ever received a prior wish from MAW or any other wish granting organization?</inlineHelpText>
        <label>Has this child ever received prior wish?</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Hospital_Treatment_Facility_Treating__c</fullName>
        <description>It holds the information about Hospital/Treatment Facility of the wish kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Of_Times_Email_Sent__c</fullName>
        <label># Of Times Email Sent</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_A_Received__c</fullName>
        <description>This field will capture the date when the status is changed Part A Sent to Eligibility Review/Qualified</description>
        <label>Diagnosis Verification Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Part_A_Sent__c</fullName>
        <description>This will capture the date when the lead status is changed from Referred to Part A Sent</description>
        <label>Diagnosis Verification Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It will hold the firstname of the child.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_child__c</fullName>
        <description>This field is used to store the relationship of the person who submits the Wish Kid details</description>
        <label>Relationship to child</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Member/Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Email__c</fullName>
        <description>This field will hold the Treating Medical Professional Email Address</description>
        <label>Treating Medical Professional Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the Treating Medical Professional First Name</description>
        <label>Treating Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Last_Name__c</fullName>
        <description>This field will hold the details about Treating Medical Professional Name</description>
        <label>Treating Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to verify the document is signed or not from docusign.</description>
        <label>isSign</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>Contact_Dup_Check__c</fullName>
        <description>Hidden field for checking contact dup</description>
        <label>Contact Dup Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Block Contact Dup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>Dup_Check__c</fullName>
        <description>This hidden field used in lead duplicate page.</description>
        <label>Dup Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Block Lead Dup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

make-a-wish-salesforce/src/classes/SendDiagnosisVerficationLC_AC.cls
/**
 * Author      : MST Solutions
 * CreatedBy   : Vignesh SM
 * Date        : 13/03/2018
 * Description : Class contains AURA enbaled utility methods used by the SendDiagnosisVerficationLC component
 * Modification Log:
 * 1. 03/28/2018 - Yuvraj - IME-59 - Line No: 22Hospital_Treatment_Facility_Treating__c
 * 2. 04/12/2018 - Yuvraj - IME-77 - Line:No: 32
 * 3. 06/03/3030- Brittany - SIW-543
 **/
public without sharing class SendDiagnosisVerficationLC_AC {

    /*
     * @description     Get the necessary lead information for further process of sending diagnosis verification
     * @param           Id leadId`
     * @return          String
     * @date            unknown
     * @author          MST Solutions
    */
    @AuraEnabled
    public static Lead getLeadInformation(Id leadId) {
        Lead data = [
                SELECT Id, Has_this_child_ever_received_prior_wish__c, Contact_Dup_Check__c,
                        Using_Paper_Process_For_DV__c, Status,Dup_Check__c, Sub_Status__c, Part_A_Sent__c,
                        HiddenMedicalProfessionalEmail__c, Pending_Diagnosis_Date__c, PD_ICD_Code__c,
                        PD_Condition_Description__c, Of_Times_Email_Sent__c, Part_A_Received__c,
                        isSign__c, Child_Age__c, Relationship_to_child__c, Referring_MP__c, Referring_MP_HTF__c,
                        Referrer_FirstName__c, Referrer_Last_Name__c, Referring_MP_HTF_Name__c,
                        Treating_MP__c, Treating_MP_HTF__c, Hospital_Treatment_Facility_Treating__c,
                        Treating_Medical_Professional_First_Name__c, Treating_Medical_Professional_Last_Name__c,
                        Treating_Medical_Professional_Email__c, Best_Contact__c, Best_Contact_HTF__c,
                        Best_Contact_HTF_Name__c, Best_Contact_for_Physician_First_Name__c,
                        Best_Contact_for_Physician_Last_Name__c, Best_contact_for_Physician_Email__c,
                        Alternate1MedicalProfessionalEmail__c, Alternate2MedProfessionalEmail__c
                FROM Lead
                WHERE Id = :leadId
                AND RecordTypeId = :Constant_AC.LEAD_RT_WISH_CHILD
        ];
        return data;
    }

    /*
     * @description     Wrapper method to call reset DV medical summary
     * @param           Id leadId
     * @return          String
     * @date            unknown
     * @author          MST Solutions
    */
    @AuraEnabled
    public static String resetDVMedicalSummary(Id leadId) {
        String result = LeadDuplicateService.resetDVMedicalSummary(leadId);
        return result;
    }

    /*
     * @description     Wrapper method to call Find Lead Dupe
     * @param           Id leadId
     * @return          String
     * @date            unknown
     * @author          MST Solutions
    */
    @AuraEnabled
    public static String findLeadDupe(Id leadId) {
        String result = LeadDuplicateService.FindLeadDupe(leadId);
        return result;
    }

    /*
     * @description     Wrapper method to call Find Family Contact Dupe
     * @param           Id leadId
     * @return          String
     * @date            unknown
     * @author          MST Solutions
    */
    @AuraEnabled
    public static String findFamilyContactDupe(Id leadId) {
        String result = LeadDuplicateService.FindFamilyContactDupe(leadId);
        return result;
    }

    /*
     * @description     Update the lead appropriate information when the diagnosis verification has been sent
     * @param           Id leadId
     * @return          String
     * @date            unknown
     * @author          MST Solutions
    */
    @AuraEnabled
    public static String updateLead(Id leadId, String HiddenDVformMedicalprofessionalType, Integer OfTimesEmailSent, String HiddenMedicalProfessionalEmail, String SubStatus) {
        Lead currLead = new Lead();
        currLead.Id = leadId;
        currLead.HiddenMedicalProfessionalEmail__c = HiddenMedicalProfessionalEmail;
        currLead.Hidden_DV_form_Medical_professional_Type__c = HiddenDVformMedicalprofessionalType;
        currLead.Of_Times_Email_Sent__c = Integer.valueOf(OfTimesEmailSent);
        currLead.Sub_Status__c = SubStatus;
        currLead.Pending_Diagnosis_Date__c = Date.today();//IME-77
        update currLead;
        return 'UPDATED';
    }
}