make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Diagnosis_Given_By_Referrer__c</fullName>
        <description>Used to hold the diagnosis given by referrer</description>
        <label>Diagnosis Given By Referrer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>It will hold the gender information.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Self-describe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ICD_10_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold the ICD-10 code.</description>
        <label>Primary ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate the wish Child Family aware of Referral at MAWA.</description>
        <label>Is Family Aware Of Referral?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wish referrer.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture the referrer Email.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It capture the wish child Referrer name.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It capture the wish referrer Zip code.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Angina__c</fullName>
        <description>It will hold the value of angina travel algorithm.</description>
        <label>Angina</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Any_medical_reason_for_moving_quickly__c</fullName>
        <description>Is there a medical reason why we need to move quickly?</description>
        <inlineHelpText>Is there a medical reason why we need to move quickly?</inlineHelpText>
        <label>Any medical reason for moving quickly?</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Arrhythmia__c</fullName>
        <description>it will hold the value of Arrhythmia Travel Algorithm.</description>
        <label>Arrhythmia</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chronic_Heart_Failure__c</fullName>
        <description>It will hold the value of Chronic Heart Failure Travel Algorithm value.</description>
        <label>Chronic Heart Failure</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chronic_Hepatitis__c</fullName>
        <description>It will hold the Travel Algorithm additional question values.</description>
        <label>Chronic Hepatitis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Congenital_Heart_Disease__c</fullName>
        <description>It will hold the value of Travel Algorithm&apos;s Congenital_Heart_Disease value.</description>
        <label>Congenita Heart Disease</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Convulsive_Disorders__c</fullName>
        <description>It will hold the value of Conclusive Disorder&apos;s Travel Algorithm.</description>
        <label>Convulsive Disorders</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Heart_Failure__c</fullName>
        <description>It will hold the value of Heart_Failure travel algorithm.</description>
        <label>Heart Failure</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ICD_10_Code__c</fullName>
        <description>This field will hold the ICD-10 code.</description>
        <label>ICD-10 Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>I_am_Recognized_To_Practice_As_a__c</fullName>
        <description>It will hold which type of practice she/he is going to get</description>
        <label>I am Recognized To Practice As a</label>
        <picklist>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse Practitioner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Life Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lung_Disease__c</fullName>
        <label>Lung Disease</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Medical_Questions__c</fullName>
        <description>Holds all medical Questions</description>
        <label>Medical Questions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pulmonary_Hypertension__c</fullName>
        <description>It hold the value of Travel Algorithm additional questions.</description>
        <label>Pulmonary Hypertension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wih&apos;s parent.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture email address of wish parent from referral form.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It will hold the firstname of the child.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It will capture the zipcode of wish&apos;s parent.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_child__c</fullName>
        <description>This field is used to store the relationship of the person who submits the Wish Kid details</description>
        <label>Relationship to child</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Member/Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sibling_Detail__c</fullName>
        <description>It will hold the sibling name and age details.</description>
        <label>Sibling Detail</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Strokes__c</fullName>
        <description>It will hold the value of Travel Algorithm additional questions. Hidden field.</description>
        <label>Strokes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_algorithm__c</fullName>
        <description>Used to store travel checklists</description>
        <label>Travel algorithm</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ventilator__c</fullName>
        <description>It will hold the value of Ventilator travel algorithm.</description>
        <label>Ventilator</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Wish_Family_ContactId__c</fullName>
        <description>It is an hidden field. Storing the original Wish Family Contact Id. So while converting the lead, we can create a relationship under this wish Family Record instead of creating dup wish family. we are capturing value for this field on Find Duplicate page.</description>
        <label>Wish Family ContactId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to verify the document is signed or not from docusign.</description>
        <label>isSign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/ContactFileServiceTest.cls
@IsTest
public class ContactFileServiceTest {

	@TestSetup
	public static void setUp() {
		trac_TriggerHandlerBase.blockTrigger = true;

		List<Account> accounts = TestDataFactory.createAccount(1);
		Account account = accounts.get(0);
		account.Name = 'Make-A-Wish Arizona';
		account.RecordTypeId = Constant_AC.CHAPTER_RT_ID;
		insert accounts;

		List<ICD_Codes__c> icdCodes = TestDataFactory.createIcdCode(1);
		ICD_Codes__c icdCode = icdCodes.get(0);
		insert icdCode;

		List<Contact> contacts = TestDataFactory.createContact(1);
		Contact contact1 = contacts.get(0);
		contact1.FirstName = 'Jack';
		contact1.LastName = 'Smith';
		contact1.AccountId = account.Id;
		contact1.ICD_10_Code__c = icdCode.Id;
		insert contacts;

		List<Lead> leads = TestDataFactory.createLead(1);
		Lead qualifiedLead = leads.get(0);
		qualifiedLead.RecordTypeId = Constant_AC.LEAD_RT_WISH_CHILD;
		qualifiedLead.ChapterName__c = account.Id;
		qualifiedLead.FirstName = 'Jack';
		qualifiedLead.LastName = 'Smith';
		qualifiedLead.Hidden_Chapter_Change_Confirmation__c = account.Id;
		qualifiedLead.Diagnosis_Given_By_Referrer__c = 'Test Diagnosis';
		qualifiedLead.PD_ICD_Code__c = icdCode.Id;
		qualifiedLead.Phone = '9600467559';
		qualifiedLead.Email = 'testmawa@email.com';
		qualifiedLead.Street = 'KuttaiKarai Street';
		qualifiedLead.StateCode = 'AZ';
		qualifiedLead.City = 'Phoenix';
		qualifiedLead.PostalCode = '840001';
		qualifiedLead.CountryCode = 'US';
		qualifiedLead.DOB__c = System.today() - 1435;
		qualifiedLead.Company = 'MAW';
		qualifiedLead.Status = Constant_AC.LEAD_STATUS_REFERRED;
		qualifiedLead.Gender__c = 'Male';
		qualifiedLead.I_am_Recognized_To_Practice_As_a__c = 'Physician';
		qualifiedLead.Any_medical_reason_for_moving_quickly__c = 'No';
		qualifiedLead.Referrer_FirstName__c = 'SteveJune';
		qualifiedLead.Referrer_Last_Name__c = 'Waughone';
		qualifiedLead.Referrer_Email__c = 'testmawa2d@email.com';
		qualifiedLead.Referrer_Phone__c = '9600467578';
		qualifiedLead.Referrer_City__c = 'Trichy';
		qualifiedLead.Referrer_Zip__c = '6210';
		qualifiedLead.PD_Condition_Description__c = 'Test Diagnosis';
		qualifiedLead.Wish_Family_ContactId__c = contact1.Id;
		qualifiedLead.Hidden_DV_form_Medical_professional_Type__c = Constant_AC.LEAD_DV_FORM_TYPE_TREATING_MEDICAL_PROFESSIONAL;
		qualifiedLead.is_Family_Aware_of_Referral__c = 'Yes';
		qualifiedLead.Medical_Questions__c = 'Test Diagnosis';
		qualifiedLead.Lung_Disease__c = 'Test1;Test2';
		qualifiedLead.Angina__c = 'Test1;Test2';
		qualifiedLead.Ventilator__c = 'Test1;Test2';
		qualifiedLead.Arrhythmia__c = 'Test1;Test2';
		qualifiedLead.Heart_Failure__c = 'Test1;Test2';
		qualifiedLead.Congenital_Heart_Disease__c = 'Test1;Test2';
		qualifiedLead.Chronic_Hepatitis__c = 'Test1;Test2';
		qualifiedLead.Convulsive_Disorders__c = 'Test1;Test2';
		qualifiedLead.Pulmonary_Hypertension__c = 'Test1;Test2';
		qualifiedLead.Strokes__c = 'Test1;Test2';
		qualifiedLead.Chronic_Heart_Failure__c = 'Test1;Test2';
		qualifiedLead.isSign__c = true;
		qualifiedLead.Travel_algorithm__c = 'Test1;Test2;';
		qualifiedLead.Sibling_Detail__c = 'aa | aaab | 14 <br> bbb | bbbc | 15 <br>';
		qualifiedLead.Relationship_to_child__c = Constant_AC.MEDICAL_PROFESSIONAL_RT_LABEL;
		insert leads;

		qualifiedLead.Sub_Status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
		update qualifiedLead;

		List<cg__Lead_File__c> leadFileList = TestDataFactory.createLeadFile(1);
		cg__Lead_File__c leadFileFrieda = leadFileList.get(0);
		leadFileFrieda.cg__Lead__c = qualifiedLead.Id;
		leadFileFrieda.cg__Description__c = 'Medical Information for Frieda Crowley';
		leadFileFrieda.File_Path__c = 'TestPath';
		insert leadFileList;

		cg__ContactFile__c contactFolder = new cg__ContactFile__c();
		contactFolder.cg__File_Name__c = 'Documents';
		contactFolder.cg__Contact__c = contact1.Id;
		contactFolder.cg__Content_Type__c = Constant_AC.FILE_CONTENT_TYPE_FOLDER;
		insert contactFolder;
		cg__ContactFile__c contactFile = new cg__ContactFile__c();
		contactFile.cg__File_Name__c = 'MedicalSummary2.txt';
		contactFile.cg__Contact__c = contact1.Id;
		contactFile.cg__Content_Type__c = Constant_AC.FILE_NAME_DOCUMENTS;
		insert contactFile;

		trac_TriggerHandlerBase.blockTrigger = false;
	}

	@IsTest
	public static void shouldBuildFileFoldersLeadConvert() {
		Contact contact = [
				SELECT Id
				FROM Contact
				WHERE Name = 'Jack Smith'
		];

		ContactFileService.buildFileFoldersLeadConvert(contact.Id);
	}

	@IsTest
	public static void shouldBuildFilesLeadConvert() {
		Lead leadToConvert = [
				SELECT Id
				FROM Lead
				LIMIT 1
		];
		LeadStatus convertStatus = [
				SELECT MasterLabel
				FROM LeadStatus
				WHERE IsConverted = TRUE
				LIMIT 1
		];
		Database.LeadConvert lc = new Database.LeadConvert();
		lc.setLeadId(leadToConvert.Id);
		lc.setDoNotCreateOpportunity(true);
		lc.setConvertedStatus(convertStatus.MasterLabel);
		Database.convertLead(new List<Database.LeadConvert>{lc});
		Lead convertedLead = [
				SELECT Id, ConvertedContactId
				FROM Lead
				LIMIT 1
		];

		ContactFileService.buildFilesLeadConvert(new Map<Id, Lead>{
				convertedLead.Id => convertedLead
		});
	}

	@IsTest
	public static void shouldUpdateContactFilePath() {
		List<cg__ContactFile__c> contactFiles = [
				SELECT Id
				FROM cg__ContactFile__c
		];

		ContactFileService.updateContactFilePath(contactFiles);
	}

	@IsTest
	public static void shouldUpdateContactFileFolderId() {
		List<cg__ContactFile__c> contactFiles = [
				SELECT Id, cg__Contact__c, cg__Content_Type__c, cg__Parent_Folder_Id__c
				FROM cg__ContactFile__c
		];

		ContactFileService.updateContactFileFolderId(contactFiles);
	}
}