make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_last_engagement__c</fullName>
        <description>It capture the volunteer last engagement  date.</description>
        <label>Date Of Last Engagement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Continuing_Edu_Date__c</fullName>
        <description>Completed Date for most recent training</description>
        <label>Last Continuing Edu. Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Migrated_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It indicated the record is created by manually or from mulesoft.</description>
        <label>Migrated Record</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Orientation_Training__c.object
<CustomObject>
    <description>It is a junction object for volunteer and Orientation &amp; Training  object. It will capture the volunteer and his completed  training information details</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>It will capture information about whether it is a orientation or training</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Orientation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to Volunteer Contact records</description>
        <label>Volunteer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Orientation &amp; Trainings</relationshipLabel>
        <relationshipName>Volunteer_Orientation_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Orientation &amp; Training</label>
    <nameField>
        <displayFormat>VOT-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Orientation &amp; Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_UpdatLastEduDate.cls
global class batch_UpdatLastEduDate implements Database.Batchable<AggregateResult>{ 

  
     
    
     global Iterable<AggregateResult> start(Database.BatchableContext bc){ 
     
         list<AggregateResult> volunteerOppList = [SELECT Volunteer__c FROM Volunteer_Orientation_Training__c 
                                                     WHERE RE_Completed_Date__c !=Null
                                                     AND Volunteer__c != Null AND Type__c = 'Training' 
                                                     AND Migrated_Record__c = True
                                                     GROUP BY Volunteer__c];
        
         return volunteerOppList;                      
                                
     }
     
    
     global void execute(Database.BatchableContext bc, list<AggregateResult> scope)
     {
           Set<Id> volunteerIds = new Set<Id>();
           for(AggregateResult currVol : scope)
           {
              volunteerIds.add(String.valueOf(currVol.get('Volunteer__c')));
           }  
           
           Map<Id,Date> volunteerTrainedDate = new Map<Id,Date>();
           for(Volunteer_Orientation_Training__c currRec : [SELECT Id, RE_Completed_Date__c,Volunteer__c FROM Volunteer_Orientation_Training__c 
                                                            WHERE RE_Completed_Date__c !=Null AND Volunteer__c IN :volunteerIds
                                                            AND Volunteer__c != Null AND Type__c = 'Training' AND Migrated_Record__c = True])
           {
             string dateVal = currRec.RE_Completed_Date__c.subString(0,10);
             if(volunteerTrainedDate.containsKey(currRec.Volunteer__c))
             {
                if(volunteerTrainedDate.get(currRec.Volunteer__c) < Date.valueOf(dateVal)) 
                  volunteerTrainedDate.put(currRec.Volunteer__c,Date.valueOf(dateVal));
                     
             }
             else
                 volunteerTrainedDate.put(currRec.Volunteer__c,Date.valueOf(dateVal));
                
           }
           
           List<Contact> updateContacts = new List<Contact>();
           
           for(String currId : volunteerTrainedDate.KeySet())
           {
               Contact currContact = new Contact();
               currContact.id = currId;
               currContact.Last_Continuing_Edu_Date__c = volunteerTrainedDate.get(currId);
               currContact.Date_of_last_engagement__c = volunteerTrainedDate.get(currId);
               updateContacts.add(currContact);
           }
           
           if(updateContacts.size() > 0)
               update updateContacts;
           
       }


      global void finish(Database.BatchableContext bc)
      {
      
      }


}