make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ICD_10_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold the ICD-10 code.</description>
        <label>Primary ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Affiliation__c.object
<CustomObject>
    <description>A junction object between the Wish (Case) and Contacts to track individuals related to a particular Wish.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>A Wish Affiliation's related Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Wish Affiliations</relationshipLabel>
        <relationshipName>Wish_Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wish_Affiliation_Type__c</fullName>
        <description>Captures the type/status of the Wish Affiliated contact.</description>
        <label>Wish Affiliation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved Participant</fullName>
                </value>
                <value>
                    <fullName>Requested Participant</fullName>
                </value>
                <value>
                    <fullName>Declined Participant</fullName>
                </value>
                <value>
                    <fullName>Medical Professional</fullName>
                </value>
                <value>
                    <fullName>Guardian of Minor Participant</fullName>
                </value>
                <value>
                    <fullName>Wish Child</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wish__c</fullName>
        <description>The Wish Affiliation's related Wish.</description>
        <label>Wish</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Wish (case) record type must be of the type 'Wish'.</errorMessage>
            <filterItems>
                <field>Case.RecordType.Name</field>
                <operation>equals</operation>
                <value>Wish</value>
            </filterItems>
            <infoMessage>The Wish (Case) record type must be of the type 'Wish'.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Wish Affiliations</relationshipLabel>
        <relationshipName>Wish_Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wish Affiliation</label>
    <nameField>
        <displayFormat>WA-{00000}</displayFormat>
        <label>Wish Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Signature_Chapter_Form__c.object
<CustomObject>
    <description>Contains the record set of Wish Signature Forms that relate to the needs of a specific chapter.</description>
    <fields>
        <fullName>Chapter_Account__c</fullName>
        <description>The related Chapter Account for this Wish Signature Chapter Form record.</description>
        <label>Chapter Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wish Signature Chapter Forms</relationshipLabel>
        <relationshipName>Wish_Signature_Chapter_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wish_Signature_Form__c</fullName>
        <description>The related Wish Signature Form associated with this Wish Signature Chapter Form record.</description>
        <label>Wish Signature Form</label>
        <referenceTo>Wish_Signature_Forms__c</referenceTo>
        <relationshipLabel>Chapter Forms</relationshipLabel>
        <relationshipName>Wish_Signature_Chapter_Forms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wish Signature Chapter Form</label>
    <nameField>
        <displayFormat>WSCF-{000}</displayFormat>
        <label>Wish Signature Chapter Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Signature Chapter Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Signature_Forms__c.object
<CustomObject>
    <description>Contains the master data set of Wish Required Form records which are utilized selectively by affiliated chapters via the Junction object &apos;Wish Signature Chapter Forms&apos; Object records.</description>
    <fields>
        <fullName>Form_Type__c</fullName>
        <description>The type of signature required: medical or family (i.e. from a participant, family member or household member of the Wish Child). This value gets written to the Type field of the Wish Required SIgnature.</description>
        <inlineHelpText>Family forms are signed by a family member of the Wish Child or participant. Medical forms are signed by a designated medical professional.</inlineHelpText>
        <label>Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Wish Signature Form</label>
    <nameField>
        <label>Wish Signature Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wish Signature Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/CustomLookUpController_Test.cls
@isTest
public class CustomLookUpController_Test 
{
    private final static Id CHAPTER_RECORD_TYPE_ID = Constant_AC.CHAPTER_RT_ID;
    private final static Id WISH_RECORD_TYPE_ID = Constant_AC.WISH_RT_ID;
    private final static Id WISH_FAMILY_RECORD_TYPE_ID = Constant_AC.WISH_FAMILY_RT_ID;
    private final static Id HOUSEHOLD_RECORD_TYPE_ID = Constant_AC.HOUSEHOLD_RT_ID;
    private final static Id WISH_CHILD_RECORD_TYPE_ID = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
    private final static Id MEDICAL_PROF_RECORD_TYPE_ID = Constant_AC.MEDICAL_PROFESSIONAL_RT_ID;
    
    
    @TestSetup
    private static void insertTestData() {
        trac_TriggerHandlerBase.blockTrigger = true;
        List<Account> accountsDataFactory = TestDataFactory.createAccount(2);
        accountsDataFactory[0].RecordTypeId = HOUSEHOLD_RECORD_TYPE_ID;
        accountsDataFactory[1].RecordTypeId = CHAPTER_RECORD_TYPE_ID  ;  
        insert accountsDataFactory;
        
        ICD_Codes__c obj = new ICD_Codes__c();
        obj.Name = 'Q917';
        insert obj;
        List<Contact> contactsDataFactory = TestDataFactory.createContact(4);
        contactsDataFactory[0].RecordTypeId = WISH_CHILD_RECORD_TYPE_ID;
        contactsDataFactory[0].ICD_10_Code__c = obj.Id;
        contactsDataFactory[1].RecordTypeId = WISH_FAMILY_RECORD_TYPE_ID;
        contactsDataFactory[1].BirthDate = System.today().addYears(-20);
        contactsDataFactory[2].RecordTypeId = MEDICAL_PROF_RECORD_TYPE_ID;
        contactsDataFactory[3].RecordTypeId = WISH_FAMILY_RECORD_TYPE_ID;
        contactsDataFactory[3].BirthDate = System.today().addYears(-10);
        insert  contactsDataFactory;
        
        List<Case> casesDataFactory = TestDataFactory.createCase(1);
        casesDataFactory[0].RecordTypeId = WISH_RECORD_TYPE_ID;
        casesDataFactory[0].ChapterName__c =  accountsDataFactory[1].Id;
        casesDataFactory[0].AccountId =  accountsDataFactory[0].Id;
        casesDataFactory[0].ContactId =  contactsDataFactory[0].Id;
        casesDataFactory[0].Origin = 'Email';
        casesDataFactory[0].Status = 'Qualified';
        insert casesDataFactory;
        
        List<Wish_Affiliation__c> wishAffiliationsDataFactory = TestDataFactory.createWishAffiliation(2);
        wishAffiliationsDataFactory[0].Contact__c = contactsDataFactory[1].Id;
        wishAffiliationsDataFactory[0].Wish_Affiliation_Type__c = 'Approved Participant' ;
        wishAffiliationsDataFactory[0].Wish__c = casesDataFactory[0].Id;
        wishAffiliationsDataFactory[1].Contact__c = contactsDataFactory[3].Id;
        wishAffiliationsDataFactory[1].Wish_Affiliation_Type__c = 'Approved Participant' ;
        wishAffiliationsDataFactory[1].Wish__c = casesDataFactory[0].Id;
        insert wishAffiliationsDataFactory;
        
        List<Wish_Signature_Forms__c> wishSignFormsDataFactory  = TestDataFactory.createWishSignatureForm(1);
        wishSignFormsDataFactory[0].Form_Type__c = 'Medical';
        insert wishSignFormsDataFactory;
        
        List<Wish_Signature_Chapter_Form__c> wishSignChapFormsDataFactory = TestDataFactory.createWishSignatureChapterForm(1);
        wishSignChapFormsDataFactory[0].Chapter_Account__c = accountsDataFactory[1].Id;
        wishSignChapFormsDataFactory[0].Wish_Signature_Form__c = wishSignFormsDataFactory[0].Id;
        insert wishSignChapFormsDataFactory;
        trac_TriggerHandlerBase.blockTrigger = false;
    }
    
    public static testmethod void customLookUp()
    {   
        Contact confamily = OrientationandTrainingUtil.CreateWishFamily();
        List<String> additionalAttributes = new List<String>();
        additionalAttributes.add('Email');
        additionalAttributes.add('Phone');
        customLookUpController.fetchLookUpValues('MAWAFirstName','Contact',additionalAttributes,null,'');
    }
    
    @isTest
    public static void testWishSignature(){
        Test.startTest();
        Case wishCase = [SELECT Id FROM Case LIMIT 1];
        system.assertEquals(true, wishCase != null);
        List<sObject> objList = customLookUpController.fetchLookUpValues('Medical','Wish_Signature_Forms__c',new List<String>(),wishCase.Id,'Medical');
        system.assertEquals(true, !objList.isEmpty());
        Test.stopTest();
    }
    
    @isTest
    public static void testContact(){
        Test.startTest();
        Case wishCase = [SELECT Id FROM Case LIMIT 1];
        system.assertEquals(true, wishCase != null);
        List<sObject> objList = customLookUpController.fetchLookUpValues('John','Contact',new List<String>(),wishCase.Id,'Family');
        system.assertEquals(true, !objList.isEmpty());
        List<sObject> objectList = customLookUpController.fetchLookUpValues('John','Contact',new List<String>(),wishCase.Id,'');
        system.assertEquals(true, !objectList.isEmpty());
        Test.stopTest();
    }
}