make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_last_engagement__c</fullName>
        <description>It capture the volunteer last engagement  date.</description>
        <label>Date Of Last Engagement</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will define the location of the event</description>
        <label>Chapter</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>It store the event date field</description>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>It holds the name of the Event.</description>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>Event date indicated when the event started</description>
        <formula>Non_Wish_Event__r.Event_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>This Holds the value of event name</description>
        <formula>Non_Wish_Event__r.Event_Name__c</formula>
        <label>Non-WIsh/Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Wish_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It hold the record of each event</description>
        <label>Name</label>
        <referenceTo>Non_Wish_Events__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Wish</fullName>
        <active>true</active>
        <description>This record type would associate the volunteer to the wish</description>
        <label>Wish</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_UpdateVolunteerLastEngageTest.cls
@isTest
private class batch_UpdateVolunteerLastEngageTest {
    
    private final static Id CHAPTER_RT_ID = Constant_AC.CHAPTER_RT_ID;
    private final static Id VOLUNTEER_RT_ID = Constant_AC.VOLUNTEER_RT_ID;
    private final static Id NON_WISH_EVENT_RT_ID = Constant_AC.NON_WISH_EVENT_RT_ID;
    private final static Date fiveDaysPast = Date.today().addDays(-5);
    
    @TestSetup
    private static void setup() {
        trac_TriggerHandlerBase.blockTrigger = true;
        
        List<Account> accounts = TestDataFactory.createAccount(1);
        Account accountAzChapter = accounts.get(0);
        accountAzChapter.Name = 'Make-A-Wish Arizona';
        accountAzChapter.RecordTypeId = CHAPTER_RT_ID;
        insert accounts;
        
        List<Contact> contactList = TestDataFactory.createContact(1);
        Contact volunteerAgnes = contactList.get(0);
        volunteerAgnes.RecordTypeId = VOLUNTEER_RT_ID;
        volunteerAgnes.AccountId = accountAzChapter.Id;
        volunteerAgnes.FirstName = 'Agnes';
        volunteerAgnes.LastName = 'Reynolds';
        insert contactList;
        
        List<Non_Wish_Events__c> nonWishEvents = TestDataFactory.createNonwishEvent(2);
        Non_Wish_Events__c nonWishEventMeetup = nonWishEvents.get(0);
        nonWishEventMeetup.Event_Name__c = 'Team Engagement Meeting';
        nonWishEventMeetup.Chapter__c = accountAzChapter.Id;
        nonWishEventMeetup.Event_Date__c = Date.today().addDays(-7);
        Non_Wish_Events__c nonWishEventTraining = nonWishEvents.get(1);
        nonWishEventTraining.Event_Name__c = 'Volunteer Training Updates';
        nonWishEventTraining.Chapter__c = accountAzChapter.Id;
        nonWishEventTraining.Event_Date__c = fiveDaysPast;
        insert nonWishEvents;
        
        List<Volunteer_Opportunity__c> volOppsList = TestDataFactory.createVolunteerOpportunity(2);
        Volunteer_Opportunity__c volOpp1 = volOppsList.get(0);
        volOpp1.Volunteer_Name__c = volunteerAgnes.Id;
        volOpp1.Non_Wish_Event__c = nonWishEventMeetup.Id;
        volOpp1.RecordTypeId = NON_WISH_EVENT_RT_ID;
        Volunteer_Opportunity__c volOpp2 = volOppsList.get(1);
        volOpp2.Volunteer_Name__c = volunteerAgnes.Id;
        volOpp2.Non_Wish_Event__c = nonWishEventTraining.Id;
        volOpp2.RecordTypeId = NON_WISH_EVENT_RT_ID;
        insert volOppsList;
        
        trac_TriggerHandlerBase.blockTrigger = false;
    }
    
    @isTest
    private static void validateBatchUpdate() {
        Test.startTest();
        Database.executeBatch(new batch_UpdateVolunteerLastEngage());
        Test.stopTest();
        Contact contactAgnes = [
            SELECT Id, Date_of_last_engagement__c 
            FROM Contact
            WHERE Name = 'Agnes Reynolds'];
        system.assert(contactAgnes.Date_of_last_engagement__c == fiveDaysPast);
    }
    
    @isTest
    private static void validateScheduler() {
        test.startTest();
        String CRON_EXP = '0 0 23 * * ? *';
        System.schedule('testJobSchedule', CRON_EXP, new batch_UpdateVolunteerLastEngage());
        test.stopTest();
        List<AsyncApexJob> batchJobs = [
            SELECT Id, ApexClass.Name 
            FROM AsyncApexJob 
            WHERE JobType = 'ScheduledApex'
            AND ApexClass.Name = 'batch_UpdateVolunteerLastEngage'];
        system.assert(!batchJobs.isEmpty());
    }
}