make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Hidden_Medical_Physician_Email__c</fullName>
        <description>This field is used to store the medical professional email address for docusign purpose.</description>
        <label>Wish Clearance Medical Physician Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hidden_Medical_Physician__c</fullName>
        <description>This field is used to store the treating medical professional name for docusign purpose.</description>
        <label>Wish Clearance Medical Physician</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>It will hold the value of middle name.</description>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <description>This field will used to store all related contact  in the relationship object record of the wish child</description>
        <label>Hidden Parent/Legal Guardian</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>This field is used to specify the relationship to wish child.</description>
        <label>Relationship Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>It will hold the relationship infromation</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Stepsister</fullName>
                </value>
                <value>
                    <fullName>Stepbrother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbour</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_Shirt_Size__c</fullName>
        <description>It will capture the wish child T.Shirt size</description>
        <label>T-Shirt Size</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Contact__c</fullName>
        <label>Hidden Type of Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referring</fullName>
                </value>
                <value>
                    <fullName>Parent/Guardian</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Qualifing</fullName>
                </value>
                <value>
                    <fullName>Referrer&amp;Treating</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wish_Child_Id_Hidden__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field holds the ID of the Wish Child</description>
        <label>Wish Child Id Hidden</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe01__WorkPhone__c</fullName>
        <description>See &apos;Preferred Phone&apos; field.</description>
        <inlineHelpText>See &apos;Preferred Phone&apos; field.</inlineHelpText>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>This field is used to store middle name</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_child__c</fullName>
        <description>This field is used to store the relationship of the person who submits the Wish Kid details</description>
        <label>Relationship to child</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Member/Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wish_Family_ContactId__c</fullName>
        <description>It is an hidden field. Storing the original Wish Family Contact Id. So while converting the lead, we can create a relationship under this wish Family Record instead of creating dup wish family. we are capturing value for this field on Find Duplicate page.</description>
        <label>Wish Family ContactId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Best_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Best Contact for Treating Healthcare Provider</inlineHelpText>
        <label>Best Contact for Treating MP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hidden_isparentFirst__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hidden isparentFirst</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <defaultValue>false</defaultValue>
        <description>describe Parent or Legal Guardian of wish child</description>
        <label>Parent/Legal Guardian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualifying_Medical_Professional__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked when Type field is Medical Professional.</description>
        <label>Qualifying MP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referring_Medical_Professional__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked when Type is selected as Medical Professional.</description>
        <label>Referral Source</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Treating_HCP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Treating MP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wish_Participant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Described Wish Participants</description>
        <label>Wish Participant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe4__Contact__c</fullName>
        <description>Related Contact is this Contact's ______.</description>
        <inlineHelpText>Related Contact is this Contact's ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe4__RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe4__Status__c</fullName>
        <description>Status of the Relationship.</description>
        <inlineHelpText>Status of the Relationship.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active Treating</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe4__Type__c</fullName>
        <description>Field that describes how the Related Contact is connected to the Contact.</description>
        <inlineHelpText>Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Wish Child(Self)</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Step Sister</fullName>
                </value>
                <value>
                    <fullName>Step Brother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbor</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/RelationshipService.cls
/**
 * @description Relationship Service, centralizes Relationship business rules.
 * @author Gustavo Mayer, Traction on Demand
 * @createdDate 10/23/2020
 */
public class RelationshipService {

	private final static Id WISH_FAMILY_ID = Constant_AC.WISH_FAMILY_RT_ID;
	private final static Id MEDICAL_PROFESSIONAL_ID = Constant_AC.MEDICAL_PROFESSIONAL_RT_ID;
	private final static Id CONTACT_WISH_CHILD_RT_ID = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
	private final static String MEDICAL_PROFESSIONAL_LABEL = Constant_AC.MEDICAL_PROFESSIONAL_RT_LABEL;
	private static final String LEAD_DV_FORM_TYPE_TREATING_MEDICAL_PROFESSIONAL = Constant_AC.LEAD_DV_FORM_TYPE_TREATING_MEDICAL_PROFESSIONAL;
	private static final String LEAD_DV_FORM_TYPE_BEST_CONTACT = Constant_AC.LEAD_DV_FORM_TYPE_BEST_CONTACT;
	private static final String LEAD_DV_FORM_TYPE_ALTERNATE_1_MEDICAL_PROFESSIONAL = Constant_AC.LEAD_DV_FORM_TYPE_ALTERNATE_1_MEDICAL_PROFESSIONAL;
	private static final String LEAD_DV_FORM_TYPE_ALTERNATE_2_MEDICAL_PROFESSIONAL = Constant_AC.LEAD_DV_FORM_TYPE_ALTERNATE_2_MEDICAL_PROFESSIONAL;
	private static final String RELATIONSHIP_ACTIVE = Constant_AC.RELATIONSHIP_STATUS_ACTIVE;
	private static final String CONTACT_PARENT = Constant_AC.CONTACT_TYPE_PARENT_LEGAL_GUARDIAN;
	private static final String CONTACT_SIBLING = Constant_AC.CONTACT_TYPE_SIBLING;
	private static final String CONTACT_REFERRING = Constant_AC.CONTACT_TYPE_REFERRING;
	private static final String LEAD_RELATIONSHIP_TO_CHILD_PARENT_GUARDIAN = Constant_AC.LEAD_RELATIONSHIP_TO_CHILD_PARENT_GUARDIAN;

	/**
	 * Build Lead Converted Relationships
	 * @param convertedLead
	 * @return List of Relationships
	 */
	public static Map<Id, npe4__Relationship__c> buildLeadConvertRelationships(Lead convertedLead) {
		Map<Id, npe4__Relationship__c> relationshipMap = new Map<Id, npe4__Relationship__c>();
		// Create Relationship Treating Medical Professional
		if (convertedLead.Treating_MP__c != null) {
			npe4__Relationship__c newRelationship = new npe4__Relationship__c();
			if (relationshipMap.containsKey(convertedLead.Treating_MP__c)) {
				newRelationship = relationshipMap.get(convertedLead.Treating_MP__c);
			} else {
				newRelationship.npe4__Contact__c = convertedLead.ConvertedContactId;
				newRelationship.npe4__Type__c = MEDICAL_PROFESSIONAL_LABEL;
				newRelationship.npe4__RelatedContact__c = convertedLead.Treating_MP__c;
				newRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
				newRelationship.Treating_HCP__c = true;
			}
			Boolean isTreatingMedicalProfessionalAlsoReferrer = convertedLead.Treating_MP__c == convertedLead.Referring_MP__c;
			if (isTreatingMedicalProfessionalAlsoReferrer) {
				newRelationship.Referring_Medical_Professional__c = true;
			}
			if (convertedLead.Hidden_DV_form_Medical_professional_Type__c == LEAD_DV_FORM_TYPE_TREATING_MEDICAL_PROFESSIONAL) {
				newRelationship.Qualifying_Medical_Professional__c = true;
			}
			relationshipMap.put(convertedLead.Treating_MP__c, newRelationship);
		}

		// Create Relationship Referring Medical Professional
		if (convertedLead.Referring_MP__c != null) {
			npe4__Relationship__c newRelationship = new npe4__Relationship__c();
			if (relationshipMap.containsKey(convertedLead.Referring_MP__c)) {
				newRelationship = relationshipMap.get(convertedLead.Referring_MP__c);
			} else {
				newRelationship.npe4__Contact__c = convertedLead.ConvertedContactId;
				newRelationship.npe4__Type__c = MEDICAL_PROFESSIONAL_LABEL;
				newRelationship.npe4__RelatedContact__c = convertedLead.Referring_MP__c;
				newRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
				newRelationship.Treating_HCP__c = true;
			}
			newRelationship.Referring_Medical_Professional__c = true;
			Boolean isTreatingMedicalProfessionalAlsoReferrer = convertedLead.Treating_MP__c == convertedLead.Referring_MP__c;
			if (isTreatingMedicalProfessionalAlsoReferrer) {
				if (convertedLead.Hidden_DV_form_Medical_professional_Type__c == LEAD_DV_FORM_TYPE_TREATING_MEDICAL_PROFESSIONAL) {
					newRelationship.Qualifying_Medical_Professional__c = true;
				}
			}
			relationshipMap.put(convertedLead.Referring_MP__c, newRelationship);
		}

		// Create Relationship Alternate 1 Medical Professional
		if (convertedLead.Alt_1_MP__c != null) {
			npe4__Relationship__c newRelationship = new npe4__Relationship__c();
			if (relationshipMap.containsKey(convertedLead.Alt_1_MP__c)) {
				newRelationship = relationshipMap.get(convertedLead.Alt_1_MP__c);
			} else {
				newRelationship.npe4__Contact__c = convertedLead.ConvertedContactId;
				newRelationship.npe4__Type__c = MEDICAL_PROFESSIONAL_LABEL;
				newRelationship.npe4__RelatedContact__c = convertedLead.Alt_1_MP__c ;
				newRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
			}
			Boolean isAlternate1MedicalProfessionalAlsoReferrer = convertedLead.Alt_1_MP__c == convertedLead.Referring_MP__c;
			if (isAlternate1MedicalProfessionalAlsoReferrer) {
				newRelationship.Referring_Medical_Professional__c = true;
			}
			if (convertedLead.Hidden_DV_form_Medical_professional_Type__c == LEAD_DV_FORM_TYPE_ALTERNATE_1_MEDICAL_PROFESSIONAL) {
				newRelationship.Qualifying_Medical_Professional__c = true;
			}
			relationshipMap.put(convertedLead.Alt_1_MP__c, newRelationship);
		}

		// Create Relationship Alternate 2 Medical Professional
		if (convertedLead.Alt_2_MP__c != null) {
			npe4__Relationship__c newRelationship = new npe4__Relationship__c();
			if (relationshipMap.containsKey(convertedLead.Alt_2_MP__c)) {
				newRelationship = relationshipMap.get(convertedLead.Alt_2_MP__c);
			} else {
				newRelationship.npe4__Contact__c = convertedLead.ConvertedContactId;
				newRelationship.npe4__Type__c = MEDICAL_PROFESSIONAL_LABEL;
				newRelationship.npe4__RelatedContact__c = convertedLead.Alt_2_MP__c ;
				newRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
			}
			Boolean isAlternate2MedicalProfessionalAlsoReferrer = convertedLead.Alt_2_MP__c == convertedLead.Referring_MP__c;
			if (isAlternate2MedicalProfessionalAlsoReferrer) {
				newRelationship.Referring_Medical_Professional__c = true;
			}
			if (convertedLead.Hidden_DV_form_Medical_professional_Type__c == LEAD_DV_FORM_TYPE_ALTERNATE_2_MEDICAL_PROFESSIONAL) {
				newRelationship.Qualifying_Medical_Professional__c = true;
			}
			relationshipMap.put(convertedLead.Alt_2_MP__c, newRelationship);
		}

		// Create Relationship Best Contact
		if (convertedLead.Best_Contact__c != null) {
			npe4__Relationship__c newRelationship = new npe4__Relationship__c();
			if (relationshipMap.containsKey(convertedLead.Best_Contact__c)) {
				newRelationship = relationshipMap.get(convertedLead.Best_Contact__c);
			} else {
				newRelationship.npe4__Contact__c = convertedLead.ConvertedContactId;
				newRelationship.npe4__Type__c = MEDICAL_PROFESSIONAL_LABEL;
				newRelationship.npe4__RelatedContact__c = convertedLead.Best_Contact__c;
				newRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
			}
			newRelationship.Best_Contact__c = true;
			Boolean isBestContactMedicalProfessionalAlsoReferrer = convertedLead.Best_Contact__c == convertedLead.Referring_MP__c;
			if (isBestContactMedicalProfessionalAlsoReferrer) {
				newRelationship.Referring_Medical_Professional__c = true;
			}
			Boolean isTreatingMedicalProfessionalAlsoBestContact = convertedLead.Treating_MP__c == convertedLead.Best_Contact__c;
			if (isTreatingMedicalProfessionalAlsoBestContact) {
				newRelationship.Treating_HCP__c = true;
			}
			if (convertedLead.Hidden_DV_form_Medical_professional_Type__c == LEAD_DV_FORM_TYPE_BEST_CONTACT) {
				newRelationship.Qualifying_Medical_Professional__c = true;
			}
			relationshipMap.put(convertedLead.Best_Contact__c, newRelationship);
		}

		// Create Relationship Family Parent Guardian
		if (convertedLead.Wish_Family_ContactId__c != null) {
			npe4__Relationship__c newRelationship = new npe4__Relationship__c();
			newRelationship.npe4__Contact__c = convertedLead.ConvertedContactId;
			newRelationship.npe4__Type__c = convertedLead.Parent_Relationship_to_Child__c;
			newRelationship.Hidden_isparentFirst__c = true;
			newRelationship.Parent_Legal_Guardian__c = true;
			newRelationship.npe4__RelatedContact__c = convertedLead.Wish_Family_ContactId__c;
			newRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
			if (convertedLead.Relationship_to_child__c == LEAD_RELATIONSHIP_TO_CHILD_PARENT_GUARDIAN) {
				newRelationship.Referring_Medical_Professional__c = true;
			}
			relationshipMap.put(convertedLead.Wish_Family_ContactId__c, newRelationship);
		}

		// Create Relationship Additional Family Parent Guardian
		if (convertedLead.Hidden_Additional_Parent_Id__c != null) {
			npe4__Relationship__c newRelationship = new npe4__Relationship__c();
			newRelationship.npe4__Contact__c = convertedLead.ConvertedContactId;
			newRelationship.Hidden_isparentFirst__c = false;
			newRelationship.Parent_Legal_Guardian__c = true;
			newRelationship.npe4__Type__c = convertedLead.Additional_Parent_Relationship_to_Child__c;
			newRelationship.npe4__RelatedContact__c = convertedLead.Hidden_Additional_Parent_Id__c;
			newRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
			relationshipMap.put(convertedLead.Hidden_Additional_Parent_Id__c, newRelationship);
		}
		return relationshipMap;
	}

	/**
	 * Update the medical physician name and email value into contact record.
	 * @param relatedContactId
	 * @param relationShipList
	 */
	public static void updatePhysicianDetails(Set<Id> relatedContactId, List<npe4__Relationship__c> relationShipList) {
		if (relatedContactId.isEmpty() || !RecursiveTriggerHandler.isFirstTime) {
			return;
		}
		RecursiveTriggerHandler.isFirstTime = false;
		Map<Id, Contact> medicalProfContactMap = new Map<Id, Contact>();
		Map<Id, Contact> updateContactMap = new Map<Id, Contact>();
		try {
			if (relatedContactId.isEmpty()) {
				return;
			}
			for (Contact dbWishChildCon : [
					SELECT Id,Name,Email,RecordTypeId
					FROM Contact
					WHERE Id IN:relatedContactId
					AND RecordTypeId = :MEDICAL_PROFESSIONAL_ID
			]) {
				medicalProfContactMap.put(dbWishChildCon.Id, dbWishChildCon);
			}
			if (medicalProfContactMap.isEmpty()) {
				return;
			}
			for (npe4__Relationship__c newRecord : relationShipList) {
				if (medicalProfContactMap.containsKey(newRecord.npe4__RelatedContact__c)) {
					Contact newContact = new Contact();
					newContact.Id = newRecord.npe4__Contact__c;
					newContact.Hidden_Medical_Physician__c = medicalProfContactMap.get(newRecord.npe4__RelatedContact__c).Name;
					newContact.Hidden_Medical_Physician_Email__c = medicalProfContactMap.get(newRecord .npe4__RelatedContact__c).Email;
					updateContactMap.put(newContact.Id, newContact);
				}
			}
			if (updateContactMap.isEmpty()) {
				return;
			}
			update updateContactMap.values();
			if (Test.isRunningTest()) {
				throw new CommonTriggerException('Test Class execution');
			}
		} catch (Exception ex) {
			for (npe4__Relationship__c relationship : relationShipList) {
				ErrorMessage_AC.createDebugRec('RelationshipService',
						String.valueOf(relationship), String.valueOf(ex), 'updatePhysicianDetails',
						relationship.Id, ex.getStackTraceString(), 'Error');
			}
			if (!Test.isRunningTest()) {
				for (npe4__Relationship__c currRec : relationShipList) {
					currRec.addError(Label.Debug_log_error_message);
				}
			}
		}
	}


	/**
	 * Build Lead Converted Relationship
	 * @param leadConvertWrapper wrapper
	 * @return Relationship
	 */
	public static List<npe4__Relationship__c> buildWishFamilyLeadConvertRelationship(List<Contact> contacts) {
		List<npe4__Relationship__c> relationships = new List<npe4__Relationship__c>();
		for(Contact familyContact : contacts){
			if (familyContact.Relationship_Type__c.equals(CONTACT_PARENT)) {
				// Parent Legal Guardian Relationship
				npe4__Relationship__c parentLegGuardRelationship = new npe4__Relationship__c();
				parentLegGuardRelationship.npe4__Contact__c = familyContact.Wish_Child_Id_Hidden__c;
				parentLegGuardRelationship.npe4__Type__c = familyContact.Relationship__c;
				parentLegGuardRelationship.Parent_Legal_Guardian__c = true;
				if (familyContact.Type_of_Contact__c.equals(CONTACT_REFERRING)) {
					parentLegGuardRelationship.Referring_Medical_Professional__c = true;
				}
				parentLegGuardRelationship.npe4__RelatedContact__c = familyContact.Id;
				parentLegGuardRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
				relationships.add(parentLegGuardRelationship);
			} else {
				// Sibling Relationship
				npe4__Relationship__c siblingRelationship = new npe4__Relationship__c();
				siblingRelationship.npe4__Contact__c = familyContact.Wish_Child_Id_Hidden__c;
				siblingRelationship.npe4__Type__c = CONTACT_SIBLING;
				siblingRelationship.npe4__RelatedContact__c = familyContact.Id;
				siblingRelationship.npe4__Status__c = RELATIONSHIP_ACTIVE;
				relationships.add(siblingRelationship);
			}
		}
		return relationships;
	}

	/**
	 * Update the type of relationship in contact record.
	 * @param relationshipMap
	 */
	public static void updateRelationshipType(Map<Id, String> relationshipMap) {
		if (relationshipMap.isEmpty()) {
			return;
		}
		List<Contact> familyContactList = new List<Contact>();
		try {
			for (Contact dbContact : [
					SELECT Id,Name,Relationship_Type__c,RecordTypeId
					FROM Contact
					WHERE Id IN:relationshipMap.keySet() AND RecordTypeId = :WISH_FAMILY_ID
			]) {
				if (relationshipMap.containsKey(dbContact.Id)) {
					dbContact.Relationship_Type__c = relationshipMap.get(dbContact.Id);
					familyContactList.add(dbContact);
				}
			}
			update familyContactList;
			if (Test.isRunningTest()) {
				throw new CommonTriggerException('Test Class execution');
			}
		} catch (Exception ex) {
			for (npe4__Relationship__c relationship : [
					SELECT Id,npe4__Contact__c,npe4__Type__c
					FROM npe4__Relationship__c
					WHERE npe4__Contact__c IN:relationshipMap.keySet()
			]) {
				ErrorMessage_AC.createDebugRec('RelationshipService',
						String.valueOf(relationship), String.valueOf(ex),
						'updateRelationshipType', relationship.Id, ex.getStackTraceString(), 'Error');
				if (!Test.isRunningTest()) {
					relationship.addError(Label.Debug_log_error_message);
				}
			}
		}
	}

	/**
	 * Populate Guargian Name
	 * @param contactMap
	 */
	public static void populateGuardianName(Map<Id, Id> contactMap) {
		if (contactMap.isEmpty()) {
			return;
		}
		String parentGuardianName;
		Map<Id, String> parentGuardianMap = new Map<Id, String>();
		Set<String> names = new Set<String>();
		for (npe4__Relationship__c relationship : [
				SELECT Id,npe4__RelatedContact__c, npe4__RelatedContact__r.Name, npe4__RelatedContact__r.FirstName,
						npe4__RelatedContact__r.LastName, npe4__Contact__c, npe4__RelatedContact__r.Email,
						Hidden_isparentFirst__c, npe4__RelatedContact__r.Phone, npe4__RelatedContact__r.Middle_Name__c,
						npe4__RelatedContact__r.MailingCity, npe4__RelatedContact__r.MailingStreet,
						npe4__RelatedContact__r.MailingState, npe4__RelatedContact__r.MailingPostalCode,
						npe4__Type__c,npe4__RelatedContact__r.HomePhone,npe4__RelatedContact__r.npe01__WorkPhone__c,
						npe4__RelatedContact__r.MobilePhone,npe4__RelatedContact__r.T_Shirt_Size__c,
						npe4__RelatedContact__r.Hidden_Wish_Form_Id__c,Parent_Legal_Guardian__c,Wish_Participant__c
				FROM npe4__Relationship__c
				WHERE npe4__RelatedContact__c = :contactMap.keySet()
				AND npe4__RelatedContact__r.RecordTypeId = :WISH_FAMILY_ID
				AND (Parent_Legal_Guardian__c = TRUE OR Wish_Participant__c = TRUE)
				AND npe4__RelatedContact__r.Hidden_Wish_Form_Id__c != NULL
		]) {
			if (contactMap.containsKey(relationship.npe4__RelatedContact__c) && relationship.Id != null) {
				if (relationship.Parent_Legal_Guardian__c == true) {
					if (String.isEmpty(parentGuardianName) && (!names.contains(relationship.npe4__RelatedContact__c))) {
						parentGuardianName = relationship.npe4__RelatedContact__r.Name;
						names.add(relationship.npe4__RelatedContact__c);
					} else if (!names.contains(relationship.npe4__RelatedContact__c)) {
						parentGuardianName = parentGuardianName + ', ' + relationship.npe4__RelatedContact__r.Name;
						names.add(relationship.npe4__RelatedContact__c);
					}
					parentGuardianMap.put(relationship.npe4__Contact__c, parentGuardianName);
				}
			}
		}
		if (parentGuardianMap.isEmpty()) {
			return;
		}
		List<Contact> contacts = new List<Contact>();
		for (Contact contact : [
				SELECT Id,Name,Parent_Legal_Guardian__c,RecordTypeId
				FROM Contact
				WHERE Id IN:parentGuardianMap.keySet()
				AND RecordTypeId = :CONTACT_WISH_CHILD_RT_ID
		]) {
			if (parentGuardianMap.containsKey(contact.Id)) {
				if (String.isNotEmpty(contact.Parent_Legal_Guardian__c)) {
					contact.Parent_Legal_Guardian__c = parentGuardianMap.get(contact.Id);
				} else {
					contact.Parent_Legal_Guardian__c = contact.Parent_Legal_Guardian__c + ', '
							+ parentGuardianMap.get(contact.Id);
				}
				contacts.add(contact);
			}
			update contacts;
		}
	}

	/**
	 * Build Contact Set from new Relationships
	 * @param newRelationshipsList
	 * @return Set of npe4__RelatedContact__c
	 */
	public static Set<Id> buildQualifyingMedProfessionalRelationshipMap(List<npe4__Relationship__c> newRelationshipsList) {
		Set<Id> qualifyingMedicalProfessionalContactIds = new Set<Id>();
		for (npe4__Relationship__c newRecord : newRelationshipsList) {
			if (Bypass_Triggers__c.getValues(UserInfo.getUserId()) == null) {
				if (newRecord.npe4__Contact__c != null
						&& newRecord.npe4__Type__c == Constant_AC.MEDICAL_PROFESSIONAL_RT_LABEL
						&& newRecord.Qualifying_Medical_Professional__c
						&& RELATIONSHIP_ACTIVE.equals(newRecord.npe4__Status__c)) {
					qualifyingMedicalProfessionalContactIds.add(newRecord.npe4__RelatedContact__c);
				}
			}
		}
		return qualifyingMedicalProfessionalContactIds;
	}

	/**
	 * Build Relationship Map from new Relationships
	 * @param newRelationshipsList
	 * @return Map of npe4__RelatedContact__c and npe4__Contact__c
	 */
	public static Map<Id, String> buildNonMedicalRelationshipMap(List<npe4__Relationship__c> newRelationshipsList) {
		Map<Id, String> relationshipMap = new Map<Id, String>();
		for (npe4__Relationship__c newRecord : newRelationshipsList) {
			if (newRecord.npe4__Contact__c != null
					&& newRecord.npe4__RelatedContact__c != null
					&& newRecord.npe4__Type__c != Constant_AC.MEDICAL_PROFESSIONAL_RT_LABEL) {
				relationshipMap.put(newRecord.npe4__RelatedContact__c, newRecord.npe4__Type__c);
			}
		}
		return relationshipMap;
	}

	/**
	 * Build Contact Map from new Relationships
	 * @param newRelationshipsList
	 * @return Map of npe4__RelatedContact__c and npe4__Contact__c
	 */
	public static Map<Id, Id> buildContactMap(List<npe4__Relationship__c> newRelationshipsList) {
		Map<Id, Id> contactMap = new Map<Id, Id>();
		for (npe4__Relationship__c newRecord : newRelationshipsList) {
			if (newRecord.npe4__Contact__c != null
					&& newRecord.npe4__RelatedContact__c != null) {
				contactMap.put(newRecord.npe4__RelatedContact__c, newRecord.npe4__Contact__c);
			}
		}
		return contactMap;
	}
}