make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birth_Day__c</fullName>
        <description>It will hold the day value of the Birth day</description>
        <label>Birth Day</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Birth_Month__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Birth_Month__c</fullName>
        <description>It will hold the month value of the DOB</description>
        <label>Birth Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Birth_Year__c</fullName>
        <description>It will capture the volunteer birth year value</description>
        <label>Birth Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HiddenMobilePhone__c</fullName>
        <description>This field is used to store the updated mobile phone value from Updated contact info page.</description>
        <label>Hidden Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>HiddenOtherPhone__c</fullName>
        <description>This field is used to store the updated other phone value from Updated contact info page.</description>
        <label>Hidden Other Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_Email__c</fullName>
        <description>This field is used as hidden to update the contact email from volunteer portal</description>
        <label>Hidden Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hidden_First_Name__c</fullName>
        <description>This field is used as hidden to update the contact first name from volunteer portal</description>
        <label>Hidden First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Last_Name__c</fullName>
        <description>This field is used as hidden to update the contact last name from volunteer portal</description>
        <label>Hidden Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Phone__c</fullName>
        <description>This field is used as hidden to update the contact phone from volunteer portal</description>
        <label>Hidden Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Hidden_Preferred_Contact_Rel_Id__c</fullName>
        <description>This field is used to hold the relationship record id for preferred contact chooses from the Update Contact Info.</description>
        <label>Hidden Preferred Contact Rel Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_State__c</fullName>
        <description>Hidden State Value</description>
        <label>Hidden State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Street__c</fullName>
        <description>This field is used as hidden to update the contact Street from volunteer portal</description>
        <label>Hidden Street</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Zip_Code__c</fullName>
        <description>This field is used as hidden to update the contact Zip Code from volunteer portal</description>
        <label>Hidden Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_city__c</fullName>
        <description>This field is used as hidden to update the contact city from volunteer portal</description>
        <label>Hidden City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ICD_10_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold the ICD-10 code.</description>
        <label>Primary ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsContactInfoUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for update contact info approval process.</description>
        <label>Hidden IsContactInfoUpdated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRejected_Contact_Info__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for update contact info approval process.</description>
        <label>Hidden IsRejected Contact Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SD1_ICD_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It holds Secondary Diagnosis value.</description>
        <label>Secondary Diagnosis 1 ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts (Secondary Diagnosis 1 ICD-10 Code)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SD2_ICD_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It contains ICD code for Secondary Diagnosis 2.</description>
        <label>Secondary Diagnosis 2 ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts (Secondary Diagnosis 2 ICD-10 Code)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SD3_ICD_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It contains ICD code for Secondary Diagnosis 3.</description>
        <label>Secondary Diagnosis 3 ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts (Secondary Diagnosis 3 ICD-10 Code)</relationshipLabel>
        <relationshipName>Contacts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SD4_ICD_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It contains ICD code for Secondary Diagnosis 4.</description>
        <label>Secondary Diagnosis 4 ICD-10 Code</label>
        <referenceTo>ICD_Codes__c</referenceTo>
        <relationshipLabel>Contacts (Secondary Diagnosis 4 ICD-10 Code)</relationshipLabel>
        <relationshipName>Contacts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>npe4__Contact__c</fullName>
        <description>Related Contact is this Contact's ______.</description>
        <inlineHelpText>Related Contact is this Contact's ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe4__RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe4__Status__c</fullName>
        <description>Status of the Relationship.</description>
        <inlineHelpText>Status of the Relationship.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active Treating</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Contact_OnBeforeUpdateTriggerHandlerTest.cls
/**
 * @author Steve Doucette, Traction on Demand 
 * @date 9/30/2019
 *
 * Created to cover any code from the Contact_OnBeforeUpdateTriggerHandler code that isn't covered by other test classes
 * NOTE: This will have NO assertions
 */

@IsTest
private class Contact_OnBeforeUpdateTriggerHandlerTest {
	@IsTest
	static void coverChangedICDFields() {
		List<ICD_Codes__c> icdCodes = TestDataFactory.createIcdCode(2);
		insert icdCodes;

		Contact c = TestDataFactory.createContact(1)[0];
		c.SD1_ICD_Code__c = icdCodes[0].Id;
		c.SD2_ICD_Code__c = icdCodes[0].Id;
		c.SD3_ICD_Code__c = icdCodes[0].Id;
		c.SD4_ICD_Code__c = icdCodes[0].Id;
		c.ICD_10_Code__c = icdCodes[0].Id;
		insert c;
		c.SD1_ICD_Code__c = icdCodes[1].Id;
		c.SD2_ICD_Code__c = icdCodes[1].Id;
		c.SD3_ICD_Code__c = icdCodes[1].Id;
		c.SD4_ICD_Code__c = icdCodes[1].Id;
		c.ICD_10_Code__c = icdCodes[1].Id;
		update c;
	}

	@IsTest
	static void coverChangedBirthdayFields() {
		ICD_Codes__c icdCode = TestDataFactory.createIcdCode(1)[0];
		insert icdCode;

		List<Contact> contacts = TestDataFactory.createContact(3);
		Contact birthdayChange = contacts[0];
		Contact birthdayChangeNull = contacts[1];
		Contact birthdayCustomChange = contacts[2];

		birthdayChange.RecordTypeId = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
		birthdayChange.SD1_ICD_Code__c = icdCode.Id;
		birthdayChange.SD2_ICD_Code__c = icdCode.Id;
		birthdayChange.SD3_ICD_Code__c = icdCode.Id;
		birthdayChange.SD4_ICD_Code__c = icdCode.Id;
		birthdayChange.ICD_10_Code__c = icdCode.Id;
		birthdayChange.Birthdate = System.now().date();

		birthdayChangeNull.Birthdate = System.now().date();
		birthdayChangeNull.RecordTypeId = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
		birthdayChangeNull.SD1_ICD_Code__c = icdCode.Id;
		birthdayChangeNull.SD2_ICD_Code__c = icdCode.Id;
		birthdayChangeNull.SD3_ICD_Code__c = icdCode.Id;
		birthdayChangeNull.SD4_ICD_Code__c = icdCode.Id;
		birthdayChangeNull.ICD_10_Code__c = icdCode.Id;

		birthdayCustomChange.RecordTypeId = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
		birthdayCustomChange.SD1_ICD_Code__c = icdCode.Id;
		birthdayCustomChange.SD2_ICD_Code__c = icdCode.Id;
		birthdayCustomChange.SD3_ICD_Code__c = icdCode.Id;
		birthdayCustomChange.SD4_ICD_Code__c = icdCode.Id;
		birthdayCustomChange.ICD_10_Code__c = icdCode.Id;
		birthdayCustomChange.Birth_Year__c = '1';
		birthdayCustomChange.Birth_Month__c = 'January';
		//birthdayCustomChange.Birth_Day__c = '1';
		insert contacts;
		birthdayChange.Birthdate = birthdayChange.Birthdate.addDays(1);
		birthdayChangeNull.Birthdate = null;
		birthdayCustomChange.Birth_Year__c = '2';
		update contacts;
	}

	@IsTest
	static void coverHiddenFields() {
		ICD_Codes__c icdCode = TestDataFactory.createIcdCode(1)[0];
		insert icdCode;

		Contact c = TestDataFactory.createContact(1)[0];
		c.RecordTypeId = Constant_AC.CONTACT_WISH_CHILD_RT_ID;
		c.SD1_ICD_Code__c = icdCode.Id;
		c.SD2_ICD_Code__c = icdCode.Id;
		c.SD3_ICD_Code__c = icdCode.Id;
		c.SD4_ICD_Code__c = icdCode.Id;
		c.ICD_10_Code__c = icdCode.Id;
		insert c;

		npe4__Relationship__c newRlet = new npe4__Relationship__c();
		newRlet.npe4__RelatedContact__c = c.Id;
		newRlet.npe4__Status__c = 'Active';
		newRlet.npe4__Contact__c = c.Id;
		insert newRlet;

		c.Hidden_First_Name__c = 'FirstTest';
		c.Hidden_Last_Name__c = 'LastTest';
		c.Hidden_Phone__c = '1234567890';
		c.HiddenOtherPhone__c = '1234567890';
		c.HiddenMobilePhone__c = '1234567890';
		c.Hidden_Email__c = 'Test@test.com';
		c.Hidden_Street__c = 'Test Street';
		c.Hidden_Zip_Code__c = '12345';
		c.Hidden_city__c = 'Test';
		c.Hidden_State__c = 'Arizona';
		c.Hidden_Preferred_Contact_Rel_Id__c = newRlet.Id;
		update c;
		c.IsContactInfoUpdated__c = true;
		update c;
		c.IsRejected_Contact_Info__c = true;
		c.Hidden_Preferred_Contact_Rel_Id__c = 'Remove';
		c.Hidden_First_Name__c = null;
		c.Hidden_Last_Name__c = null;
		c.Hidden_Phone__c = null;
		c.HiddenOtherPhone__c = null;
		c.HiddenMobilePhone__c = null;
		c.Hidden_Email__c = null;
		c.Hidden_Street__c = null;
		c.Hidden_Zip_Code__c = null;
		c.Hidden_city__c = null;
		c.Hidden_State__c = null;
		update c;
	}
}