make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Communication__c</fullName>
        <description>It will hold which type of communication can understand by child and this field mapped from lead at the time of lead conversion.</description>
        <label>Communication</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>This child is non-verbal</fullName>
                </value>
                <value>
                    <fullName>This child is developmentally on target for chronological age</fullName>
                </value>
                <value>
                    <fullName>This child functions at a 0-2 year old, Sensorimotor stage</fullName>
                </value>
                <value>
                    <fullName>This child functions at a 2-7 year old, Preoperational stage</fullName>
                </value>
                <value>
                    <fullName>This child functions at a 7-11 year old, Concrete Operational stage</fullName>
                </value>
                <value>
                    <fullName>This child functions at an 11+ year old, Formal Operational stage</fullName>
                </value>
                <value>
                    <fullName>I am not sure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Communication__c</fullName>
        <description>It will hold which type of communication can understand by child</description>
        <label>Communication</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appropriate for chronological age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sensorimotor (0-2 year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preoperational (2-7 year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Operational (7-11 year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formal Operational (11+ year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chronological age</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>I_am_Recognized_To_Practice_As_a__c</fullName>
        <description>It will hold which type of practice she/he is going to get</description>
        <label>I am Recognized To Practice As a</label>
        <picklist>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse Practitioner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Life Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>I_m_Part_of_The_Treating_HealthCare_Team__c</fullName>
        <description>This field will identify whether he/she is part of the treating health care team or not</description>
        <label>I&apos;m Part of The Treating HealthCare Team</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/WishChildWrapper.cls
/*****************************************************************************************************************
Author      : MST Solutions
Date        : 
Description : 
*******************************************************************************************************************/
public class WishChildWrapper {
    public String describePatient {get; set;}     
    public String password{get; set;}
    public boolean login {get; set;}
    public String healthCareWork {get;set;}
    /***********************************************
     Used to get treating medical professional details.
     ****************************************************/
    public String treatingFName {get;set;}
    public String treatingLName {get;set;}
    
    /***********************************************
     Used to get best contact for treating medical professional details.
     ****************************************************/
    public String bestPhyFname {get;set;}
    public String bestPhyLname {get;set;}
    public String bestPhyEmail {get;set;}
    
    /***********************************************
     Used to get alternate 1 treating medical professional details.
     ****************************************************/
    public String alt1MedFname {get;set;}
    public String alt1MedLname {get;set;}
    public String alt1MedEmail {get;set;}
    public String alt1MedPhone {get;set;}
    public String alt1MedHosp {get;set;}
    /***********************************************
     Used to get alternate 2 treating medical professional details.
     ****************************************************/
    public String alt2MedFname {get;set;}
    public String alt2MedLname {get;set;}
    public String alt2MedEmail {get;set;}
    public String alt2MedPhone {get;set;}
    public String alt2MedHosp {get;set;}
    
    public String medProfTypeHid {get;set;}
    
    public String treatingPhone {get;set;}
    public String treatingEmail {get;set;}
    public String treatingHospital {get;set;}
    public String recognizationPickValSelected {get;set;}
    public String vegetativeState {get;set;}
    public String explainDeteriorate {get;set;}
    public String expediteTheProcess{get;set;}
    public String plzExplain{get;set;}
    public String conditioDeteriorate{get;set;}
    public String stillEligibile {get;set;}
    public String additionalInfo {get;set;}
    Public String wishChildEligibilityNotes {get;set;} 
    public List<String> communicationList {get;set;}
    public String selectedItemValue {get; set;}
    public WishChildWrapper(){
        communicationList = new List<String>();       
    }
     /***********************************************
     Used to get state recognization picklist values
     ****************************************************/
    Public List<SelectOption> getStateRecognizationPicklistValues(){
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Lead.I_am_Recognized_To_Practice_As_a__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        options.add(new SelectOption('', 'Please Select'));
        for(Schema.PicklistEntry fieldValue : picklistValues){
            options.add(new SelectOption(fieldValue.getLabel(), fieldValue.getValue()));
        } 
        return options;           
    }
    /***********************************************
     Used to get treating helth care team picklist values
     ****************************************************/
    public List<SelectOption> getHealthCareWorks(){
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult =  Lead.I_m_Part_of_The_Treating_HealthCare_Team__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        options.add(new SelectOption('', 'Please Select')); 
        for( Schema.PicklistEntry currVal : picklistValues) {      
            options.add(new SelectOption(currVal.getLabel(), currVal.getValue())); 
        }  
        return options; 
    }
    /***********************************************
     Used to get communication  picklist values
     ****************************************************/ 
    public List<SelectOption> getCommunications(){
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult =  Lead.Communication__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        options.add(new SelectOption('', 'Please Select',true));
        for( Schema.PicklistEntry currVal : picklistValues)
        {      options.add(new SelectOption(currVal.getLabel(), currVal.getValue())); 
         
        }  
        return options;
    }   
}