make-a-wish-salesforce/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <description>This field will used to store all related contact  in the relationship object record of the wish child</description>
        <label>Hidden Parent/Legal Guardian</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>This field is used to specify the relationship to wish child.</description>
        <label>Relationship Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>It will hold the relationship infromation</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Stepsister</fullName>
                </value>
                <value>
                    <fullName>Stepbrother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbour</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <defaultValue>false</defaultValue>
        <description>describe Parent or Legal Guardian of wish child</description>
        <label>Parent/Legal Guardian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Under_18__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Non-adults participants</description>
        <label>Under 18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe4__Contact__c</fullName>
        <description>Related Contact is this Contact's ______.</description>
        <inlineHelpText>Related Contact is this Contact's ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Affiliation__c.object
<CustomObject>
    <description>A junction object between the Wish (Case) and Contacts to track individuals related to a particular Wish.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>A Wish Affiliation's related Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Wish Affiliations</relationshipLabel>
        <relationshipName>Wish_Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_Legal_Guardian__c</fullName>
        <description>Displays the Parent Legal Guardian status of the related Relationship record</description>
        <formula>Relationship__r.Parent_Legal_Guardian__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Legal Guardian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>If there is a related relationship record it displays the name of the related contact, and a Hyperlink link to their Salesforce record.</description>
        <formula>HYPERLINK("/" &amp; Relationship__r.npe4__Contact__r.Id,  Relationship__r.npe4__Contact__r.FirstName &amp; " " &amp; Relationship__r.npe4__Contact__r.LastName , "_self")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>If linked to an existing relationship record displays the type of relationship</description>
        <formula>Text( Relationship__r.npe4__Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Wish Affiliation's related Relationship record.</description>
        <label>Relationship</label>
        <referenceTo>npe4__Relationship__c</referenceTo>
        <relationshipLabel>Wish Affiliations</relationshipLabel>
        <relationshipName>Wish_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Under_18__c</fullName>
        <description>'Yes' if the related contact is less than 18 years old.</description>
        <formula>IF(ISBLANK(Contact__r.Birthdate), "No Birthdate Recorded",
IF(Contact__r.Birthdate &gt; ADDMONTHS(TODAY(),-216), "Yes", "No"))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Under 18 Years of Age</label>
        <type>Text</type>
    </fields>
    <label>Wish Affiliation</label>
    <nameField>
        <displayFormat>WA-{00000}</displayFormat>
        <label>Wish Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Required_Signature__c.object
<CustomObject>
    <description>The Wish Required Signature stores information about signatures that are required (from a legal and/or logistical standpoint) for a wish to proceed. It is linked to the Wish (Case) and to the person signing the form (Contact). It includes information about the Wish Signature Form. It tracks the life-cycle of each signature: the date it is sent out to be signed, the date it is signed and received, and (if applicable) the date on which the signature changes from valid to invalid.</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of signature required: medical or family (i.e. from a participant, family member or household member of the Wish Child). Auto-populated from the Wish Signature Form.</description>
        <inlineHelpText>Family forms are signed by a family member of the Wish Child or participant. Medical forms are signed by a designated medical professional.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wish_Affiliation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Wish Affiliation record</description>
        <label>Wish Affiliation</label>
        <referenceTo>Wish_Affiliation__c</referenceTo>
        <relationshipLabel>Wish Required Signatures</relationshipLabel>
        <relationshipName>Wish_Required_Signatures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wish_Signature_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related Wish Signature Form record.</description>
        <label>Wish Signature Form</label>
        <referenceTo>Wish_Signature_Forms__c</referenceTo>
        <relationshipLabel>Wish Required Signatures</relationshipLabel>
        <relationshipName>Wish_Required_Signatures</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Wish Required Signature</label>
    <nameField>
        <displayFormat>WRS-{000000}</displayFormat>
        <label>Wish Required Signature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Required Signatures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Signature_Chapter_Form__c.object
<CustomObject>
    <description>Contains the record set of Wish Signature Forms that relate to the needs of a specific chapter.</description>
    <fields>
        <fullName>Chapter_Account__c</fullName>
        <description>The related Chapter Account for this Wish Signature Chapter Form record.</description>
        <label>Chapter Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wish Signature Chapter Forms</relationshipLabel>
        <relationshipName>Wish_Signature_Chapter_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wish_Signature_Form__c</fullName>
        <description>The related Wish Signature Form associated with this Wish Signature Chapter Form record.</description>
        <label>Wish Signature Form</label>
        <referenceTo>Wish_Signature_Forms__c</referenceTo>
        <relationshipLabel>Chapter Forms</relationshipLabel>
        <relationshipName>Wish_Signature_Chapter_Forms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wish Signature Chapter Form</label>
    <nameField>
        <displayFormat>WSCF-{000}</displayFormat>
        <label>Wish Signature Chapter Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Signature Chapter Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Wish_Signature_Forms__c.object
<CustomObject>
    <description>Contains the master data set of Wish Required Form records which are utilized selectively by affiliated chapters via the Junction object &apos;Wish Signature Chapter Forms&apos; Object records.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this form is being used by MAWA. When unchecked, this form is no longer being used. There is no automation that invalidates forms where the form is inactive but the wish is still actively progressing.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form_Type__c</fullName>
        <description>The type of signature required: medical or family (i.e. from a participant, family member or household member of the Wish Child). This value gets written to the Type field of the Wish Required SIgnature.</description>
        <inlineHelpText>Family forms are signed by a family member of the Wish Child or participant. Medical forms are signed by a designated medical professional.</inlineHelpText>
        <label>Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Wish Signature Form</label>
    <nameField>
        <label>Wish Signature Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wish Signature Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/WishSignatureController.cls
/**
 * @description Wish Signature Controller, exposes methods for the front end components.
 * @author Mitali Nahar, Traction on Demand
 * @createdDate 6/18/2019
 */
public without sharing class WishSignatureController {

	/**
	 * Find Wish Signature Forms
	 * @param caseId
	 * @param formType
	 * @return List of Wish Signature Forms
	 */
	@AuraEnabled
	public static List<Wish_Signature_Forms__c> getWishSignatureForms(Id caseId, String formType) {
		Case objCase = [
				SELECT ChapterName__c
				FROM Case
				WHERE Id = :caseId
		];
		Set<Id> wishSignFormId = new Set<Id>();
		//Get Wish Signature Chapter forms for a Case
		for (Wish_Signature_Chapter_Form__c obj : [
				SELECT Chapter_Account__c, Wish_Signature_Form__c
				FROM Wish_Signature_Chapter_Form__c
				WHERE Chapter_Account__c = :objCase.ChapterName__c
		]) {
			wishSignFormId.add(obj.Wish_Signature_Form__c);
		}
		//Get Medical and Non-Medical Wish Signature Forms belonging to a Chapter
		String sQuery = '';
		sQuery = 'select id ' + ', Name from Wish_Signature_Forms__c where Id In : wishSignFormId AND Active__c = True';
		if (formType.equals('Medical')) {
			sQuery += ' AND Form_Type__c =' + '\'Medical\'';
		} else {
			sQuery += ' AND Form_Type__c != ' + '\'Medical\'';
		}
		sQuery += ' order by Name';
		List <SObject> lstOfRecords = Database.query(sQuery);
		return (List<Wish_Signature_Forms__c>) lstOfRecords;
	}

	/**
	 * Find Wish Affiliations(except Medical) for a Case
	 * @param caseId
	 * @return List of wrapper class
	 */
	@AuraEnabled
	public static List<childWrapper> getWishAffiliations(Id caseId) {
		try {
			if (caseId != null) {
				List<childWrapper> wrapperList = new List<childWrapper>();
				List<childWrapper> minorsList = new List<childWrapper>();
				//Get a List of all adults and minors related to the case and put in WrapperList
				for (Wish_Affiliation__c obj : [
						SELECT Id,Under_18__c,Contact__c,Contact__r.LastName,Contact__r.FirstName,Related_To__c,Relationship__r.npe4__Contact__r.FirstName,
								Relationship__r.npe4__Contact__r.LastName,Parent_Legal_Guardian__c,Relationship_Type__c,Wish_Affiliation_Type__c,Send_Clearance_Forms_To__c,Best_Medical_Contact__c
						FROM Wish_Affiliation__c
						WHERE Wish__c = :caseId AND Wish_Affiliation_Type__c != :Constant_AC.WISH_AFFILIATION_TYPE_MEDICAL_PROFESSIONAL
				]) {
					childWrapper objChild = new childWrapper();
					objChild.wishAff = obj;
					objChild.con = new Contact(Id = obj.Contact__c, LastName = obj.Contact__r.LastName, FirstName = obj.Contact__r.FirstName);
					if (obj.Under_18__c == 'No' || obj.Under_18__c == 'No Birthdate Recorded') {
						wrapperList.add(objChild);
					} else if (obj.Under_18__c == 'Yes') {
						minorsList.add(objChild);
					}
				}
				for (childWrapper obj : wrapperList) {
					obj.lstMinors = minorsList;
				}
				return wrapperList;
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return null;
	}

	/**
	 * Find Medical Wish Affiliations ofr a Case
	 * @param caseId
	 * @return List of wrapper class
	 */
	@AuraEnabled
	public static List<childWrapper> getWishAffiliationsMedical(Id caseId) {
		try {
			if (caseId != null) {
				List<childWrapper> wrapperList = new List<childWrapper>();
				//Get a List of all medical professionals related to the case and put in WrapperList
				for (Wish_Affiliation__c obj : [
						SELECT Id,Medical_Professional_Status__c,Contact__c,Contact__r.LastName,Contact__r.FirstName,Best_Medical_Contact__c, Send_Clearance_Forms_To__c
						FROM Wish_Affiliation__c
						WHERE Wish__c = :caseId AND Wish_Affiliation_Type__c = :Constant_AC.WISH_AFFILIATION_TYPE_MEDICAL_PROFESSIONAL
				]) {
					childWrapper objChild = new childWrapper();
					objChild.wishAff = obj;
					objChild.con = new Contact(Id = obj.Contact__c, LastName = obj.Contact__r.LastName, FirstName = obj.Contact__r.FirstName);
					wrapperList.add(objChild);
				}
				return wrapperList;
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return null;
	}

	/**
	 * Save Medical Wish Signatures
	 * @param adultsIdList
	 * @param caseId
	 * @param formId
	 */
	@AuraEnabled
	public static void saveMedicalWishSignatures(String adultsIdList, String caseId, String formId) {
		try {
			List<AdultWrapData> objAdultDataList = (List<AdultWrapData>) JSON.deserialize(adultsIdList, List<AdultWrapData>.class);
			Set<Id> wishAffIdSet = new Set<Id>();
			List<Wish_Required_Signature__c> wrsToInsert = new List<Wish_Required_Signature__c>();
			//Create Wish Required Signature records and Insert them
			if (objAdultDataList != null && !objAdultDataList.isEmpty()) {
				for (AdultWrapData obj : objAdultDataList) {
					wishAffIdSet.add(obj.wishAff);
				}
			}
			List<Wish_Affiliation__c> wishAffiliations = [
					SELECT Id, Contact__r.Email
					FROM Wish_Affiliation__c
					WHERE Id In:wishAffIdSet
			];
			wrsToInsert = createWRSRecord('Medical', wishAffiliations, caseId, formId);
			if (!wrsToInsert.isEmpty()) {
				insert wrsToInsert;
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	/**
	 * Build new Wish Signatures records
	 * @param type
	 * @param wishAffiliations
	 * @param caseId
	 * @param formId
	 * @return List of Wish Required Signature to be inserted
	 */
	private static List<Wish_Required_Signature__c> createWRSRecord(String type, List<Wish_Affiliation__c> wishAffiliations, Id caseId, Id formId) {
		Wish_Signature_Forms__c wishForm = [
				SELECT Days_From_Signature_to_Expiry__c
				FROM Wish_Signature_Forms__c
				WHERE Id = :formId
		];
		List<Wish_Required_Signature__c> wrsToInsert = new List<Wish_Required_Signature__c>();
		for (Wish_Affiliation__c wishAff : wishAffiliations) {
			Wish_Required_Signature__c wrs = new Wish_Required_Signature__c();
			wrs.Wish_Case__c = caseId;
			wrs.Wish_Signature_Form__c = formId;
			wrs.Status__c = 'Not Sent';
			wrs.Days_From_Signature_to_Expiry__c = wishForm.Days_From_Signature_to_Expiry__c;
			wrs.Type__c = type;
			wrs.Wish_Affiliation__c = wishAff.Id;
			wrs.Sent_to_Email_Address__c = wishAff.Contact__r.Email;
			wrsToInsert.add(wrs);
		}
		return wrsToInsert;
	}

	/**
	 * Save Wish Family Wish Signatures
	 * @param adultsIdList
	 * @param adultsToChildIds
	 * @param caseId
	 * @param formId
	 */
	@AuraEnabled
	public static void saveFamilyWishSignatures(String adultsIdList, String adultsToChildIds, String caseId, String formId) {
		try {
			Set<Id> adultsIds = new Set<Id>();
			Map<Id, Wish_Affiliation__c> adultToWishAff = new Map<Id, Wish_Affiliation__c>();
			//Parse the list of adults and minors
			List<AdultWrapData> adultDataList = (List<AdultWrapData>) JSON.deserialize(adultsIdList, List<AdultWrapData>.class);
			List<AdultMinorWrapData> adultMinorDataList = (List<AdultMinorWrapData>) JSON.deserialize(adultsToChildIds, List<AdultMinorWrapData>.class);

			//Get a list of adults Ids selected via Self/Minors
			if (adultDataList != null && !adultDataList.isEmpty()) {
				for (AdultWrapData obj : adultDataList) {
					adultsIds.add(obj.adult);
				}
			}
			if (adultMinorDataList != null && !adultMinorDataList.isEmpty()) {
				for (AdultMinorWrapData obj : adultMinorDataList) {
					adultsIds.add(obj.adult);
				}
			}
			//Get Wish Affiliations of selected adults
			for (Wish_Affiliation__c wishAffiliation : [
					SELECT Id, Contact__c, Contact__r.Email
					FROM Wish_Affiliation__c
					WHERE Contact__c In :adultsIds
			]) {
				adultToWishAff.put(wishAffiliation.Contact__c, wishAffiliation);
			}
			//Create Wish Required Signature records and Insert them
			Map<Id, Id> mapWishAffToWRS = new Map<Id, Id>();
			Set<Id> wishAffIdSet = new Set<Id>();
			List<Wish_Required_Signature__c> wrsToInsert = new List<Wish_Required_Signature__c>();
			wrsToInsert = createWRSRecord('Family', adultToWishAff.values(), caseId, formId);
			if (!wrsToInsert.isEmpty()) {
				insert wrsToInsert;
			}
			if (!wrsToInsert.isEmpty()) {
				//Get Ids of WRSs just created to created corresponding Guardian records
				for (Wish_Required_Signature__c wishReqSigns : [
						SELECT Id,Wish_Affiliation__c,Wish_Affiliation__r.Contact__c
						FROM Wish_Required_Signature__c
						WHERE Id In :wrsToInsert
				]) {
					mapWishAffToWRS.put(wishReqSigns.Wish_Affiliation__r.Contact__c, wishReqSigns.Id);
				}
				//Create junction Guardian Signature records and insert them
				List<Guardian_Signature__c> guardiansToInsert = new List<Guardian_Signature__c>();
				if (adultMinorDataList != null && !adultMinorDataList.isEmpty()) {
					for (AdultMinorWrapData obj : adultMinorDataList) {
						if (!mapWishAffToWRS.isEmpty() && mapWishAffToWRS.containsKey(obj.adult)) {
							Guardian_Signature__c gs = new Guardian_Signature__c();
							gs.Signature__c = mapWishAffToWRS.get(obj.adult);
							gs.Signing_on_Behalf_Of__c = obj.wishAffMinor;
							guardiansToInsert.add(gs);
						}
					}
				}
				if (!guardiansToInsert.isEmpty()) {
					insert guardiansToInsert;
				}
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	//Wrapper class to hold response of Adults and their related minors - This response is used in the lightning:accordion component
	public class childWrapper {
		@AuraEnabled
		public Boolean isSelected { get; set; }
		@AuraEnabled
		public Contact con { get; set; }
		@AuraEnabled
		public Wish_Affiliation__c wishAff { get; set; }
		@AuraEnabled
		public List<childWrapper> lstMinors { get; set; }

		public childWrapper() {
			this.isSelected = false;
			this.con = new Contact();
			this.wishAff = new Wish_Affiliation__c();
			this.lstMinors = new List<childWrapper>();
		}
	}

	//Wrapper class to hold Adult and its Wish Affiliation Id
	public class AdultWrapData {
		public String adult;
		public String wishAff;
	}

	//Wrapper class to hold response of Adult, Minor and its Wish Affiliation Id
	public class AdultMinorWrapData {
		public String adult;
		public String minor;
		public String wishAffMinor;
	}

	//Wrapper class to hold Signature Forms data
	public class FormOptionsData {
		public String label;
		public Id value;
	}
}