make-a-wish-salesforce/src/objects/Dynamic_Content__c.object
<CustomObject>
    <description>This object have the ability to change the dynamic content on the volunteer portal in declarative manner.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whenever the Dynamic Content content is created newly, this flag would be marked as Active by default.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interview_Additional_Info__c</fullName>
        <description>It holds the text for Interview Additional Info for prospective volunteer</description>
        <label>Interview Additional Info</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Dynamic Content</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Dynamic Content ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Contents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Affiliation&apos;s Organization will be stored on the Contact record.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolunteerInterview_AC_Test.cls
@IsTest
private class VolunteerInterview_AC_Test {

    private final static Id CHAPTER_RT_ID = Constant_AC.CHAPTER_RT_ID;
    private final static Id NATIONAL_RT_ID = Constant_AC.NATIONAL_RT_ID;

    @TestSetup
    private static void setUp() {
        trac_TriggerHandlerBase.blockTrigger = true;

        User volunteer = [
                SELECT Id, ContactId
                FROM User
                WHERE ContactId != NULL
                AND IsActive = TRUE
                LIMIT 1
        ];

        List<Account> accountList = TestDataFactory.createAccount(1);
        Account accountAzChapter = accountList.get(0);
        accountAzChapter.Name = 'Make-A-Wish Arizona';
        accountAzChapter.RecordTypeId = CHAPTER_RT_ID;
        insert accountList;

        List<Dynamic_Content__c> dynamicContentList = TestDataFactory.createDynamicContent(1);
        Dynamic_Content__c nationalContent = dynamicContentList.get(0);
        nationalContent.Active__c = true;
        nationalContent.RecordTypeId = NATIONAL_RT_ID;
        nationalContent.Interview_Additional_Info__c = 'Please indicate up to three day/time combinations when submitting your interview preferences.';
        insert dynamicContentList;

        List<npe5__Affiliation__c> affiliationList = TestDataFactory.createAffiliation(1);
        npe5__Affiliation__c affiliation = affiliationList.get(0);
        affiliation.npe5__Organization__c = accountAzChapter.Id;
        affiliation.npe5__Primary__c = true;
        affiliation.npe5__Contact__c = volunteer.ContactId;
        insert affiliationList;

        trac_TriggerHandlerBase.blockTrigger = false;
    }

    @IsTest
    private static void validateVolunteerInterviewController() {
        List<npe5__Affiliation__c> affiliationList = [
                SELECT Id, npe5__Contact__c
                FROM npe5__Affiliation__c
                WHERE npe5__Contact__c != NULL
        ];
        User volunteerUser = [
                SELECT Id, ContactId
                FROM User
                WHERE ContactId = :affiliationList[0].npe5__Contact__c
        ];

        ApexPages.currentPage().getParameters().put('bgRequired', 'true');
        ApexPages.currentPage().getParameters().put('trainingRequired', 'true');

        System.runAs(volunteerUser) {
            VolunteerInterview_AC controller = new VolunteerInterview_AC();
            controller.getTimes();
            controller.confirmReschedule();
            controller.hidePopup();
            System.assert(controller.interviewContent == 'Please indicate up to three day/time combinations when submitting your interview preferences.');
        }
    }
}