make-a-wish-salesforce/src/objects/Dynamic_Content__c.object
<CustomObject>
    <description>This object have the ability to change the dynamic content on the volunteer portal in declarative manner.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whenever the Dynamic Content content is created newly, this flag would be marked as Active by default.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chapter_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will look up to chapter records in the account object</description>
        <label>Chapter Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Accounts related to Dynamic Content need to be a chapter name</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Chapter</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dynamic Contents</relationshipLabel>
        <relationshipName>Dynamic_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dynamic Content</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Dynamic Content ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Contents</pluralLabel>
    <recordTypes>
        <fullName>National</fullName>
        <active>true</active>
        <description>It will associated with National page layout</description>
        <label>National</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DynamicContent_ATTest.cls
/****************************************
Created by : Vennila Paramasivam
Created Date : 07/24/2016.
Author : Mst Solutions.
Description : Unit Test for DynamicContent_AT Trigger.
****************************************/

@isTest
Public class DynamicContent_ATTest
{
    static testmethod void createDynamicContent()
    {
      Dynamic_Content__c dynamicContent1 = TestClassUtil.createDynamicContent();
      Dynamic_Content__c dynamicContent2 = TestClassUtil.createDynamicContent();
      
      dynamicContent1.Active__c = True;
      Database.SaveResult result = Database.Update(dynamicContent1,false);
      System.assertEquals('Active National Record already exist', result.getErrors()[0].getMessage());
    
    }
    static testmethod void createProspectDynamicContent()
    {
     
      Dynamic_Content__c dynamicContent1 = TestClassUtil.createProspectiveDynamicContent();
      Dynamic_Content__c dynamicContent2 = dynamicContent1.clone();
      insert dynamicContent2;
      dynamicContent1.Active__c = True;
      Database.SaveResult result = Database.Update(dynamicContent1,false);
      System.assertEquals('Active record already exist for this chapter and record type', result.getErrors()[0].getMessage());
    
    }
    //Create a user with Arizona Role.
    @testSetup
    private static void createUser(){
        User arizonaUser = OrientationandTrainingUtil.createUserWithRole([select Id from UserRole where Name='Arizona - Chapter'].Id);
    }
    //Create a DynamicContent record with other chapter.
    static testmethod void createOtherChapterDynamicContent(){
    
        Chapter_Vs_Role__c newCR = new Chapter_Vs_Role__c();
        newCR.Chapter_Name__c='Make-A-Wish Arizona';
        newCR.Role_Name__c='Arizona - Chapter'; 
        newCR.Name='Make-A-Wish Arizona';       
        Insert newCR;
        
        Chapter_Vs_Role__c alabamaCR = new Chapter_Vs_Role__c();
        alabamaCR.Chapter_Name__c='Make-A-Wish Alabama';
        alabamaCR.Role_Name__c='Alabama - Chapter'; 
        alabamaCR.Name='Make-A-Wish Alabama';       
        Insert alabamaCR;
                
        User arizonaUser=[SELECT Id FROM USER WHERE UserRole.Name='Arizona - Chapter' AND isActive = true LIMIT 1];
        System.runAs(arizonaUser) {
            try{
               Dynamic_Content__c dynamicContent1 = OrientationandTrainingUtil.ChapterDynamicContent(OrientationandTrainingUtil.createchapterAccount().Id);
            }
            catch(Exception ex){
               System.assert(ex.getmessage().contains('You have no access to create broadcast records for other chapters')); 
            }
        }
        
        
    }

}