make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <fields>
        <fullName>Condition_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It has one to many relationship with Condition Description.</description>
        <label>Condition Description</label>
        <referenceTo>Condition_Description__c</referenceTo>
        <relationshipLabel>ICD Codes</relationshipLabel>
        <relationshipName>ICD_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Any_medical_reason_for_moving_quickly__c</fullName>
        <description>Is there a medical reason why we need to move quickly?</description>
        <inlineHelpText>Is there a medical reason why we need to move quickly?</inlineHelpText>
        <label>Any medical reason for moving quickly?</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Child_Age__c</fullName>
        <description>It would capture the child of the age.</description>
        <label>Child Age</label>
        <picklist>
            <picklistValues>
                <fullName>Under 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18 &amp; Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Child_Middle_Initial__c</fullName>
        <description>It will hold the Child Middle name details</description>
        <label>Child Middle Initial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_this_child_ever_received_prior_wish__c</fullName>
        <description>Has this child ever received a prior wish from MAW or any other wish granting organization?</description>
        <inlineHelpText>Has this child ever received a prior wish from MAW or any other wish granting organization?</inlineHelpText>
        <label>Has this child ever received prior wish?</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Hospital_Treatment_Facility_Treating__c</fullName>
        <description>It holds the information about Hospital/Treatment Facility of the wish kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_First_Name__c</fullName>
        <description>It hold the First name of wish&apos;s parent.</description>
        <label>Parent First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Last_Name__c</fullName>
        <description>It hold the last name of Wish&apos;s parent.</description>
        <label>Parent Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_A_Sent__c</fullName>
        <description>This will capture the date when the lead status is changed from Referred to Part A Sent</description>
        <label>Diagnosis Verification Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFI_Form_Info_Hidden__c</fullName>
        <description>In hold the RFI form status level. And this field is hidden field for preventing dup criteria while creating new lead from RFI.</description>
        <label>RFI Form Info Hidden</label>
        <picklist>
            <picklistValues>
                <fullName>Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referred_Date__c</fullName>
        <description>This field will capture the date value when the lead is is referred</description>
        <label>Referred Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wih&apos;s parent.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture email address of wish parent from referral form.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It will hold the firstname of the child.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It will capture the zipcode of wish&apos;s parent.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_child__c</fullName>
        <description>This field is used to store the relationship of the person who submits the Wish Kid details</description>
        <label>Relationship to child</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Member/Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Email__c</fullName>
        <description>This field will hold the Treating Medical Professional Email Address</description>
        <label>Treating Medical Professional Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the Treating Medical Professional First Name</description>
        <label>Treating Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Last_Name__c</fullName>
        <description>This field will hold the details about Treating Medical Professional Name</description>
        <label>Treating Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Phone__c</fullName>
        <description>This field will hold the Treating Medical Professional Phone number</description>
        <label>Treating Medical Professional Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>What_is_the_family_s_primary_spoken_lang__c</fullName>
        <description>Primary language of the wish family.</description>
        <label>Family Primary Language</label>
        <picklist>
            <picklistValues>
                <fullName>American Sign Language</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French and French Creole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Polish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tagalog</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vietnamese</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>Dup_Check__c</fullName>
        <description>This hidden field used in lead duplicate page.</description>
        <label>Dup Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Block Lead Dup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>unique_wish_identifier__c</fullName>
        <description>To store the unique wish identifier</description>
        <label>unique wish identifier</label>
        <length>20</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/classes/DiagnosisVerficationRemainder_ACTest.cls
// This class used to do the unit testing and code coverage
// It will create the lead record
@isTest
private class DiagnosisVerficationRemainder_ACTest {
    private static Date todayDate = Date.today();

    @testSetup
    static void setup() {
        trac_TriggerHandlerBase.blockTrigger = true;
        Account makeAWish = OrientationandTrainingUtil.CreateAmericaAccount();
        Condition_Description__c descrip = OrientationandTrainingUtil.createConditionDesCription(); 
        insert descrip;
        ICD_Codes__c icdCode = OrientationandTrainingUtil.createICDCode(descrip.Id);
        insert icdCode;
        List<Lead> leadList = new List<Lead>(TestDataFactory.createLead(20));
        for(Integer i = 0; i < leadList.size(); i++) {
            leadList[i].Has_this_child_ever_received_prior_wish__c = 'Yes';
            leadList[i].Has_this_child_ever_received_prior_wish__c = 'Yes';
            leadList[i].Any_medical_reason_for_moving_quickly__c  = 'Yes';
            leadList[i].Relationship_To_Child__c = 'Self';
            leadList[i].Diagnosis_Given_By_Referrer__c = 'Malignant';
            leadList[i].Referrer_FirstName__c = 'Testing' + i;
            leadList[i].Referrer_Last_Name__c = 'Testing' + i;
            leadList[i].Referrer_Phone__c = '8220708920';
            leadList[i].Referrer_Email__c = 'testmawa@gmail.com';
            leadList[i].Referrer_City__c = 'karur';
            leadList[i].unique_wish_identifier__c ='059-17-1236' + i;
            leadList[i].Referrer_Zip__c = '35004';
            leadList[i].is_Family_Aware_of_Referral__c = 'Yes';
            leadList[i].FirstName = 'Testing' + i;
            leadList[i].Child_Middle_Initial__c = 'Testing' + i;
            leadList[i].lastName = 'Testing' + i;
            leadList[i].Gender__c = 'Male';
            leadList[i].Child_Age__c = '16';
            leadList[i].DOB__c = Date.valueOf('2000-09-11');
            leadList[i].Parent_First_Name__c = 'Testing' + i;
            leadList[i].Parent_Last_Name__c = 'Testing' + i;
            leadList[i].Street = 'Karur';
            leadList[i].City = 'Karur';
            leadList[i].state = 'Arizona';
            leadList[i].PostalCode= '35004';
            leadList[i].Email= 'testmawa2@gmail.com';
            leadList[i].Phone= '8220708920';
            leadList[i].What_is_the_family_s_primary_spoken_lang__c= 'English';
            leadList[i].Hospital_Treatment_Facility_Treating__c= 'Malignant Neoplasm';
            leadList[i].Treating_Medical_Professional_First_Name__c = 'Treating' + i;
            leadList[i].Treating_Medical_Professional_Last_Name__c= 'Treating' + i;
            leadList[i].Treating_Medical_Professional_Phone__c = '8220708921';
            leadList[i].Treating_Medical_Professional_Email__c= 'testmawa3@gmail.com';
            leadList[i].Any_medical_reason_for_moving_quickly__c= 'yes';
            leadList[i].PD_Condition_Description__c  = 'c00';
            leadList[i].PD_ICD_Code__c = icdCode.Id;
            leadList[i].RFI_Form_Info_Hidden__c = 'Referred';
            leadList[i].Company = 'MST';
            leadList[i].Status = 'Referred';
            leadList[i].Referred_Date__c = todayDate.addDays(-3);
        }
        insert leadList;
        trac_TriggerHandlerBase.blockTrigger = false;
    }
       
    @isTest
    static void testBatchPartAReminderSevenDays() {
        Test.startTest();
        List<Lead> leadsBeforeUpdate = new List<Lead>();
        leadsBeforeUpdate = [SELECT Id, Diagnosis_Given_By_Referrer__c, Status, Part_A_Sent__c, Sub_Status__c, 
                            Referred_Date__c, Dup_Check__c, Diagnosis_Pending_Days__c 
                            FROM Lead];
        System.assertEquals(NULL, leadsBeforeUpdate[0].Diagnosis_Pending_Days__c);
        for(Lead lead : leadsBeforeUpdate) {
            lead.Diagnosis_Given_By_Referrer__c = 'Malignant';
            lead.Status = Constant_AC.LEAD_STATUS_REFERRED;
            lead.Part_A_Sent__c = todayDate.addDays(-7);
            lead.Sub_Status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
            lead.Referred_Date__c = todayDate;
            lead.Dup_Check__c = Constant_AC.LEAD_DUP_CHECK_BLOCK_LEAD_DUP;
        }
        update leadsBeforeUpdate;
        DiagnosisVerficationRemainder_AC batchAffiliation = new DiagnosisVerficationRemainder_AC();
        Database.executeBatch(batchAffiliation, 200);
        Test.stopTest();
    }
    
    @isTest
    static void testBatchPartAReminderFourteenDays() {
        Test.startTest();
        List<Lead> leadsBeforeUpdate = new List<Lead>();
        leadsBeforeUpdate = [SELECT Id, Diagnosis_Given_By_Referrer__c, Status, Part_A_Sent__c, Sub_Status__c, 
                            Referred_Date__c, Dup_Check__c, Diagnosis_Pending_Days__c 
                            FROM Lead];
        System.assertEquals(NULL, leadsBeforeUpdate[0].Diagnosis_Pending_Days__c);
        for(Lead lead : leadsBeforeUpdate) {
            lead.Diagnosis_Given_By_Referrer__c = 'Malignant';
            lead.Status = Constant_AC.LEAD_STATUS_REFERRED;
            lead.Part_A_Sent__c = todayDate.addDays(-14);
            lead.Sub_Status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
            lead.Referred_Date__c = todayDate;
            lead.Dup_Check__c = Constant_AC.LEAD_DUP_CHECK_BLOCK_LEAD_DUP;
        }
        update leadsBeforeUpdate;
        DiagnosisVerficationRemainder_AC batchAffiliation = new DiagnosisVerficationRemainder_AC();
        Database.executeBatch(batchAffiliation, 200);
        Test.stopTest();
    }
    
    @isTest
    static void testBatchPartAReminderTwentyOneDays() {
        Test.startTest();
        List<Lead> leadsBeforeUpdate = new List<Lead>();
        leadsBeforeUpdate = [SELECT Id, Diagnosis_Given_By_Referrer__c, Status, Part_A_Sent__c, Sub_Status__c, 
                            Referred_Date__c, Dup_Check__c, Diagnosis_Pending_Days__c 
                            FROM Lead];
        System.assertEquals(NULL, leadsBeforeUpdate[0].Diagnosis_Pending_Days__c);
        for(Lead lead : leadsBeforeUpdate) {
            lead.Diagnosis_Given_By_Referrer__c = 'Malignant';
            lead.Status = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
            lead.Part_A_Sent__c = todayDate.addDays(-21);
            lead.Sub_Status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
            lead.Referred_Date__c = todayDate;
            lead.Dup_Check__c = Constant_AC.LEAD_DUP_CHECK_BLOCK_LEAD_DUP;
        }
        update leadsBeforeUpdate;
        DiagnosisVerficationRemainder_AC batchAffiliation = new DiagnosisVerficationRemainder_AC();
        Database.executeBatch(batchAffiliation, 200);
        Test.stopTest(); 
    }
    
    @isTest
    static void testBatchReferredDateThreeDays() {
        Test.startTest();
        List<Lead> leadsBeforeUpdate = new List<Lead>();
        leadsBeforeUpdate = [SELECT Id, Diagnosis_Given_By_Referrer__c, Status, Part_A_Sent__c, Sub_Status__c, 
                            Referred_Date__c, Dup_Check__c, Diagnosis_Pending_Days__c 
                            FROM Lead];
        for(Lead lead : leadsBeforeUpdate) {
            lead.Diagnosis_Given_By_Referrer__c = 'Malignant';
            lead.Status = Constant_AC.LEAD_STATUS_REFERRED;
            lead.Part_A_Sent__c = todayDate;
            lead.Sub_Status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
            lead.Inquiry_Date__c = todayDate.addDays(-4);
            lead.Referred_Date__c = todayDate.addDays(-3);
            lead.Dup_Check__c = Constant_AC.LEAD_DUP_CHECK_BLOCK_LEAD_DUP;
        }
        update leadsBeforeUpdate;
        DiagnosisVerficationRemainder_AC batchAffiliation = new DiagnosisVerficationRemainder_AC();
        Database.executeBatch(batchAffiliation, 200);
        Test.stopTest();
    }

    @isTest
    static void testScheduler() {
        Test.startTest();
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        //Schedule the test job
        String jobId = System.schedule('testJob1',
                                       CRON_EXP, 
                                       new DiagnosisVerficationRemainder_AC());
        //Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        //Verify the expressions are the same
        System.assertEquals(CRON_EXP, 
                            ct.CronExpression,'Does not match');
        //Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered,'Does not match');
        //Verify the next time the job will run
        System.assertEquals('2022-03-15 00:00:00', 
                            String.valueOf(ct.NextFireTime),'Does not match');
        Test.stopTest();
    }
}