make-a-wish-salesforce/src/objects/ICD_Codes__c.object
<CustomObject>
    <description>List of ICD codes and descriptions.</description>
    <label>ICD Code</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICD Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Angina__c</fullName>
        <description>It will hold the value of angina travel algorithm.</description>
        <label>Angina</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Arrhythmia__c</fullName>
        <description>it will hold the value of Arrhythmia Travel Algorithm.</description>
        <label>Arrhythmia</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chronic_Heart_Failure__c</fullName>
        <description>It will hold the value of Chronic Heart Failure Travel Algorithm value.</description>
        <label>Chronic Heart Failure</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chronic_Hepatitis__c</fullName>
        <description>It will hold the Travel Algorithm additional question values.</description>
        <label>Chronic Hepatitis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Congenital_Heart_Disease__c</fullName>
        <description>It will hold the value of Travel Algorithm&apos;s Congenital_Heart_Disease value.</description>
        <label>Congenita Heart Disease</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Convulsive_Disorders__c</fullName>
        <description>It will hold the value of Conclusive Disorder&apos;s Travel Algorithm.</description>
        <label>Convulsive Disorders</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Condition_Label__c</fullName>
        <label>Current Condition Label</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Condition__c</fullName>
        <label>Travel Recommendation</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Heart_Failure__c</fullName>
        <description>It will hold the value of Heart_Failure travel algorithm.</description>
        <label>Heart Failure</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hospital_Treatment_Facility_Treating__c</fullName>
        <description>It holds the information about Hospital/Treatment Facility of the wish kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lung_Disease__c</fullName>
        <label>Lung Disease</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Medical_Questions__c</fullName>
        <description>Holds all medical Questions</description>
        <label>Medical Questions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_First_Name__c</fullName>
        <description>It hold the First name of wish&apos;s parent.</description>
        <label>Parent First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Last_Name__c</fullName>
        <description>It hold the last name of Wish&apos;s parent.</description>
        <label>Parent Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pulmonary_Hypertension__c</fullName>
        <description>It hold the value of Travel Algorithm additional questions.</description>
        <label>Pulmonary Hypertension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Strokes__c</fullName>
        <description>It will hold the value of Travel Algorithm additional questions. Hidden field.</description>
        <label>Strokes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel_algorithm__c</fullName>
        <description>Used to store travel checklists</description>
        <label>Travel algorithm</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the Treating Medical Professional First Name</description>
        <label>Treating Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Last_Name__c</fullName>
        <description>This field will hold the details about Treating Medical Professional Name</description>
        <label>Treating Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ventilator__c</fullName>
        <description>It will hold the value of Ventilator travel algorithm.</description>
        <label>Ventilator</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Medical_Questions__c.object
<CustomObject>
    <description>It holds the medical questions for the diagnosis entered by the submitter.</description>
    <fields>
        <fullName>Current_Condition__c</fullName>
        <description>It contains wish child diagnosis current condition</description>
        <label>Current Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recommendation_to_Chapter__c</fullName>
        <description>It holds the recommendation for kids based on travel list they selected</description>
        <label>Recommendation to Chapter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Medical Question</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Medical Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DvTravelQuestionsControllerTest.cls
/**
 * @description Test class for DvTravelQuestionsController Class and it's inner class
 * @author Christopher Smith, Make-A-Wish America
 * @createdDeate 2/24/2021
 */

@isTest
private class DvTravelQuestionsControllerTest {
  @TestSetup
  static void setup() {
    trac_TriggerHandlerBase.blockTrigger = true;

    ICD_Codes__c icd = new ICD_Codes__c(Name = 'D83.4');
    upsert icd;

    List<Lead> testLeads = TestDataFactory.createLead(1);
    Lead wk = testLeads.get(0);
    wk.firstName = 'Timmy';
    wk.LastName = 'Smith';

    wk.RecordTypeId = Constant_AC.LEAD_RT_WISH_CHILD;
    wk.Status = Constant_AC.LEAD_STATUS_REFERRED;
    wk.Parent_First_Name__c = 'Mom';
    wk.Parent_Last_Name__c = 'Smith';
    wk.Company = 'Make-A-Wish America';
    wk.dob__c = Date.Today().AddYears(-7);
    wk.is_Family_Aware_of_Referral__c = 'Yes';
    wk.PD_Condition_Description__c = 'Neoplasm';
    wk.Phone = '123456789';
    wk.Email = 'test@email.com';
    wk.Street = '123 Street';
    wk.City = 'Phoenix';
    wk.State = 'Arizona';
    wk.StateCode = 'AZ';
    wk.PostalCode = '8042000';
    wk.CountryCode = 'US';
    wk.gender__c = 'Male';
    wk.Treating_Medical_Professional_First_Name__c = 'Dr';
    wk.Treating_Medical_Professional_Last_Name__c = 'John';
    wk.Hospital_Treatment_Facility_Treating__c = 'Mercy';
    wk.ICD_Given_By_Referrer__c = icd.id;

    upsert wk;
    //necessary to update before setting substatus
    wk.sub_status__c = Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION;
    update wk;

    List<Medical_Questions__c> travRecs = TestDataFactory.createMedicalQuestions(
      2
    );
    travRecs[0].recordTypeId = Constant_AC.TRAVEL_ALGM_RT_ID;
    travRecs[0].current_condition__c = 'testCondition';
    travRecs[0].recommendation_to_chapter__c = '';
    travRecs[1].recordTypeId = Constant_AC.TRAVEL_ALGM_RT_ID;
    travRecs[1].current_condition__c = 'testOption';
    travRecs[1].recommendation_to_chapter__c = 'travelRestriction';
    upsert travRecs;
    trac_TriggerHandlerBase.blockTrigger = false;
  }

  @isTest
  private static void shouldMakeWrapperWithFalseValues() {
    test.startTest();

    Lead wk = [
      SELECT
        id,
        Lung_Disease__c,
        Pulmonary_Hypertension__c,
        Ventilator__c,
        Angina__c,
        Arrhythmia__c,
        Heart_Failure__c,
        Chronic_Heart_Failure__c,
        Congenital_Heart_Disease__c,
        Chronic_Hepatitis__c,
        Hidden_Proto_Pulmonary_Hypertension__c,
        Strokes__c,
        Convulsive_Disorders__c,
        Travel_Restriction__c,
        Current_Condition_Label__c,
        Travel_Algorithm__c
      FROM Lead
      WHERE
        sub_status__c = :Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION
    ];

    DvTravelQuestionsController.TravelQuestionsWrapper wrapper = DvTravelQuestionsController.getTravelWrapperByLead(
      String.valueOf(wk.id)
    );
    System.AssertEquals(false, wrapper.isLungDisease);

    test.stopTest();
  }

  @isTest
  private static void shouldFillValuesOnLead() {
    test.startTest();
    Lead wk = [
      SELECT
        id,
        Lung_Disease__c,
        Pulmonary_Hypertension__c,
        Ventilator__c,
        Angina__c,
        Arrhythmia__c,
        Heart_Failure__c,
        Chronic_Heart_Failure__c,
        Congenital_Heart_Disease__c,
        Chronic_Hepatitis__c,
        Hidden_Proto_Pulmonary_Hypertension__c,
        Strokes__c,
        Convulsive_Disorders__c,
        Travel_Restriction__c,
        Current_Condition_Label__c,
        Travel_Algorithm__c
      FROM Lead
      WHERE
        sub_status__c = :Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION
    ];
    wk.lung_disease__c = 'testOption';
    wk.Pulmonary_Hypertension__c = 'testOption';
    wk.Ventilator__c = 'testOption';
    wk.Angina__c = 'testOption';
    wk.arrhythmia__c = 'testOption';
    wk.Heart_Failure__c = 'testOption';
    wk.Chronic_Heart_Failure__c = 'testOption';
    wk.Congenital_Heart_Disease__c = 'testOption';
    wk.Chronic_Hepatitis__c = 'testOption';
    wk.Hidden_Proto_Pulmonary_Hypertension__c = 'testOption';
    wk.Strokes__c = 'testOption';
    wk.Convulsive_Disorders__c = 'testOption';
    wk.Travel_Algorithm__c = 'testOption';
    update wk;

    DvTravelQuestionsController.TravelQuestionsWrapper wrapper = DvTravelQuestionsController.getTravelWrapperByLead(
      String.valueOf(wk.id)
    );
    System.AssertEquals(true, wrapper.isLungDisease);

    DVTravelQuestionsController.saveTravelQuestionData(wrapper);

    wk = [
      SELECT
        id,
        Lung_Disease__c,
        Pulmonary_Hypertension__c,
        Ventilator__c,
        Angina__c,
        Arrhythmia__c,
        Heart_Failure__c,
        Chronic_Heart_Failure__c,
        Congenital_Heart_Disease__c,
        Chronic_Hepatitis__c,
        Hidden_Proto_Pulmonary_Hypertension__c,
        Strokes__c,
        Convulsive_Disorders__c,
        Travel_Restriction__c,
        Current_Condition_Label__c,
        Travel_Algorithm__c
      FROM Lead
      WHERE
        sub_status__c = :Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION
    ];
    System.AssertNotEquals(null, wk.Current_Condition_Label__c);
    System.AssertNotEquals(null, wk.Travel_Restriction__c);

    test.stopTest();
  }

  @isTest
  private static void shouldFillValuesOnWrapper() {
    test.startTest();
    Lead wk = [
      SELECT
        id,
        Lung_Disease__c,
        Pulmonary_Hypertension__c,
        Ventilator__c,
        Angina__c,
        Arrhythmia__c,
        Heart_Failure__c,
        Chronic_Heart_Failure__c,
        Congenital_Heart_Disease__c,
        Chronic_Hepatitis__c,
        Hidden_Proto_Pulmonary_Hypertension__c,
        Strokes__c,
        Convulsive_Disorders__c,
        Travel_Restriction__c,
        Current_Condition_Label__c,
        Travel_Algorithm__c
      FROM Lead
      WHERE
        sub_status__c = :Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION
    ];
    wk.Travel_Algorithm__c =
      Constant_AC.INFECTIOUS_TUBERCULOSIS +
      ';' +
      Constant_AC.AIRBORNE_VIRAL_INFECTIONS_OF_HIGH_MORTALITY +
      ';' +
      Constant_AC.PNEUMOTHORAX +
      ';' +
      Constant_AC.PLEURAL_EFFUSION +
      ';' +
      Constant_AC.OXYGEN_DEPENDENCE_AT_SEA_LEVEL +
      ';' +
      Constant_AC.OXYGEN_REQUIREMENT_4L_MIN_AT_SEA_LEVEL +
      ';' +
      Constant_AC.LONG_TERM_OXYGEN_WITHIN_LAST_6_MONTHS +
      ';' +
      Constant_AC.HOSPITALIZATION_FOR_ACUTE_RESPIRATORY +
      ';' +
      Constant_AC.SEVERE_UNCONTROLLED_HYPERTENSION +
      ';' +
      Constant_AC.PORTAL_HYPERTENSION +
      ';' +
      Constant_AC.HEPTOPULMONARY_SYNDROME +
      ';' +
      Constant_AC.CHRONIC_LIVER_DISEASE +
      ';' +
      Constant_AC.END_STAGE_LIVER_DISEASE +
      ';' +
      Constant_AC.ESOPHAGEAL_VARICES_OR_HISTORY_OF +
      ';' +
      Constant_AC.INCREASED_INTRACRANIAL_PRESSURE +
      ';' +
      Constant_AC.PANIC_DISORDER +
      ';' +
      Constant_AC.MAJOR_BLEEDING +
      ';' +
      Constant_AC.SYMPTOMATIC_ANEMIA +
      ';' +
      Constant_AC.SICKLE_CELL_ANEMIA +
      ';' +
      Constant_AC.SURGERY_IN_THE_PAST_2_MONTHS +
      ';' +
      Constant_AC.MEDICALLY_FRAGILE_MEDICALLY_COMPLEX +
      ';' +
      Constant_AC.I_AM_NOT_SURE;

    update wk;

    DvTravelQuestionsController.TravelQuestionsWrapper wrapper = DvTravelQuestionsController.getTravelWrapperByLead(
      String.valueOf(wk.id)
    );
    wrapper.pulmonaryHypertensionSelection = 'abc';
    wrapper.chestPainSelections = new List<String>{ 'def' };
    wrapper.arrhythmiaSelections = new List<String>{ 'ghi' };
    wrapper.acuteHeartFailureSelections = new List<String>{ 'jkl' };
    wrapper.chronicHeartFailureSelections = new List<String>{ 'mno' };
    wrapper.cyanoticHeartDiseaseSelections = new List<String>{ 'pqr' };
    wrapper.convulsiveDisorderSelections = new List<String>{ 'stu' };

    DvTravelQuestionsController.saveTravelQuestionData(wrapper);

    wk = [
      SELECT id, Current_Condition_Label__c
      FROM Lead
      WHERE
        sub_status__c = :Constant_AC.LEAD_SUB_STATUS_PENDING_DIAGNOSIS_VERIFICATION
    ];

    System.AssertNotEquals(null, wk.Current_Condition_Label__c);

    test.stopTest();
  }
}