make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Angina__c</fullName>
        <description>It will hold the value of angina travel algorithm.</description>
        <label>Angina</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Arrhythmia__c</fullName>
        <description>it will hold the value of Arrhythmia Travel Algorithm.</description>
        <label>Arrhythmia</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ChapterName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It  associate with Chapter.</description>
        <label>Chapter Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chronic_Heart_Failure__c</fullName>
        <description>It will hold the value of Chronic Heart Failure Travel Algorithm value.</description>
        <label>Chronic Heart Failure</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chronic_Hepatitis__c</fullName>
        <description>It will hold the Travel Algorithm additional question values.</description>
        <label>Chronic Hepatitis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communication__c</fullName>
        <description>It will hold which type of communication can understand by child</description>
        <label>Communication</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appropriate for chronological age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sensorimotor (0-2 year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preoperational (2-7 year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Operational (7-11 year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formal Operational (11+ year old) stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chronological age</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Congenital_Heart_Disease__c</fullName>
        <description>It will hold the value of Travel Algorithm&apos;s Congenital_Heart_Disease value.</description>
        <label>Congenita Heart Disease</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Convulsive_Disorders__c</fullName>
        <description>It will hold the value of Conclusive Disorder&apos;s Travel Algorithm.</description>
        <label>Convulsive Disorders</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>This field holds the DOB details of the Wish Kid</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Heart_Failure__c</fullName>
        <description>It will hold the value of Heart_Failure travel algorithm.</description>
        <label>Heart Failure</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hospital_Treatment_Facility_Treating__c</fullName>
        <description>It holds the information about Hospital/Treatment Facility of the wish kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hospital_Treatment_Facility__c</fullName>
        <description>This field will hold the details of the Hospital/Treatment Facility for the Wish Kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lung_Disease__c</fullName>
        <label>Lung Disease</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Medical_Professional_Email__c</fullName>
        <description>This field will hold the details about the Medical Professional Email</description>
        <label>Medical Professional Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the details of Medical Professional First Name</description>
        <label>Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Professional_Last_Name__c</fullName>
        <description>It will display the details of the Medical Professional Last Name.</description>
        <label>Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Professional_Phone__c</fullName>
        <description>This field will hold the Medical Professional Phone details</description>
        <label>Medical Professional Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Medical_Questions__c</fullName>
        <description>Holds all medical Questions</description>
        <label>Medical Questions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_First_Name__c</fullName>
        <description>It hold the First name of wish&apos;s parent.</description>
        <label>Parent First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Last_Name__c</fullName>
        <description>It hold the last name of Wish&apos;s parent.</description>
        <label>Parent Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pulmonary_Hypertension__c</fullName>
        <description>It hold the value of Travel Algorithm additional questions.</description>
        <label>Pulmonary Hypertension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_City__c</fullName>
        <description>It will capture city of the wih&apos;s parent.</description>
        <label>Referrer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>It will capture email address of wish parent from referral form.</description>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_FirstName__c</fullName>
        <description>It will hold the firstname of the child.</description>
        <label>Referrer FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <description>It will capture the phone number of Referrer</description>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Referrer_Zip__c</fullName>
        <description>It will capture the zipcode of wish&apos;s parent.</description>
        <label>Referrer Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sibling_Detail__c</fullName>
        <description>It will hold the sibling name and age details.</description>
        <label>Sibling Detail</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Strokes__c</fullName>
        <description>It will hold the value of Travel Algorithm additional questions. Hidden field.</description>
        <label>Strokes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel_algorithm__c</fullName>
        <description>Used to store travel checklists</description>
        <label>Travel algorithm</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Email__c</fullName>
        <description>This field will hold the Treating Medical Professional Email Address</description>
        <label>Treating Medical Professional Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the Treating Medical Professional First Name</description>
        <label>Treating Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Last_Name__c</fullName>
        <description>This field will hold the details about Treating Medical Professional Name</description>
        <label>Treating Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Phone__c</fullName>
        <description>This field will hold the Treating Medical Professional Phone number</description>
        <label>Treating Medical Professional Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ventilator__c</fullName>
        <description>It will hold the value of Ventilator travel algorithm.</description>
        <label>Ventilator</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>isSign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to verify the document is signed or not from docusign.</description>
        <label>isSign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Family_Aware_of_Referral__c</fullName>
        <description>This field indicate that Child Family aware of Referral at MAWA</description>
        <label>Is Family Aware of Referral?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Medical_Questions__c.object
<CustomObject>
    <description>It holds the medical questions for the diagnosis entered by the submitter.</description>
    <label>Medical Question</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Medical Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Batch_updateTaskToRelatedRec_Test.cls
/* This class is used to increase the code coverage of Batch_updateTaskToRelatedRec class*/
@isTest
public class Batch_updateTaskToRelatedRec_Test{
    
    /* This method is used to create Lead and Task and update the task with the associate lead record */
    
    public testmethod static void CreateLead(){
       // Lead newLead = OrientationandTrainingUtil.createTestLeadRec(OrientationandTrainingUtil.createchapterAccount().Id);
        Lead newLead = new Lead();
        newLead.FirstName = 'moss';
        newLead.LastName = 'Smith Household';
        newLead.Phone = '9600467559';
        newLead.Email = 'testmawa@gmail.com';
        newLead.Street = 'KuttaiKarai Street';
        newLead.StateCode = 'AZ';
        newLead.city = 'Trichy';
        newLead.Postalcode = '6201717';
        newLead.CountryCode = 'US';
        newLead.DOB__c = System.today() - 1435;
        newLead.company = 'MAWA';
        newLead.Status = 'Inquiry';
       // newLead.Sub_Status__c = 'Pending Diagnosis Verification';
        newLead.Gender__c = 'Male';
        newLead.ChapterName__c = OrientationandTrainingUtil.createchapterAccount().Id;
        newLead.Referrer_FirstName__c = 'Sudhar';
        newLead.Referrer_Last_Name__c = 'test';
        newLead.Referrer_Email__c = 'sudhar1@gmail.com';
        newLead.Referrer_Phone__c = '0600467559';
        newLead.Referrer_City__c = 'Trichy';
        newLead.Referrer_Zip__c = '6210';
        newLead.Sibling_Detail__c = 'aa | aaab | 14 bbb | bbbc | 15';
        newLead.PD_Condition_Description__c = 'Test Diagnosis';
        newLead.Parent_First_Name__c = 'MAWAFirstJune';
        newLead.Parent_Last_Name__c = 'MAWALastJune';
        newLead.Medical_Professional_First_Name__c = 'mossJune';
        newLead.Medical_Professional_Last_Name__c = 'hartJune';
        newLead.Medical_Professional_Phone__c = '9600467559';
        newLead.Medical_Professional_Email__c = 'testmawa1s@gmail.com';
        newLead.Hospital_Treatment_Facility__c = 'Moss Hart AC';
        newLead.Treating_Medical_Professional_First_Name__c = 'SteveJune';
        newLead.Treating_Medical_Professional_Last_Name__c = 'Waughone';
        newLead.Treating_Medical_Professional_Phone__c = '9600467578';
        newLead.Treating_Medical_Professional_Email__c = 'testmawa2d@gmail.com';
        newLead.Hospital_Treatment_Facility_Treating__c = 'Steve Smith AC';
        newLead.is_Family_Aware_of_Referral__c = 'Yes';
        newLead.Medical_Questions__c = 'Test Diagnosis';
        //newLead.PD_ICD_Code__c  = 'C12.0';
        newLead.Lung_Disease__c = 'Test1;Test2';
        newLead.Angina__c = 'Test1;Test2';
        newLead.Ventilator__c = 'Test1;Test2';
        newLead.Arrhythmia__c = 'Test1;Test2';
        newLead.Heart_Failure__c = 'Test1;Test2';
        newLead.Congenital_Heart_Disease__c = 'Test1;Test2';
        newLead.Chronic_Hepatitis__c = 'Test1;Test2';
        newLead.Convulsive_Disorders__c = 'Test1;Test2';
        newLead.Pulmonary_Hypertension__c = 'Test1;Test2';
        newLead.Strokes__c = 'Test1;Test2';
        newLead.Chronic_Heart_Failure__c = 'Test1;Test2';
        newLead.isSign__c = true;
        //newLead.Communication__c = 'Non-Verbal';
        newLead.Travel_algorithm__c = 'Test1;Test2;';
        Insert newLead;
        Task newTask = new Task(subject ='Lead ET : Online Wish Referral Received');
        Insert newTask;
        system.assertEquals('Smith Household',[SELECT lastName FROM Lead WHERE id =: newLead.Id].LastName);
        
        Test.StartTest();
        Database.executeBatch(new Batch_updateTaskToRelatedRec_AC());
        Test.StopTest();
        
        system.assertEquals(newLead.Id,[SELECT WhoId FROM Task WHERE id =: newTask.Id].WhoId);
    }
 }