make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Child_Age__c</fullName>
        <description>It would capture the child of the age.</description>
        <label>Child Age</label>
        <picklist>
            <picklistValues>
                <fullName>Under 2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18 &amp; Above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hospital_Treatment_Facility__c</fullName>
        <description>This field will hold the details of the Hospital/Treatment Facility for the Wish Kid</description>
        <label>Hospital/Treatment Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Override_Dupe_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to bypass the duplicate validation.</description>
        <label>No Duplicate Found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Email__c</fullName>
        <description>This field will hold the Treating Medical Professional Email Address</description>
        <label>Treating Medical Professional Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the Treating Medical Professional First Name</description>
        <label>Treating Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Last_Name__c</fullName>
        <description>This field will hold the details about Treating Medical Professional Name</description>
        <label>Treating Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Phone__c</fullName>
        <description>This field will hold the Treating Medical Professional Phone number</description>
        <label>Treating Medical Professional Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>unique_wish_identifier__c</fullName>
        <description>To store the unique wish identifier</description>
        <label>unique wish identifier</label>
        <length>20</length>
        <type>Text</type>
    </fields>

make-a-wish-salesforce/src/classes/LeadDuplicate_ACTest.cls
@isTest
Public class LeadDuplicate_ACTest
{
   
  // Creating duplicate lead and duplicate wish Family record.
  static testmethod void createDuplicateFamily()
  {
     Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
     Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
     Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
     newLead.Child_Age__c = '4';
     newLead.unique_wish_identifier__c = '1234567';
     insert newLead;
      
     Lead newdupLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
     newdupLead.Override_Dupe_Check__c = True;
     newdupLead.Child_Age__c = '4';
     newdupLead.unique_wish_identifier__c = '123456';
     insert newdupLead;
      
     ApexPages.currentPage().getParameters().put('wishFamily','True');
     ApexPages.currentPage().getParameters().put('Id',newLead.id);
     List<Lead> currLead = new List<Lead>();
     currLead.add(newLead);
     currLead.add(newdupLead);
     ApexPages.StandardSetController std = new ApexPages.StandardSetController(currLead);
     LeadDuplicate_AC controller = new LeadDuplicate_AC(std);
     controller.getdupLeadList();
     controller.getdupContactList();
     controller.getdupMedicalContactList();
     controller.getdupTreatingContactList();
     controller.getdupParentContactList();
     controller.nextStep();
  
  }
  // Selecting No duplicate Option on Lead Merge page.
  static testmethod void SelectNoDuplicate()
  {
     Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
     Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
     Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
     newLead.Child_Age__c = '4';
     newLead.unique_wish_identifier__c = '1234567';
     insert newLead;
      
     Lead newdupLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
     newdupLead.Override_Dupe_Check__c = True;
     newdupLead.Child_Age__c = '4';
     newdupLead.unique_wish_identifier__c = '1234568';
     insert newdupLead;
      
     ApexPages.currentPage().getParameters().put('wishFamily','True');
     ApexPages.currentPage().getParameters().put('Id',newLead.id);
     List<Lead> currLead = new List<Lead>();
     currLead.add(newLead);
     currLead.add(newdupLead);
     ApexPages.StandardSetController std = new ApexPages.StandardSetController(currLead);
     LeadDuplicate_AC controller = new LeadDuplicate_AC(std);
     controller.NoDuplicate = True; 
    
     controller.nextStep();
     controller.ContinuePartAForm();
     controller.CompleteDupeCheck();
  
  }
  
  // Creating duplicate medical professional contacts.
  static testmethod void duplicateMedicalProfessional()
  {
     Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
     Contact wishChildContact = OrientationandTrainingUtil.CreateWishChildCon();
     Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id); 
     
     
     newLead.Treating_Medical_Professional_First_Name__c = 'moss';
     newLead.Treating_Medical_Professional_Last_Name__c  = 'hart';
     newLead.Treating_Medical_Professional_Phone__c  = '9600467558';
     newLead.Treating_Medical_Professional_Email__c = 'testmawa1@gmail.com';
     newLead.Hospital_Treatment_Facility__c = 'Moss Hart AC';
     newLead.Child_Age__c = '4';
     newLead.unique_wish_identifier__c = '1234567';
     insert newLead;
     Lead newdupLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id); 
     newdupLead.Override_Dupe_Check__c = True;
     newdupLead.Child_Age__c = '4';
     newdupLead.unique_wish_identifier__c = '1234568';
     insert newduplead;
     
     
     ApexPages.currentPage().getParameters().put('wishFamily','True');
     ApexPages.currentPage().getParameters().put('Id',newLead.id);
     List<Lead> currLead = new List<Lead>();
     currLead.add(newLead);
     currLead.add(newdupLead);
     ApexPages.StandardSetController std = new ApexPages.StandardSetController(currLead);
     LeadDuplicate_AC controller = new LeadDuplicate_AC(std);
    
     controller.getdupContactList();
     controller.getdupMedicalContactList();
     controller.getdupTreatingContactList();
     controller.getdupParentContactList();
       for(Lead currDup : currLead)
         {
           LeadDuplicate_AC.leadWrapper newWrapper = new LeadDuplicate_AC.LeadWrapper(currDup);
           newWrapper.selected = True;
           controller.wrapperList.add(newWrapper);
         }
     controller.getdupLeadList();
     controller.nextStep();
     Apexpages.currentPage().getParameters().put('recordId',currLead[0].id);
     controller.selectDefaultRecord();
     controller.mergeContacts();
  
  }
   //No duplicate creation.
   static testmethod void BlankLead()
  {
     List<Lead> currLead = new List<Lead>();
     ApexPages.StandardSetController std = new ApexPages.StandardSetController(currLead);
     LeadDuplicate_AC controller = new LeadDuplicate_AC(std);
  }

}