make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This field holds the Gender information of the Wish Kid</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_First_Name__c</fullName>
        <description>It hold the First name of wish&apos;s parent.</description>
        <label>Parent First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Last_Name__c</fullName>
        <description>It hold the last name of Wish&apos;s parent.</description>
        <label>Parent Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Last_Name__c</fullName>
        <description>It will capture the last name of child.</description>
        <label>Referrer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_child__c</fullName>
        <description>This field is used to store the relationship of the person who submits the Wish Kid details</description>
        <label>Relationship to child</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Member/Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/DVChildInfoController.cls
/**
* @description DV Child Information Controller
* @author Brittany Maclaughlin, Make-A-Wish
* @createdDate 02/09/2021
*/
public class DVChildInfoController {
    
    @AuraEnabled(cacheable=true)
    public static ChildInformationWrapper getLeadChildInformation(String leadId) {
        ChildInformationWrapper dvChildInfoWrapper = new ChildInformationWrapper();
        if (String.isBlank(leadId)){
            return dvChildInfoWrapper;

        } 
     
       Lead dvLead = [
            SELECT Id, Name, Gender__c, DOB_Text__c, Parent_First_Name__c, Parent_Last_Name__c, Referring_MP__r.FirstName, Referring_MP__r.LastName, Referrer_Last_Name__c, Relationship_to_child__c, 
            Diagnosis_Given_By_Referrer__c, ICD_Given_By_Referrer__r.Name
            FROM Lead 
            WHERE Id = :leadId
        ];
        
        
            dvChildInfoWrapper.leadId = dvLead.Id;
            dvChildInfoWrapper.name = dvLead.Name;
            dvChildInfoWrapper.gender = dvLead.Gender__c;
            dvChildInfoWrapper.dob = dvLead.DOB_Text__c;
            dvChildInfoWrapper.parentGuardianName =dvLead.Parent_First_Name__c + ' ' + 
            dvLead.Parent_Last_Name__c;
            dvChildInfoWrapper.referrerName = dvLead.Referring_MP__r.FirstName + ' ' + 
                    dvLead.Referring_MP__r.LastName;
            dvChildInfoWrapper.relationshipToChild = dvLead.Relationship_to_child__c;
            dvChildInfoWrapper.diagnosisGivenByReferrer = dvLead.Diagnosis_Given_By_Referrer__c;
            dvChildInfoWrapper.icdGivenByReferrer = dvLead.ICD_Given_By_Referrer__r.Name;
            
        
        return dvChildInfoWrapper;
    }
    
   
    
    public class ChildInformationWrapper {
        @AuraEnabled
        public Id leadId {get; set;}
        @AuraEnabled
        public String name {get; set;}
        @AuraEnabled
        public String gender {get; set;}
        @AuraEnabled
        public String dob {get; set;}
        @AuraEnabled
        public String parentGuardianName {get; set;}
        @AuraEnabled
        public String referrerName {get; set;}
        @AuraEnabled
        public String relationshipToChild {get; set;}
        @AuraEnabled
        public String diagnosisGivenByReferrer {get; set;}
        @AuraEnabled
        public String icdGivenByReferrer {get; set;}
       
    }
}