make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>PD_Condition_Description__c</fullName>
        <description>This filed is used to store the condition description from PartA from.</description>
        <label>PD Condition Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_ICD_Code__c</fullName>
        <description>This field is used to store the ICD code value from PartA form.</description>
        <label>PD ICD Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SD2_Condition_Description__c</fullName>
        <description>It holds the condition description for Secoundary Diagnosis 2</description>
        <label>SD2 Condition Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SD2_ICD_Code__c</fullName>
        <description>It contains ICD code for Secondary Diagnosis 2</description>
        <label>SD2 ICD Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/PARTAPDF_Test.cls
@isTest
public class PARTAPDF_Test {
    
 public testmethod static void SignDocument(){  
     Account chapterAccount = OrientationandTrainingUtil.createVolunteerAccount();
     OrientationandTrainingUtil.insertDocusignSetting();
     Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
     newLead.PD_ICD_Code__c = 'C00';
     newLead.PD_Condition_Description__c = 'Malignant Melanoma';
     newLead.SD2_ICD_Code__c = '';
     newLead.SD2_Condition_Description__c = '';
     insert newLead;
       
       PageReference pageRef = Page.LeadPartA_ApprovalForm_VF_Output;
       pageRef.getParameters().put('Id', newLead.id);
       Test.setCurrentPage(pageRef);
       ApexPages.StandardController sc = new ApexPages.StandardController(newLead);
       PARTAPDF testAccPlan = new PARTAPDF(sc);
      
      Test.setMock(HttpCalloutMock.class, new Mock_ResponseGenerator()); 
     Test.StartTest();
     testAccPlan.SubmitSign();
     testAccPlan.cancel();
     Test.StopTest();
           
   
    }
}