make-a-wish-salesforce/src/objects/Lead_File__c.object
<CustomObject>
    <fields>
        <fullName>File_Path__c</fullName>
        <label>File Path</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Lead File</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Lead File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/LeadFile_AT_Test.cls
/*****************************************************************************************************************
Author      : MST Solutions
Date        : 10/26/2016
Description : This class contains test method for LeadFile object
*******************************************************************************************************************/
@isTest
public class LeadFile_AT_Test {
    
    static testmethod void createLeadFile() {
        Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
        Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
        Lead_File__c newFileRecord = OrientationandTrainingUtil.createLeadFileRecord(newLead.Id);
    }
    
    static testmethod void updateLeadFile(){
        Account chapterAccount = OrientationandTrainingUtil.createchapterAccount();
        Lead newLead = OrientationandTrainingUtil.createTestLeadRec(chapterAccount.Id);
        Lead_File__c newFileRecord = OrientationandTrainingUtil.createLeadFileRecord(newLead.Id);
        newFileRecord.File_Path__c = 'https://salesforce.com';
        update newFileRecord;
        
    }
}