make-a-wish-salesforce/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Of_Times_Email_Sent__c</fullName>
        <label># Of Times Email Sent</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field value is updated when the part A case status is In progress.</description>
        <label>Sub Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Wish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Diagnosis Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Email__c</fullName>
        <description>This field will hold the Treating Medical Professional Email Address</description>
        <label>Treating Medical Professional Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_First_Name__c</fullName>
        <description>This field will hold the Treating Medical Professional First Name</description>
        <label>Treating Medical Professional First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treating_Medical_Professional_Last_Name__c</fullName>
        <description>This field will hold the details about Treating Medical Professional Name</description>
        <label>Treating Medical Professional Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

make-a-wish-salesforce/objects/Lead.object
    <fields>
        <fullName>Dup_Check__c</fullName>
        <description>This hidden field used in lead duplicate page.</description>
        <label>Dup Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Block Lead Dup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

make-a-wish-salesforce/src/classes/LeadSelectMedEmailController_AC.cls
/**************************************************************************************
Author : MST Solutions
Description : This class referred in the LeadSelectMedEmail_VF.Intake form contains both treating medical professional and 
best contact for physicians Then the user must select who have received DV form. 

****************************************************************************************/
public class LeadSelectMedEmailController_AC{
    public boolean success {get;set;}
    public Lead currLead {get;set;}
    public string URLToRedirect {get;set;}
    
    public LeadSelectMedEmailController_AC(){
        currLead = [SELECT id,Best_Contact_for_Physician_Last_Name__c ,Best_Contact_for_Physician_First_Name__C,Best_contact_for_Physician_Email__c,
                    Treating_Medical_Professional_First_Name__c,Of_Times_Email_Sent__c,Treating_Medical_Professional_Last_Name__c,Treating_Medical_Professional_Email__c FROM Lead WHERE id =: ApexPages.currentPage().getParameters().get('id') LIMIT 1];
    }
    
    //Update the Lead medical professional type.
    public void updateLead(){       
        URLToRedirect = URL.getSalesforceBaseUrl().toExternalForm()+'/'+currLead.Id;
        currLead.Hidden_DV_form_Medical_professional_Type__c = Apexpages.currentPage().getParameters().get('type');
        //currLead.Hidden_Send_DV_Email__c = email;
        currLead.Sub_Status__c='Pending Diagnosis Verification'; 
        currLead.Dup_Check__c= 'Block Lead Dup'; 
        
        IF( currLead.Of_Times_Email_Sent__c == Null )
            currLead.Of_Times_Email_Sent__c =  0;
        
        currLead.Of_Times_Email_Sent__c= currLead.Of_Times_Email_Sent__c+1; 
        Update currLead;
        
        success = True;
    }
    
    //Go to the lead detail page.
    public pageReference GoToLeadViewPage(){
        pageReference page = new pageReference('/'+currLead.Id);
        return page;
    }
    
}