make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will define the location of the event</description>
        <label>Chapter</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>It store the event date field</description>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>It holds the name of the Event.</description>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>It will define the priority of the event.</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/classes/NonWishEvents_ATTest.cls
/********************************************************
Created by : Vennila Paramasivam
Created Date: 07/24/2016
Description : Unit Test for NonWishEvents_AT
***********************************************************/

@isTest
public class NonWishEvents_ATTest
{

    @TestSetup static void createWishRecord()
    {
      Non_Wish_Events__c  newWish = new Non_Wish_Events__c();
      newWish.Event_Name__c= 'Test 1';
      newWish.Event_Date__c  = Date.Today().addDays(5);
      newWish.Priority__c = '1';
      newWish.chapter__c  = TestClassUtil.createVolunteerAccount().id;
      insert newWish;
    }
    static testmethod void createPastWish()
    {
      Non_Wish_Events__c  newWish = new Non_Wish_Events__c();
      newWish.Event_Name__c= 'Test 1';
      newWish.Event_Date__c  = Date.Today().addDays(-5);
      Database.SaveResult result = Database.Insert(newWish,false);
      //System.assertEquals('Event Date should be greater than Today', result.getErrors()[0].getMessage());
    
    }
    static testmethod void UpdateEventDate()
    {
       Non_Wish_Events__c currWish = [SELECT Id, Event_Date__c FROM Non_Wish_Events__c];
       currWish.Event_Date__c  = Date.Today().addDays(-5);
       Database.SaveResult result = Database.update(currWish,false);
       //System.assertEquals('Event Date should be greater than Today', result.getErrors()[0].getMessage());
        
    }
    static testmethod void UpdatePriority()
    {
       
       Non_Wish_Events__c currWish = [SELECT Id, Event_Date__c,chapter__c FROM Non_Wish_Events__c];
      
       Non_Wish_Events__c  newWish = new Non_Wish_Events__c();
       newWish.Event_Name__c= 'Test 1';
       newWish.Event_Date__c  = Date.Today().addDays(5);
       newWish.Priority__c = '2';
       newWish.chapter__c  = currWish.chapter__c;
       insert newWish;
      
       
       currWish.Priority__c = '2';
       currWish.Event_Date__c  = Date.Today().addDays(5);
       Database.SaveResult result = Database.update(currWish,false);
       System.assertEquals('This Chapter already has event for same priority. Please select some other priority.', result.getErrors()[0].getMessage());
       
    
    }


}