make-a-wish-salesforce/src/objects/Non_Wish_Events__c.object
<CustomObject>
    <description>It holds the Event details</description>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>It store the event date field</description>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>It holds the name of the Event.</description>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Text__c</fullName>
        <description>It will hold the details about Event</description>
        <label>Event Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Non-Wish &amp; Events</label>
    <nameField>
        <displayFormat>Event-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Wish &amp; Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Event_Date__c</fullName>
        <description>Event date indicated when the event started</description>
        <formula>Non_Wish_Event__r.Event_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>This Holds the value of event name</description>
        <formula>Non_Wish_Event__r.Event_Name__c</formula>
        <label>Non-WIsh/Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Wish_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It hold the record of each event</description>
        <label>Name</label>
        <referenceTo>Non_Wish_Events__c</referenceTo>
        <relationshipLabel>Volunteer Opportunities</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>It indicate different status of the volunteer opportunity.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_changeVolunOppSatus_Test.cls
@IsTest
public class batch_changeVolunOppSatus_Test {
    
    @TestSetup
    static void setUp() {
        trac_TriggerHandlerBase.blockTrigger = true;
        
        Non_Wish_Events__c event = TestDataFactory.createNonwishEvent(1)[0];
        event.Event_Name__c = 'Monthly Team Meeting';
        event.Event_Text__c = 'Monthly touchpoint for the Arizona volunteer team.';
        event.Event_Date__c = Date.today().addDays(-1);
        insert event;
        
        List<Volunteer_Opportunity__c> volOppList = TestDataFactory.createVolunteerOpportunity(25);
        for(integer i = 0; i < volOppList.size(); i++) {
            volOppList[i].Non_Wish_Event__c = event.Id;
            volOppList[i].Status__c = Constant_AC.VOLUNTEER_OPPORTUNITY_STATUS_PENDING;
            volOppList[i].RecordTypeId = Constant_AC.NON_WISH_EVENT_RT_ID;
        }
        insert volOppList;
        
        trac_TriggerHandlerBase.blockTrigger = false;
    }
    
    @IsTest
    static void testchangeVolunOppStatusCompleted() {
        String cron = '0 0 1 * * ? *';
        Test.startTest();
        String jobId = System.schedule('batch_changeVolunOppSatus_Test', cron, new batch_changeVolunOppSatus());
        Test.stopTest();
        CronTrigger ct = [
            SELECT Id, CronExpression, TimesTriggered, NextFireTime
            FROM CronTrigger
            WHERE Id = :jobId
        ];
        System.assertEquals(cron, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
    }
}