make-a-wish-salesforce/src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>npe4__RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe4__Type__c</fullName>
        <description>Field that describes how the Related Contact is connected to the Contact.</description>
        <inlineHelpText>Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Wish Child(Self)</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Step Sister</fullName>
                </value>
                <value>
                    <fullName>Step Brother</fullName>
                </value>
                <value>
                    <fullName>Half Sister</fullName>
                </value>
                <value>
                    <fullName>Half Brother</fullName>
                </value>
                <value>
                    <fullName>Foster Mother</fullName>
                </value>
                <value>
                    <fullName>Foster Father</fullName>
                </value>
                <value>
                    <fullName>Foster Sister</fullName>
                </value>
                <value>
                    <fullName>Foster Brother</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Neighbor</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Legal Guardian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/AbsentForm_AC_Test.cls
/*****************************************************************************
Author : MST Solutions
CreateDate : 03/25/2016
Description : AbsentForm_AC_Test is used to increase the code coverage for AbsentForm_AC.
******************************************************************************/

@isTest
Public class AbsentForm_AC_Test{
    
    //Relation ship record creation
    public static testMethod void createParentCase(){
        Contact contactWishChild =   OrientationandTrainingUtil.CreateWishChild(); 
        Contact contactWishParent =  OrientationandTrainingUtil.CreateWishFamily();
        npe4__Relationship__c relationShip = OrientationandTrainingUtil.relationshipChild(contactWishChild.id,contactWishParent.id);
        npe4__Relationship__c  newRelationShip = new npe4__Relationship__c();
        newRelationShip.Id = relationShip.Id;
        newRelationShip.npe4__Type__c = 'Father';
        Update newRelationShip;
        Case caseId = OrientationandTrainingUtil.CreateParentCaseWithTravel(contactWishChild.Id);
        OrientationandTrainingUtil.insertDocusignSetting();
        ApexPAges.StandardController sc = new ApexPages.StandardController(caseId);
        PageReference pageRef = Page.AbsentForm_VF;
        pageRef.getParameters().put('id',String.valueOf(caseId.Id));
        Test.setCurrentPage(pageRef);
        AbsentForm_AC absentIns = new AbsentForm_AC(sc);
        Test.StartTest();
        System.assert(relationShip.npe4__RelatedContact__c.equals(caseId.ContactId),'Check RelatedContact equals to Contact in Case');
        Test.setMock(HttpCalloutMock.class, new Mock_ResponseGenerator()); 
        absentIns.CallouttoDocusign();
        absentIns.cancel();
        absentIns.getRecpList();
        absentIns.DisplayMessage();
        Test.StopTest();
        
    }
    //Email update for relation ship
    public static testMethod void createParentCaseWithWishChild(){
        Map<Id, npe4__Relationship__c> relMap = new Map<Id, npe4__Relationship__c>();
        Contact contactWishChild =   OrientationandTrainingUtil.CreateWishChild(); 
        Contact contactWishParent =  OrientationandTrainingUtil.CreateWishFamily();
        npe4__Relationship__c relationShip = OrientationandTrainingUtil.relationshipChild(contactWishChild.id,contactWishParent.id);
        npe4__Relationship__c  newRelationShip = new npe4__Relationship__c();
        newRelationShip.Id = relationShip.Id;
        newRelationShip.npe4__Type__c = 'Mother';
        Update newRelationShip;
        Case caseId = OrientationandTrainingUtil.CreateParentCaseWithTravel(contactWishChild.Id);
        OrientationandTrainingUtil.insertDocusignSetting();
        ApexPAges.StandardController sc = new ApexPages.StandardController(caseId);
        PageReference pageRef = Page.AbsentForm_VF;
        pageRef.getParameters().put('id',String.valueOf(caseId.Id));
        Test.setCurrentPage(pageRef);
        AbsentForm_AC absentIns = new AbsentForm_AC(sc);
        Test.StartTest();
        relMap.put(relationShip.Id, relationShip);
        absentIns.relationShipMap = relMap;
        absentIns.recpName = relationShip.Id;
        System.assert(relationShip.npe4__RelatedContact__c.equals(caseId.ContactId),'Check RelatedContact equals to Contact in Case');
        Test.setMock(HttpCalloutMock.class, new Mock_ResponseGenerator()); 
        absentIns.getRecpList();
        absentIns.displayReturnToWish = true;
        //absentIns.updateRelatedContact();
        absentIns.recpName = relationShip.Id;
        absentIns.recpEmail = contactWishParent.Email;
        absentIns.CallouttoDocusign();
        absentIns.ReturnToWish();
        absentIns.cancel();
        Test.StopTest();
        
    }
    
    //Docusign callout
    public static testMethod void createParentCaseWithWishFamily(){
        Contact contactWishChild =   OrientationandTrainingUtil.CreateWishChild(); 
        Contact contactWishParent =  OrientationandTrainingUtil.CreateWishFamily();
        npe4__Relationship__c relationShip = OrientationandTrainingUtil.relationshipChild(contactWishChild.id,contactWishParent.id);
        npe4__Relationship__c  newRelationShip = new npe4__Relationship__c();
        newRelationShip.Id = relationShip.Id;
        newRelationShip.npe4__Type__c = 'Legal Guardian';
        Update newRelationShip;
        Case caseId = OrientationandTrainingUtil.CreateParentCaseWithTravel(contactWishChild.Id);
        OrientationandTrainingUtil.insertDocusignSetting();
        ApexPAges.StandardController sc = new ApexPages.StandardController(caseId);
        PageReference pageRef = Page.AbsentForm_VF;
        pageRef.getParameters().put('id',String.valueOf(caseId.Id));
        Test.setCurrentPage(pageRef);
        AbsentForm_AC absentIns = new AbsentForm_AC(sc);
        Test.StartTest();
        absentIns.ReturnToWish();
        absentIns.displayRelatedInfo();
        System.assert(relationShip.npe4__RelatedContact__c.equals(caseId.ContactId),'Check RelatedContact equals to Contact in Case');
        Test.setMock(HttpCalloutMock.class, new Mock_ResponseGenerator()); 
        absentIns.CallouttoDocusign();
        absentIns.ReturnToWishClearanceForm();
        absentIns.cancel();
        Test.StopTest();
        
    }
    
}