make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Affiliation&apos;s Organization will be stored on the Contact record.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe5__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Out of Compliance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/objects/Volunteer_Roles__c.object
<CustomObject>
    <description>This custom object would store the roles for which the volunteer has expressed interest or has been approved for.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>It will indicate the volunteer role that volunteer has completed the training for that chpater role or not.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trained</fullName>
                </value>
                <value>
                    <fullName>Pending Training</fullName>
                </value>
                <value>
                    <fullName>Chapter Review</fullName>
                </value>
                <value>
                    <fullName>Former - Chapter</fullName>
                </value>
                <value>
                    <fullName>Former - Volunteer</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will hold the volunteer name and define chapter and role for this volunteer.</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Volunteer Roles ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/batch_BUpdateAffiliation_AC.cls
global class batch_BUpdateAffiliation_AC implements Database.Batchable<sObject> {

	global Database.QueryLocator start(Database.BatchableContext BC) {
		String volunteerRtLabel = Constant_AC.VOLUNTEER_RT_LABEL;
		return Database.getQueryLocator([
				SELECT Id, npe5__Contact__c,npe5__Status__c
				FROM npe5__Affiliation__c
				WHERE npe5__Contact__r.RecordType.Name = :volunteerRtLabel
				AND (npe5__Status__c != 'Active' AND npe5__Status__c != 'Pending' ) AND npe5__Primary__c = TRUE
		]);
	}

	global void execute(Database.BatchableContext BC, List<npe5__Affiliation__c> AffiliationList) {
		// Declarations
		Set<ID> volunteerIdsSet = new Set<ID>();
		List<Volunteer_Roles__c> volRoleList = new List<Volunteer_Roles__c>();
		map<id, list<Volunteer_Roles__c>> volunteerRoleStatusMap = new map<id, list<Volunteer_Roles__c>>();

		//Fetch affiliation records based on the volunteer contact and primary
		for (npe5__Affiliation__c currAff : AffiliationList) {
			volunteerIdsSet.add(currAff.npe5__Contact__c);
		}

		//Fetch Volunteer role records based on the volunteerIdsSet

		for (Volunteer_Roles__c currVolRole : [
				SELECT ID,Status__c,Volunteer_Name__c
				from Volunteer_Roles__c
				WHERE Volunteer_Name__c IN:volunteerIdsSet
		]) {
			if (volunteerRoleStatusMap.containsKey(currVolRole.Volunteer_Name__c)) {
				volunteerRoleStatusMap.get(currVolRole.Volunteer_Name__c).add(currVolRole);
			} else {
				volunteerRoleStatusMap.put(currVolRole.Volunteer_Name__c, new list<Volunteer_Roles__c>{
						currVolRole
				});
			}
			volRoleList.add(currVolRole);
		}

		// Call the apex method to execute the functionality
		if (volunteerRoleStatusMap.size() > 0) {
			system.debug('Number of records' + volunteerRoleStatusMap.size());
			VolunteerRole_OnAfterInsertHelper_AC.updateVolunteerRoleStatus(volunteerRoleStatusMap, 'Update', volRoleList);
		}

	}
	global void finish(Database.BatchableContext BC) {

	}
}