make-a-wish-salesforce/src/objects/npe5__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>npe5__Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Organization Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe5__Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/Affiliation_OnAfterDeleteTriggerHandler.cls
/**************************************************************************************
Author       : MST Solutions
Created Date : 08/11/2016
Description  : 
***************************************************************************************/
public class Affiliation_OnAfterDeleteTriggerHandler
{
    /* This method will be called after record is deleted and it is fired,
       to remove the user to the public group to restrict the approved In-Kind donor account record based on the affiliation record*/   
    public static void OnAfterDelete(List<npe5__Affiliation__c> deletelist)
    {
        Set<String> vlounteerNameSet = new Set<String>();
        Set<String> chapterNameSet = new Set<String>();
        Set<Id> affiliationSet = new Set<Id>();
        Map<Id,String> affliationRecMap = new Map<Id,String>();
        for(npe5__Affiliation__c currentRecord : deletelist)
        {
            vlounteerNameSet.add(currentRecord.npe5__Contact__c);
            chapterNameSet.add(currentRecord.npe5__Organization__c);  
            affiliationSet.add(currentRecord.id);
            affliationRecMap.put(currentRecord.id,String.valueOf(currentRecord));
        }
        
        if(vlounteerNameSet.size() > 0 && chapterNameSet.size() > 0 && affiliationSet.size() > 0)
        {
            Affiliation_OnAfterDeleteTriggerHelper.removeMemberFromGroup(vlounteerNameSet,chapterNameSet,affiliationSet,affliationRecMap);
        }
    }
}