make-a-wish-salesforce/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>It holds the related Case, Event, User and Role Name</description>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It will lookup to the contact, which record type as volunteer</description>
        <label>Volunteer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volunteer Contact, Board Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Opportunities (Volunteer Name)</relationshipLabel>
        <relationshipName>Volunteer_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <displayFormat>VR-{00000}</displayFormat>
        <label>Volunteer Opportunity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/VolOpportunity_OnBefore_Delete_Handler.cls
/*****************************************************************************************************************
Author      : MST Solutions
Date        : 5/27/2016
Description : When a Volunteer Opportunity record delete then it will call the VolOpportunity_OnBefore_Delete_Helper class based 
on the collection size() > 0.
Modification Log: 
04/17/2018 - Kanagaraj - WVC-1885
*******************************************************************************************************************/
public class VolOpportunity_OnBefore_Delete_Handler{
     
     // When volunteer Opportunity record gets deleted then it will call the VolOpportunity_OnBefore_Delete_Helper class methods.
     public static void onBeforeDelete(List<Volunteer_Opportunity__c> oldVolOpportunityList){
         
            Set<Id> updateUserSet = new Set<Id>();
            Set<Id> volconId= new Set<Id>();
            for(Volunteer_Opportunity__c oldDbRec : oldVolOpportunityList){
                if(oldDbRec.Volunteer_Name__c != Null){
                    updateUserSet.add(oldDbRec.Id);
                    volconId.add(oldDbRec.Volunteer_Name__c );
                }
            }
            
            if(updateUserSet.size() > 0) {
            VolOpportunity_OnBefore_Delete_Helper.updateUserRoleId(updateUserSet,volconId);
        }
     }    
}