make-a-wish-salesforce/src/objects/Wish_Child_Form__c.object
<CustomObject>
    <description>It will hold the value of Wish Child, Wish Info and Wish Family values.</description>
    <fields>
        <fullName>Case_Team_Member1__c</fullName>
        <description>It holds the updated case team member details.</description>
        <label>Case Team Member1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Team_Member2__c</fullName>
        <description>It will hold the updated Case Team Member details.</description>
        <label>Case Team Member2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It lookup to case record</description>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wish</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipName>Wish_Child_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Driver_Details__c</fullName>
        <label>Driver Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Wish Child Last Name</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant_Contacts__c</fullName>
        <label>Participant Contacts</label>
        <length>131000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Wish_Determination_Case_Id__c</fullName>
        <description>It holds the Wish Determination Case Id value.</description>
        <label>Wish Determination Case Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wish_Family_Contact__c</fullName>
        <label>Wish Family Contact</label>
        <length>131000</length>
        <type>Html</type>
    </fields>
    <label>Wish Paperwork Packet</label>
    <nameField>
        <displayFormat>WC-{00}</displayFormat>
        <label>Wish Child Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Paperwork Packets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

make-a-wish-salesforce/src/classes/WishChildFormValUpdate_AC_Test.cls
@isTest
public class WishChildFormValUpdate_AC_Test {
    public static testMethod void createCase() {
        Case currentCase = OrientationandTrainingUtil.createParentCase();
        map<string,Case> caseDetails = new map<string,Case>();
        caseDetails.put(currentCase.id, currentCase);
        Wish_Child_Form__c newWish = new Wish_Child_Form__c();
        newWish.Case__c = currentCase.id;
        newWish.Case_Team_Member1__c = 'Member 1';
        newWish.Case_Team_Member2__c = 'Member 2';
        insert newWish;
        WishChildFormValUpdate_AC.updateWishType(caseDetails);
    }
    
    public static testMethod void callUpdateWishdetails(){
        Contact newCon = OrientationandTrainingUtil.CreateWishChild();
        Case currentCase = OrientationandTrainingUtil.createParentCase(newCon.Id);
        Case parentCase = OrientationandTrainingUtil.createParentCase();
        case wihdetermination = OrientationandTrainingUtil.createWishDeterminationCase(newCon.id, parentCase.id);
        map<Id,Case> caseDetails = new map<Id,Case>();
        caseDetails.put(currentCase.Id, currentCase);
        Wish_Child_Form__c newWish = new Wish_Child_Form__c();
        newWish.Case__c = currentCase.id;
        newWish.Case_Team_Member1__c = 'Member 1';
        newWish.Case_Team_Member2__c = 'Member 2';
        newWish.Wish_Determination_Case_Id__c = wihdetermination.id;
        insert newWish;
        WishChildFormValUpdate_AC.updateWishdetails(caseDetails);
        
    }
    public static testMethod void UpdateWishChildandWishFamily(){
        
        Contact newCon = OrientationandTrainingUtil.CreateWishChild();
        Case parentCase = OrientationandTrainingUtil.createParentCase(newCon.Id);
        Case currentCase = OrientationandTrainingUtil.createParentCase(newCon.Id);
        case wihdetermination = OrientationandTrainingUtil.createWishDeterminationCase(newCon.id, parentCase.id);
        map<Id,Case> caseDetails = new map<Id,Case>();
        caseDetails.put(currentCase.Id, currentCase);
        Wish_Child_Form__c newWish = new Wish_Child_Form__c();
        newWish.Case__c = currentCase.id;
        newWish.Wish_Family_Contact__c = 'Vennila | | Paramasivam | Spouse | 8220708920 | 8220708920 | 8220708920 | mcavennila@gmail.com | 2016-11-6';
        newWish.Driver_Details__c = 'Vennila karur | Tamil Nadu | Alabama | 2016-10-12';
        newWish.Participant_Contacts__c = 'Vennila | | karur | Child | 2016-11-01 00:00:00 | asdfasdfdsafasfdsa@12gmail.com | 12 | true | true sathis Kumar | | def | Friend | - | vi@gmail.com | | false | false';
        newWish.LastName__c = 'Test Name';
        newWish.Case_Team_Member1__c = 'Member 1';
        newWish.Case_Team_Member2__c = 'Member 2';
        newWish.Wish_Determination_Case_Id__c = wihdetermination.id;
        insert newWish;
        WishChildFormValUpdate_AC.UpdateWishChildandWishFamily(caseDetails);
        
        
    }
    
}